Revert "Move CryptoToken access behind a feature flag and origin trial"
This reverts commit 40a92739954f1edba69ac14db63cc9232ecb235e.

Reason for revert: suspect causing compile failure on Network Service Linux.

First build failure:
https://ci.chromium.org/ui/p/chromium/builders/ci/Network%20Service%20Linux/29981/overview

Failure log:
https://logs.chromium.org/logs/chromium/buildbucket/cr-buildbucket/8836615275881784945/+/u/compile/stdout?format=raw
---
[3209/7705] CXX obj/chrome/test/browser_tests/cryptotoken_private_browsertest.o
FAILED: obj/chrome/test/browser_tests/cryptotoken_private_browsertest.o
/b/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF...(too long)
../../chrome/browser/extensions/api/cryptotoken_private/cryptotoken_private_browsertest.cc:128:3: error: ignoring return value of function declared with 'warn_unused_result' attribute [-Werror,-Wunused-result]
ui_test_utils::NavigateToURL(browser(),
^~~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~
---

Original change's description:
> Move CryptoToken access behind a feature flag and origin trial
>
> The U2F Security Key API is being deprecated:
> https://groups.google.com/a/chromium.org/g/blink-dev/c/xHC3AtU_65A
>
> This CL introduces a default-enabled base::Feature and a Blink Origin
> Trial, each named `U2FSecurityKeyAPI`. If neither the feature flag, nor
> the Reverse OT are enabled, Chrome will practically behave as if
> CryptoToken were removed. I.e., attempts to send messages to the
> CryptoToken extension ID will fail; and chrome.runtime will be undefined
> for any document that does not have any other connectable extensions
> available.
>
> Bug: 1224886
> Change-Id: I3a265cece91da3bade69f636a3ff6c9f9bfa947e
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3137353
> Reviewed-by: Devlin <rdevlin.cronin@chromium.org>
> Reviewed-by: Dave Tapuska <dtapuska@chromium.org>
> Commit-Queue: Martin Kreichgauer <martinkr@google.com>
> Cr-Commit-Position: refs/heads/main@{#919519}

Bug: 1224886
Change-Id: I7666994b6e62ffb8886c21aeebcb0f6dce72f5e4
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3151030
Owners-Override: Takashi Sakamoto <tasak@google.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Takashi Sakamoto <tasak@google.com>
Cr-Commit-Position: refs/heads/main@{#919525}