[gcc 4.8] Explicitly initialize net_error in ProxyRetryInfo to fix build failure
gcc 4.8 reports build failure as net_error is not explicitly initialized. The error
thrown is as below -

net/proxy/proxy_retry_info.h: In member function
‘virtual void net::{anonymous}::ProxyListTest_DeprioritizeBadProxies_Test::TestBody()’:
net/proxy/proxy_retry_info.h:15:8: error: ‘proxy_retry_info.net::ProxyRetryInfo::net_error’
is used uninitialized in this function [-Werror=uninitialized]

R=kundaji@chromium.org, rsleevi@chromium.org

Review URL: https://codereview.chromium.org/485603002

Cr-Commit-Position: refs/heads/master@{#290239}
git-svn-id: svn://svn.chromium.org/chrome/trunk/src@290239 0039d316-1c4b-4281-b951-d872f2087c98