IWYU: Add missing include for std::variant usage in ai_text_session.h
In the CL https://crrev.com/c/5790446 added a std::variant
typed argument into AITextSession::SetInfo() but corresponding include
was missed. Added missing include for std::variant usage.
Otherwise the build with libstdc++ fails with error:
third_party/blink/renderer/modules/ai/ai_text_session.h:45:16:
error: 'std::variant' has not been declared

Bug: 41455655
Change-Id: Ib952863b1af64818953a7d213b2958da996db606
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5848129
Reviewed-by: Jiacheng Guo <gjc@google.com>
Commit-Queue: DongHwan Yu <donghwan.yu@lge.com>
Reviewed-by: Tsuyoshi Horo <horo@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1353109}