stack_symbolizer.py: Help Python3 write str to tmpfile
By default tempfile.NamedTemporaryFile() opens the file as 'w+b', which
does not accept an str as an argument to .write():

```
TypeError: a bytes-like object is required, not 'str'
```

Fix it by opening as 'w'.

Bug: 1223747
Change-Id: Ib455da9b06b5b29fb6392abf714cde1a09f0c6a6
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3006156
Commit-Queue: Egor Pasko <pasko@chromium.org>
Commit-Queue: Andrew Grieve <agrieve@chromium.org>
Auto-Submit: Egor Pasko <pasko@chromium.org>
Reviewed-by: Andrew Grieve <agrieve@chromium.org>
Cr-Commit-Position: refs/heads/master@{#898612}