document.cc: Adjust max_tokens for Oilpan library
Mac debug fails with:
../../third_party/blink/renderer/core/dom/document.cc:36:31: error: the number of preprocessor source tokens (971459) exceeds this token limit (970000) [-Werror,-Wmax-tokens]

Adjust limit to 975000 for Oilpan library which is less than 1 percent
increase.

Bug: 1056170
Change-Id: I7737789a919cfb7b54ea7742047d079cb9fac3c8
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2866553
Commit-Queue: Michael Lippautz <mlippautz@chromium.org>
Commit-Queue: Kentaro Hara <haraken@chromium.org>
Auto-Submit: Michael Lippautz <mlippautz@chromium.org>
Reviewed-by: Kentaro Hara <haraken@chromium.org>
Cr-Commit-Position: refs/heads/master@{#878401}