Revert "Reland: "Add support for creating VP9 format extensions for VTVDA.""
This reverts commit 659a4e4ebfb90b51e7825437f0161a359c3e48da.

Reason for revert: Closed the tree with a compile failure:

https://ci.chromium.org/p/chromium/builders/ci/mac-arm64-rel/334

[263/11988] OBJCXX clang_x64/obj/base/base/sdk_forward_declarations.o
FAILED: clang_x64/obj/base/base/sdk_forward_declarations.o
/opt/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -...(too long)
In file included from ../../base/mac/sdk_forward_declarations.mm:5:
../../base/mac/sdk_forward_declarations.h:70:3: error: declaration shadows a variable in the global namespace [-Werror,-Wshadow]
kCMVideoCodecType_VP9 = 'vp09'
^
../../build/mac_files/xcode_binaries/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk/System/Library/Frameworks/CoreMedia.framework/Headers/CMFormatDescription.h:618:2: note: previous declaration is here

Original change's description:
> Reland: "Add support for creating VP9 format extensions for VTVDA."
> 
> Creates a vpcc box based on the configuration info. Reland now uses
> a forward declaration for the kCMVideoCodecType_VP9 which is in the
> 11.0/10.16 SDK.
> 
> R=​avi, sandersd
> 
> Bug: 1103432, 1105187
> Test: Updated unittests.
> Change-Id: I15158ec3329054981cab4eefc3316283952f2f48
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2348330
> Commit-Queue: Dale Curtis <dalecurtis@chromium.org>
> Reviewed-by: Avi Drissman <avi@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#796873}

TBR=avi@chromium.org,dalecurtis@chromium.org,sandersd@chromium.org

Change-Id: I6b767665887cee003dea63c3b037769a34021ea7
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 1103432
Bug: 1105187
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2346979
Reviewed-by: Elly Fong-Jones <ellyjones@chromium.org>
Commit-Queue: Elly Fong-Jones <ellyjones@chromium.org>
Cr-Commit-Position: refs/heads/master@{#796907}