Revert "[rust] Enable on official builds"
This reverts commit 7cbbfa8c13ac9fab4f762c74fcef897ef49a2012.

Reason for revert: bindgen_test (etc.) fail to link on Android official builds, starting with https://ci.chromium.org/p/chromium/builders/ci/android-official/14914
with duplicate symbol errors such as:
  = note: ld.lld: error: duplicate symbol: core::panicking::panic::he4fbf426c7c8358a

Original change's description:
> [rust] Enable on official builds
>
> This enables Rust test executables on official builds. It does not alter
> the Chrome binary - it just enables some test executables on various CI
> builders.
>
> Bug: 1292038
> Change-Id: I997f7b7ef0d09a0b879dc87afb657e2b5f35df3b
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4446364
> Commit-Queue: Adrian Taylor <adetaylor@chromium.org>
> Reviewed-by: danakj <danakj@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1133218}

Bug: 1292038
Change-Id: I858bb875c8d4b57b21088b77e0acba812ab7855b
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4455096
Owners-Override: David Baron <dbaron@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Auto-Submit: David Baron <dbaron@chromium.org>
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Cr-Commit-Position: refs/heads/main@{#1133324}