GCC: Add check for __has_feature support in blink::IsOnStack()
GCC doesn't support '__has_feature' macro, so we need to check for its
support before using it.
Without it the GCC build fails with error:
../../third_party/blink/renderer/platform/wtf/stack_util.cc:184:18: error: missing binary operator before token "("
    184 | #if __has_feature(safe_stack)
        |                  ^

Bug: 40565911
Change-Id: Ie206f3af42cbd2d1417bbd4b6568fd77077355be
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7882784
Reviewed-by: Michael Lippautz <mlippautz@chromium.org>
Reviewed-by: Anton Bikineev <bikineev@chromium.org>
Commit-Queue: Ivan Pavlotsky <ivan.pavlotsky@lge.com>
Cr-Commit-Position: refs/heads/main@{#1681323}