fix missing deps for obj/chrome/browser/ui/webui/about/about/about_ui.o
[57462/87088] CXX obj/chrome/browser/ui/webui/about/about/about_ui.o
FAILED: obj/chrome/browser/ui/webui/about/about/about_ui.o

In file included from ../../chrome/browser/ui/webui/about/about_ui.cc:41:
../../chrome/browser/ui/webui/chrome_urls/chrome_urls_ui.h:10:10: fatal error: 'components/webui/chrome_urls/mojom/chrome_urls.mojom.h' file not found
10 | #include "components/webui/chrome_urls/mojom/chrome_urls.mojom.h"
|          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

//components/webui/chrome_urls/mojom:mojo_bindings should be
in //chrome/browser:browser_generated_files

Bug: 417302597
Change-Id: If2fddcc340e34df631004ba5083e892a432bf6ad
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6537749
Auto-Submit: Fumitoshi Ukai <ukai@google.com>
Reviewed-by: Takuto Ikuta <tikuta@chromium.org>
Commit-Queue: Fumitoshi Ukai <ukai@google.com>
Cr-Commit-Position: refs/heads/main@{#1459234}