[rust] Fix missing allocator dep on buildflag.h
In file included from ../../build/rust/allocator/alias.cc:12:
In file included from ../../build/rust/allocator/compiler_specific.h:13:
../../build/build_config.h:60:10: fatal error: 'build/buildflag.h' file not found
 60 | #include "build/buildflag.h"  // IWYU pragma: export
    |          ^~~~~~~~~~~~~~~~~~~

Files in the "alloc_error_handler_impl" target include
./compiler_specific.h, which depends on build/build_config.h and
transitively on build/buildflag.h - we need to define this dependency so
that the build system pulls the required files in remote builds.

Change-Id: Ia041e443f772deb5889b200c7db910a2681dc115
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7840227
Commit-Queue: Maksim Ivanov <emaxx@chromium.org>
Reviewed-by: Łukasz Anforowicz <lukasza@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1629344}