Revert "mac: Enabled chained fixups on arm!"
This reverts commit 72a32dd95bdd1401cb55941e67018e9f92c2923d.

Reason for revert: Is probably the cause of the breakage of the
mac-arm64 builder, due to tools that don’t understand the new load
command.

https://ci.chromium.org/ui/p/chrome/builders/official/mac-arm64/8619/overview

```
ValueError: Unknown load command: 2147483700
```

Original change's description:
> mac: Enabled chained fixups on arm!
>
> Now that we're dropping support for macOS 11, we can use chained fixups,
> at least on arm.
>
> No intended behavior change. Should reduce binary size a bit, speed up
> start up a bit, and might possibly confuse tools that look at Mach-O
> files (but "mainstream" tools like lldb, dsymutil, etc should be fine).
>
> Bug: 420708323
> Change-Id: Ib6f889da00ba81a049020095ce17353cd222717d
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6593616
> Auto-Submit: Nico Weber <thakis@chromium.org>
> Reviewed-by: Mark Mentovai <mark@chromium.org>
> Commit-Queue: Mark Mentovai <mark@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1466242}

Bug: 420708323
Fixed: 420795049
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Change-Id: I217afdbfabf9842b43936d58e249ea073679b763
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6597955
Auto-Submit: Avi Drissman <avi@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Reviewed-by: Nico Weber <thakis@chromium.org>
Commit-Queue: Nico Weber <thakis@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1466490}