Fix incorrect wmain prototype
This incorrect prototype was introduced here:
  https://codereview.chromium.org/2621223003/

My head was somewhere else! My bad.

1 error generated.
[11/10562] CXX obj/remoting/host/win/remoting_desktop/entry_point.obj
FAILED: obj/remoting/host/win/remoting_desktop/entry_point.obj
../../../../llvm/ninja/bin/clang-cl.exe /nologo /showIncludes /FC @obj/remoting/host/win/remoting_desktop/entry_point.ob
j.rsp /c ../../remoting/host/win/entry_point.cc /Foobj/remoting/host/win/remoting_desktop/entry_point.obj /Fd"obj/remoti
ng/host/win/remoting_desktop_cc.pdb"
D:\src\chromium\src\remoting\host\win\entry_point.cc(22,6):  error: conflicting types for 'wWinMain'
int  wWinMain (HINSTANCE hInstance,
     ^
D:\src\depot_tools\win_toolchain\vs_files\d3cb0e37bdd120ad0ac4650b674b09e81be45616\win_sdk\Include\10.0.14393.0\um\winba
se.h(928,1):  note: previous declaration is here
wWinMain(
^
1 error generated.

R=grt
BUG=

Review-Url: https://codereview.chromium.org/2636963002
Cr-Commit-Position: refs/heads/master@{#444073}