Revert "Roll src/third_party/libunwindstack/ e184bd94b..6c228114e (3 commits)"
This reverts commit 4ee159b102a80e343a0a7c28695da3e639b09567.

Reason for revert: Causes compiler failures on Android ASAN (dbg)
https://ci.chromium.org/ui/p/chromium/builders/ci/Android%20ASAN%20(dbg)/35725/overview

[1229/22654] CXX obj/third_party/libunwindstack/libunwindstack/dex_file_tracking_registrar.o
FAILED: obj/third_party/libunwindstack/libunwindstack/dex_file_tracking_registrar.o
../../buildtools/reclient/rewrapper -cfg=../../buildtools/reclient_cfgs/chromium-browser-clang/rewra...(too long)
In file included from ../../third_party/libunwindstack/src/libdexfile/dex/dex_file_tracking_registrar.cc:31:
../../third_party/libunwindstack/src/libartbase/base/memory_tool.h:31:10: error: 'ADDRESS_SANITIZER' macro redefined [-Werror,-Wmacro-redefined]
# define ADDRESS_SANITIZER
^
<command line>:3:9: note: previous definition is here
#define ADDRESS_SANITIZER 1
^
1 error generated.


Original change's description:
> Roll src/third_party/libunwindstack/ e184bd94b..6c228114e (3 commits)
>
> https://chromium.googlesource.com/chromium/src/third_party/libunwindstack.git/+log/e184bd94bf23..6c228114e735
>
> $ git log e184bd94b..6c228114e --date=short --no-merges --format='%ad %ae %s'
> 2022-10-10 kartarsingh Move class static variables to function static
> 2022-09-29 kartarsingh Add patches to build libunwindstack with libdexfile
> 2022-09-29 kartarsingh Pull libdexfile in chromium
>
> Created with:
>   roll-dep src/third_party/libunwindstack
>
> Bug: 1365904, 1370988, b/246509988
> Change-Id: I0372fe7b342d8472d9bf9772ed56b5fcc85a6706
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3936850
> Commit-Queue: Kartar Singh <kartarsingh@google.com>
> Reviewed-by: Tushar Agarwal <agarwaltushar@google.com>
> Cr-Commit-Position: refs/heads/main@{#1057195}

Bug: 1365904, 1370988, b/246509988
Change-Id: I9130e167f6ed915168ff0444efd98814048099fc
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3944051
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Auto-Submit: Mark Pearson <mpearson@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1057209}