Change InsertParagraph to insert a BR when the editing host is a phrasing content
When the editing host[1] only allows phrasing content (e.g.
`<span>`), this patch changes `execCommand('insertParagraph')`
to insert a `<br>` instead of a `<div>`.

This patch matches the recent WebKit behavior change[2].

This change should turn wpt tests[3] to pass, but these tests
fail in Blink bots with the following error:
```
Error: We do not support keydown and keyup actions, please use
test_driver.send_keys. See crbug.com/893480.
```
Hence no updates to the test expectations.

The changes are under a runtime flag enabled by default,
except for Android for a risk of kill switch taking longer to
be effective.

[1] https://html.spec.whatwg.org/multipage/interaction.html#editing-host
[2] https://bugs.webkit.org/show_bug.cgi?id=252219
[3] https://wpt.fyi/results/editing/other?label=master&label=experimental&aligned&q=label%3Ainterop-2023-webcompat

Bug: 1420675
Change-Id: Ib9e6bbb852c7e8b666234391582e7fc77502035c
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4635263
Auto-Submit: Koji Ishii <kojii@chromium.org>
Commit-Queue: Kent Tamura <tkent@chromium.org>
Commit-Queue: Koji Ishii <kojii@chromium.org>
Reviewed-by: Kent Tamura <tkent@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1161614}