Fix missing dependencies to //components/privacy_sandbox:privacy_sandbox_notice_mojom
chrome/browser/privacy_sandbox/notice/notice_model.h is in //chrome/browser
but it doesn't have dependency to
//components/privacy_sandbox:privacy_sandbox_notice_mojom

Add the dependency in browser_public_dependencies.

ukai@ukai ...src/chromium/src % gn clean out/siso
ukai@ukai ...src/chromium/src % siso ninja --verbose_failures=false -C out/siso obj/chrome/browser/profiles/profiles_extra_parts_impl/chrome_browser_main_extra_parts_profiles.o
depot_tools/siso.py: Using Siso binary from SISO_PATH: /usr/local/google/home/ukai/go/bin/siso.
ninja: Entering directory `out/siso'
reapi instance: projects/rbe-chrome-untrusted/instances/default_instance
 5.25s load siso config
 7.18s Regenerating ninja files
 4.90s reloading
[35598/35599] 3m08.58s F CXX obj/chrom...me_browser_main_extra_parts_profiles.o
FAILED: fb801b02-5e82-43ab-8842-428ded42f3e6 "./obj/chrome/browser/profiles/profiles_extra_parts_impl/chrome_browser_main_extra_parts_profiles.o" CXX obj/chrome/browser/profiles/profiles_extra_parts_impl/chrome_browser_main_extra_parts_profiles.o
err: exit=1
build step: cxx "./obj/chrome/browser/profiles/profiles_extra_parts_impl/chrome_browser_main_extra_parts_profiles.o"
siso_rule: clang/cxx
stderr:
In file included from ../../chrome/browser/profiles/chrome_browser_main_extra_parts_profiles.cc:152:
In file included from ../../chrome/browser/privacy_sandbox/notice/notice_framework_factory.h:11:
In file included from ../../chrome/browser/privacy_sandbox/notice/notice_framework.h:9:
../../chrome/browser/privacy_sandbox/notice/notice_model.h:10:10: fatal error: 'components/privacy_sandbox/privacy_sandbox_notice.mojom.h' file not found
   10 | #include "components/privacy_sandbox/privacy_sandbox_notice.mojom.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

build failed
local:5703 remote:257 cache:29639 fallback:0 retry:0 skip:14808
reapi: ops: 30427(err:258) / r:107794(err:0) 2.81GiB / w:2230(err:0) 327.53MiB
fs: ops: 1895520(err:482908) / r:317406(err:0) 15.16GiB / w:63695(err:0) 2.11GiB
    resource/capa used(err)  wait-avg |   s m |  serv-avg |   s m |
        rbe:sched    257(0)     0.97s |█▂▃▄   |     3.46s |  ▄█▂▂ |
       rbe:worker    257(0)     0.55s |   █▂  |     2.91s |  ██▂▂ |
 remoteexec/10240    257(0)     0.00s |█      |     5.84s |   █▂▂ |

3m09.55s Build Failure: 35599 done 1 failed 0 remaining - 187.81/s
 1 steps failed: exit=1
see ./out/siso/siso_output for full command line and output
 or ./out/siso/siso.INFO
use ./out/siso/siso_failed_commands.sh to re-run failed commands

Bug: 405211100
Change-Id: I287bae5e49cc8fff6393cf47253d920abd12fec9
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6380293
Reviewed-by: Junji Watanabe <jwata@google.com>
Reviewed-by: Takuto Ikuta <tikuta@chromium.org>
Commit-Queue: Fumitoshi Ukai <ukai@google.com>
Auto-Submit: Fumitoshi Ukai <ukai@google.com>
Cr-Commit-Position: refs/heads/main@{#1435884}