Revert "[crd host][wayland] Introduce PipewireCaptureStreamManager"
This reverts commit a2e5ae4b3d55d1458e9e480223b270287b7d64eb.

Reason for revert: causing compile failure on ASan Release (32-bit x86 with V8-ARM) bot.

First build failure:
https://ci.chromium.org/ui/p/chromium/builders/ci/ASan%20Release%20(32-bit%20x86%20with%20V8-ARM)/375557/overview

Sample log:
```
../../remoting/host/linux/gnome_display_config.h:61:69: error: implicit conversion from 'unsigned long long' to 'const webrtc::ScreenId' (aka 'const int') changes value from 4294967296 to 0 [-Werror,-Wconstant-conversion]
   61 |   static constexpr webrtc::ScreenId kFirstNonVirtualScreenId = 1ULL << 32;
      |                                     ~~~~~~~~~~~~~~~~~~~~~~~~   ~~~~~^~~~~
../../remoting/host/linux/gnome_display_config.cc:20:17: error: static assertion failed due to requirement 'sizeof(int) == sizeof(long long)'
   20 |   static_assert(sizeof(webrtc::ScreenId) == sizeof(int64_t));
```

Bug: 432217140
Original change's description:
> [crd host][wayland] Introduce PipewireCaptureStreamManager
>
> Before this CL, we create a single pipewire stream when creating the
> desktop environment, then use the same stream for all
> CreateVideoCapturer calls, ignoring the screen ID parameter. This won't
> work for multi-stream/multi-window.
>
> This CL introduces a PipewireCaptureStreamManager class for managing
> pipewire screencast streams, and moves stream creation logic from
> GnomeInteractionStrategy into it. It is also responsible for inferring
> the screen ID for the newly added streams. Since the ScreenCast D-BUS
> API does not give us the connector name of the new virtual monitor, we
> have to guess it by watching for changes in the display config, and
> assuming the newly seen monitors are associated with the streams that
> are being created.
>
> Bug: 432217140
> Change-Id: I84bac9d1e47047a733a23d976bf075fdce4b310e
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6822796
> Commit-Queue: Yuwei Huang <yuweih@chromium.org>
> Reviewed-by: Lambros Lambrou <lambroslambrou@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1498514}

Bug: 432217140
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Change-Id: I366b7d1b68400e6d735f9ebc93676be60effc606
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6830325
Commit-Queue: Yuwei Huang <yuweih@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Reviewed-by: Yuwei Huang <yuweih@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1498534}