Revert "[dPWA]: Skeleton for OS Integration Sub Managers"
This reverts commit fd112e842a1db0caa219d2921de6357d78ee133a.

Reason for revert: Tree is closed because of compilation error: https://ci.chromium.org/ui/p/chromium/builders/ci/android-x86-rel/9101/overview

Original change's description:
> [dPWA]: Skeleton for OS Integration Sub Managers
>
> This CL introduces the prototype for the OS Integration sub-manager
> design and sets up the initial plumbing.
>
> DD: go/osintegrationsubmngrdd
>
> Bug: 1295044
> Change-Id: I06de9b04f8939095b2e97fa82700999519f26290
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3758034
> Commit-Queue: Dibyajyoti Pal <dibyapal@chromium.org>
> Reviewed-by: Daniel Murphy <dmurph@chromium.org>
> Reviewed-by: Phillis Tang <phillis@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1031493}

Bug: 1295044
Change-Id: Ib59cf62089ec40ef3b9d5291251831ff228df464
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3810939
Reviewed-by: Stephen McGruer <smcgruer@chromium.org>
Owners-Override: Liviu Tinta <liviutinta@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Liviu Tinta <liviutinta@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1031502}