Revert "[infra] Add isolate_profile_data mixin to Windows GPU tests"
This reverts commit 8fe1887e2919b769255877ccbcc602429dd2f3c4.

Reason for revert: Likely causing flaky CQ failures (flaky enough that
CQ basically always fails)

[snip: unrelated warning about win32con]
Traceback (most recent call last):
  File "C:\b\s\w\ir\testing\test_env.py", line 541, in <module>
    sys.exit(main())
             ^^^^^^
  File "C:\b\s\w\ir\testing\test_env.py", line 537, in main
    return run_executable(sys.argv[1:], os.environ.copy())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\b\s\w\ir\testing\test_env.py", line 463, in run_executable
    common.set_lpac_acls(ROOT_DIR, is_test_script=True)
  File "C:\b\s\w\ir\testing\scripts\common.py", line 127, in set_lpac_acls
    _grant_acls(full_filename, [('S-1-15-2-2', '(RX)')])
  File "C:\b\s\w\ir\testing\scripts\common.py", line 66, in _grant_acls
    os.makedirs(target_dir, exist_ok=True)
  File "<frozen os>", line 225, in makedirs
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\b\\s\\w\\ir\\out\\9f0d-Dawn_Win10_x64_\\chrome_100_percent.pak'


Failure Link:
https://ci.chromium.org/ui/p/chromium/builders/ci/Dawn%20Win10%20x64%20Release%20(NVIDIA)/92435/overview
https://chromium-swarm.appspot.com/task?id=79aed7d87b2b0c10
Also happening on CQ.

Original change's description:
> [infra] Add isolate_profile_data mixin to Windows GPU tests
>
> This CL adds the isolate_profile_data mixin to Windows GPU tests so that
> Swarming test isolates collect and upload .profraw code coverage profile
> files for aggregation in coverage reports.
>
> Look at bug comments for more information.
>
> Sibling CL:
> chromium-review.git.corp.google.com/c/chromium/src/+/8140821
> Control Build:
> ci.chromium.org/ui/p/chromium/builders/try/win-rel/1602109
> Fix Build:
> ci.chromium.org/ui/p/chromium/builders/try/win-rel/1602110
>
> Bug: 40917276
> Change-Id: Iad2b3c46f0248602c90a1aaf14adbd21fa0faba2
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/8140266
> Commit-Queue: Aadarsh Battula <aadarshb@google.com>
> Reviewed-by: Brian Sheedy <bsheedy@chromium.org>
> Reviewed-by: Ben Pastene <bpastene@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1668042}

Bug: 40917276
No-Tree-Checks: true
No-Try: true
Change-Id: I568754a591b7f08aaed562dfbadfaff3dccd5af5
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/8145767
Auto-Submit: Kai Ninomiya <kainino@chromium.org>
Reviewed-by: Brian Sheedy <bsheedy@chromium.org>
Bot-Commit: rubber-stamper@appspot.gserviceaccount.com <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Brian Sheedy <bsheedy@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1668301}