Revert "Refactor HashPasswordManager to accept multiple password hashes"
This reverts commit 3c6230c781c1de68657cda6bebfbcb3c15128e30.

Reason for revert:

Breaks lots of trybots.

https://logs.chromium.org/v/?s=chromium%2Fbuildbucket%2Fcr-buildbucket.appspot.com%2F8946884395716827184%2F%2B%2Fsteps%2Fcompile__with_patch_%2F0%2Fstdout

/b/swarming/w/ir/cache/goma_client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/chrome/test/browser_tests/chrome_password_protection_service_browsertest.o.d -DHAS_[.l..]rd_party/libc++abi/trunk/include --sysroot=../../build/linux/debian_sid_amd64-sysroot -fvisibility-inlines-hidden -c ../../chrome/browser/safe_browsing/chrome_password_protection_service_browsertest.cc -o obj/chrome/test/browser_tests/chrome_password_protection_service_browsertest.o
../../chrome/browser/safe_browsing/chrome_password_protection_service_browsertest.cc:491:22: error: too many arguments to function call, expected 2, have 3
                     "stub-user@example.com");
                     ^~~~~~~~~~~~~~~~~~~~~~~
../../chrome/browser/safe_browsing/chrome_password_protection_service_browsertest.cc:120:3: note: 'PrepareSyncAccount' declared here
  void PrepareSyncAccount(const std::string& hosted_domain,
  ^
1 error generated.


Original change's description:
> Refactor HashPasswordManager to accept multiple password hashes
> 
> This CL doesn't change existing behavior, but only refactor
> HashPasswordManager class such that it can keep track of multiple
> password hashes. This CL introduces a new struct PasswordHashData to
> replace SyncPassswordData.
> 
> Migration from SyncPasswordData to PasswordHashData is in place so that
> we'll not lose already captured sync password. IsSyncPasswordHashSaved
> histogram enum is added to track this migration. SyncPasswordData
> will be deprecated after the transition period.
> 
> Bug: 830998
> Cq-Include-Trybots: master.tryserver.chromium.mac:ios-simulator-cronet;master.tryserver.chromium.mac:ios-simulator-full-configs
> Change-Id: I50b52adcd1cf14a6bfddc74838019f3c7d287a99
> 
> TBR=jochen@chromium.org
> 
> Change-Id: I50b52adcd1cf14a6bfddc74838019f3c7d287a99
> Reviewed-on: https://chromium-review.googlesource.com/1036464
> Commit-Queue: Jialiu Lin <jialiul@chromium.org>
> Reviewed-by: Mustafa Emre Acer <meacer@chromium.org>
> Reviewed-by: Xiyuan Xia <xiyuan@chromium.org>
> Reviewed-by: Vadym Doroshenko <dvadym@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#557646}

TBR=xiyuan@chromium.org,meacer@chromium.org,dvadym@chromium.org,jialiul@chromium.org

Change-Id: I9c30d5a060590f6bf3fd24c2a527e5838d5308c1
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 830998
Cq-Include-Trybots: master.tryserver.chromium.mac:ios-simulator-cronet;master.tryserver.chromium.mac:ios-simulator-full-configs
Reviewed-on: https://chromium-review.googlesource.com/1054467
Reviewed-by: Avi Drissman <avi@chromium.org>
Commit-Queue: Avi Drissman <avi@chromium.org>
Cr-Commit-Position: refs/heads/master@{#557654}