Revert "[TabStrip] Refactor left/right bounds"
This reverts commit b635b635b2570c9f6ddf8f7d8ca7ccbdd9addbf4.

Reason for revert: Test failure: java.lang.AssertionError: ChromeTab should be visible. expected:<true> but was:<false>. Reverted locally and test passed https://ci.chromium.org/ui/inv/u-kaiyilin-2026-06-12-03-32-00-a739d6e4cf6721a8/test-results.

Failure Link: https://ci.chromium.org/ui/p/chromium/builders/ci/android-15-tablet-x64-rel/7642/overview

Original change's description:
> [TabStrip] Refactor left/right bounds
>
> Refactor left/right bounds.
> -Add separate methods for true bounds, (partially) visible bounds, fully
>  visible bounds, and fully visible unpinned bounds.
>
> Bug: 519335654
> Change-Id: I22f8209f020cf24298fc224c7963d150da078d0c
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7899873
> Commit-Queue: Neil Coronado <nemco@google.com>
> Reviewed-by: Zhe Li <zheliooo@google.com>
> Cr-Commit-Position: refs/heads/main@{#1645625}

Bug: 519335654
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Change-Id: Iacc4a1de8cd2a1a681557579387530a408edbd07
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7930906
Commit-Queue: Kay Lin <kaiyilin@google.com>
Bot-Commit: rubber-stamper@appspot.gserviceaccount.com <rubber-stamper@appspot.gserviceaccount.com>
Owners-Override: Kay Lin <kaiyilin@google.com>
Cr-Commit-Position: refs/heads/main@{#1645776}