Revert "Add fake typed TRACE_EVENT macros for IOS and NACL builds."
This reverts commit 60dfcf2f8893e3fbffddf3a7bad5cc7ce341390e.

Reason for revert:

FAILED: 
../../third_party/perfetto/src/protozero/message_unittest.cc:298:40: error: expected '(' for function-style cast or type construction
        MessageHandle<FakeRootMessage> handle(msg);
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
../../third_party/perfetto/src/base/test/utils.h:34:30: note: expanded from macro 'EXPECT_DCHECK_DEATH'
    GTEST_EXECUTE_STATEMENT_(statement, "PERFETTO_CHECK")
                             ^~~~~~~~~
1 error generated.

https://logs.chromium.org/logs/chromium/buildbucket/cr-buildbucket.appspot.com/8891267197314487504/+/steps/compile/0/stdout

Original change's description:
> Add fake typed TRACE_EVENT macros for IOS and NACL builds.
> 
> This allows users to not care if tracing is supported on their system.
> 
> Bug: 916074
> Change-Id: I69aa8178bb19f1a65186a2aba4f08699b6ba6ee3
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1953210
> Reviewed-by: Stephen Nusko <nuskos@chromium.org>
> Reviewed-by: Eric Seckler <eseckler@chromium.org>
> Commit-Queue: Stephen Nusko <nuskos@chromium.org>
> Auto-Submit: Stephen Nusko <nuskos@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#731514}

TBR=eseckler@chromium.org,nuskos@chromium.org

Change-Id: Ia0cc5d2a330a408898c6248378726e43ddd8a732
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 916074
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2000964
Reviewed-by: Dan Beam <dbeam@chromium.org>
Commit-Queue: Dan Beam <dbeam@chromium.org>
Cr-Commit-Position: refs/heads/master@{#731531}