Revert of Implement aura::WindowPortMus::CreateCompositorFrameSink() (patchset #27 id:620001 of https://codereview.chromium.org/2875753002/ )
Reason for revert:
Broke chromeos compile.

https://luci-logdog.appspot.com/v/?s=chromium%2Fbb%2Fchromium.chromiumos%2FChromiumOS_x86-generic_Compile%2F36632%2F%2B%2Frecipes%2Fsteps%2Fcompile%2F0%2Fstdout

[1661/3845] CXX obj/ui/aura/aura/window_port_mus.o
FAILED: obj/ui/aura/aura/window_port_mus.o
/b/c/goma_client/gomacc i686-pc-linux-gnu-g++ -B/b/c/b/ChromiumOS_x86_generic_Compile/.cros_cache/chrome-sdk/tarballs/x86-generic+9588.0.0+target_toolchain/usr/x86_64-pc-linux-gnu/i686-pc-linux-gnu/binutils-bin/2.25.51-gold -MMD -MF obj/ui/aura/aura/window_port_mus.o.d -DAURA_IMPLEMENTATION -DV8_DEPRECATION_WARNINGS -DUSE_UDEV -DUSE_ASH=1 -DUSE_AURA=1 -DUSE_NSS_CERTS=1 -DUSE_OZONE=1 -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHROMIUM_BUILD -DFIELDTRIAL_TESTING_ENABLED -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -DOS_CHROMEOS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DUSE_EGL -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DU_STATIC_IMPLEMENTATION -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_FILE -DUCHAR_TYPE=uint16_t -DSK_IGNORE_LINEONLY_AA_CONVEX_PATH_OPTS -DSK_HAS_PNG_LIBRARY -DSK_HAS_WEBP_LIBRARY -DSK_HAS_JPEG_LIBRARY -DSK_SUPPORT_GPU=1 -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DHAVE_PTHREAD -DMESA_EGL_NO_X11_HEADERS -I../.. -Igen -I../../third_party/libwebp -I../../third_party/khronos -I../../gpu -I../../third_party/ced/src -I../../third_party/icu/source/common -I../../third_party/icu/source/i18n -I../../skia/config -I../../skia/ext -I../../third_party/skia/include/c -I../../third_party/skia/include/config -I../../third_party/skia/include/core -I../../third_party/skia/include/effects -I../../third_party/skia/include/encode -I../../third_party/skia/include/images -I../../third_party/skia/include/lazy -I../../third_party/skia/include/pathops -I../../third_party/skia/include/pdf -I../../third_party/skia/include/pipe -I../../third_party/skia/include/ports -I../../third_party/skia/include/utils -I../../third_party/skia/third_party/vulkan -I../../third_party/skia/include/gpu -I../../third_party/skia/src/gpu -I../../third_party/skia/src/sksl -I../../third_party/protobuf/src -Igen/protoc_out -I../../third_party/protobuf/src -I../../third_party/boringssl/src/include -I/b/c/b/ChromiumOS_x86_generic_Compile/.cros_cache/chrome-sdk/tarballs/x86-generic+9588.0.0+sysroot_chromeos-base_chromeos-chrome.tar.xz/usr/include/nss -I/b/c/b/ChromiumOS_x86_generic_Compile/.cros_cache/chrome-sdk/tarballs/x86-generic+9588.0.0+sysroot_chromeos-base_chromeos-chrome.tar.xz/usr/include/nspr -I../../third_party/mesa/src/include -fno-strict-aliasing -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -funwind-tables -fPIC -pipe -B../../third_party/binutils/Linux_x64/Release/bin -pthread -m32 -msse2 -mfpmath=sse -mmmx -Wall -Werror -Wno-unused-local-typedefs -Wno-maybe-uninitialized -Wno-missing-field-initializers -Wno-unused-parameter -O2 -fno-ident -fdata-sections -ffunction-sections -fno-omit-frame-pointer -g2 -gsplit-dwarf --sysroot=../../../.cros_cache/chrome-sdk/tarballs/x86-generic+9588.0.0+sysroot_chromeos-base_chromeos-chrome.tar.xz -fvisibility=hidden -std=gnu++11 -Wno-narrowing -fno-rtti -fno-exceptions -fvisibility-inlines-hidden -march=i686 -pipe -march=i686 -pipe -pipe -march=i686 -mfpmath=sse -mmmx -msse -msse2 -msse3 -D__google_stl_debug_vector=1 -c ../../ui/aura/mus/window_port_mus.cc -o obj/ui/aura/aura/window_port_mus.o
../../ui/aura/mus/window_port_mus.cc: In member function 'virtual std::unique_ptr<cc::CompositorFrameSink> aura::WindowPortMus::CreateCompositorFrameSink()':
../../ui/aura/mus/window_port_mus.cc:542:10: error: cannot bind 'std::unique_ptr<viz::ClientCompositorFrameSink>' lvalue to 'std::unique_ptr<viz::ClientCompositorFrameSink>&&'
   return frame_sink;
          ^
In file included from /b/c/b/ChromiumOS_x86_generic_Compile/.cros_cache/chrome-sdk/tarballs/x86-generic+9588.0.0+target_toolchain/usr/x86_64-pc-linux-gnu/i686-pc-linux-gnu/gcc-bin/4.9.x/../../../../lib/gcc/i686-pc-linux-gnu/4.9.x/include/g++-v4/memory:81:0,
                 from ../../base/sequence_checker_impl.h:8,
                 from ../../base/sequence_checker.h:10,
                 from ../../base/memory/ref_counted.h:19,
                 from ../../base/memory/weak_ptr.h:79,
                 from ../../components/viz/client/client_compositor_frame_sink.h:9,
                 from ../../ui/aura/mus/window_port_mus.h:16,
                 from ../../ui/aura/mus/window_port_mus.cc:5:
/b/c/b/ChromiumOS_x86_generic_Compile/.cros_cache/chrome-sdk/tarballs/x86-generic+9588.0.0+target_toolchain/usr/x86_64-pc-linux-gnu/i686-pc-linux-gnu/gcc-bin/4.9.x/../../../../lib/gcc/i686-pc-linux-gnu/4.9.x/include/g++-v4/bits/unique_ptr.h:220:2: note: initializing argument 1 of 'std::unique_ptr<_Tp, _Dp>::unique_ptr(std::unique_ptr<_Up, _Ep>&&) [with _Up = viz::ClientCompositorFrameSink; _Ep = std::default_delete<viz::ClientCompositorFrameSink>; <template-parameter-2-3> = void; _Tp = cc::CompositorFrameSink; _Dp = std::default_delete<cc::CompositorFrameSink>]'
  unique_ptr(unique_ptr<_Up, _Ep>&& __u) noexcept
  ^
../../ui/aura/mus/window_port_mus.cc:543:1: error: control reaches end of non-void function [-Werror=return-type]
 }

Original issue's description:
> Implement aura::WindowPortMus::CreateCompositorFrameSink()
>
> This CL implements aura::WindowPortMus::CreateCompositorFrameSink().
> Exo will use it in Mushrome and Mustash to create a frame sink
> and use it to submit frames.
>
>
> BUG=720600
>
> Review-Url: https://codereview.chromium.org/2875753002
> Cr-Commit-Position: refs/heads/master@{#478287}
> Committed: https://chromium.googlesource.com/chromium/src/+/810bd6f44ea3be0e7ff4522190cf2e4924769e17

TBR=reveman@chromium.org,fsamuel@chromium.org,fsamuel@google.com,kylechar@chromium.org,sadrul@chromium.org,sky@chromium.org,penghuang@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=720600

Review-Url: https://codereview.chromium.org/2934523002
Cr-Commit-Position: refs/heads/master@{#478304}