Revert "Delete components/reporting/proto/interface.proto"
This reverts commit 273f3702edfdf26bab7eee5d94b632bcf9e46289.

Reason for revert: Broke compile on https://ci.chromium.org/ui/p/chromium/builders/ci/chromeos-kevin-rel/42753/overview

FAILED: obj/chromeos/dbus/missive/missive/fake_missive_client.o
../../build/cros_cache/chrome-sdk/symlinks/kevin+14844.0.0+target_toolchain/bin/armv7a-cros-linux-gn...(too long)
In file included from ../../chromeos/dbus/missive/fake_missive_client.cc:5:
In file included from ../../chromeos/dbus/missive/fake_missive_client.h:11:
../../chromeos/dbus/missive/missive_client.h:13:10: fatal error: 'components/reporting/proto/interface.pb.h' file not found
#include "components/reporting/proto/interface.pb.h"
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Original change's description:
> Delete components/reporting/proto/interface.proto
>
> Instead, we should use `components/reporting/proto/synced/interface.proto`.
>
> `components/reporting/proto/synced/interface.proto` is made to keep up
> with the deleted `interface.proto`.
>
> Bug: None
> Change-Id: I992ed72bfb5e7745f2729ffbe9e2f2b658652c79
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3662121
> Commit-Queue: Hong Xu <xuhong@google.com>
> Reviewed-by: Leonid Baraz <lbaraz@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1006599}

Bug: None
Change-Id: I435cab3d57d0c015a7c5ddd61935cff0f5da480c
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3662202
Owners-Override: Marijn Kruisselbrink <mek@chromium.org>
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Auto-Submit: Marijn Kruisselbrink <mek@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Cr-Commit-Position: refs/heads/main@{#1006620}