Revert "Adding DumpAccessibilityTree Tests (8 of 20)"
This reverts commit 711d923e3b9dd778e482f991f280e6dd937d1abf.

flaky a bunch of times. as an example, see
http://build.chromium.org/p/chromium.win/builders/Win7%20Tests%20%28dbg%29%282%29/builds/22538/steps/content_browsertests/logs/AccessibilityFrameset
DumpAccessibilityTreeTest.AccessibilityFrameset (run #1):
[ RUN      ] DumpAccessibilityTreeTest.AccessibilityFrameset
Testing: E:\b\build\slave\Win7_Tests__dbg__2_\build\src\content\test\data\accessibility\frameset.html
c:\b\build\slave\win_builder__dbg_\build\src\content\browser\accessibility\dump_accessibility_tree_browsertest.cc(252): error: Value of: is_different
  Actual: true
Expected: false
[3080:2208:0913/171203:4867433:WARNING:channel.cc(211)] WriteMessage() while shutting down
* Line Expected
- ---- --------
     1 ROLE_SYSTEM_DOCUMENT READONLY FOCUSABLE
     2     ROLE_SYSTEM_CLIENT FOCUSABLE
     3         IA2_ROLE_SCROLL_PANE
     4             ROLE_SYSTEM_DOCUMENT READONLY FOCUSABLE
     5                 IA2_ROLE_PARAGRAPH
     6                     ROLE_SYSTEM_STATICTEXT name='My favorite browser is '
     7                     ROLE_SYSTEM_STATICTEXT name='ABC'
     8                     ROLE_SYSTEM_STATICTEXT name='Chrome'
     9                     ROLE_SYSTEM_STATICTEXT name='!'
    10     ROLE_SYSTEM_CLIENT FOCUSABLE
    11         IA2_ROLE_SCROLL_PANE
    12             ROLE_SYSTEM_DOCUMENT READONLY FOCUSABLE
*   13                 IA2_ROLE_PARAGRAPH
    14                     ROLE_SYSTEM_STATICTEXT name='This test is to check '
    15                     ROLE_SYSTEM_STATICTEXT name='mark tag'
    16                     ROLE_SYSTEM_STATICTEXT name='.'
    17 \u003C-- End-of-file -->

Actual
------
ROLE_SYSTEM_DOCUMENT READONLY FOCUSABLE
    ROLE_SYSTEM_CLIENT FOCUSABLE
        IA2_ROLE_SCROLL_PANE
            ROLE_SYSTEM_DOCUMENT READONLY FOCUSABLE
                IA2_ROLE_PARAGRAPH
                    ROLE_SYSTEM_STATICTEXT name='My favorite browser is '
                    ROLE_SYSTEM_STATICTEXT name='ABC'
                    ROLE_SYSTEM_STATICTEXT name='Chrome'
                    ROLE_SYSTEM_STATICTEXT name='!'
    ROLE_SYSTEM_CLIENT FOCUSABLE
        IA2_ROLE_SCROLL_PANE
            ROLE_SYSTEM_DOCUMENT READONLY FOCUSABLE

[  FAILED  ] DumpAccessibilityTreeTest.AccessibilityFrameset, where TypeParam =  and GetParam() =  (1903 ms)

BUG=

Review URL: https://codereview.chromium.org/567223002

Cr-Commit-Position: refs/heads/master@{#294764}