Revert of Move more vector icons to respective directories and update code to (patchset #1 id:1 of https://codereview.chromium.org/2620613005/ )
Reason for revert:
Hey,

The change in #15 has broken chromium os builds:

obj/chrome/browser/ui/libui.a(browser_header_painter_ash.o):../../chrome/browser/ui/views/frame/browser_header_painter_ash.cc:function BrowserHeaderPainterAsh::UpdateCaptionButtons(): error: undefined reference to 'ash::kWindowControlMinimizeIcon'
obj/chrome/browser/ui/libui.a(browser_header_painter_ash.o):../../chrome/browser/ui/views/frame/browser_header_painter_ash.cc:function BrowserHeaderPainterAsh::UpdateCaptionButtons(): error: undefined reference to 'ash::kWindowControlCloseIcon'
obj/chrome/browser/ui/libui.a(browser_header_painter_ash.o):../../chrome/browser/ui/views/frame/browser_header_painter_ash.cc:function BrowserHeaderPainterAsh::UpdateCaptionButtons(): error: undefined reference to 'ash::kWindowControlLeftSnappedIcon'
obj/chrome/browser/ui/libui.a(browser_header_painter_ash.o):../../chrome/browser/ui/views/frame/browser_header_painter_ash.cc:function BrowserHeaderPainterAsh::UpdateCaptionButtons(): error: undefined reference to 'ash::kWindowControlRightSnappedIcon'
obj/chrome/browser/ui/libui.a(browser_header_painter_ash.o):../../chrome/browser/ui/views/frame/browser_header_painter_ash.cc:function BrowserHeaderPainterAsh::UpdateCaptionButtons(): error: undefined reference to 'ash::kWindowControlRestoreIcon'
obj/chrome/browser/ui/libui.a(browser_header_painter_ash.o):../../chrome/browser/ui/views/frame/browser_header_painter_ash.cc:function BrowserHeaderPainterAsh::UpdateCaptionButtons(): error: undefined reference to 'ash::kWindowControlMaximizeIcon'

The new icon constants are not checked in. I will revert to unblock the build.

Original issue's description:
> Move more vector icons to respective directories and update code to
> use gfx::VectorIcon structs instead of the VectorIconId enum.
>
> Also add version of ImageButton::SetImage that takes a const ref image.
>
> BUG=626786
>
> Review-Url: https://codereview.chromium.org/2620613005
> Cr-Commit-Position: refs/heads/master@{#442488}
> Committed: https://chromium.googlesource.com/chromium/src/+/f5157480667e99269e0062e9df1df3875db85197

TBR=sky@chromium.org,estade@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=626786

Review-Url: https://codereview.chromium.org/2618383004
Cr-Commit-Position: refs/heads/master@{#442595}