Revert "mb: Make check for generated `data` directories work on Win and enable there."
This reverts commit 02536c5796a2d3485b99082563477f8d85691025.

Reason for revert: suspect Step('generate .isolate files') failure on Deterministic Linux(dbg) bot

Sample build: https://ci.chromium.org/p/chromium/builders/ci/Deterministic%20Linux%20%28dbg%29/10441
(The 10441 contains only #690259)

Sample log: https://logs.chromium.org/logs/chromium/buildbucket/cr-buildbucket.appspot.com/8904094727741717040/+/steps/generate_.isolate_files/0/stdout?format=raw
---
/b/s/w/ir/cache/builder/src/buildtools/linux64/gn gen //out/Debug --runtime-deps-list-file=/b/s/w/ir/cache/builder/src/out/Debug/runtime_deps
Done. Made 11992 targets from 2025 files in 6457ms
error: gn `data` items may not list generated directories; list files in directory instead for:
//out/Debug/../apprtc/out/app_engine/
//out/Debug/../apprtc/temp/google-cloud-sdk/
//out/Debug/../collider/
---


Original change's description:
> mb: Make check for generated `data` directories work on Win and enable there.
> 
> The line `os.path.normpath(self.PathJoin(build_dir, f))` had two problems
> on Windows:
> 
> 1. Since `build_dir` was something like `//out/Release`, on Windows normpath
>    wouldn't resolve '..' against it, so `//out/Release/../../net/data`
>    would become `\\out\Release\net\data`
> 
> 2. The slash flipping for `path` made the `path.startswith(build_dir)` always
>    fail.
> 
> Just remove `path` completely and check if `f` starts with '../../' to find
> directories that are not in the build dir instead.
> 
> Also mixing stderr and stdout on Windows produced strange output, so print
> the error message to stdout instead.
> 
> The Windows build doesn't have any additional violations, so no new
> whitelist entries are needed.
> 
> Bug: 912946
> Change-Id: I4db9850103751b4736e5990caddddc9dd223786d
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1769205
> Reviewed-by: Takuto Ikuta <tikuta@chromium.org>
> Commit-Queue: Takuto Ikuta <tikuta@chromium.org>
> Commit-Queue: Nico Weber <thakis@chromium.org>
> Auto-Submit: Nico Weber <thakis@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#690259}

TBR=thakis@chromium.org,tikuta@chromium.org

Change-Id: I4379320c19d3ce29b0a24ecd247a3a59b0a5c562
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 912946
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1771103
Reviewed-by: Takashi Sakamoto <tasak@google.com>
Commit-Queue: Takashi Sakamoto <tasak@google.com>
Cr-Commit-Position: refs/heads/master@{#690269}