Reland "siso: Enable remote execution for Rust clippy actions"
This reverts commit 53a072fcdbd9ac9dee34dcfde92e5e30dd9ae3a3.

Reason for revert: This CL includes a fix for missing inputs for clippy
actions.

Original change's description:
> Revert "siso: Enable remote execution for Rust clippy actions"
>
> This reverts commit 6d38d7903d6bcb11ca880e978bad1b2d971ce0af.
>
> Reason for revert:
> https://ci.chromium.org/ui/p/chromium/builders/build/linux-build-perf-siso/12021/overview
> ```
> python3 ../../build/rust/gni_impl/clippy_wrapper.py --clippy-driver ../../third_party/rust-toolchain/bin/clippy-driver --rustc-env-and-flags clang_x64_for_rust_host_build_tools/obj/build/rust/allocator/allocator.rustflags.json --build-stamp-file clang_x64_for_rust_host_build_tools/obj/build/rust/allocator/allocator.clippy
> Traceback (most recent call last):
>   File "/b/f/w/out/x/../../build/rust/gni_impl/clippy_wrapper.py", line 13, in <module>
>     from rustc_wrapper import (ConvertPathsToAbsolute, LoadRustEnvAndFlags,
>   File "/b/f/w/build/rust/gni_impl/rustc_wrapper.py", line 21, in <module>
>     import action_helpers
> ModuleNotFoundError: No module named 'action_helpers'
> remote-exec ddbbd34cb683a1025a83c0062d189e35535ca9535537ba851b22c5bf982c3eed/147 failed: exit=1
> ```
>
> Original change's description:
> > siso: Enable remote execution for Rust clippy actions
> >
> > The Rust clippy actions have been settled for a while.
> > Let's enable remote execution.
> >
> > Bug: 487271213
> > Change-Id: I3a0e41c5f0dfc2078c44623fdf938bc2b2989924
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7755000
> > Reviewed-by: Łukasz Anforowicz <lukasza@chromium.org>
> > Commit-Queue: Junji Watanabe <jwata@google.com>
> > Cr-Commit-Position: refs/heads/main@{#1614097}
>
> Bug: 487271213
> No-Presubmit: true
> No-Tree-Checks: true
> No-Try: true
> Change-Id: I5e39069b2c685bdaa46873b89fbb975ae03f5e4f
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7760782
> Bot-Commit: rubber-stamper@appspot.gserviceaccount.com <rubber-stamper@appspot.gserviceaccount.com>
> Reviewed-by: Junji Watanabe <jwata@google.com>
> Commit-Queue: Junji Watanabe <jwata@google.com>
> Reviewed-by: Takuto Ikuta <tikuta@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1614173}

Bug: 487271213
Change-Id: I1867198f74abb0f345787f2c8a99c0bcc1985bb5
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7762144
Commit-Queue: Junji Watanabe <jwata@google.com>
Reviewed-by: Łukasz Anforowicz <lukasza@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1614786}