python3, not python in chrome/tools/build presubmit
When running "git cl presubmit --all" or, more quickly, this command:

    git cl presubmit --files=chrome/tools/build/* --force

an exception is halted because the presubmit tries to run python instead
of python3. This halts the presubmit run, thus hiding all other
presubmit warnings and errors.

    OSError: Execution failed with error: [Errno 2]
    No such file or directory: 'python'.

Bug: 1309977
Change-Id: Ic1312ce906dcbad66a66021e5948e75325f6815c
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3575682
Auto-Submit: Bruce Dawson <brucedawson@chromium.org>
Owners-Override: Wanda Mora <morawand@google.com>
Reviewed-by: David Trainor <dtrainor@chromium.org>
Commit-Queue: David Trainor <dtrainor@chromium.org>
Cr-Commit-Position: refs/heads/main@{#990288}