Revert of Linux: Sync GetDesktopName in gtk2_util.cc (patchset #2 id:20001 of https://codereview.chromium.org/2195063003/ )
Reason for revert:
Broke Linux GN build on my desktop (linker error):

obj/chrome/browser/ui/libgtk2ui/libgtk2ui/gtk2_util.o:../../chrome/browser/ui/libgtk2ui/gtk2_util.cc:function libgtk2ui::GetDesktopName(base::Environment*): error: undefined reference to 'chrome::GetChannel()'
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Contents of my out/Release/args.gn:

  is_component_build = true
  is_debug = false
  is_chrome_branded = true
  dcheck_always_on = true
  use_goma = true

Original issue's description:
> Linux: Sync GetDesktopName in gtk2_util.cc
>
> BUG=632841
>
> Committed: https://crrev.com/12d7c7f1f6a38f067803c676e5cac9cccc11dab2
> Cr-Commit-Position: refs/heads/master@{#408846}

TBR=thestig@chromium.org,thomasanderson@google.com
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=632841

Review-Url: https://codereview.chromium.org/2196073002
Cr-Commit-Position: refs/heads/master@{#408880}