Revert "Enable -Wunused-but-set-variable."
This reverts commit 8dee7275fc1d41784d3302380c148d05a2a1e301.

Reason for revert: [sheriff] Suspected to cause compile failure on https://ci.chromium.org/p/chromium/builders/ci/Linux%20Builder%20(dbg)(32)/188864 

[16816/51501] CXX obj/components/policy/core/common/internal/policy_statistics_collector.o
FAILED: obj/components/policy/core/common/internal/policy_statistics_collector.o
/b/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF...(too long)
../../components/policy/core/common/policy_statistics_collector.cc:103:10: error: variable 'group_has_conflicts' set but not used [-Werror,-Wunused-but-set-variable]
bool group_has_conflicts = false;
^
1 error generated.


Original change's description:
> Enable -Wunused-but-set-variable.
>
> Bug: 1203071
> Change-Id: Ia68fb963a35a107b5f1d91b38bea27002520af12
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3116869
> Commit-Queue: Dirk Pranke <dpranke@google.com>
> Auto-Submit: Peter Kasting <pkasting@chromium.org>
> Reviewed-by: Dirk Pranke <dpranke@google.com>
> Cr-Commit-Position: refs/heads/main@{#932217}

Bug: 1203071
Change-Id: I9d51eb373417439e48a2b925d40c84dc998e0d6b
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3227536
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Alex Moshchuk <alexmos@chromium.org>
Owners-Override: Alex Moshchuk <alexmos@chromium.org>
Cr-Commit-Position: refs/heads/main@{#932222}