grit: use write instead of writelines for strings
The writelines func expects an iterable of bytes-like objects.  If you
pass it bytes in Python 3, iteration yields integers which write does
not accept causing it to blow up.  For example:
  >>> fp = open('/dev/null', 'wb')
  >>> fp.writelines(b'asdf')
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
  TypeError: a bytes-like object is required, not 'int'

Handle this difference ourselves by only calling write on strings/bytes
and writelines for everything else (assuming they're iterable).

Bug: 983071
Test: `./grit/test_suite_all.py` passes
Change-Id: I3bdf65f1a3a42e782fc811b0afbdb8fe2ab13d2e
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1756089
Commit-Queue: Mike Frysinger <vapier@chromium.org>
Reviewed-by: Nico Weber <thakis@chromium.org>
Cr-Commit-Position: refs/heads/master@{#687492}