Revert "Send right system capture muted status"
This reverts commit 8b2d3aa31ba24a6ce76df097ce56f6509994c9a8.

Reason for revert: Build failure:

% autoninja -C out_$BOARD/Release chrome nacl_helper
ninja: Entering directory `out_betty-pi-arc/Release'
[0/1] Regenerating ninja files
[5140/19834] CXX obj/media/audio/audio/cras_input.o
FAILED: obj/media/audio/audio/cras_input.o 
../../media/audio/cras/cras_input.cc:445:3: error: use of undeclared identifier 'libcras_client_get_system_capture_muted'; did you mean 'cras_client_set_system_capture_mute'?
  libcras_client_get_system_capture_muted(client_, &muted);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  cras_client_set_system_capture_mute
../../build/cros_cache/chrome-sdk/symlinks/betty-pi-arc+14929.0.0+sysroot_chromeos-base_chromeos-chrome.tar.xz/usr/include/cras_client.h:797:5: note: 'cras_client_set_system_capture_mute' declared here
int cras_client_set_system_capture_mute(struct cras_client *client, int mute);
    ^
../../media/audio/cras/cras_input.cc:445:43: error: cannot initialize a parameter of type 'struct cras_client *' with an lvalue of type 'struct libcras_client *'
  libcras_client_get_system_capture_muted(client_, &muted);
                                          ^~~~~~~
../../build/cros_cache/chrome-sdk/symlinks/betty-pi-arc+14929.0.0+sysroot_chromeos-base_chromeos-chrome.tar.xz/usr/include/cras_client.h:797:61: note: passing argument to parameter 'client' here
int cras_client_set_system_capture_mute(struct cras_client *client, int mute);
                                                            ^
2 errors generated.

Original change's description:
> Send right system capture muted status
>
> Implement CrasInputStream::IsMuted to get real system capture muted
> status on chrome os.
>
> Bug: b/235164478
> Test: Open Google meet and muted system capture. See if there is a hint tell you your mic is muted by system.
>
> Change-Id: I7b3c32fea7c8441380b1e50853aeee2291682476
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3709279
> Reviewed-by: Dale Curtis <dalecurtis@chromium.org>
> Commit-Queue: Ching Yun Chang <whalechang@google.com>
> Reviewed-by: Yu-Hsuan Hsu <yuhsuan@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1020729}

Bug: b/235164478
Change-Id: Ib496c1b875c2dc6fa6066b1c7e1582c996da39b0
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3749218
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Auto-Submit: Leonid Baraz <lbaraz@chromium.org>
Reviewed-by: Dale Curtis <dalecurtis@chromium.org>
Commit-Queue: Dale Curtis <dalecurtis@chromium.org>
Commit-Queue: Leonid Baraz <lbaraz@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1021296}