Revert "Reland "[SidePanelPinning] Add enabled state for global sidepanel actions upon creation.""
This reverts commit 45cd253668d1d312bc22ef481dc8a94b43618bb8.

Reason for revert: Compile failure on webview bot:

https://ci.chromium.org/ui/p/chrome/builders/ci/webview-arm64-rel-ready

Log:
...
../../chrome/browser/ui/signin/signin_view_controller.h:27:2: error: This file should only be included on desktop.

Original change's description:
> Reland "[SidePanelPinning] Add enabled state for global sidepanel actions upon creation."
>
> This is a reland of commit f7c0ae27e475343c5f153df5510bd7b422345ffc
>
> Original change's description:
> > [SidePanelPinning] Add enabled state for global sidepanel actions upon creation.
> >
> > This also modifies the enabled state for the action item tied to the search companion.
> >
> > Change-Id: I5d12303626f115d7b5703209487ec3d1cbd739db
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4939375
> > Reviewed-by: Caroline Rising <corising@chromium.org>
> > Code-Coverage: findit-for-me@appspot.gserviceaccount.com <findit-for-me@appspot.gserviceaccount.com>
> > Commit-Queue: Shibalik Mohapatra <shibalik@chromium.org>
> > Cr-Commit-Position: refs/heads/main@{#1214460}
>
> Change-Id: I4d666af67986d42af4e50f5527b25adf0c44675f
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4975869
> Reviewed-by: Caroline Rising <corising@chromium.org>
> Commit-Queue: Shibalik Mohapatra <shibalik@chromium.org>
> Code-Coverage: findit-for-me@appspot.gserviceaccount.com <findit-for-me@appspot.gserviceaccount.com>
> Cr-Commit-Position: refs/heads/main@{#1215073}

Change-Id: I8959bfe3be81b1e01d284e191074e95dcec253e5
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4977112
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Matthew Jones <mdjones@chromium.org>
Owners-Override: Matt Jones <mdjones@google.com>
Cr-Commit-Position: refs/heads/main@{#1215114}