remote linking for Android x64 Builder All Targets (dbg)
To mitigate bot died (probably due to OOM),
use remote linking for the builder, so let heavly link action
off-load to the RBE worker.

It won't work output_local_strategy=minimum, as some java steps
failed due to file not found error.

[33995/193974] 5m30.87s F ACTION //thi...d/toolchain/android:android_clang_x64)
FAILED: e9d8a043-ea40-48ce-aa0d-8afcc5b325cc "./obj/third_party/android_sdk/window_extensions/androidx_window_extensions_java__validate.bytecode.stamp" ACTION //third_party/android_sdk/window_extensions:androidx_window_extensions_java__validate(//build/toolchain/android:android_clang_x64)
err: exit=1
python3 ../../build/android/gyp/check_for_missing_direct_deps.py --depfile gen/third_party/android_sdk/window_extensions/androidx_window_extensions_java__validate.d --target-name //third_party/android_sdk/window_extensions:androidx_window_extensions_java__validate --gn-target=//third_party/android_sdk/window_extensions:androidx_window_extensions_java --input-jar obj/third_party/android_sdk/window_extensions/androidx_window_extensions_java.javac.jar --stamp obj/third_party/android_sdk/window_extensions/androidx_window_extensions_java__validate.bytecode.stamp --chromium-output-dir . --direct-classpath-jars=@FileArg\(gen/third_party/android_sdk/window_extensions/androidx_window_extensions_java.build_config.json:interface_classpath\) --full-classpath-jars=@FileArg\(gen/third_party/android_sdk/window_extensions/androidx_window_extensions_java.build_config.json:javac_full_interface_classpath\) --full-classpath-gn-targets=@FileArg\(gen/third_party/android_sdk/window_extensions/androidx_window_extensions_java.build_config.json:javac_full_classpath_targets\) --sdk-classpath-jars=@FileArg\(gen/third_party/android_sdk/window_extensions/androidx_window_extensions_java.build_config.json:sdk_jars\) --warnings-as-errors
build step: __third_party_android_sdk_window_extensions_androidx_window_extensions_java__validate___build_toolchain_android_android_clang_x64__rule "./obj/third_party/android_sdk/window_extensions/androidx_window_extensions_java__validate.bytecode.stamp"
stderr:
Traceback (most recent call last):
  File "/usr/local/google/home/ukai/src/chromium/src/out/android/../../build/android/gyp/check_for_missing_direct_deps.py", line 305, in <module>
    sys.exit(main(sys.argv))
             ^^^^^^^^^^^^^^
  File "/usr/local/google/home/ukai/src/chromium/src/out/android/../../build/android/gyp/check_for_missing_direct_deps.py", line 289, in main
    _EnsureDirectClasspathIsComplete(
  File "/usr/local/google/home/ukai/src/chromium/src/out/android/../../build/android/gyp/check_for_missing_direct_deps.py", line 89, in _EnsureDirectClasspathIsComplete
    deps = jar_utils.extract_full_class_names_from_jar(jar)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/google/home/ukai/src/chromium/src/build/android/gyp/util/jar_utils.py", line 70, in extract_full_class_names_from_jar
    with zipfile.ZipFile(jar_path) as z:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/google/home/ukai/depot_tools/bootstrap-2@3.11.8.chromium.35_bin/python3/lib/python3.11/zipfile.py", line 1286, in __init__
    self.fp = io.open(file, filemode)
              ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'obj/third_party/kotlin_stdlib/kotlin_stdlib_java.ijar.jar'

Bug: 414960420
Change-Id: Iaf787b838b7ce6cbaaae0f308181c15b294639f6
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6567127
Auto-Submit: Fumitoshi Ukai <ukai@google.com>
Reviewed-by: Takuto Ikuta <tikuta@chromium.org>
Reviewed-by: Junji Watanabe <jwata@google.com>
Commit-Queue: Fumitoshi Ukai <ukai@google.com>
Cr-Commit-Position: refs/heads/main@{#1462586}