Re-fix TFLite build error on linux when using the system zlib
In commit ae0f9adb7e14c0d19ca695ef6ad40b321a8cb64c, I fixed some build
errors related to minizip patch inclusion in TFLite. However, after that
when TFLite Support was rolled to HEAD, a small part of that patch got
dropped. The result is the following build error with 107.0.5304.62:

../../third_party/tflite_support/src/tensorflow_lite_support/metadata/cc/utils/zip_readonly_mem_file.cc:22:10: fatal error: 'contrib/minizip/ioapi.h' file not found
         ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

This commit re-adds the lost fix.

R=junzou@chromium.org

Change-Id: Ie96c3571894b5100a1e2a2771da29699eff0beb3
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3972087
Reviewed-by: Robert Ogden <robertogden@chromium.org>
Commit-Queue: Robert Ogden <robertogden@chromium.org>
Auto-Submit: Andres Salomon <dilinger@queued.net>
Cr-Commit-Position: refs/heads/main@{#1063478}