Revert "Define 2 new tab width experiments"
This reverts commit a12900df432a692d220ca56233305a59cc37059c.

Reason for revert: Compile failures on multiple Android bots.  Example: https://ci.chromium.org/p/chromium/builders/ci/android-11-x86-rel/2759

[20053/39209] CXX obj/chrome/browser/browser/about_flags.o
FAILED: obj/chrome/browser/browser/about_flags.o
../../buildtools/reclient/rewrapper -cfg=../../buildtools/reclient_cfgs/chromium-browser-clang/rewra...(too long)
../../chrome/browser/about_flags.cc:2646:12: error: no member named 'size' in namespace 'base'
base::size(kBookmarksRefreshNormal), nullptr},
~~~~~~^
../../chrome/browser/about_flags.cc:2648:12: error: no member named 'size' in namespace 'base'
base::size(kBookmarksRefreshCompact), nullptr},
~~~~~~^
../../chrome/browser/about_flags.cc:2650:12: error: no member named 'size' in namespace 'base'
base::size(kBookmarksRefreshVisuals), nullptr},
~~~~~~^


Original change's description:
> Define 2 new tab width experiments
>
> This CL adds 2 min tab width experiment parameters for the Tab Strip
> Improvements feature. One experiment is for 108dp and another for 156dp.
>
> Screenshots:
> 108 dp: https://screenshot.googleplex.com/AzbBXm9ymRdqdZe.png
> 156 dp: https://screenshot.googleplex.com/BFXptKeTRGs3Hxn.png
>
> Bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1296999
> Change-Id: I4a484f488014d448f3d0a3ed06c47828d5a3f237
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3491655
> Reviewed-by: Theresa Sullivan <twellington@chromium.org>
> Commit-Queue: Gaurav Jayasawal <gauravjj@google.com>
> Cr-Commit-Position: refs/heads/main@{#975995}

Bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1296999
Change-Id: I319f727f1e18ec0a0b11bddad8fc110612372d98
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3496078
Auto-Submit: Alex Moshchuk <alexmos@chromium.org>
Owners-Override: Alex Moshchuk <alexmos@chromium.org>
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Cr-Commit-Position: refs/heads/main@{#976013}