Revert "Reland "[side search] Use the monochrome icon for side search""
This reverts commit cc7e41379e8870894183524343fc58eef2d36a1a.

Reason for revert: causing build failures on lacros:
https://ci.chromium.org/p/chrome/builders/ci/lacros-arm-generic-chrome

[11346/11658] CXX obj/chrome/browser/ui/ui/side_search_browser_controller.o
FAILED: obj/chrome/browser/ui/ui/side_search_browser_controller.o
../../build/cros_cache/chrome-sdk/symlinks/arm-generic+14284.0.0+target_toolchain/bin/armv7a-cros-li...(too long)
../../chrome/browser/ui/views/side_search/side_search_browser_controller.cc:276:33: error: use of undeclared identifier 'kGoogleGLogoMonochromeIcon'
toolbar_button->SetVectorIcon(kGoogleGLogoMonochromeIcon);

Original change's description:
> Reland "[side search] Use the monochrome icon for side search"
>
> This is a reland of 3ecb9de273af3d23e43c058a0207e9391275d9ce
>
> Original change's description:
> > [side search] Use the monochrome icon for side search
> >
> > This CL updates the side search toolbar icon to use the new
> > monochrome Google G icon. This new icon does not use hardcoded
> > colors for the Google G and matches the size of the other
> > toolbar icons.
> >
> > Bug: 1260144
> > Change-Id: Ia7392f72881aab84840bc01b9a1b26275acc2de5
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3224343
> > Commit-Queue: Thomas Lukaszewicz <tluk@chromium.org>
> > Commit-Queue: Robert Liao <robliao@chromium.org>
> > Reviewed-by: Robert Liao <robliao@chromium.org>
> > Cr-Commit-Position: refs/heads/main@{#931732}
>
> Bug: 1260144
> Change-Id: I0962601c0dbf6c804dc587d76b71c065669d81af
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3227299
> Reviewed-by: Thomas Lukaszewicz <tluk@chromium.org>
> Commit-Queue: Robert Liao <robliao@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#932120}

Bug: 1260144
Change-Id: If58255b2565f87b72b2ee04e63d313edad5b7f28
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3227002
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Reviewed-by: Thomas Lukaszewicz <tluk@chromium.org>
Commit-Queue: Yi Gu <yigu@chromium.org>
Cr-Commit-Position: refs/heads/main@{#932154}