Revert "[Clank CBCM] Adds more test cases to FirstRunIntegrationTest"
This reverts commit 5d05a6e07f060f4a71ee9a14f2a4f50cd8ecdd4d.

Reason for revert:
Error: Default interface methods are only supported starting with Android N (--min-api 24): Lorg/chromium/base/supplier/ObservableSupplier;hasValue()Z

Original change's description:
> [Clank CBCM] Adds more test cases to FirstRunIntegrationTest
>
> This CL extends the test coverage of FirstRunIntegrationTest by
> allowing tests with all promos enabled or disabled (today, only the
> enabled cases for Data Saver and Sync promos are covered), and more
> tests for onBackPressed during FRE.
>
> This refactoring is part of a larger goal to skip FRE promos disabled
> by cloud policy when policies are received before a promo is shown.
> A follow-up CL will change FirstRunActivity to react to changes in
> preferences due to cloud policies being set after FR started, and
> integration tests will need to cover more cases as well. Because of
> that, I decided to send this CL separately to make review easier.
>
> Other than the additional tests, this CL also mock settings for
> Sign-in/Sync enabled and Data Saver enabled in FirstRunIntegrationTest,
> so we can test all the possible combinations.
>
> Tests for the new sign-in flow on FRE will be added later.
>
> Please notice that we preferred not to use parametrized tests because
> not all tests on this file make sense to be run with multiple
> configurations.
>
> Bug: 1203435
> Change-Id: If2423e288f9f87e145aa99afece8ee5be99c7de2
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3081379
> Commit-Queue: Jan Krcal <jkrcal@chromium.org>
> Auto-Submit: Fabio Tirelo <ftirelo@chromium.org>
> Reviewed-by: Jan Krcal <jkrcal@chromium.org>
> Reviewed-by: Sky Malice <skym@chromium.org>
> Reviewed-by: Wenyu Fu <wenyufu@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#922795}

Bug: 1203435
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Change-Id: I3324f6f1de44c23933244b5a98126e2fd1f47690
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3171053
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Owners-Override: Swapnil Gupta <swapnilgupta@google.com>
Auto-Submit: Swapnil Gupta <swapnilgupta@google.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Cr-Commit-Position: refs/heads/main@{#922853}