Fix compile error in color_space.cc: Wsign-compare
Fix the CHECK expression in color_space.cc to compare two signed
ints, instead of a signed with an unsigned one.

Excerpt from the error message:

  ../../base/check_op.h:191:26: error: comparison of integers of
  different signs: 'int' and 'unsigned int' [-Werror,-Wsign-compare]

  ../../components/exo/wayland/clients/color_space.cc:33:3: note: in
  instantiation of function template specialization
  'logging::CheckEQImpl<int, unsigned int, 0>' requested here
  	  CHECK_EQ(gbm_bo_get_plane_count(bo), 1u);

This was seen in the clang-tidy builds (probably they're using slightly
different build settings than the regular Chrome builds).

Bug: none
Change-Id: I8e929691560b1485e4fd5c05a4fb83f2c4c1a5be
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2548464
Commit-Queue: Maksim Ivanov <emaxx@chromium.org>
Commit-Queue: Daniele Castagna <dcastagna@chromium.org>
Auto-Submit: Maksim Ivanov <emaxx@chromium.org>
Reviewed-by: Daniele Castagna <dcastagna@chromium.org>
Cr-Commit-Position: refs/heads/master@{#829054}