Fix invalid characters in policy_templates.json
policy_templates.json contained invalid characters to represent
copyright symbols. Switch to UTF-8.

Also change the PRESUBMIT check for policy_templates.json to
fail if the file is not correctly UTF-8 encoded. On bad econding,
the PRESUBMIT will fail with an error resembling this:
>>>
Traceback (most recent call last):
File "/usr/local/google/home/pmarko/chromium2/src/components/policy/tools/syntax_check_policy_template_json.py", line 454, in Main
   data = eval(f.read().decode("UTF-8"))
File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
   return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xae in position 463499: invalid start byte
Error: Invalid Python/JSON syntax.
<<<

BUG=none

Change-Id: I5954c5a2c8e5a72fa36578918168338fb9000095
Reviewed-on: https://chromium-review.googlesource.com/632058
Reviewed-by: Maksim Ivanov <emaxx@chromium.org>
Commit-Queue: Pavol Marko <pmarko@chromium.org>
Cr-Commit-Position: refs/heads/master@{#497050}