Revert of Don't handle NaturalScroll in Chrome but pass it to CMT instead (https://codereview.chromium.org/212603005/)
Reason for revert:
Has caused many compile failures.  We think the trybots didn't catch it because they didn't build ash_unittests.

Example:
http://build.chromium.org/p/chromium.chromiumos/builders/Linux%20ChromiumOS%20Builder%20%28dbg%29/builds/46547

../../ash/sticky_keys/sticky_keys_unittest.cc: In member function 'virtual void ash::StickyKeysTest_ScrollEventOneshot_Test::TestBody()':
../../ash/sticky_keys/sticky_keys_unittest.cc:622:41:error: 'class ui::DeviceDataManager' has no member named 'set_natural_scroll_enabled'
../../ash/sticky_keys/sticky_keys_unittest.cc: In member function 'virtual void ash::StickyKeysTest_ScrollDirectionChanged_Test::TestBody()':
../../ash/sticky_keys/sticky_keys_unittest.cc:674:41:error: 'class ui::DeviceDataManager' has no member named 'set_natural_scroll_enabled'
../../ash/sticky_keys/sticky_keys_unittest.cc: In member function 'virtual void ash::StickyKeysTest_ScrollEventLocked_Test::TestBody()':
../../ash/sticky_keys/sticky_keys_unittest.cc:711:41:error: 'class ui::DeviceDataManager' has no member named 'set_natural_scroll_enabled'
ninja: build stopped: subcommand failed.


Original issue's description:
> Don't handle NaturalScroll in Chrome but pass it to CMT instead
> 
> In order to support mice via CMT (Project Cobra) we will have to do
> the natural scroll handling in the CMT driver instead of Chrome.
> 
> BUG=chromium:285663
> TEST=test with touchpads and traditional mice. Everything should work as before,
> touchpad should have natural scroll applied, scroll wheels should not.
> Test changing the natural scroll property and see if it's applied correctly.
> Also test if touch mice have natural scroll applied.
> 
> Committed: https://src.chromium.org/viewvc/chrome?view=rev&revision=260926

TBR=achuith@chromium.org,sky@chromium.org,sadrul@chromium.org,denniskempin@chromium.org
NOTREECHECKS=true
NOTRY=true
BUG=chromium:285663

Review URL: https://codereview.chromium.org/221363002

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@260932 0039d316-1c4b-4281-b951-d872f2087c98