Revert of Update V8 to version 5.3.230. (patchset #1 id:1 of https://codereview.chromium.org/2064953005/ )
Reason for revert:
Broke clobber bots, e.g. https://build.chromium.org/p/chromium/builders/Mac/builds/16732/steps/compile/logs/stdio
../../v8/src/tracing/trace-event.h:10:10: fatal error: 'base/trace_event/common/trace_event_common.h' file not found
#include "base/trace_event/common/trace_event_common.h"
         ^
1 error generated.

Original issue's description:
> Update V8 to version 5.3.230.
>
> Summary of changes available at:
> https://chromium.googlesource.com/v8/v8/+log/a52b41ed..3c389b2c
>
> Please follow these instructions for assigning/CC'ing issues:
> https://github.com/v8/v8/wiki/Triaging%20issues
>
> Please close rolling in case of a roll revert:
> https://v8-roll.appspot.com/
> This only works with a Google account.
>
> CQ_INCLUDE_TRYBOTS=tryserver.blink:linux_blink_rel
>
> TBR=hablich@chromium.org,machenbach@chromium.org,yangguo@chromium.org,vogelheim@chromium.org
>
> Committed: https://crrev.com/24bb735828d354a357bbf30cb70d4d5ec41cb939
> Cr-Commit-Position: refs/heads/master@{#399867}

TBR=hablich@chromium.org,machenbach@chromium.org,vogelheim@chromium.org,yangguo@chromium.org,v8-autoroll@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true

Review-Url: https://codereview.chromium.org/2066243002
Cr-Commit-Position: refs/heads/master@{#399882}