SimpleCache: audit M85-expiring histograms (1/???)
(There are a lot of those, so this will be done in
 multiple CLs)

StaleIndex various: keeping as potential area of improvement,
                    low traffic
SyncKeySHA256Result: removed, not interesting any more
                     (long ago format changes)
SyncWriteResult: kept as can help diagnose trouble root cause.

SyncCheckEOFHasCRC: removed, old format migrationi
SyncCheckEOFResult: kept, diagnostic value
SyncCreateResult: removed, file error peer probably more useful
SyncCreatePlatformFileError: kept, diagnostic value
SyncCloseResult: kept since Close() doesn't have way of signaling
                 failure and trouble here may mean data loss.
SyncOpenEntryAge: removed
SyncOpenResult,PlatformFileError: kept, trouble-shooting value

WriteResult2: removed
ReadResult: removed.
ReadStream1FromPrefetched: removed.

Bug: 1089963, 1089962, 1089961
Bug: 1089980, 1089979, 1089981
Bug: 1089973, 1089974, 1089975
Bug: 1089967, 1089968, 1089969
Bug: 1089970, 1089971, 1089972
Change-Id: I463dc981806e71c6ab26e75c2fe7917a199119b4
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2252958
Reviewed-by: Alexei Svitkine <asvitkine@chromium.org>
Reviewed-by: Ben Kelly <wanderview@chromium.org>
Commit-Queue: Maksim Orlovich <morlovich@chromium.org>
Cr-Commit-Position: refs/heads/master@{#780464}