Revert of [WebPayments] Adding FilterProfilesForShipping to profile comparator (patchset #5 id:80001 of https://codereview.chromium.org/2884393002/ )
Reason for revert:
Appears to be causing test failures in https://luci-logdog.appspot.com/v/?s=chromium%2Fbb%2Fchromium.win%2FWin10_Tests_x64%2F11929%2F%2B%2Frecipes%2Fsteps%2Fbrowser_side_navigation_browser_tests_on_Windows-10-10586%2F0%2Flogs%2FPaymentRequestProfileListTest.PrioritizeCompleteness%2F0

 RUN      ] PaymentRequestProfileListTest.PrioritizeCompleteness
[640:3644:0523/102806.488:WARNING:embedded_test_server.cc(219)] Request not handled. Returning 404: /favicon.ico
c:\b\c\b\win\src\chrome\browser\ui\views\payments\profile_list_view_controller_browsertest.cc(46): error:       Expected: partial
      Which is: b5e544d1-6a66-49bf-bd4c-f2eb38671fd3 https://www.example.com/ Jane A. Smith jsmith@example.com ACME      48838  US  13105557889
To be equal to: *profiles[0]
      Which is: 63b73e74-aacb-4a0e-bde5-a3260918586c http://www.example.com/ John H. Doe johndoe@hades.com Underworld 666 Erebus St. Apt 8  Elysium CA 91111  US  16502111111
c:\b\c\b\win\src\chrome\browser\ui\views\payments\profile_list_view_controller_browsertest.cc(47): error:       Expected: complete
      Which is: 63b73e74-aacb-4a0e-bde5-a3260918586c http://www.example.com/ John H. Doe johndoe@hades.com Underworld 666 Erebus St. Apt 8  Elysium CA 91111  US  16502111111
To be equal to: *profiles[1]
      Which is: b5e544d1-6a66-49bf-bd4c-f2eb38671fd3 https://www.example.com/ Jane A. Smith jsmith@example.com ACME      48838  US  13105557889
[  FAILED  ] PaymentRequestProfileListTest.PrioritizeCompleteness, where TypeParam =  and GetParam() =  (1292 ms)

Original issue's description:
> [WebPayments] Adding FilterProfilesForShipping to profile comparator
>
> BUG=722949
>
> Review-Url: https://codereview.chromium.org/2884393002
> Cr-Commit-Position: refs/heads/master@{#473929}
> Committed: https://chromium.googlesource.com/chromium/src/+/eb8d574b98adfcbd3b5ce2eb6e521b83efbb428a

TBR=mahmadi@chromium.org,mathp@chromium.org,tmartino@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=722949

Review-Url: https://codereview.chromium.org/2897133002
Cr-Commit-Position: refs/heads/master@{#473982}