[gnrt] Improve error messages where crates sources/inputs are not found.
This CL primarly tweaks the code to return errors (in `anyhow::Result`
sense) instead of panicking.  Additionally `with_context` is used to
provide a trail of what exactly failed.

This CL also opportunistically removes some code duplication by 1)
reusing `fn get_combined_set` after making it more generic, and 2)
extracting a `extend_root_dirs` lambda.

Error message before this CL:

```
thread 'main' panicked at gen.rs:181:18:
missing a stdlib input file, did you gclient sync?: missing path "/usr/local/google/home/aeubanks/repos/chromium/src/third_party/rust-toolchain/lib/rustlib/src/rust/library/vendor/addr2line-0.24.2/src"

Caused by:
    No such file or directory (os error 2)
```

Error message after this CL:

```
Error: Failed to collect crate files for `compiler_builtins-0.1.156`

Caused by:
    0: Failed to process `/usr/local/google/home/lukasza/src/chromium2/src/third_party/rust-toolchain/lib/rustlib/src/rust/library/vendor/compiler_builtins-0.1.156/src/../libm` path.  This path came from `extra_src_roots` entry in `gnrt_config.toml` for `compiler_builtins-0.1.156`
    1: Couldn't read metadata of `/usr/local/google/home/lukasza/src/chromium2/src/third_party/rust-toolchain/lib/rustlib/src/rust/library/vendor/compiler_builtins-0.1.156/src/../libm`
    2: No such file or directory (os error 2)
Failed.
```

Bug: 414870153
Change-Id: Icafb66e8d5a168797180c71e03cad68065ddfc4f
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6507040
Commit-Queue: Łukasz Anforowicz <lukasza@chromium.org>
Reviewed-by: Devon Loehr <dloehr@google.com>
Cr-Commit-Position: refs/heads/main@{#1454630}