Revert "Update dialog height without footnote"
This reverts commit 50eec5c48a22ec54251fe2ec2c241e70f410377b.

Reason for revert: This CL caused a consistent failure of AccessCodeCastDialogBrowserTest.InvokeUi_default starting https://ci.chromium.org/ui/p/chromium/builders/ci/Win10%20Tests%20x64/70399/overview


[ RUN      ] AccessCodeCastDialogBrowserTest.InvokeUi_default
[21280:13460:0815/175409.393:WARNING:field_trial_util.cc(104)] Field trial config study skipped: DesktopTabGroupsInProductHelp.EnabledIPH_20220401 (some of its features are already overridden)
[21280:13460:0815/175409.393:WARNING:field_trial_util.cc(104)] Field trial config study skipped: PreconnectToSearchDesktop.EnabledWithStartupDelayForegroundOnly (some of its features are already overridden)
[21280:13460:0815/175409.393:WARNING:field_trial_util.cc(104)] Field trial config study skipped: SharedHighlightingIphDesktop.Enabled (some of its features are already overridden)
[21280:13460:0815/175409.393:WARNING:field_trial_util.cc(104)] Field trial config study skipped: TabAudioMuting.Enabled (some of its features are already overridden)
[21280:13460:0815/175409.393:WARNING:field_trial_util.cc(104)] Field trial config study skipped: TabSearchInProductHelp.TabSearchIPH (some of its features are already overridden)
[21280:13460:0815/175409.393:WARNING:field_trial_util.cc(104)] Field trial config study skipped: WebUITabStrip.Enabled (some of its features are already overridden)
[21280:13460:0815/175409.907:ERROR:device_event_log_impl.cc(214)] [17:54:09.907] Bluetooth: bluetooth_adapter_winrt.cc:1074 Getting Default Adapter failed.
content\public\test\test_utils.cc(407): error: Failed
RunLoop::Run() timed out. Timeout set at ProxyRunTestOnMainThreadLoop@content\public\test\browser_test_base.cc:837.
Stack trace:
Backtrace:
	base::internal::Invoker<base::internal::BindState<`lambda at ../../base/test/scoped_run_loop_timeout.cc:51:9',base::Location,base::RepeatingCallback<std::Cr::basic_string<char,std::Cr::char_traits<char>,std::Cr::allocator<char> > ()> >,void (const base::L [0x00007FF668D94F46+166] (o:\base\bind_internal.h:832)
	base::`anonymous namespace'::OnRunLoopTimeout [0x00007FF668CF3ADC+60] (o:\base\run_loop.cc:48)
	base::internal::Invoker<base::internal::BindState<void (*)(base::RunLoop *, const base::Location &, base::OnceCallback<void (const base::Location &)>),base::internal::UnretainedWrapper<base::RunLoop>,base::Location,base::RepeatingCallback<void (const base [0x00007FF668CF4E86+102] (o:\base\bind_internal.h:819)
	base::internal::CancelableCallbackImpl<base::OnceCallback<void ()> >::ForwardOnce<> [0x00007FF665B8AFFD+61] (o:\base\cancelable_callback.h:127)
	base::TaskAnnotator::RunTaskImpl [0x00007FF668D12567+327] (o:\base\task\common\task_annotator.cc:135)
	base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl [0x00007FF66A640425+965] (o:\base\task\sequence_manager\thread_controller_with_message_pump_impl.cc:424)
	base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork [0x00007FF66A63FEA5+165] (o:\base\task\sequence_manager\thread_controller_with_message_pump_impl.cc:303)
	base::MessagePumpForUI::DoRunLoop [0x00007FF668D473B6+150] (o:\base\message_loop\message_pump_win.cc:215)
	base::MessagePumpWin::Run [0x00007FF668D46D40+144] (o:\base\message_loop\message_pump_win.cc:79)
	base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run [0x00007FF66A640E5A+394] (o:\base\task\sequence_manager\thread_controller_with_message_pump_impl.cc:580)
	base::RunLoop::Run [0x00007FF668CF34DD+493] (o:\base\run_loop.cc:143)
	content::WindowedNotificationObserver::Wait [0x00007FF66915D7A3+79] (o:\content\public\test\test_utils.cc:408)
	content::WaitForLoadStopWithoutSuccessCheck [0x00007FF66910E5AE+211] (o:\content\public\test\browser_test_utils.cc:818)
	content::WaitForLoadStop [0x00007FF66910E05D+138] (o:\content\public\test\browser_test_utils.cc:825)
	media_router::AccessCodeCastDialogBrowserTest::ShowUi [0x00007FF6647ECA19+313] (o:\chrome\browser\ui\webui\access_code_cast\access_code_cast_dialog_browsertest.cc:44)
	TestBrowserUi::ShowAndVerifyUi [0x00007FF668C5550B+263] (o:\chrome\browser\ui\test\test_browser_ui.cc:116)
	TestBrowserDialog::ShowAndVerifyUi [0x00007FF664797525+13] (o:\chrome\browser\ui\test\test_browser_dialog.cc:77)
	content::BrowserTestBase::ProxyRunTestOnMainThreadLoop [0x00007FF66910C1C4+740] (o:\content\public\test\browser_test_base.cc:912)
	content::BrowserMainLoop::InterceptMainMessageLoopRun [0x00007FF666CDB5A2+92] (o:\content\browser\browser_main_loop.cc:1014)
	content::BrowserMainLoop::RunMainMessageLoop [0x00007FF666CDB5EF+37] (o:\content\browser\browser_main_loop.cc:1026)
	content::BrowserMainRunnerImpl::Run [0x00007FF666CDD421+17] (o:\content\browser\browser_main_runner_impl.cc:158)
	content::BrowserMain [0x00007FF666CD8F23+203] (o:\content\browser\browser_main.cc:30)
	content::RunBrowserProcessMain [0x00007FF6687C1DB7+239] (o:\content\app\content_main_runner_impl.cc:680)
	content::ContentMainRunnerImpl::RunBrowser [0x00007FF6687C2EA8+374] (o:\content\app\content_main_runner_impl.cc:1207)
	content::ContentMainRunnerImpl::Run [0x00007FF6687C2CF1+849] (o:\content\app\content_main_runner_impl.cc:1073)
	content::RunContentProcess [0x00007FF6687C1820+1993] (o:\content\app\content_main.cc:433)
	content::ContentMain [0x00007FF6687C1953+90] (o:\content\app\content_main.cc:461)
	content::BrowserTestBase::SetUp [0x00007FF66910B805+1957] (o:\content\public\test\browser_test_base.cc:733)
	InProcessBrowserTest::SetUp [0x00007FF668C8B8C5+421] (o:\chrome\test\base\in_process_browser_test.cc:477)

..\..\content\public\test\test_utils.cc(408): error: Value of: seen_
  Actual: false
Expected: true
Stack trace:
Backtrace:
	content::WindowedNotificationObserver::Wait [0x00007FF66915D854+256] (o:\content\public\test\test_utils.cc:408)
	content::WaitForLoadStopWithoutSuccessCheck [0x00007FF66910E5AE+211] (o:\content\public\test\browser_test_utils.cc:818)
	content::WaitForLoadStop [0x00007FF66910E05D+138] (o:\content\public\test\browser_test_utils.cc:825)
	media_router::AccessCodeCastDialogBrowserTest::ShowUi [0x00007FF6647ECA19+313] (o:\chrome\browser\ui\webui\access_code_cast\access_code_cast_dialog_browsertest.cc:44)
	TestBrowserUi::ShowAndVerifyUi [0x00007FF668C5550B+263] (o:\chrome\browser\ui\test\test_browser_ui.cc:116)
	TestBrowserDialog::ShowAndVerifyUi [0x00007FF664797525+13] (o:\chrome\browser\ui\test\test_browser_dialog.cc:77)
	content::BrowserTestBase::ProxyRunTestOnMainThreadLoop [0x00007FF66910C1C4+740] (o:\content\public\test\browser_test_base.cc:912)
	content::BrowserMainLoop::InterceptMainMessageLoopRun [0x00007FF666CDB5A2+92] (o:\content\browser\browser_main_loop.cc:1014)
	content::BrowserMainLoop::RunMainMessageLoop [0x00007FF666CDB5EF+37] (o:\content\browser\browser_main_loop.cc:1026)
	content::BrowserMainRunnerImpl::Run [0x00007FF666CDD421+17] (o:\content\browser\browser_main_runner_impl.cc:158)
	content::BrowserMain [0x00007FF666CD8F23+203] (o:\content\browser\browser_main.cc:30)
	content::RunBrowserProcessMain [0x00007FF6687C1DB7+239] (o:\content\app\content_main_runner_impl.cc:680)
	content::ContentMainRunnerImpl::RunBrowser [0x00007FF6687C2EA8+374] (o:\content\app\content_main_runner_impl.cc:1207)
	content::ContentMainRunnerImpl::Run [0x00007FF6687C2CF1+849] (o:\content\app\content_main_runner_impl.cc:1073)
	content::RunContentProcess [0x00007FF6687C1820+1993] (o:\content\app\content_main.cc:433)
	content::ContentMain [0x00007FF6687C1953+90] (o:\content\app\content_main.cc:461)
	content::BrowserTestBase::SetUp [0x00007FF66910B805+1957] (o:\content\public\test\browser_test_base.cc:733)
	InProcessBrowserTest::SetUp [0x00007FF668C8B8C5+421] (o:\chrome\test\base\in_process_browser_test.cc:477)

[21280:13460:0815/175443.391:ERROR:browser_test_utils.cc(826)] WebContents was destroyed during waiting for load stop.
..\..\chrome\browser\ui\webui\access_code_cast\access_code_cast_dialog_browsertest.cc(44): error: Value of: content::WaitForLoadStop(dialog_contents)
  Actual: false
Expected: true
Stack trace:
Backtrace:
	media_router::AccessCodeCastDialogBrowserTest::ShowUi [0x00007FF6647ECA99+441] (o:\chrome\browser\ui\webui\access_code_cast\access_code_cast_dialog_browsertest.cc:44)
	TestBrowserUi::ShowAndVerifyUi [0x00007FF668C5550B+263] (o:\chrome\browser\ui\test\test_browser_ui.cc:116)
	TestBrowserDialog::ShowAndVerifyUi [0x00007FF664797525+13] (o:\chrome\browser\ui\test\test_browser_dialog.cc:77)
	content::BrowserTestBase::ProxyRunTestOnMainThreadLoop [0x00007FF66910C1C4+740] (o:\content\public\test\browser_test_base.cc:912)
	content::BrowserMainLoop::InterceptMainMessageLoopRun [0x00007FF666CDB5A2+92] (o:\content\browser\browser_main_loop.cc:1014)
	content::BrowserMainLoop::RunMainMessageLoop [0x00007FF666CDB5EF+37] (o:\content\browser\browser_main_loop.cc:1026)
	content::BrowserMainRunnerImpl::Run [0x00007FF666CDD421+17] (o:\content\browser\browser_main_runner_impl.cc:158)
	content::BrowserMain [0x00007FF666CD8F23+203] (o:\content\browser\browser_main.cc:30)
	content::RunBrowserProcessMain [0x00007FF6687C1DB7+239] (o:\content\app\content_main_runner_impl.cc:680)
	content::ContentMainRunnerImpl::RunBrowser [0x00007FF6687C2EA8+374] (o:\content\app\content_main_runner_impl.cc:1207)
	content::ContentMainRunnerImpl::Run [0x00007FF6687C2CF1+849] (o:\content\app\content_main_runner_impl.cc:1073)
	content::RunContentProcess [0x00007FF6687C1820+1993] (o:\content\app\content_main.cc:433)
	content::ContentMain [0x00007FF6687C1953+90] (o:\content\app\content_main.cc:461)
	content::BrowserTestBase::SetUp [0x00007FF66910B805+1957] (o:\content\public\test\browser_test_base.cc:733)
	InProcessBrowserTest::SetUp [0x00007FF668C8B8C5+421] (o:\chrome\test\base\in_process_browser_test.cc:477)

[21280:13460:0815/175443.393:INFO:test_browser_dialog.cc(106)] VerifyUi(): Expected 1 added widget; got 0
..\..\chrome\browser\ui\test\test_browser_ui.cc(117): error: Value of: VerifyUi()
  Actual: false
Expected: true
Stack trace:
Backtrace:
	TestBrowserUi::ShowAndVerifyUi [0x00007FF668C555D8+468] (o:\chrome\browser\ui\test\test_browser_ui.cc:117)
	TestBrowserDialog::ShowAndVerifyUi [0x00007FF664797525+13] (o:\chrome\browser\ui\test\test_browser_dialog.cc:77)
	content::BrowserTestBase::ProxyRunTestOnMainThreadLoop [0x00007FF66910C1C4+740] (o:\content\public\test\browser_test_base.cc:912)
	content::BrowserMainLoop::InterceptMainMessageLoopRun [0x00007FF666CDB5A2+92] (o:\content\browser\browser_main_loop.cc:1014)
	content::BrowserMainLoop::RunMainMessageLoop [0x00007FF666CDB5EF+37] (o:\content\browser\browser_main_loop.cc:1026)
	content::BrowserMainRunnerImpl::Run [0x00007FF666CDD421+17] (o:\content\browser\browser_main_runner_impl.cc:158)
	content::BrowserMain [0x00007FF666CD8F23+203] (o:\content\browser\browser_main.cc:30)
	content::RunBrowserProcessMain [0x00007FF6687C1DB7+239] (o:\content\app\content_main_runner_impl.cc:680)
	content::ContentMainRunnerImpl::RunBrowser [0x00007FF6687C2EA8+374] (o:\content\app\content_main_runner_impl.cc:1207)
	content::ContentMainRunnerImpl::Run [0x00007FF6687C2CF1+849] (o:\content\app\content_main_runner_impl.cc:1073)
	content::RunContentProcess [0x00007FF6687C1820+1993] (o:\content\app\content_main.cc:433)
	content::ContentMain [0x00007FF6687C1953+90] (o:\content\app\content_main.cc:461)
	content::BrowserTestBase::SetUp [0x00007FF66910B805+1957] (o:\content\public\test\browser_test_base.cc:733)
	InProcessBrowserTest::SetUp [0x00007FF668C8B8C5+421] (o:\chrome\test\base\in_process_browser_test.cc:477)

[21280:13460:0815/175443.499:WARNING:pref_notifier_impl.cc(41)] Pref observer for media_router.cast_allow_all_ips found at shutdown.
[  FAILED  ] AccessCodeCastDialogBrowserTest.InvokeUi_default, where TypeParam =  and GetParam() =  (34129 ms)

Original change's description:
> Update dialog height without footnote
>
> Bug: b/238244922
> Change-Id: I3d425887ed3535090b347e04cf39f9f0fec69358
> Screenshot: https://screenshot.googleplex.com/8EdCAVivHuUFnvJ.png
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3830741
> Commit-Queue: Luke Cao <caott@google.com>
> Reviewed-by: Benjamin Zielinski <bzielinski@google.com>
> Cr-Commit-Position: refs/heads/main@{#1035280}

Bug: b/238244922
Change-Id: I1b82cb372c31c1935e5f83a79f36ef263a183a95
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3829100
Commit-Queue: Maxim Kolosovskiy <kolos@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Reviewed-by: Maxim Kolosovskiy <kolos@chromium.org>
Owners-Override: Maxim Kolosovskiy <kolos@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1035527}