Revert "[vr] On-demand install VR dynamic feature module"
This reverts commit 0275d36033c0a24af4c67ec8eb1a71cb84adb347.

Reason for revert: 
Suspect compile failure on Android(x64) Builder Dbg.

Example:
https://ci.chromium.org/p/chromium/builders/luci.chromium.ci/Android%20x64%20Builder%20%28dbg%29/30291

Log:
../../chrome/android/java/src/org/chromium/chrome/browser/vr/VrModuleProvider.java:114: error: cannot find symbol
        Toast.makeText(ContextUtils.getApplicationContext(), R.string.vr_module_install_start_text,
                                                                     ^
  symbol:   variable vr_module_install_start_text
  location: class string
../../chrome/android/java/src/org/chromium/chrome/browser/vr/VrModuleProvider.java:127: error: cannot find symbol
            int mToastTextRes = success ? R.string.vr_module_install_success_text
                                                  ^
  symbol:   variable vr_module_install_success_text
  location: class string
../../chrome/android/java/src/org/chromium/chrome/browser/vr/VrModuleProvider.java:128: error: cannot find symbol
                                        : R.string.vr_module_install_failure_text;
                                                  ^
  symbol:   variable vr_module_install_failure_text
  location: class string
3 errors


Original change's description:
> [vr] On-demand install VR dynamic feature module
> 
> With this CL we initate the module install once the user enters VR on a
> WebXR/VR page. In more detail this CL
> 
> - Introduces native VrModuleDelegate used to request VR module from
>   native,
> 
> - Refactors GvrDevice to request the VR module as part of its
>   initialization flow,
> 
> - Adds native side of the VrModuleProvider for Java-native
>   communication.
> 
> Bug: 862689
> Cq-Include-Trybots: luci.chromium.try:android_optional_gpu_tests_rel;luci.chromium.try:linux_optional_gpu_tests_rel;luci.chromium.try:linux_vr;luci.chromium.try:mac_optional_gpu_tests_rel;luci.chromium.try:win_optional_gpu_tests_rel
> Change-Id: I960d2bdd4d2c64a19fa6069e457d44f77ab0e73b
> Reviewed-on: https://chromium-review.googlesource.com/c/1241458
> Commit-Queue: Tibor Goldschwendt <tiborg@chromium.org>
> Reviewed-by: Ted Choc <tedchoc@chromium.org>
> Reviewed-by: Bill Orr <billorr@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#602922}

TBR=tedchoc@chromium.org,billorr@chromium.org,tiborg@chromium.org

Change-Id: I19d05dd6f13e5d6eee5ea0ac2f168a3a4d1a3680
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 862689
Cq-Include-Trybots: luci.chromium.try:android_optional_gpu_tests_rel;luci.chromium.try:linux_optional_gpu_tests_rel;luci.chromium.try:linux_vr;luci.chromium.try:mac_optional_gpu_tests_rel;luci.chromium.try:win_optional_gpu_tests_rel
Reviewed-on: https://chromium-review.googlesource.com/c/1301194
Reviewed-by: Takashi Sakamoto <tasak@google.com>
Commit-Queue: Takashi Sakamoto <tasak@google.com>
Cr-Commit-Position: refs/heads/master@{#603007}