Reland #2 "Make proto_library() actions depend directly on their dep's actions"
This reverts commit ff6e76aec780005f6b81df93c63e8fc6360b6c1c.

Reason for reland: Fixed link error on fuzzer bot
* Also made a couple other fuzzer-related GN simplifications.

Original change's description:
> Revert "Reland "Make proto_library() actions depend directly on their dep's actions""
>
> This reverts commit c3c72ad87345c26e28f78b6d97f571402548cd47.
>
> Reason for revert: suspect compile failure on Libfuzzer Upload Chrome OS Asan
>
> First build failure:
> https://ci.chromium.org/ui/p/chromium/builders/ci/Libfuzzer%20Upload%20Chrome%20OS%20ASan/122004/overview
>
> Failure summary:
> ---
> [75972/75984] LINK ./policy_fuzzer
> python3 ../../build/toolchain/gcc_link_wrapper.py --output=./policy_fuzzer -- ../../third_party/llvm-build/Release+Asserts/bin/clang++ -Werror...(too long)
> ld.lld: error: duplicate symbol: enterprise_management::DevicePolicyRefreshRateProto::DevicePolicyRefreshRateProto(google::protobuf::Arena*)
> >>> defined at chrome_device_policy.pb.cc:5287 (gen/components/policy/proto/chrome_device_policy.pb.cc:5287)
> >>>            obj/components/policy/proto/proto_internal/chrome_device_policy.pb.o:(enterprise_management::DevicePolicyRefreshRateProto::DevicePolicyRefreshRateProto(google::protobuf::Arena*))
> >>> defined at chrome_device_policy.pb.cc:7534 (gen/components/policy/proto/fuzzer/chrome_device_policy.pb.cc:7534)
> >>>            chrome_device_policy_full_runtime_proto__proto/chrome_device_policy.pb.o:(.text+0x0) in archive obj/components/policy/proto/fuzzer/libchrome_device_policy_full_runtime_proto__proto.a
> ---
>
> Original change's description:
> > Reland "Make proto_library() actions depend directly on their dep's actions"
> >
> > This reverts commit 3c31897013d5a332da2b05cf5f1ed1469433233b.
> >
> > Reason for reland: Update dep labels
> >
> > Original change's description:
> > > Revert "Make proto_library() actions depend directly on their dep's actions"
> > >
> > > This reverts commit 01bb32f8cee2c8a36a55e8b9b82600170ee8303b.
> > >
> > > Reason for revert: broke https://ci.chromium.org/ui/p/chromium/builders/ci/Libfuzzer%20Upload%20Chrome%20OS%20ASan :
> > >
> > > ERROR Unresolved dependencies.
> > > //chrome/browser/resources/chromeos/contact_center_insights:reporting_protos(//build/toolchain/linux:clang_x64)
> > >   needs //components/reporting/proto:proto_library_health_proto_gen(//build/toolchain/linux:clang_x64)
> > >
> > > and the latter is changed by this CL.
> > >
> > > Original change's description:
> > > > Make proto_library() actions depend directly on their dep's actions
> > > >
> > > > Instead of on their source_set() targets, which blocks the actions on
> > > > compile steps that it doesn't need.
> > > >
> > > > This necessitates removing visibility from the generation action, and
> > > > thus removing the need for "generator_visibility", which IMO provided
> > > > negative value.
> > > >
> > > > Change-Id: I75abd295ee5a2943fcdd9c4a15d569c43056b872
> > > > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6505727
> > > > Commit-Queue: Andrew Grieve <agrieve@chromium.org>
> > > > Owners-Override: Andrew Grieve <agrieve@chromium.org>
> > > > Reviewed-by: Takuto Ikuta <tikuta@chromium.org>
> > > > Cr-Commit-Position: refs/heads/main@{#1456968}
> > >
> > > No-Presubmit: true
> > > No-Tree-Checks: true
> > > No-Try: true
> > > Change-Id: Idd8cd73bf8d9485414d1adbade6bf9082010fb1c
> > > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6519496
> > > Owners-Override: Avi Drissman <avi@chromium.org>
> > > Auto-Submit: Avi Drissman <avi@chromium.org>
> > > Commit-Queue: Avi Drissman <avi@chromium.org>
> > > Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
> > > Cr-Commit-Position: refs/heads/main@{#1457005}
> >
> > Change-Id: I4f109ce03d7941df914b2dc01e99729b77950092
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6518391
> > Auto-Submit: Andrew Grieve <agrieve@chromium.org>
> > Owners-Override: Andrew Grieve <agrieve@chromium.org>
> > Commit-Queue: Andrew Grieve <agrieve@chromium.org>
> > Reviewed-by: Sam Maier <smaier@chromium.org>
> > Cr-Commit-Position: refs/heads/main@{#1457159}
>
> No-Presubmit: true
> No-Tree-Checks: true
> No-Try: true
> Change-Id: I21b0b25281904a4db0ce35b5763a49c74aa37917
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6521886
> Auto-Submit: Takashi Sakamoto <tasak@google.com>
> Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
> Owners-Override: Takashi Sakamoto <tasak@google.com>
> Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
> Cr-Commit-Position: refs/heads/main@{#1457346}

Change-Id: I48cff63e3dd7e8405af2ea9cdff175e27c69b1ee
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6528249
Auto-Submit: Andrew Grieve <agrieve@chromium.org>
Commit-Queue: Andrew Grieve <agrieve@chromium.org>
Reviewed-by: Takuto Ikuta <tikuta@chromium.org>
Owners-Override: Andrew Grieve <agrieve@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1458070}