Revert "[ios] Improve build/toolchain/ios/swiftc.py script"
This reverts commit 555b7f43f59a6291b935c1dd8e99fc6ce77d183e.

Reason for revert: Broke Libfuzzer Upload iOS Catalyst Debug bot
https://logs.chromium.org/logs/chromium/buildbucket/cr-buildbucket/8754254641265655537/+/u/compile/stdout

```
error: unknown argument: '-isystem'
```

Original change's description:
> [ios] Improve build/toolchain/ios/swiftc.py script
>
> Change the script build/toolchain/ios/swiftc.py to configure the
> swift compiler to generate $input.swiftconstvalues files (needed
> for Intents API in swift).
>
> Improve the code to put all the derived data in one directory,
> which allow removing the need for -pch-output-dir $dir from the
> invocation of the script and its list of outputs (should avoid
> the compilation error where $dir is created as a file instead of
> a directory).
>
> Change toolchain.gni to pass all the tool versions as environment
> variables instead of command-line arguments (reduce the length of
> the command-line and remove the need to parse those arguments in
> the script).
>
> Allow keeping the derived data dir between invocations of the
> script (which may improve the build performance as the swiftc
> binary will not have to rebuild the module cache each time).
>
> Bug: 326059372
> Change-Id: I5e42676eb917fe2d355383aaa39a60d5674816fb
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5319176
> Commit-Queue: Sylvain Defresne <sdefresne@chromium.org>
> Reviewed-by: Federica Germinario <fedegermi@google.com>
> Cr-Commit-Position: refs/heads/main@{#1268444}

Bug: 326059372
No-Try: true
Change-Id: Iba4f5e665f1e2b1ebc87594cc09117ee44026729
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5348396
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Auto-Submit: Mikihito Matsuura <mikt@google.com>
Owners-Override: Mikihito Matsuura <mikt@google.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Cr-Commit-Position: refs/heads/main@{#1268853}