[base] Properly detect NEON support on ARM{,64}
This is essentially a reland of
https://chromium-review.googlesource.com/c/chromium/src/+/4579589 which
was reverted because it was breaking a WPT test for WebAudio due to
float precision issues on macOS 11, see crbug.com/40915857.

Since then, the upstream test has been updated to increase tolerances,
see
https://github.com/web-platform-tests/wpt/commit/e164c49e841a37398fed3cbafe76d5f5a4547f19.

Original change description:
olivierli@chromium.org discovered that CPU_ARM_NEON is not defined where
it should (in particular on ARM64). This commit fixes the detection.

However, fixing this makes ARM64 builds fail. This is because of buggy
hand-written assembly code in WTF::CopyLCharsFramUCharSource() for the
NEON path. The path uses inline assembly to perform the char16_t -> char
conversion in the case where all the characters in the char16_t array
are 8-bit. This is potentially quite hot code in blink, but the code is
broken because it uses inline assembly with incorrect registers.

A clean solution would be to use intrinsics, but a lazier one is to
trust the "sufficiently smart compiler", which indeed auto-vectorizes
the loop at "-O2" (tested with compiler explorer, on reasonably recent
clang versions). Since this assembly code path wasn't used before, we
lose nothing by not using inline assembly.

For reference, the error message generated when leaving the inline
assembly as is:

In file included from ../../third_party/blink/renderer/platform/wtf/text/wtf_string.cc:41:
../../third_party/blink/renderer/platform/wtf/text/copy_lchars_from_uchar_source.h:97:11: error: vector register expected
      asm("vld2.8   { d0-d1 }, [%[SOURCE]] !\n\t"
          ^
<inline asm>:1:13: note: instantiated into assembly here
        vld2.8   { d0-d1 }, [x1] !

Also need to update a webaudio fingerprinting test. The result changes
because... floating point, and enabling NEON expectedly changes the
results.

Note for sheriffs: If there is a build breakage on ARM64 in range, this is likely the culprit.

Change-Id: I2ba48eaa3924148b79f1a80be244949e9e195805
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6343101
Commit-Queue: Benoit Lize <lizeb@chromium.org>
Reviewed-by: Hongchan Choi <hongchan@chromium.org>
Reviewed-by: Sylvain Defresne <sdefresne@chromium.org>
Reviewed-by: Michael Lippautz <mlippautz@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1431544}