Switch to py3 and fix TypeError in download_optimization_profile
The change fixes the following error raised in CheckCallOrExit when an
input command is failing:

  File "src/tools/download_optimization_profile.py", line 63, in CheckCallOrExit
    '## Stdout:\n' + stdout,
TypeError: can only concatenate str (not "bytes") to str.

Switch to python3 and remove backward compatibility with python2.

BUG=b:202735786
TEST=`./download_optimization_profile.py` passed with chromeos-chrome-amd64-atom-96-4652.0-1633342296-benchmark-96.0.4664.4-r1-redacted.afdo.xz profile

Change-Id: I96ca0749db3ac50f173996c4d36b5929a5510487
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3218487
Reviewed-by: George Burgess <gbiv@chromium.org>
Reviewed-by: Dirk Pranke <dpranke@google.com>
Commit-Queue: Denis Nikitin <denik@chromium.org>
Cr-Commit-Position: refs/heads/main@{#932085}