Revert "[android] Enable shipping both snapshots on android"
This reverts commit dbe657ecce09220eee9c16d8cfd2e585349ca368.

Reason for revert: Speculative fix for https://ci.chromium.org/ui/p/chrome/builders/ci/android-x86_64/18890

In file included from ../../base/allocator/partition_allocator/src/partition_alloc/partition_address_space.h:26:
../../base/allocator/partition_allocator/src/partition_alloc/thread_isolation/thread_isolation.h:23:2: error: "thread isolation support requires 64 bit pointers"
23 | #error "thread isolation support requires 64 bit pointers"

Original change's description:
> [android] Enable shipping both snapshots on android
>
> Reland of crrev.com/c/3219567. We want to experiment with this again,
> potentially limiting it to high-end Android only (depending on impact).
>
> Binary-Size: Increase is temporary for experiment.
> Bug: 40200623, 40539769
> Change-Id: Ide7e11ab9b9c1fcf9c42cb97df9e831dbd0cb6e7
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5518514
> Auto-Submit: Leszek Swirski <leszeks@chromium.org>
> Commit-Queue: Andrew Grieve <agrieve@chromium.org>
> Reviewed-by: Andrew Grieve <agrieve@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1297053}

Bug: 40200623, 40539769
Change-Id: I511704e059f234cdfa4536e4024bf3c6d1cbc335
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5519779
Commit-Queue: Justin DeWitt <dewittj@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Owners-Override: Justin DeWitt <dewittj@chromium.org>
Auto-Submit: Justin DeWitt <dewittj@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1297280}