Revert "Android: Add --wait-for-java-debugger to test_runner.py"
This reverts commit d77bb0d5597845d282f38df6dbc9a8207cae0b84.

Reason for revert: Fails on Android Cronet Perf bot(s).

I    0.000s Main  command: ... Android_Cronet_x86_Builder ... test_runner.py perf ...
E    0.001s Main  Unrecognized error occurred.
Traceback (most recent call last):
  File ".../src/build/android/test_runner.py", line 1001, in main
    return RunTestsCommand(args)
  ...
  File ".../src/build/android/pylib/local/device/local_device_environment.py", line 148, in __init__
    self._wait_for_java_debugger = args.wait_for_java_debugger
AttributeError: 'Namespace' object has no attribute 'wait_for_java_debugger'
  ...
Original change's description:
> Android: Add --wait-for-java-debugger to test_runner.py
  ...
> 
> Change-Id: I7cd58c747534b3b539afcc84fcbae48475c4d9c3
> Reviewed-on: https://chromium-review.googlesource.com/693218
> Commit-Queue: Andrew Grieve <agrieve@chromium.org>
> Reviewed-by: Yoland Yan <yolandyan@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#506049}

TBR=agrieve@chromium.org,yolandyan@chromium.org

Change-Id: I7cf9a5e3c52f29b24df77e0e27eb6272416c5f30
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/698127
Reviewed-by: Peter Mayo <petermayo@chromium.org>
Cr-Commit-Position: refs/heads/master@{#506097}