Revert "[Omnibox] Implement accordion for Fusebox popup variations"
This reverts commit 74a44463b267cc199b6cecb29de59466138ba471.

Reason for revert: FuseboxViewBinderUnitTest doesn't import OmniboxFeatures

../../chrome/browser/ui/android/omnibox/.../FuseboxViewBinderUnitTest.java:1094: error: cannot find symbol
        OmniboxFeatures.setUseAccordionForTesting(true);
  symbol: variable OmniboxFeatures

Original change's description:
> [Omnibox] Implement accordion for Fusebox popup variations
>
> Implements UI layouts and interactions for the Fusebox popup variations
> experiment. Depending on experiment parameters, the popup supports
> presentation as a floating context menu or a bottom sheet, displaying
> attachment actions in either a horizontal carousel or a vertical list.
> Additionally introduces a collapsible "More options" accordion container
> to defer presentation of secondary options (tools, model picker, and
> file attachments) until toggled by the user. Key changes:
> - Accordion: Encapsulated secondary actions inside a collapsible
>   container in fusebox_context_popup.xml.
> - MVC & Properties: Added POPUP_ACCORDION_EXPANDED,
>   POPUP_MORE_OPTIONS_CLICKED, and POPUP_MORE_OPTIONS_VISIBLE properties
>
> Bug: 559307688
> Change-Id: I303e9bde9f4d9df772f91ab37a229ea319b1f807
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/8390658
> Reviewed-by: Tomasz Wiszkowski <ender@google.com>
> Reviewed-by: Patrick Noland <pnoland@chromium.org>
> Commit-Queue: Peter Kang <peterkang@google.com>
> Cr-Commit-Position: refs/heads/main@{#1696499}

Bug: 559307688
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Change-Id: I36508afe9b9052d41a528f826166ac8cf049a975
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/8395533
Bot-Commit: rubber-stamper@appspot.gserviceaccount.com <rubber-stamper@appspot.gserviceaccount.com>
Auto-Submit: Sky Malice <skym@chromium.org>
Reviewed-by: Tomasz Wiszkowski <ender@google.com>
Commit-Queue: Sky Malice <skym@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1696509}