Revert "Migrate chrome/browser/browsing_data to PasswordStoreInterface."
This reverts commit 2d8fa6a9a96a2db536478549409f5925fce5abdf.

Reason for revert: This CL broke building chromeos-linux build with the following error:

chrome/browser/browsing_data/chrome_browsing_data_remover_delegate.cc:886:20: error: member access into incomplete type 'password_manager::SmartBubbleStatsStore'
        stats_store->RemoveStatisticsByOriginAndTime(
                   ^
../../components/password_manager/core/browser/password_store_interface.h:26:7: note: forward declaration of 'password_manager::SmartBubbleStatsStore'
class SmartBubbleStatsStore;
      ^
../../chrome/browser/browsing_data/chrome_browsing_data_remover_delegate.cc:893:20: error: member access into incomplete type 'password_manager::FieldInfoStore'
        field_store->RemoveFieldInfoByTime(
                   ^
../../components/password_manager/core/browser/password_store_interface.h:23:7: note: forward declaration of 'password_manager::FieldInfoStore'
class FieldInfoStore;
      ^

Original change's description:
> Migrate chrome/browser/browsing_data to PasswordStoreInterface.
>
> PasswordStoreInterface is an interface that should be used by other
> classes instead of interacting directly with PasswordStore.
>
> Bug: 1218413
> Change-Id: I41c99d2a6e4d5565624487c1085f520eb7a3c9c9
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3193541
> Auto-Submit: Maria Kazinova <kazinova@google.com>
> Commit-Queue: Martin Šrámek <msramek@chromium.org>
> Reviewed-by: Martin Šrámek <msramek@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#926323}

Bug: 1218413
Change-Id: Ia0fd74439edb8673d7a0d9d4e10ecc522001e899
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3195083
Auto-Submit: Ahmed Fakhry <afakhry@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Jenny Zhang <jennyz@chromium.org>
Reviewed-by: James Cook <jamescook@chromium.org>
Reviewed-by: Jenny Zhang <jennyz@chromium.org>
Owners-Override: Jenny Zhang <jennyz@chromium.org>
Cr-Commit-Position: refs/heads/main@{#926528}