Revert "Create sandbox::SeatbeltExtension to dynamically expand the Mac sandbox policy."
This reverts commit fa1f0b26ababc0ee9156619d25aa7adb39bd706d.

Reason for revert: Looks to have broken the build.

https://luci-logdog.appspot.com/v/?s=chromium%2Fbb%2Fchromium.chrome%2FGoogle_Chrome_Mac%2F26445%2F%2B%2Frecipes%2Fsteps%2Fcompile%2F0%2Fstdout

In file included from ../../sandbox/mac/mojom/seatbelt_extension_token_struct_traits.cc:5:
../../sandbox/mac/mojom/seatbelt_extension_token_struct_traits.h:10:10: fatal error: 'sandbox/mac/mojom/seatbelt_extension_token.mojom-shared.h' file not found
#include "sandbox/mac/mojom/seatbelt_extension_token.mojom-shared.h"

Original change's description:
> Create sandbox::SeatbeltExtension to dynamically expand the Mac sandbox policy.
> 
> Sandbox policy extensions can be issued for resources in a trusted process,
> which generates a token that may be passed over Mojo IPC. The receiving process
> can then consume the token to be granted access to the resource. Currently only
> file-read extensions are permitted.
> 
> Bug: 510604
> Change-Id: Iaa92c48c120e051c5df72602d09329ebe84ea317
> Reviewed-on: https://chromium-review.googlesource.com/685583
> Reviewed-by: Greg Kerr <kerrnel@chromium.org>
> Reviewed-by: Ken Rockot <rockot@chromium.org>
> Reviewed-by: Justin Schuh <jschuh@chromium.org>
> Commit-Queue: Robert Sesek <rsesek@chromium.org>
> Commit-Queue: Justin Schuh <jschuh@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#505819}

TBR=jschuh@chromium.org,rockot@chromium.org,kerrnel@chromium.org,rsesek@chromium.org

Change-Id: Ic0fc32e651db586169ecd127c1674cd8dc205915
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 510604
Reviewed-on: https://chromium-review.googlesource.com/696343
Reviewed-by: Devlin <rdevlin.cronin@chromium.org>
Commit-Queue: Devlin <rdevlin.cronin@chromium.org>
Cr-Commit-Position: refs/heads/master@{#505843}