DocumentWebSocketChannelTest: Rename |WebCallbacks()| to avoid naming conflicts
GCC is stricter than clang when it comes to class members' names and how
they can change the meaning of a previously existing symbol with the same
name:

    ../../third_party/WebKit/Source/modules/websockets/DocumentWebSocketChannelTest.cpp:154:3: error: declaration of ‘blink::WebCallbacks<void, const blink::WebString&>* blink::{anonymous}::DocumentWebSocketChannelTest::WebCallbacks()’ [-fpermissive]
       }
       ^
    In file included from ../../third_party/WebKit/Source/modules/websockets/DocumentWebSocketChannel.h:53:0,
                     from ../../third_party/WebKit/Source/modules/websockets/DocumentWebSocketChannelTest.cpp:5:
    ../../third_party/WebKit/public/platform/WebCallbacks.h:53:7: error: changes meaning of ‘WebCallbacks’ from ‘class blink::WebCallbacks<void, const blink::WebString&>’ [-fpermissive]
     class WebCallbacks<void, T> {
           ^~~~~~~~~~~~~~~~~~~~~

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=84709 contains a longer
explanation, but essentially having a |WebCallbacks()| method can change the
meaning of references to the outside type in the code depending on where it
is declared, which contradicts the C++ standard.

Fix it by renaming the method to |GetWebCallbacks()|.

Change-Id: I418cf7d941d9ed3be030be2fda93690d3be76468
Reviewed-on: https://chromium-review.googlesource.com/968624
Reviewed-by: Kentaro Hara <haraken@chromium.org>
Commit-Queue: Raphael Kubo da Costa <raphael.kubo.da.costa@intel.com>
Cr-Commit-Position: refs/heads/master@{#544096}