Reland "[ios] Remove forward swipe for reading list."
This reverts commit 27f55bc8ec4c7780737dabb8fe7cb9c52fa66c53.

Reason for revert: Seems like the fix is about to land. So reverting
this revert. Sorry for the noise.

Original change's description:
> Revert "[ios] Remove forward swipe for reading list."
> 
> This reverts commit b74b9644d1301e77bbd00106bf31c46c189137a4.
> 
> Reason for revert: ios_chrome_web_egtests failing
> 
> https://ci.chromium.org/p/chromium/builders/luci.chromium.ci/ios-slimnav/465
> 
> ../../ios/chrome/browser/web/tab_order_egtest.mm:74: error: -[TabOrderTestCase testChildTabOrdering] : Exception: ActionFailedException
> 
> Exception Name: ActionFailedException
> Exception Reason: An action failed. Please refer to the error trace below.
> Exception with Action: {
>   "Action Name":  "Locate element bounds",
>   "Element Matcher":  "web view in web state"
> }
> 
> Exception Details: Error Trace: [
>   {
>     "Description":  "Couldn't locate a bounding rect for element with ID normal-link; either it isn't there or it has no area.",
>     "Error Domain":  "com.google.earlgrey.ElementInteractionErrorDomain",
>     "Error Code":  "2"
>   }
> ]
> 
> Bundle ID: org.chromium.gtest.generic-unit-test
> 
> Original change's description:
> > [ios] Remove forward swipe for reading list.
> > 
> > Bug: 909724
> > Change-Id: I24c3341ca5245d599ce43cba8b17c164e38e3618
> > Reviewed-on: https://chromium-review.googlesource.com/c/1354414
> > Commit-Queue: Justin Cohen <justincohen@chromium.org>
> > Reviewed-by: Olivier Robin <olivierrobin@chromium.org>
> > Cr-Commit-Position: refs/heads/master@{#612291}
> 
> TBR=justincohen@chromium.org,olivierrobin@chromium.org
> 
> Change-Id: I3b9b6b9b2a61eaaa11924b5b3e189034831c59d0
> No-Presubmit: true
> No-Tree-Checks: true
> No-Try: true
> Bug: 909724
> Reviewed-on: https://chromium-review.googlesource.com/c/1356176
> Reviewed-by: Giovanni Ortuño Urquidi <ortuno@chromium.org>
> Commit-Queue: Giovanni Ortuño Urquidi <ortuno@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#612568}

TBR=justincohen@chromium.org,ortuno@chromium.org,olivierrobin@chromium.org

Change-Id: I8174acbe3d36adb70fbf19a12454373c1b247ea4
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 909724
Reviewed-on: https://chromium-review.googlesource.com/c/1356178
Reviewed-by: Giovanni Ortuño Urquidi <ortuno@chromium.org>
Commit-Queue: Giovanni Ortuño Urquidi <ortuno@chromium.org>
Cr-Commit-Position: refs/heads/master@{#612569}