Reland "BundledExchangesParser: Update the bundle format [1/2]"
This reverts commit 3a99193da55d30636073f77eaa15322b54ec7a24.

Reason for revert: 
This was already reverted at [1] and relanded with a fix at [2].
[1] https://chromium.googlesource.com/chromium/src/+/5bd3e578821d1daacdb92dd5180255a771bf6d6c
[2] https://chromium.googlesource.com/chromium/src/+/4f518dc059bb7e0167335a3bb01b47d01bd0da80

Original change's description:
> Revert "BundledExchangesParser: Update the bundle format [1/2]"
> 
> This reverts commit d8c863a6de9b4f8a3607d696aeae21b08c76a7ba.
> 
> Reason for revert: 
> https://findit-for-me.appspot.com/waterfall/failure?url=https://build.chromium.org/p/chromium.linux/builders/Deterministic%20Linux/builds/24310
> 
> 
> https://luci-milo.appspot.com/p/chromium/builders/ci/Deterministic%20Linux/24310
> 
> Compile failure, List of errors:
> 
> ../../mojo/public/cpp/bindings/struct_ptr.h:56:18: error: no matching constructor for initialization of 'mojo::StructPtr<data_decoder::mojom::BundleMetadataParseError>::Struct' (aka 'data_decoder::mojom::BundleMetadataParseError')
> 
> 
> Original change's description:
> > BundledExchangesParser: Update the bundle format [1/2]
> > 
> > This updates BundledExchangesParser to parse the new bundle format [1].
> > 
> > Changes:
> > - Updated the magic header bytes [2]
> > - Version field is added (we use implementation-specific version string
> >   "b1\0\0", which matches gen-bundle's output [3])
> > - Fallback URL (== Primary URL) field is added
> > - ParseMetadata() returns error type ("format error" or "version error")
> >   and fallback URL if available
> > - Updated spec ref comments
> > 
> > The structure change of the index section is not reflected yet. It will
> > be updated in the next CL.
> > 
> > The test bundle file (hello.wbn) is generated with gen-bundle of
> > github.com/WICG/webpackage revision a3cef2c, which supports the new
> > bundle format except for the new index section structure.
> > 
> > [1] https://github.com/WICG/webpackage/pull/450
> > [2] https://github.com/WICG/webpackage/pull/454
> > [3] https://github.com/WICG/webpackage/pull/458
> > 
> > Bug: 969596
> > Change-Id: I95744ed00fdd09d369bb8648d1cdf62ca181d0dd
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1715487
> > Reviewed-by: Robert Sesek <rsesek@chromium.org>
> > Reviewed-by: Tsuyoshi Horo <horo@chromium.org>
> > Reviewed-by: Takashi Toyoshima <toyoshim@chromium.org>
> > Reviewed-by: Kinuko Yasuda <kinuko@chromium.org>
> > Commit-Queue: Kunihiko Sakamoto <ksakamoto@chromium.org>
> > Cr-Commit-Position: refs/heads/master@{#684200}
> 
> TBR=horo@chromium.org,kinuko@chromium.org,toyoshim@chromium.org,ksakamoto@chromium.org,rsesek@chromium.org
> 
> Change-Id: I0e4c550179c4433022646f8ecc27cbdf4983ce87
> No-Presubmit: true
> No-Tree-Checks: true
> No-Try: true
> Bug: 969596
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1738036
> Reviewed-by: Noel Gordon <noel@chromium.org>
> Commit-Queue: Noel Gordon <noel@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#684219}

TBR=horo@chromium.org,kinuko@chromium.org,toyoshim@chromium.org,noel@chromium.org,ksakamoto@chromium.org,rsesek@chromium.org

Change-Id: I27423f80338576b35506bb8f7e6010fc4c2d2ec7
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 969596
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1735802
Reviewed-by: Kunihiko Sakamoto <ksakamoto@chromium.org>
Commit-Queue: Kunihiko Sakamoto <ksakamoto@chromium.org>
Cr-Commit-Position: refs/heads/master@{#684221}