Fix flaky org.chromium.chrome.browser.tabmodel.TabModelMergingTest#testMergeOnMultiDisplay_OnDisplayChanged failure on android-backuprefptr-arm64-fyi-rel
Sample build: https://ci.chromium.org/ui/p/chromium/builders/ci/android-backuprefptr-arm64-fyi-rel/1856/overview
---
java.lang.AssertionError: Must only be used on a single thread.
at org.chromium.base.ThreadUtils$ThreadChecker.assertOnValidThread(ThreadUtils.java:74)
at org.chromium.base.ObserverList.removeObserver(ObserverList.java:96)
at org.chromium.base.ApplicationStatus.unregisterActivityStateListener(ApplicationStatus.java:573)
at org.chromium.chrome.browser.tabmodel.TabModelMergingTest.waitForActivityStateChange(TabModelMergingTest.java:300)
---
The ActivityStateListener listener should be unregistered on UI thread
(i.e. use runOnUiThreadBlocking), because it is registered on UI thread.

Change-Id: I791fea971490a461d07f51146b1b5071407a17d0
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3109268
Reviewed-by: Theresa  <twellington@chromium.org>
Commit-Queue: Takashi Sakamoto <tasak@google.com>
Cr-Commit-Position: refs/heads/main@{#914665}