Revert "[vr] Add a flag for experimental VR features"
This reverts commit c536e658005c4fbacdb9de6d7f83a293e117f994.

Reason for revert:
This is failing the Google Chrome Win bot:
https://build.chromium.org/p/chromium.chrome/builders/Google%20Chrome%20Win/builds/22616

Error log:
../..\chrome/common/chrome_features.h(14): fatal error C1083: Cannot open include file: 'device/vr/features/features.h': No such file or directory

Original change's description:
> [vr] Add a flag for experimental VR features
> 
> Having this flag will allow VR feature work without putting the shipping
> code at risk. Having it available via about:flags makes for much easier
> use on Android.
> 
> Bug: None
> Change-Id: I12cf3edaad80f9129fe4b00fcbf630f71b5e0b53
> Reviewed-on: https://chromium-review.googlesource.com/700477
> Commit-Queue: Ian Vollick <vollick@chromium.org>
> Reviewed-by: Scott Violet <sky@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#506646}

TBR=vollick@chromium.org,sky@chromium.org

Change-Id: I82a0a817772a5b5e26ad9a94d3e5431165efdab4
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: None
Reviewed-on: https://chromium-review.googlesource.com/701956
Reviewed-by: Hiroki Nakagawa <nhiroki@chromium.org>
Commit-Queue: Hiroki Nakagawa <nhiroki@chromium.org>
Cr-Commit-Position: refs/heads/master@{#506658}