Revert of net: build fix about CertificateList (patchset #1 id:1 of https://codereview.chromium.org/1572253002/ )
Reason for revert:
This issue is known in crbug.com/506663 and we want to fix c++ spec and clang rather than making chromium code silly.
Nico asked to revert it.

Original issue's description:
> net: build fix about CertificateList
>
> clang complains it doesn't initialize const member, so this CL calls the
> default constructor explicitly.
>
> ../../net/cert/multi_threaded_cert_verifier.cc:430:25: error: default initialization of an object of const type 'const CertificateList' (aka 'const vector<scoped_refptr<net::X509Certificate> >') without a user-provided default constructor
>   const CertificateList empty_cert_list;
>                         ^
> 1 error generated.
>
> Committed: https://crrev.com/18937ad93812903be37e75f60510ed258c4117e1
> Cr-Commit-Position: refs/heads/master@{#368585}

TBR=pauljensen@chromium.org
# Not skipping CQ checks because original CL landed more than 1 days ago.

Review URL: https://codereview.chromium.org/1584783002

Cr-Commit-Position: refs/heads/master@{#369131}