Add '-ldl' to Linux targets that use dynamic loader functions.
This fixes compilation errors on Karmic, where dlopen() and friends were undefined:
http://chrome-buildbot.corp.google.com:8016/builders/Chromium%20Linux%20Builder%20(dbg-shlib)/builds/7777/steps/compile/logs/stdio

The missing '-ldl' is papered over on Hardy because pretty much everything
depends on gtk, which brings that in through pkg-config, but pkg-config gtk
no longer includes '-ldl' on Karmic.

Review URL: http://codereview.chromium.org/656014

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@39754 0039d316-1c4b-4281-b951-d872f2087c98