change server_certificate_database to a component instead of static_library
Should address this DCHECK failure that was reported to me:
[base/feature_list.cc:871] DCHECK failed: CheckFeatureIdentity(feature).
EnableNSSCertMigration has multiple definitions. Either it is defined
more than once in code or (for component builds) the code is built into
multiple components (shared libraries) without a corresponding export
statement

Bug: 390333881
Change-Id: I2e9c69e83eb2e9815356939c3bf9defe169dfa06
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7807582
Reviewed-by: Hubert Chao <hchao@chromium.org>
Commit-Queue: Matt Mueller <mattm@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1624939}