Revert "Remove enable-send-tab-to-self-omnibox-sending-animation flag."
This reverts commit 974e1b68d1c24826515aabe1f14840f5333b9d17.

Reason for revert: culprit CL for a build error on mac-archive-rel

https://ci.chromium.org/p/chromium/builders/ci/mac-archive-rel/16425?

In file included from gen/third_party/blink/renderer/bindings/modules/v8/v8_internals.cc:12:
In file included from gen/third_party/blink/renderer/bindings/core/v8/v8_animation.h:11:
In file included from ../../third_party/blink/renderer/core/animation/animation.h:42:
In file included from ../../third_party/blink/renderer/core/animation/animation_effect.h:35:
../../third_party/blink/renderer/core/animation/animation_time_delta.h:8:10: fatal error: 'third_party/blink/renderer/core/animation/buildflags.h' file not found
#include "third_party/blink/renderer/core/animation/buildflags.h"



Original change's description:
> Remove enable-send-tab-to-self-omnibox-sending-animation flag.
>
> This bug fix has been launched since M84.
>
> Bug: 1124205
> Change-Id: I99dd4b7edbab9443c10169144f5ecf3b115c74f9
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2391508
> Reviewed-by: Jeffrey Cohen <jeffreycohen@chromium.org>
> Commit-Queue: Sophey Dong <sophey@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#819562}

TBR=jeffreycohen@chromium.org,sophey@chromium.org

Change-Id: I20af4e4dc812a4b934d435fabc4d7e1930d37a33
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 1124205
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2490965
Reviewed-by: Hayato Ito <hayato@chromium.org>
Commit-Queue: Hayato Ito <hayato@chromium.org>
Cr-Commit-Position: refs/heads/master@{#819642}