Revert "Set START_BROWSER_WITH_DEFAULT_PRIORITY=True for mac platform"
This reverts commit 3bc02d14d24ab739784f121e634cb240eecd7588.

Reason for revert: Broke tests:
 - telemetry_perf_unittests
    - core.benchmark_runner_test.BenchmarkRunnerUnittest.testMain_ReturnCode
    - scripts_smoke_unittest.ScriptsSmokeTest.testRunBenchmarkListBenchmarks
    - scripts_smoke_unittest.ScriptsSmokeTest.testRunPerformanceTestsTelemetry_end2end
on bots:
 - mac11-arm64-rel-tests (https://ci.chromium.org/ui/p/chromium/builders/ci/mac11-arm64-rel-tests/23194/overview)
 - mac12-arm64-rel-tests (https://ci.chromium.org/ui/p/chromium/builders/ci/mac12-arm64-rel-tests/11151/overview)
 - mac13-arm64-rel-tests (https://ci.chromium.org/ui/p/chromium/builders/ci/mac13-arm64-rel-tests/3508/overview)
with output:
```
Traceback (most recent call last):
  File "/opt/s/w/ir/tools/perf/benchmarks/../core/benchmark_runner_test.py", line 44, in testMain_ReturnCode
    return_code = benchmark_runner.main(config, [
  File "/opt/s/w/ir/tools/perf/benchmarks/../core/benchmark_runner.py", line 29, in main
    os.environ["START_BROWSER_WITH_DEFAULT_PRIORITY"] = True
  File "/opt/s/w/ir/.task_template_vpython_cache/vpython/store/python_venv-9f7hbvgfrn8q36kjmeeagm18js/contents/lib/python3.8/os.py", line 680, in __setitem__
    value = self.encodevalue(value)
  File "/opt/s/w/ir/.task_template_vpython_cache/vpython/store/python_venv-9f7hbvgfrn8q36kjmeeagm18js/contents/lib/python3.8/os.py", line 750, in encode
    raise TypeError("str expected, not %s" % type(value).__name__)
TypeError: str expected, not bool
```

https://chromium-review.googlesource.com/c/chromium/src/+/4771092/2#message-36b3a78ecb8d66a0f3005ca6c2244ee0223ffdc1: Environment variables must be strings, not boolean.

Original change's description:
> Set START_BROWSER_WITH_DEFAULT_PRIORITY=True for mac platform
>
> Bug: chromium:1454294
> Change-Id: I71a5c1a40eae4a080249c55aa6102c1ff7509b40
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4771092
> Commit-Queue: John Chen <johnchen@chromium.org>
> Auto-Submit: Prakhar Asthana <pasthana@google.com>
> Reviewed-by: John Chen <johnchen@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1182371}

Bug: chromium:1454294
Change-Id: I48a5c2fa0786b75725f52058283c1ebc7e9fa8ec
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4775059
Auto-Submit: Mark Mentovai <mark@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Mark Mentovai <mark@chromium.org>
Owners-Override: Mark Mentovai <mark@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1182586}