webxr: Replace AndroidX Nullable with Chromium Nullable.
This two files won't be compiled if |enable_cardboard| and |enable_arcore|
are true. If they are set to false, compile errors raise as follows.

```
CardboardClassProvider.java:21: error:
  annotation @Nullable not applicable in this type context
    /*package*/ static XrImmersiveOverlay.@Nullable Delegate getOverlayDelegate(
```

Use the Chromium Nullable instead to fix them.

Bug: 389129271
Change-Id: I509169a8a55e7a6c9ddb537bb4c83e02baf05016
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6472159
Reviewed-by: Henrique Nakashima <hnakashima@chromium.org>
Auto-Submit: Guobin Wu <wuguobin.1229@bytedance.com>
Reviewed-by: Andrew Grieve <agrieve@chromium.org>
Commit-Queue: Andrew Grieve <agrieve@chromium.org>
Owners-Override: Henrique Nakashima <hnakashima@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1449892}