Update mini player layout
Colors and icons still need to be polished but the main playback state layouts look like this:

Playing: http://shortn/_kjT2xNR7mE
Buffering: http://shortn/_8kHNHTpptG
Error: http://shortn/_VKMVDNwegU

This CL removes MiniPlayer classes which will be added back in a few later CLs.

Bug: b/301515553
Change-Id: I6e388490f0929082ca5dbb28554663df2ce69b82
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4885449
Reviewed-by: Basia Zimirska <basiaz@google.com>
Commit-Queue: Ian Wells <iwells@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1200396}