Remove variable shadowing in blink/modules/filesystem
In an effort to reduce or even ban variable shadowing, this renames
a variable to avoid such shadowing. I'm interested in prohibiting
shadowing because I think it might prevent potential jumbo problems.

The exact warnings this avoids is:

third_party/blink/renderer/modules/filesystem/directory_reader.cc:140:21: error: declaration shadows a local variable [-Werror,-Wshadow]
    EntryHeapVector entries;
                    ^
third_party/blink/renderer/modules/filesystem/directory_reader.cc:136:57: note: previous declaration is here
void DirectoryReader::AddEntries(const EntryHeapVector& entries) {
                                                        ^
third_party/blink/renderer/modules/filesystem/dom_window_file_system.cc:248:37: error: declaration shadows a local variable [-Werror,-Wshadow]
              Vector<ScriptPromise> result;
                                    ^
third_party/blink/renderer/modules/filesystem/dom_window_file_system.cc:238:32: note: previous declaration is here

             base::File::Error result,
                               ^

Bug: 923510
Change-Id: Ib907382435b0d1417e9ca2f070bfb68ef591e123
Reviewed-on: https://chromium-review.googlesource.com/c/1478871
Commit-Queue: Daniel Bratell <bratell@opera.com>
Commit-Queue: Kentaro Hara <haraken@chromium.org>
Commit-Queue: Hiroki Nakagawa <nhiroki@chromium.org>
Auto-Submit: Daniel Bratell <bratell@opera.com>
Reviewed-by: Kentaro Hara <haraken@chromium.org>
Reviewed-by: Hiroki Nakagawa <nhiroki@chromium.org>
Cr-Commit-Position: refs/heads/master@{#633728}