ozone: demo: Fix crash in GLRenderer
This fixes the following crash in DCHECK builds:

    ERROR: gl_surface_egl.cc(1608) Check failed: context.

We just need to resize after making current.

Change-Id: I9d51925a2e4d7fdb123c7588febdc43d4ceca5d7
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2174471
Commit-Queue: Michael Spang <spang@chromium.org>
Reviewed-by: Robert Kroeger <rjkroege@chromium.org>
Cr-Commit-Position: refs/heads/master@{#764736}