Revert "Turn on remove_src_checkout_experiment on M-arm64 to 10%"
This reverts commit ef0275a1d6bae0886c7f1b062de3c21b488b0e92.

Reason for revert: Getting infra failure: https://ci.chromium.org/ui/p/chromium/builders/try/android-marshmallow-arm64-rel/1219557/overview
```
  File "/b/s/w/ir/x/w/recipe_cleanup/src/third_party/jinja2/environment.py", line 830, in handle_exception
    from .debug import rewrite_traceback_stack
ImportError: No module named debug
```

Original change's description:
> Turn on remove_src_checkout_experiment on M-arm64 to 10%
>
> Enables the remove_src_checkout_experiment experiment to 10% of
> marsh-arm64 builds. This is the first android builder to use this
> experiment.
>
> Previously turned on and reverted due to error with android test result
> presentation templates missing (fixed here:
> https://chromium-review.googlesource.com/c/chromium/src/+/3759238)
>
> Bug: 1287228
> Change-Id: Ib25eaaed9c4880d4e9f9bdd4c62ba5e61cdac06d
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3760864
> Commit-Queue: Stephanie Kim <kimstephanie@google.com>
> Reviewed-by: Ben Pastene <bpastene@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1023882}

Bug: 1287228
Change-Id: I51e512be802f16440c06fceec515ac5991bdc0ed
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3761197
Commit-Queue: Stephanie Kim <kimstephanie@google.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Cr-Commit-Position: refs/heads/main@{#1023933}