Revert "Enable -Wextra-semi on Linux"
This reverts commit 4412168fcc037e8c529760c9382967bb9dc65707.

Reason for revert: Broke Linux MSAN compile

See https://ci.chromium.org/ui/p/chromium/builders/ci/WebKit%20Linux%20MSAN/16533/overview

This broke the build with a large number of occurrences of
../../v8/src/codegen/arm64/constants-arm64.h:566:34: error: extra ';' outside of a function is incompatible with C++98 [-Werror,-Wc++98-compat-extra-semi]
ADD_SUB_OP_LIST(ADD_SUB_EXTENDED);
                                 ^

Original change's description:
> Enable -Wextra-semi on Linux
>
> R=​thakis
>
> Change-Id: I972da398288caa7735684a78478428d1de179b37
> Bug: 1355871
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3866763
> Commit-Queue: Thomas Anderson <thomasanderson@chromium.org>
> Commit-Queue: Nico Weber <thakis@chromium.org>
> Auto-Submit: Thomas Anderson <thomasanderson@chromium.org>
> Reviewed-by: Nico Weber <thakis@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1042275}

Bug: 1355871
Change-Id: I91ce45e2ef2fde63fac83efa7f09bd5cafd1acb9
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3866768
Commit-Queue: Ian Clelland <iclelland@chromium.org>
Auto-Submit: Ian Clelland <iclelland@chromium.org>
Owners-Override: Ian Clelland <iclelland@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Cr-Commit-Position: refs/heads/main@{#1042289}