Fix ChromeVox api re-injection on re-load
When toggling ChromeVox, api injection gets blocked due to stricter same
origin policies since this code was written:

Error: Blocked script execution in
'https://docs.google.com/document/d/1WKvVF1Qu7LrJjAsop0HrmhgTvq3ZNI2IiBvPrThIpRU/edit'
because the document's frame is sandboxed and the 'allow-scripts'
permission is not set.  From
https://docs.google.com/document/d/1WKvVF1Qu7LrJjAsop0HrmhgTvq3ZNI2IiBvPrThIpRU/edit

This makes a fix by removing the previous script node.

off keeps on working.

Test: toggle ChromeVox off/on repeatedly. Verify Docs with braille mode
Bug: 
Cq-Include-Trybots: master.tryserver.chromium.linux:closure_compilation
Change-Id: Ibcc5e66d070d658a41ce7b5f7176bf3b67d7cfec
Reviewed-on: https://chromium-review.googlesource.com/843146
Reviewed-by: Dominic Mazzoni <dmazzoni@chromium.org>
Commit-Queue: David Tseng <dtseng@chromium.org>
Cr-Commit-Position: refs/heads/master@{#526123}