Revert "hps: Convert internal debug page to TypeScript"
This reverts commit c92fa0bc8b47b60ca5ac90dfbc9d3ebc0d63fabd.

Reason for revert: Suspect for compile breakage on ChromeOS branded builders, starting
https://ci.chromium.org/ui/p/chrome/builders/ci/chromeos-betty-arc-r-chrome/13093/steps

With

../../chromeos/components/hps/resources/hps_internals.ts:6:32 - error TS2792: Cannot find module 'chrome://resources/js/cr.m.js'

Original change's description:
> hps: Convert internal debug page to TypeScript
>
> Convert the internal HPS debug page from JavaScript to TypeScript for
> better maintainability.
>
> Bug: b:225999839
> Change-Id: I7f3331570c6dcc016079ae19f6caa3e2ee2daeae
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3544869
> Reviewed-by: Denis Kuznetsov <antrim@chromium.org>
> Commit-Queue: Sami Kyöstilä <skyostil@chromium.org>
> Auto-Submit: Sami Kyöstilä <skyostil@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#984617}

Bug: b:225999839
Change-Id: I73384a88fea7f16f43d4e50e980888d8352d54fe
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3545799
Auto-Submit: Trent Apted <tapted@chromium.org>
Owners-Override: Trent Apted <tapted@chromium.org>
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Cr-Commit-Position: refs/heads/main@{#984645}