IWYU: payments error message util uses std::vector without including it
GCC build fails because of missing include:
../../components/payments/core/error_message_util.h:20:16: error: ‘vector’ in namespace ‘std’ does not name a template type
   20 |     const std::vector<std::string>& skipped_apps);
      |                ^~~~~~

Bug: 957519
Change-Id: Icb7c5b0e9b136d14eb088884f8d4f8ee312b9460
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2340967
Reviewed-by: Liquan (Max) Gu <maxlg@chromium.org>
Commit-Queue: José Dapena Paz <jdapena@igalia.com>
Cr-Commit-Position: refs/heads/master@{#795819}