tflite: update deps/configs and add utils to set of files compiled
I added utils for another project using tflite that relies on
utils.

The remaining problems are necessary for some code that needs to
include from files in tflite_kernel_internals. This entailed
moving tflite_kernel_internals to public_deps and then fixing the
following:

In file included from ../../third_party/tflite/src/tensorflow/lite/kernels/internal/reference/dequantize.h:22:
../../third_party/tflite/src/tensorflow/lite/kernels/internal/common.h:28:10: fatal error: 'fixedpoint/fixedpoint.h' file not found
#include "fixedpoint/fixedpoint.h"

Fix is to move "//third_party/gemmlowp" to public_deps


In file included from ../../third_party/tflite/src/tensorflow/lite/kernels/internal/utils/sparsity_format_converter.h:20:
../../third_party/tflite/src/third_party/eigen3/Eigen/Core:1:10: fatal error: 'Eigen/Core' file not found
#include "Eigen/Core"
         ^~~~~~~~~~~~
1 error generated.

Fix is to move eigen_includes to public_configs

Bug: None

Change-Id: Ibb1bbc6bd97bd71168c8a198f82a9a3918768ff8
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4637601
Reviewed-by: Robert Ogden <robertogden@chromium.org>
Commit-Queue: Scott Violet <sky@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1161428}