GCC: add missing apps namespace to BrowserAppLauncher
GCC does not get namespace of BrowserAppLauncher right and
fails like this:

chrome/browser/apps/app_service/app_service_proxy.h:82:23: error:
declaration of 'apps::BrowserAppLauncher&
apps::AppServiceProxy::BrowserAppLauncher()' changes meaning of
'BrowserAppLauncher' [-fpermissive]

Bug: 819294
Change-Id: I1ee948723c68768e41e4d1e1861b3ed8f8fc6b2d
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2174484
Reviewed-by: Nancy Wang <nancylingwang@chromium.org>
Commit-Queue: Nancy Wang <nancylingwang@chromium.org>
Cr-Commit-Position: refs/heads/master@{#764972}