Revert of Removing references to webrtc::PortAllocatorFactoryInterface. (patchset #6 id:100001 of https://codereview.chromium.org/1500663003/ )
Reason for revert:
Broke the build:

../../remoting/host/remoting_me2me_host.cc:1505:9: error: no viable conversion from 'scoped_ptr<remoting::protocol::PortAllocatorFactory>' to 'rtc::scoped_refptr<webrtc::PortAllocatorFactoryInterface>'
        port_allocator_factory = protocol::ChromiumPortAllocatorFactory::Create(
        ^                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../third_party/webrtc/base/scoped_ref_ptr.h:76:3: note: candidate constructor not viable: no known conversion from 'scoped_ptr<remoting::protocol::PortAllocatorFactory>' to 'webrtc::PortAllocatorFactoryInterface *' for 1st argument
  scoped_refptr(T* p) : ptr_(p) {
  ^
../../third_party/webrtc/base/scoped_ref_ptr.h:81:3: note: candidate constructor not viable: no known conversion from 'scoped_ptr<remoting::protocol::PortAllocatorFactory>' to 'const scoped_refptr<webrtc::PortAllocatorFactoryInterface> &' for 1st argument
  scoped_refptr(const scoped_refptr<T>& r) : ptr_(r.ptr_) {
  ^
../../third_party/webrtc/base/scoped_ref_ptr.h:87:3: note: candidate template ignored: could not match 'scoped_refptr' against 'scoped_ptr'
  scoped_refptr(const scoped_refptr<U>& r) : ptr_(r.get()) {
  ^
../../base/memory/scoped_ptr.h:378:3: note: candidate function
  operator Testable() const {
  ^
1 error generated.

From https://build.chromium.org/p/chromium.linux/builders/Linux%20Builder%20%28dbg%29/builds/97032/

Original issue's description:
> Removing references to webrtc::PortAllocatorFactoryInterface.
>
> Now using a new CreatePeerConnection method that takes a
> PortAllocator as input. This removes the need for some
> boilerplate code and code duplication between webrtc and chromium.
> It also fixes an issue with TURN candidate priorities.
>
> BUG=webrtc:5209
>
> Committed: https://crrev.com/ad868b5edf13e869e835b847078b4dcc8aa7cd0d
> Cr-Commit-Position: refs/heads/master@{#364544}

TBR=sergeyu@chromium.org,deadbeef@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=webrtc:5209

Review URL: https://codereview.chromium.org/1514853003

Cr-Commit-Position: refs/heads/master@{#364556}