Revert 146954 - Use the script helper to build of content shell on Android
Breaks the ninja build for android:
KeyError: 'Undefined variable CONFIGURATION_NAME in
/usr/local/google/chrome/src/content/content.gyp while loading dependencies of
/usr/local/google/chrome/src/build/all_android.gyp while trying to load
/usr/local/google/chrome/src/build/all_android.gyp'


Review URL: https://chromiumcodereview.appspot.com/10779008

TBR=yongsheng.zhu@intel.com
Review URL: https://chromiumcodereview.appspot.com/10799010

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@147275 0039d316-1c4b-4281-b951-d872f2087c98