Fix compilation errors in FamilyUserDeviceMetricsTest.
After https://crrev.com/c/2676393 was landed, I receive the following
error when building browser_tests locally:
../../chrome/browser/chromeos/child_accounts/family_user_device_metrics_browsertest.cc:199:3: note: in instantiation of function template specialization 'testing::internal::EqHelper::Compare<int, unsigned long, nullptr>' requested here
  EXPECT_EQ(total_user_count, user_manager_->GetUsers().size());

This is caused by some extra compiler configuration that is not set
on regular trybots, but may be set on others.

R=agawronska@chromium.org, xiqiruan@chromium.org

Bug: 1172335
Change-Id: I301a856d26a1c6f484f020e50bd1c26c2146d531
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2713806
Auto-Submit: Sergey Poromov <poromov@chromium.org>
Commit-Queue: Aga Wronska <agawronska@chromium.org>
Reviewed-by: Aga Wronska <agawronska@chromium.org>
Cr-Commit-Position: refs/heads/master@{#856713}