GCC: Fix brace-enclosed initialization issue for base::NoDestructor in webui_util.cc
GCC fails to resolve from constructor to initializer list:
../../chrome/common/webui_util.cc:24:63:
error: call of overloaded ‘NoDestructor(<brace-enclosed initializer list>)’ is ambiguous

The base::SplitString() returns a vector of strings, so there are no
needs to use brace-enclosed initialization.
Hence, the impl is re-writen to satisfy both Clang and GCC.

Bug: 40565911
Change-Id: I7eab4840691340351498efc2c1a735f78b0c7517
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5832530
Commit-Queue: Ivan Murashov <ivan.murashov@lge.com>
Reviewed-by: Vasilii Sukhanov <vasilii@chromium.org>
Reviewed-by: Denis Kuznetsov <antrim@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1350774}