Revert "recorder: Add a11y labels on main page"
This reverts commit 74cedcdf586bf8d10f54982f8053183fd853f135.

Reason for revert: [Build gardener] Suspected to cause persistent ChromeVoxBackgroundTtsTest.Preprocess failures on https://ci.chromium.org/ui/p/chromium/builders/ci/Linux%20ChromiumOS%20MSan%20Tests.

First failing build:
https://ci.chromium.org/ui/p/chromium/builders/ci/Linux%20ChromiumOS%20MSan%20Tests/45863

Sample output:
[ RUN      ] ChromeVoxBackgroundTtsTest.Preprocess

../../chrome/test/base/ash/extension_js_browser_test.cc:201: Failure
Failed
Failed: RUN_TEST_F("ChromeVoxBackgroundTtsTest","Preprocess")
AssertionError: expected 'This is the ? symbol and this is the pound symbol.' to equal 'This is the pound sterling symbol and this is the pound symbol.'
    at assertEquals (file:///b/s/w/ir/out/Release/test_data/chrome/browser/resources/chromeos/accessibility/chromevox/background/tts_background_test.js:11432:15)
    at ChromeVoxBackgroundTtsTest.<anonymous> (file:///b/s/w/ir/out/Release/test_data/chrome/browser/resources/chromeos/accessibility/chromevox/background/tts_background_test.js:17562:3)
...
gen/chrome/browser/resources/chromeos/accessibility/chromevox/background/tts_background_test-gen.cc:71: Failure
Value of: RunJavascriptTestF( true, "ChromeVoxBackgroundTtsTest", "Preprocess")
  Actual: false
Expected: true

Original change's description:
> recorder: Add a11y labels on main page
>
> Add accessibility labels on components on main page.
>
> Bug: b:327537848
> Test: Use Chromevox to navigate in main page
> Change-Id: If3cc91c255fbb22865fa5e931fb35767fc0060ea
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5828681
> Reviewed-by: Pi-Hsun Shih <pihsun@chromium.org>
> Commit-Queue: Kam Kwankajornkiet <kamchonlathorn@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1350243}

Bug: b:327537848
Change-Id: Ifba98404b393a856981c1c53df233fc0c234c286
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5832812
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Owners-Override: Alex Moshchuk <alexmos@chromium.org>
Commit-Queue: Alex Moshchuk <alexmos@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1350486}