Revert "cros: Introduce common concept for conditions that can be awaited it tests."
This reverts commit ee05382ce0d0ca609541a941f97be0074d91bcd1.

Reason for revert:
browser_tests fail to compile for chromeos
../../chrome/browser/chromeos/login/sync_consent_interactive_ui_test.cc:82:10: error: allocating an object of abstract class type 'test::TestConditionWaiter'
  return test::TestConditionWaiter(base::BindRepeating(
         ^
../../chrome/browser/chromeos/login/test/test_condition_waiter.h:17:16: note: unimplemented pure virtual method 'Wait' in 'TestConditionWaiter'
  virtual void Wait() = 0;
               ^
1 error generated.


Original change's description:
> cros: Introduce common concept for conditions that can be awaited it tests.
> 
> Bug: 912704
> Change-Id: Ie1804ce8a6f05721e28a6d2c703530d8e0c53841
> Reviewed-on: https://chromium-review.googlesource.com/c/1481511
> Commit-Queue: Denis Kuznetsov <antrim@chromium.org>
> Reviewed-by: Alexander Alekseev <alemate@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#635114}

TBR=antrim@chromium.org,alemate@chromium.org,rsorokin@chromium.org,jdufault@chromium.org

Change-Id: Id0e69390d0d106f00d1a4527479b4a1752402324
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 912704
Reviewed-on: https://chromium-review.googlesource.com/c/1487433
Reviewed-by: Joel Hockey <joelhockey@chromium.org>
Commit-Queue: Joel Hockey <joelhockey@chromium.org>
Cr-Commit-Position: refs/heads/master@{#635229}