Revert "Refactor GetResolutionsForDecoders() to support AV1. Take #2"
This reverts commit 1470bc0629d94bcca415484c9490bfd619c57348.

Reason for revert: Still causing issues on windows:

https://ci.chromium.org/p/chromium/builders/ci/Win7%20Tests%20%281%29/103592

[ RUN      ] SupportedResolutionResolverTest.MultipleCodecs
../../media/gpu/windows/supported_profile_helpers_unittest.cc(249): error: Expected equality of these values:
  base::size(kSupportedH264Profiles) + 1
    Which is: 4
  supported_resolutions.size()
    Which is: 3
Stack trace:
Backtrace:
	media::SupportedResolutionResolverTest_MultipleCodecs_Test::TestBody [0x00E22189+1133]

[  FAILED  ] SupportedResolutionResolverTest.MultipleCodecs (46 ms)

Original change's description:
> Refactor GetResolutionsForDecoders() to support AV1. Take #2
> 
> Same as the previous patch, but avoids assigning from a const& that
> is destructed by the assignment. PS#1 is the original change, all
> later patch sets are the new one.
> 
> ---- [ Original Description Below ] ----
> 
> Does the following:
> - Internalizes h264 and min resolution details.
> - Sets the minimum resolution to 64,64 for both decoders.
> - Only loops through the video device profiles once.
> - Switches away from an std::pair to a named struct.
> - Adds AV1 GUID values and uses them in DXVA decoder.
> - Stops D3D11VideoDecoder for enumerating unsupported profiles.
> - Stops using the DXVA2_Intel_ModeH264_E for enumeration.
> - Gives all resolution tests a square resolution; e.g., 4k x 4k.
> - Doesn't test or indicate support for a duplicate portrait resolution.
> 
> TBR=liberato, tmathmeyer
> 
> Bug: 1073252
> Test: Updated unittests.
> Change-Id: I0503d43630238c0a11b3a683308232f13cfdf37b
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2227969
> Reviewed-by: Dale Curtis <dalecurtis@chromium.org>
> Commit-Queue: Dale Curtis <dalecurtis@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#774474}

TBR=dalecurtis@chromium.org,liberato@chromium.org,tmathmeyer@chromium.org

Change-Id: I253f981c011e79a68ccf3625386275e44698c57d
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 1073252
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2228369
Reviewed-by: Giovanni Ortuño Urquidi <ortuno@chromium.org>
Commit-Queue: Giovanni Ortuño Urquidi <ortuno@chromium.org>
Cr-Commit-Position: refs/heads/master@{#774497}