Revert "settings: Disable backspace button on setup pin dialog when nothing entered."
This reverts commit f66cf13a011713683612732274e0713e16dc1456.

Reason for revert: CrSettingsPeoplePageSetupPinDialogTest.All failures on linux-chromeos-rel

https://uberchromegw.corp.google.com/i/chromium.chromiumos/builders/linux-chromeos-rel

[8877:8877:0108/154615.238105:INFO:CONSOLE(1225)] "Running TestCase CrSettingsPeoplePageSetupPinDialogTest.All", source: test_api.js (1225)
[8877:8877:0108/154615.760757:ERROR:CONSOLE(48)] "Mocha test failed: setup-pin-dialog BackspaceDisabledWhenNothingEntered
AssertionError: expected false to be true
    at Function.assert.isTrue (chai.js:2423:31)
    at assertTrue (test_api.js:853:17)
    at Context.<anonymous> (quick_unlock_authenticate_browsertest_chromeos.js:552:9)
", source: mocha_adapter.js (48)
[8877:8877:0108/154615.761596:ERROR:web_ui_test_handler.cc(82)] Test Errors: 1/13 tests had failed assertions.
[8877:8877:0108/154615.761615:ERROR:web_ui_browser_test.cc(475)] CONDITION FAILURE: encountered javascript console error(s):
[8877:8877:0108/154615.761620:ERROR:web_ui_browser_test.cc(477)] JS ERROR: '[8877:8877:0108/154615.760757:ERROR:CONSOLE(48)] "Mocha test failed: setup-pin-dialog BackspaceDisabledWhenNothingEntered
AssertionError: expected false to be true
    at Function.assert.isTrue (chai.js:2423:31)
    at assertTrue (test_api.js:853:17)
    at Context.<anonymous> (quick_unlock_authenticate_browsertest_chromeos.js:552:9)
", source: mocha_adapter.js (48)
'

Original change's description:
> settings: Disable backspace button on setup pin dialog when nothing entered.
> 
> Test: browser_tests CrSettingsPeoplePageSetupPinDialogTest.*
> Bug: 799388
> Cq-Include-Trybots: master.tryserver.chromium.linux:closure_compilation
> Change-Id: Ia1b5ce69bd13c4e9127b04fcbaf67751a6f86cdc
> Reviewed-on: https://chromium-review.googlesource.com/854742
> Reviewed-by: Steven Bennetts <stevenjb@chromium.org>
> Commit-Queue: Sammie Quon <sammiequon@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#527776}

TBR=stevenjb@chromium.org,sammiequon@chromium.org

Change-Id: I3f62e8657bcc5e2f7dde00104c640508189c7306
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 799388
Cq-Include-Trybots: master.tryserver.chromium.linux:closure_compilation
Reviewed-on: https://chromium-review.googlesource.com/855101
Reviewed-by: Mike Wittman <wittman@chromium.org>
Commit-Queue: Mike Wittman <wittman@chromium.org>
Cr-Commit-Position: refs/heads/master@{#527822}