Revert "//base/time cleanups:"
This reverts commit 5de0588a3191035015a53df9aa8d6cb535441c41.

Reason for revert: A few time related unit tests started flaking on win-asan, starting from the build containing this CL (13964). Suspecting this CL to be the culprit.

https://ci.chromium.org/p/chromium/builders/ci/win-asan
https://ci.chromium.org/p/chromium/builders/ci/win-asan/13964

e.g.
[ RUN      ] ElapsedThreadTimerTest.Simple
../../base/timer/elapsed_timer_unittest.cc(72): error: Expected: (timer.Elapsed()) >= (kLoopingTime), actual: 0.000988 s vs 0.001 s
Stack trace:
Backtrace:
	base::ElapsedThreadTimerTest_Simple_Test::TestBody [0x00007FF7C6A735B1+1351] (C:\b\s\w\ir\cache\builder\src\base\timer\elapsed_timer_unittest.cc:72)

[  FAILED  ] ElapsedThreadTimerTest.Simple (289 ms)

Original change's description:
> //base/time cleanups:
> 
> * Make more things constexpr and/or make it possible to do so later
> * Inline SaturatedAdd/Sub(), FromDouble(), FromProduct()
> * Order the FromUnits{,D}() pairs together
> * Init members in declaration
> * Briefer implementations of various functions
> * IWYU
> * Fix declared-but-not-defined issue for FromTimeSpec() w/OS_FUSCHIA
> * Use more specific DCHECKs
> * No else after return
> * Omit needless qualifiers
> * EXPECT -> static_assert where possible
> * <atomic> is legal now
> * Don't handle DCHECK failure
> 
> The inlines don't hurt size: this saves 4 KB off chrome.dll in my local
> release build.
> 
> Bug: none
> TBR: stevenjb@chromium.org
> Change-Id: I269d6426ac1587569e7a4c785250a4dd5e95d5bf
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2358997
> Reviewed-by: Peter Kasting <pkasting@chromium.org>
> Reviewed-by: Yuri Wiitala <miu@chromium.org>
> Reviewed-by: Tom Sepez <tsepez@chromium.org>
> Commit-Queue: Peter Kasting <pkasting@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#799459}

TBR=stevenjb@chromium.org,pkasting@chromium.org,miu@chromium.org,tsepez@chromium.org,khegde@chromium.org

Change-Id: Ic855d54ae010859b82c55848fb14d8af2cb778d1
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: none
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2364062
Reviewed-by: Kevin McNee <mcnee@chromium.org>
Commit-Queue: Kevin McNee <mcnee@chromium.org>
Cr-Commit-Position: refs/heads/master@{#799731}