Revert "Setup NTP for Kaleidoscope module"
This reverts commit 0158f88de15ac1b161fcda61b695e4b1bbb6ef1b.

Reason for revert: This CL broke the entire waterfall: https://screenshot.googleplex.com/7be9bb2e-086d-4e02-a655-68373309ec83.png

Example failure: https://ci.chromium.org/p/chrome/builders/ci/linux-chrome/13827

Traceback (most recent call last):
  File "../../tools/grit/grit.py", line 29, in <module>
    sys.exit(grit.grit_runner.Main(sys.argv[1:]))
  File "/b/s/w/ir/cache/builder/src/tools/grit/grit/grit_runner.py", line 314, in Main
    return toolobject.Run(options, args[1:])
  File "/b/s/w/ir/cache/builder/src/tools/grit/grit/tool/build.py", line 274, in Run
    self.Process()
  File "/b/s/w/ir/cache/builder/src/tools/grit/grit/tool/build.py", line 409, in Process
    self.ProcessNode(self.res, output, tmpfile)
  File "/b/s/w/ir/cache/builder/src/tools/grit/grit/tool/build.py", line 333, in ProcessNode
    formatted = formatter(node, output_node.GetLanguage(), output_dir=base_dir)
  File "/b/s/w/ir/cache/builder/src/tools/grit/grit/format/data_pack.py", line 90, in Format
    value = node.GetDataPackValue(lang, util.BINARY)
  File "/b/s/w/ir/cache/builder/src/tools/grit/grit/node/include.py", line 109, in GetDataPackValue
    data = util.ReadFile(filename, util.BINARY)
  File "/b/s/w/ir/cache/builder/src/tools/grit/grit/util.py", line 214, in ReadFile
    with io.open(filename, mode, encoding=encoding) as f:
IOError: [Errno 2] No such file or directory: '../../out/Release/gen/chrome/browser/media/kaleidoscope/internal/resources/module/module.js'



Original change's description:
> Setup NTP for Kaleidoscope module
> 
> This CL moves the Kaleidoscope NTP module upstream
> into the Kaleidoscope repo.
> 
> The public Kaleidoscope module is now responsible for
> loading the resources into the NTP page.
> 
> Also adds the KaleidoscopeDataProvider to the NTP.
> 
> BUG=1114862
> 
> Change-Id: Ibc255ea9d7fd05b10cb151d0f1e86b0f94b192cb
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2354717
> Commit-Queue: Becca Hughes <beccahughes@chromium.org>
> Reviewed-by: Tibor Goldschwendt <tiborg@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#798391}

TBR=beccahughes@chromium.org,tiborg@chromium.org

Change-Id: I1ec9b538cdd360d97fea01561b21d5f4d48430e1
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 1114862
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2358694
Reviewed-by: Ahmed Fakhry <afakhry@chromium.org>
Commit-Queue: Ahmed Fakhry <afakhry@chromium.org>
Cr-Commit-Position: refs/heads/master@{#798402}