Revert "AppShell: Support reloading"
This reverts commit 65478d123ddee27fc9cdcc29621a3e299d2562ee.

Reason for revert: Caused build failure on Mac
https://ci.chromium.org/buildbot/chromium/Mac/38768
https://logs.chromium.org/v/?s=chromium%2Fbb%2Fchromium%2FMac%2F38768%2F%2B%2Frecipes%2Fsteps%2Fcompile%2F0%2Fstdout

Undefined symbols for architecture x86_64:
  "extensions::ShellNativeAppWindowAura::ShellNativeAppWindowAura(extensions::AppWindow*, extensions::AppWindow::CreateParams const&)", referenced from:
      extensions::(anonymous namespace)::TestAppWindowClient::CreateNativeAppWindow(extensions::AppWindow*, extensions::AppWindow::CreateParams*) in shell_extension_loader_unittest.o
  "extensions::ShellTestBaseAura::SetUp()", referenced from:
      extensions::ShellExtensionLoaderTest::SetUp() in shell_extension_loader_unittest.o
  "extensions::ShellTestBaseAura::ShellTestBaseAura()", referenced from:
      testing::internal::TestFactoryImpl<extensions::ShellExtensionLoaderTest_Extension_Test>::CreateTest() in shell_extension_loader_unittest.o
      testing::internal::TestFactoryImpl<extensions::ShellExtensionLoaderTest_AppLaunch_Test>::CreateTest() in shell_extension_loader_unittest.o
      testing::internal::TestFactoryImpl<extensions::ShellExtensionLoaderTest_AppLaunchAndReload_Test>::CreateTest() in shell_extension_loader_unittest.o
      testing::internal::TestFactoryImpl<extensions::ShellExtensionLoaderTest_NotFound_Test>::CreateTest() in shell_extension_loader_unittest.o
      testing::internal::TestFactoryImpl<extensions::ShellExtensionLoaderTest_ReloadFailure_Test>::CreateTest() in shell_extension_loader_unittest.o
      testing::internal::TestFactoryImpl<extensions::ShellExtensionLoaderTest_LoadAfterReloadFailure_Test>::CreateTest() in shell_extension_loader_unittest.o
      testing::internal::TestFactoryImpl<extensions::ShellExtensionLoaderTest_LoadDisabledExtension_Test>::CreateTest() in shell_extension_loader_unittest.o
      ...
  "extensions::ShellTestBaseAura::~ShellTestBaseAura()", referenced from:
      extensions::ShellExtensionLoaderTest_Extension_Test::~ShellExtensionLoaderTest_Extension_Test() in shell_extension_loader_unittest.o
      extensions::ShellExtensionLoaderTest_Extension_Test::~ShellExtensionLoaderTest_Extension_Test() in shell_extension_loader_unittest.o
      extensions::ShellExtensionLoaderTest_AppLaunch_Test::~ShellExtensionLoaderTest_AppLaunch_Test() in shell_extension_loader_unittest.o
      extensions::ShellExtensionLoaderTest_AppLaunch_Test::~ShellExtensionLoaderTest_AppLaunch_Test() in shell_extension_loader_unittest.o
      extensions::ShellExtensionLoaderTest_AppLaunchAndReload_Test::~ShellExtensionLoaderTest_AppLaunchAndReload_Test() in shell_extension_loader_unittest.o
      extensions::ShellExtensionLoaderTest_AppLaunchAndReload_Test::~ShellExtensionLoaderTest_AppLaunchAndReload_Test() in shell_extension_loader_unittest.o
      extensions::ShellExtensionLoaderTest_NotFound_Test::~ShellExtensionLoaderTest_NotFound_Test() in shell_extension_loader_unittest.o
      ...
  "extensions::ShellTestBaseAura::TearDown()", referenced from:
      extensions::ShellExtensionLoaderTest::TearDown() in shell_extension_loader_unittest.o
  "extensions::ShellTestBaseAura::InitAppWindow(extensions::AppWindow*, gfx::Rect const&)", referenced from:
      extensions::ShellExtensionLoaderTest_AppLaunch_Test::TestBody() in shell_extension_loader_unittest.o
      extensions::ShellExtensionLoaderTest_AppLaunchAndReload_Test::TestBody() in shell_extension_loader_unittest.o
      extensions::ShellExtensionLoaderTest_ReloadFailure_Test::TestBody() in shell_extension_loader_unittest.o
ld: symbol(s) not found for architecture x86_64


Original change's description:
> AppShell: Support reloading
> 
> Implement reloading in ExtensionLoader. Uses keep-alives while apps are
> reloading. A future CL will observe these keep-alives to keep app_shell open
> during reload.
> 
> Bug: 762642
> Change-Id: Ia20b81378d1aeab4ace119d9d2a8b44c2461fdcf
> Reviewed-on: https://chromium-review.googlesource.com/912694
> Commit-Queue: Michael Giuffrida <michaelpg@chromium.org>
> Reviewed-by: Devlin <rdevlin.cronin@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#540079}

TBR=michaelpg@chromium.org,rdevlin.cronin@chromium.org

Change-Id: I2db08946671be6eb37fd3f4d658573b87dd3c1b1
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 762642
Reviewed-on: https://chromium-review.googlesource.com/942701
Reviewed-by: Tsuyoshi Horo <horo@chromium.org>
Commit-Queue: Tsuyoshi Horo <horo@chromium.org>
Cr-Commit-Position: refs/heads/master@{#540098}