notification scheduler: Include <algorithm> for std::{upper,lower}_bound
IWYU. This fixes the libstdc++ build after commit
b7a9a779adee ("Notification scheduler: Add two new service APIs"):

../../chrome/browser/notifications/scheduler/internal/scheduler_utils.cc:75:18: error: no matching function for call to 'lower_bound'
    auto right = lower_bound(impressions.rbegin(), impressions.rend(),
                 ^~~~~~~~~~~
../../../../../../usr/bin/../lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/bits/stl_algobase.h:984:5: note: candidate function template not viable: requires 3 arguments, but 4 were provided
    lower_bound(_ForwardIterator __first, _ForwardIterator __last,
    ^
../../chrome/browser/notifications/scheduler/internal/scheduler_utils.cc:80:17: error: use of undeclared identifier 'upper_bound'
    auto left = upper_bound(impressions.rbegin(), impressions.rend(),
                ^

Bug: 957519
Change-Id: Id73ae91a738237ed9d3940f424e4f9d60332a862
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1681765
Auto-Submit: Raphael Kubo da Costa <raphael.kubo.da.costa@intel.com>
Commit-Queue: Xing Liu <xingliu@chromium.org>
Reviewed-by: Xing Liu <xingliu@chromium.org>
Cr-Commit-Position: refs/heads/master@{#673379}