Revert of More regular Platform implementations in unit tests (reland.) (patchset #14 id:260001 of https://codereview.chromium.org/1456873003/ )
Reason for revert:
Looks like this is causing build issues.  E.g. http://build.chromium.org/p/chromium.win/waterfall?builder=Win%20x64%20GN%20(dbg)

Example:
FAILED: ninja -t msvc -e environment.x64 -- E:\b\build\goma/gomacc.exe "E:\b\depot_tools\win_toolchain\vs2013_files\VC\bin\amd64/cl.exe" /nologo /showIncludes /FC @obj/third_party/WebKit/Source/platform/test_support/TestingPlatformSupport.obj.rsp /c ../../third_party/WebKit/Source/platform/testing/TestingPlatformSupport.cpp /Foobj/third_party/WebKit/Source/platform/test_support/TestingPlatformSupport.obj /Fdobj/third_party/WebKit/Source/platform/test_support_cc.pdb
e:\b\build\slave\win_x64_gn\build\src\third_party\webkit\source\wtf\vector.h(654) : error C2220: warning treated as error - no 'object' file generated
        e:\b\build\slave\win_x64_gn\build\src\third_party\webkit\source\wtf\vector.h(644) : while compiling class template member function 'WTF::Vector<char,0x00,WTF::PartitionAllocator>::Vector(size_t)'
        e:\b\build\slave\win_x64_gn\build\src\third_party\webkit\source\platform\testing\testingplatformsupport.cpp(38) : see reference to function template instantiation 'WTF::Vector<char,0x00,WTF::PartitionAllocator>::Vector(size_t)' being compiled
        e:\b\build\slave\win_x64_gn\build\src\third_party\webkit\source\platform\testing\testingplatformsupport.h(56) : see reference to class template instantiation 'WTF::Vector<char,0x00,WTF::PartitionAllocator>' being compiled
e:\b\build\slave\win_x64_gn\build\src\third_party\webkit\source\wtf\vector.h(654) : warning C4267: '=' : conversion from 'size_t' to 'unsigned int', possible loss of data
e:\b\build\slave\win_x64_gn\build\src\third_party\webkit\source\wtf\vector.h(313) : warning C4267: '=' : conversion from 'size_t' to 'unsigned int', possible loss of data
        e:\b\build\slave\win_x64_gn\build\src\third_party\webkit\source\wtf\vector.h(306) : while compiling class template member function 'void WTF::VectorBufferBase<T,false,Allocator>::allocateBuffer(size_t)'
        with
        [
            T=char
,            Allocator=WTF::PartitionAllocator
        ]
        e:\b\build\slave\win_x64_gn\build\src\third_party\webkit\source\wtf\vector.h(386) : see reference to function template instantiation 'void WTF::VectorBufferBase<T,false,Allocator>::allocateBuffer(size_t)' being compiled
        with
        [
            T=char
,            Allocator=WTF::PartitionAllocator
        ]
        e:\b\build\slave\win_x64_gn\build\src\third_party\webkit\source\wtf\vector.h(373) : see reference to class template instantiation 'WTF::VectorBufferBase<T,false,Allocator>' being compiled
        with
        [
            T=char
,            Allocator=WTF::PartitionAllocator
        ]
        e:\b\build\slave\win_x64_gn\build\src\third_party\webkit\source\wtf\vector.h(618) : see reference to class template instantiation 'WTF::VectorBuffer<T,0x00,Allocator>' being compiled
        with
        [
            T=char
,            Allocator=WTF::PartitionAllocator
        ]
e:\b\build\slave\win_x64_gn\build\src\third_party\webkit\source\wtf\vector.h(415) : warning C4267: '=' : conversion from 'size_t' to 'unsigned int', possible loss of data
        e:\b\build\slave\win_x64_gn\build\src\third_party\webkit\source\wtf\vector.h(411) : while compiling class template member function 'bool WTF::VectorBuffer<T,0x00,Allocator>::shrinkBuffer(size_t)'
        with
        [
            T=blink::Address
,            Allocator=WTF::PartitionAllocator
        ]
        e:\b\build\slave\win_x64_gn\build\src\third_party\webkit\source\wtf\vector.h(1093) : see reference to function template instantiation 'bool WTF::VectorBuffer<T,0x00,Allocator>::shrinkBuffer(size_t)' being compiled
        with
        [
            T=blink::Address
,            Allocator=WTF::PartitionAllocator
        ]
        e:\b\build\slave\win_x64_gn\build\src\third_party\webkit\source\wtf\vector.h(618) : see reference to class template instantiation 'WTF::VectorBuffer<T,0x00,Allocator>' being compiled
        with
        [
            T=blink::Address
,            Allocator=WTF::PartitionAllocator
        ]
        e:\b\build\slave\win_x64_gn\build\src\third_party\webkit\source\platform\heap\threadstate.h(621) : see reference to class template instantiation 'WTF::Vector<blink::Address,0x00,WTF::PartitionAllocator>' being compiled
e:\b\build\slave\win_x64_gn\build\src\third_party\webkit\source\wtf\vector.h(1024) : warning C4267: '=' : conversion from 'size_t' to 'unsigned int', possible loss of data
        e:\b\build\slave\win_x64_gn\build\src\third_party\webkit\source\wtf\vector.h(1019) : while compiling class template member function 'void WTF::Vector<blink::Address,0x00,WTF::PartitionAllocator>::shrink(size_t)'
        e:\b\build\slave\win_x64_gn\build\src\third_party\webkit\source\wtf\vector.h(1086) : see reference to function template instantiation 'void WTF::Vector<blink::Address,0x00,WTF::PartitionAllocator>::shrink(size_t)' being compiled
        e:\b\build\slave\win_x64_gn\build\src\third_party\webkit\source\wtf\vector.h(1081) : while compiling class template member function 'void WTF::Vector<blink::Address,0x00,WTF::PartitionAllocator>::shrinkCapacity(size_t)'
        e:\b\build\slave\win_x64_gn\build\src\third_party\webkit\source\wtf\vector.h(745) : see reference to function template instantiation 'void WTF::Vector<blink::Address,0x00,WTF::PartitionAllocator>::shrinkCapacity(size_t)' being compiled
ninja: build stopped: subcommand failed.

Original issue's description:
> More regular Platform implementations in unit tests.
>
> R=haraken,jbroman
> BUG=
>
> Committed: https://crrev.com/81286531cd82370140d781f6daad585d44c1747c
> Cr-Commit-Position: refs/heads/master@{#361019}

TBR=jbroman@chromium.org,haraken@chromium.org,tkent@chromium.org,sigbjornf@opera.com
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=

Review URL: https://codereview.chromium.org/1464953003

Cr-Commit-Position: refs/heads/master@{#361024}