Revert "Suppress flaky DownloadHistoryAdapterTests."
This reverts commit 66e9d5a3da56369e4537a22d53625088e0692b5f.

Reason for revert:
This change seems to have broken the build at https://build.chromium.org/p/chromium.linux/builders/Android%20Clang%20Builder%20%28dbg%29/builds/100644

../../chrome/android/javatests/src/org/chromium/chrome/browser/download/ui/DownloadHistoryAdapterTest.java:439: error: [JUnit4TestNotRun] Test method will not be run; please add @Test annotation
    public void testInProgress_FilePathMapAccurate() throws Exception {
                ^
    (see http://errorprone.info/bugpattern/JUnit4TestNotRun)
  Did you mean '@Test'?
../../chrome/android/javatests/src/org/chromium/chrome/browser/download/ui/DownloadHistoryAdapterTest.java:588: error: [JUnit4TestNotRun] Test method will not be run; please add @Test annotation
    public void testSearch_RemoveItem() throws Exception {
                ^
    (see http://errorprone.info/bugpattern/JUnit4TestNotRun)
  Did you mean '@Test'?
2 errors

Original change's description:
> Suppress flaky DownloadHistoryAdapterTests.
> 
> RemoveItem and FilePathMapAccurate are flaky at a high enough rate
> (>20%) they may still flake with RetryOnFailure, so disabling them.
> Mark Filter_SevenItems and UpdateItems RetryOnFailure.
> 
> NOTRY=true
> TBR=twellington
> BUG=749351
> 
> Change-Id: I5a771fb22caf75d721d31880122372c75ef3b8c5
> Reviewed-on: https://chromium-review.googlesource.com/588060
> Commit-Queue: Alexandre Elias <aelias@chromium.org>
> Reviewed-by: Alexandre Elias <aelias@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#489834}

TBR=aelias@chromium.org,twellington@chromium.org

Change-Id: I21e97fd624af494974d7b77ba894b393683df9cf
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 749351
Reviewed-on: https://chromium-review.googlesource.com/588427
Reviewed-by: Matt Falkenhagen <falken@chromium.org>
Commit-Queue: Matt Falkenhagen <falken@chromium.org>
Cr-Commit-Position: refs/heads/master@{#489842}