Fixed a compilation error.
CL 2900276 caused an error for different overridden function signature.
chromeos/services/libassistant/audio/audio_input_impl.cc:213:51: error:
  non-virtual member function marked 'override' hides virtual member
  function
  void OnCaptureError(const std::string& message) override {
                                                  ^
media/base/audio_capturer_source.h:48:18: note: hidden overloaded virtual
function 'media::AudioCapturerSource::CaptureCallback::OnCaptureError'
declared here: different number of parameters (2 vs 1)
  virtual void OnCaptureError(ErrorCode code, const std::string& message) = 0;
                 ^

Bug: n/a
Change-Id: I15068901612f6392413f5fd914d38ed700d7cabe
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2917766
Commit-Queue: Jun Liu <yjliu@chromium.org>
Commit-Queue: Ahmed Fakhry <afakhry@chromium.org>
Reviewed-by: Ahmed Fakhry <afakhry@chromium.org>
Owners-Override: Ahmed Fakhry <afakhry@chromium.org>
Cr-Commit-Position: refs/heads/master@{#886523}