gardener: Disable ChromeRenderProcessHostTest.ProcessPerTab
Test is flaky on all platforms:

https://ci.chromium.org/ui/test/chromium/%3A%2F%2Fchrome%2Ftest%5C%3Abrowser_tests!gtest%3A%3AChromeRenderProcessHostTest%23ProcessPerTab

Example error:
```
...\render_process_host_chrome_browsertest.cc(345): error: Expected equality of these values:
  host_count
    Which is: 4
  RenderProcessHostCount()
    Which is: 5
```

Bug: 497106715
Change-Id: I1c396f6fad494ff42f8e4c8c8d3e534ab4188005
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/8027692
Commit-Queue: Giovanni Ortuno Urquidi <ortuno@chromium.org>
Auto-Submit: Giovanni Ortuno Urquidi <ortuno@chromium.org>
Reviewed-by: Paula Gómez <paugomez@google.com>
Owners-Override: Giovanni Ortuno Urquidi <ortuno@chromium.org>
Commit-Queue: Paula Gómez <paugomez@google.com>
Cr-Commit-Position: refs/heads/main@{#1655077}