Correct comment in BACW.
Essentially, these methods can not be removed completely until the referenced
interface is also migrated over to AXPlatformNodeWin.  The reason is that they
have a name conflict which causes the compiler to get confused about the hidden
overloaded virtual function.  For example:

../..\content/browser/accessibility/browser_accessibility_com_win.h(283,3):

error: 'content::BrowserAccessibilityComWin::get_attributes' hides overloaded
virtual function [-Werror,-Woverloaded-virtual]

  get_attributes(unsigned short max_attribs,
  ^

../..\ui/accessibility/platform/ax_platform_node_win.h(377,16):  note: hidden
overloaded virtual function 'ui::AXPlatformNodeWin::get_attributes' declared
here: different number of parameters (1 vs 5)

STDMETHODIMP get_attributes(BSTR* attributes) override;

Bug: 703369
Change-Id: Ie60e432c5630b0a6c268683f6b38d80e42faa349
Reviewed-on: https://chromium-review.googlesource.com/653190
Reviewed-by: Nektarios Paisios <nektar@chromium.org>
Commit-Queue: Doug Turner <dougt@chromium.org>
Cr-Commit-Position: refs/heads/master@{#500335}