Depend on jsr305 statically
This fixes the following AOSP build failure:

  error: external/cronet/base/Android.bp:2557:1: module "cronet_aml_base_callback_java" variant "android_common": cronet_aml_base_callback_java cannot depend on jsr305. Module belonging to Apex(es) is not allowed to depend on the modules belonging to other Apex(es). Either include the depending module in the Apex or convert the depending module to java_sdk_library and depend on its stubs.

Bug: b:381421702
Change-Id: I083fc67910ec1a25aa73ba7cb566e639a3556570
Cq-Include-Trybots: luci.chromium.try:android-cronet-arm64-gn2bp-dbg
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6105831
Auto-Submit: Etienne Dechamps <edechamps@google.com>
Reviewed-by: Stefano Duo <stefanoduo@google.com>
Commit-Queue: Stefano Duo <stefanoduo@google.com>
Cr-Commit-Position: refs/heads/main@{#1407350}