Revert of Leak reports collect information about the last uptrend (patchset #4 id:60001 of https://codereview.chromium.org/2403223002/ )
Reason for revert:
Broke the MSan build:

https://build.chromium.org/p/chromium.memory.full/builders/Chromium%20Linux%20ChromeOS%20MSan%20Builder/builds/2091/steps/compile/logs/stdio
In file included from ../../base/containers/hash_tables.h:9:
../../buildtools/third_party/libc++/trunk/include/unordered_map:785:5: error: static_assert failed "Invalid allocator::value_type"
    static_assert((is_same<value_type, typename allocator_type::value_type>::value),
    ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../components/metrics/leak_detector/call_stack_table.h:98:39: note: in instantiation of template class 'std::__1::unordered_map<const metrics::leak_detector::CallStack *, metrics::leak_detector::CallStackTable::CallStackCountInfo, metrics::leak_detector::CallStackTable::StoredHash, std::__1::equal_to<const metrics::leak_detector::CallStack *>, STLAllocator<std::__1::pair<const metrics::leak_detector::CallStack *const, unsigned int>, metrics::leak_detector::CustomAllocator> >' requested here
                 TableEntryAllocator> entry_map_;
                                      ^
../../components/metrics/leak_detector/call_stack_table.h:98:39: error: private field 'entry_map_' is not used [-Werror,-Wunused-private-field]
                 TableEntryAllocator> entry_map_;
                                      ^
2 errors generated.

Original issue's description:
> Leak reports collect information about the last uptrend
>
> Leak reports collect information about the last uptrend in the number
> of allocations for a given call stack. Changes include new public methods in
> CallStackTable, new fields in LeakDetectorImpl::LeakReport and the mojo
> structs, minor changes in LeakDetector and LeakDetectorImpl, and updates in
> unit tests for CallStackTable and protobuf_to_mojo_converter.
>
> BUG=650352
>
> Committed: https://crrev.com/11aa96ed7e3423bd90af355e8a8e55db1c55fdae
> Cr-Commit-Position: refs/heads/master@{#425464}

TBR=sque@google.com,sque@chromium.org,wfh@chromium.org,asvitkine@google.com,asvitkine@chromium.org,mwlodar@google.com
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=650352

Review-Url: https://codereview.chromium.org/2417403002
Cr-Commit-Position: refs/heads/master@{#425513}