Revert "[BRP] Enable check_raw_ptr_fields for Windows"
This reverts commit ae75cc3c26b297701558c73815d42e5fa206d2ea.

Reason for revert: [Sheriff] Suspect of causing Windows compilation error:
https://ci.chromium.org/ui/p/chromium/builders/ci/GPU%20Win%20x64%20Builder/55007/overview

Original change's description:
> [BRP] Enable check_raw_ptr_fields for Windows
>
> Bug: 1273182
> Change-Id: I73d35faa5d77dafefa4f5f3f63c5a8d8e4ebd071
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4439237
> Commit-Queue: Keishi Hattori <keishi@chromium.org>
> Reviewed-by: Takuto Ikuta <tikuta@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1132893}

Bug: 1273182
Change-Id: I83287791ff8d4ab2e3e508efa55186e2147b2408
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4452347
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Owners-Override: Luciano Pacheco <lucmult@chromium.org>
Auto-Submit: Luciano Pacheco <lucmult@chromium.org>
Commit-Queue: Takuto Ikuta <tikuta@chromium.org>
Reviewed-by: Takuto Ikuta <tikuta@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1132904}