Revert "Roll gn from 4a8016dc3915 to 96297ebb3e92"
This reverts commit 560c9633364891fb1680cff71066ebfddda4cd31.

Reason for revert:
https://ci.chromium.org/ui/p/chromium/builders/ci/android-archive-rel/53404/overview
error: failed to load build.ninja: open clang_x86/toolchain.ninja: no such file or directory


Original change's description:
> Roll gn from 4a8016dc3915 to 96297ebb3e92
>
> https://gn.googlesource.com/gn.git/+log/4a8016dc3915..96297ebb3e92
>
> 2025-03-04 pcc@google.com Pass --with-lg-page=16 when building jemalloc for arm64.
> 2025-03-03 digit@google.com Remove obsolete debug checks.
>
> If this roll has caused a breakage, revert this CL and stop the roller
> using the controls here:
> https://autoroll.skia.org/r/gn-chromium-autoroll
> Please CC dpranke@chromium.org,dpranke@google.com,thakis@chromium.org on the revert to ensure that a human
> is aware of the problem.
>
> To file a bug in Chromium: https://bugs.chromium.org/p/chromium/issues/entry
>
> To report a problem with the AutoRoller itself, please file a bug:
> https://issues.skia.org/issues/new?component=1389291&template=1850622
>
> Documentation for the AutoRoller is here:
> https://skia.googlesource.com/buildbot/+doc/main/autoroll/README.md
>
> Tbr: dpranke@chromium.org,thakis@chromium.org
> Change-Id: I70152ef2e5367408b0fc83140ca049273bc937a8
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6321407
> Commit-Queue: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>
> Bot-Commit: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>
> Cr-Commit-Position: refs/heads/main@{#1427556}

No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Change-Id: I909e54f41b58b4aef08f2719925250af00703da6
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6320279
Auto-Submit: Alan Cutter <alancutter@google.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Cr-Commit-Position: refs/heads/main@{#1427561}