Open a new browser window without session restore for "New Window".
Based on the latest requirement (go/cros-full-restore-prd):
If the browser is ‘not running’ (i.e. no windows open), then we should
respect the browser’s restore setting when launched from:
Shelf or Launcher icons
Ctrl-t keyboard shortcut
Clicking on links from outside of the browser
Exception: If the user explicitly creates a new window (ctrl-n, or
right click > New window), we should open a new browser window.

This CL is used to handle the exception: Create a new browser window
without session restore if launch from:
ctrl-n
right click > New window

Modify the Browser class to add `should_restore_` to specify whether we
should restore the session for the new browser window, similar to
`omit_from_session_restore_`.

We can't reuse `omit_from_session_restore_`, because it omits the
saving process. However, with `should_restore_` = false, only the
restore process is skipped, and the browser window is still saved to
the session file to be restored for the next time.

Modify the interface `NewWindow`, to pass the parameter `restore` when
create a new browser window from ctrl-n or from the new window menu.

Modify the browser commands to add 2 new interfaces:
NewEmptyWindowWithRestoreOption
OpenEmptyWindowWithRestoreOption
To create the browser window without restoring the session.

BUG=1232060

Change-Id: I6c704115dde051ef59132464784866ba51c4c374
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3065203
Reviewed-by: Scott Violet <sky@chromium.org>
Reviewed-by: Xiyuan Xia <xiyuan@chromium.org>
Commit-Queue: Nancy Wang <nancylingwang@chromium.org>
Cr-Commit-Position: refs/heads/main@{#913266}