gamepad dispatcher: pass in execution context
Pass EC in instead of the task runner. Puts the task type in the
dispatcher class instead of the calling class. Dropped std::move:
  error: moving a temporary object prevents copy elision

Also paves the way for some new objects which will need the
execution context.

Change-Id: Id0608ccf129443532091e7bdfe0afccb146172ef
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2152134
Reviewed-by: Kentaro Hara <haraken@chromium.org>
Reviewed-by: Kouhei Ueno <kouhei@chromium.org>
Commit-Queue: Johann Koenig <johannkoenig@google.com>
Cr-Commit-Position: refs/heads/master@{#762725}