Revert "Allow kiosk apps with "videoCapture" permission to move camera"
This reverts commit 376fb723c99a94b1c54204c0e4c8c837d72767f5.

Reason for revert: Caused build failure on android-marshmallow-x86-rel
https://ci.chromium.org/p/chromium/builders/try/android-marshmallow-x86-rel

../../chrome/browser/media/webrtc/chrome_camera_pan_tilt_zoom_permission_context_delegate.cc:54:10: error: 'return' will never be executed [-Werror,-Wunreachable-code-return]
return false;
^~~~~
1 error generated.


Original change's description:
> Allow kiosk apps with "videoCapture" permission to move camera
>
> This CL allows autolaunched kiosk apps to move the camera when the
> "videoCapture" permission is granted. Without it, chrome apps can't move
> camera.
>
> Bug: 1223031
> Change-Id: Icf1a1e9271f790ac14dd0aaeb7368066ed5ea8f9
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2972683
> Reviewed-by: Clark DuVall <cduvall@chromium.org>
> Reviewed-by: Ted Choc <tedchoc@chromium.org>
> Reviewed-by: Devlin <rdevlin.cronin@chromium.org>
> Reviewed-by: Illia Klimov <elklm@chromium.org>
> Commit-Queue: François Beaufort <beaufort.francois@gmail.com>
> Cr-Commit-Position: refs/heads/main@{#913284}

Bug: 1223031
Change-Id: I6b2b9f477d40d02d87d066071950fa778132933a
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3105635
Owners-Override: Tsuyoshi Horo <horo@chromium.org>
Auto-Submit: Tsuyoshi Horo <horo@chromium.org>
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Cr-Commit-Position: refs/heads/main@{#913293}