Revert "Dynamically update cookies link row label based on cookie setting."
This reverts commit c3a9401549ef09573cde7401e70b2acf48a3633b.

Reason for revert: Flakily failing on all platforms:
https://ci.chromium.org/p/chromium/builders/ci/Linux%20Tests/88090
[27939:27939:0312/140853.144376:ERROR:CONSOLE(49)] "Mocha test failed: SiteSettingsPage CookiesLinkRowSublabel
AssertionError: expected 'Allow sites to save and read cookie data' to equal undefined
    at Function.assert.strictEqual (file:///b/s/w/ir/third_party/chaijs/chai.js:2329:32)
    at assertEquals (file:///b/s/w/ir/chrome/test/data/webui/test_api.js:699:15)
    at Context.<anonymous> (file:///b/s/w/ir/chrome/test/data/webui/settings/site_settings_page_test.js:74:5)
Bug: 1061249

Original change's description:
> Dynamically update cookies link row label based on cookie setting.
>
> Previously link rows for content settings displayed one of two labels
> describing their current setting. This CL extends the capability of
> the cookies link rows specifically to express one of the four possible
> effective cookie settings.
>     -Allow
>     -Block Third Party only in Incognito
>     -Block Third Party
>     -Block
>
> To ensure that this label remains correct across both the preference
> and content settings changes that affect the effective cookie setting,
> an additional WebUI listener is created which pushes updates to JS
> for immediate display.
>
> This updated label is applied to both cookies link row locations
> when the privacySettingsRedesign flag is enabled, and applied to
> neither when it is disabled.
>
> Bug: 1032584
> Change-Id: I11a984bce60878b6224506bfc1cd1a5cf3a2e63e
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2095925
> Commit-Queue: Theodore Olsauskas-Warren <sauski@google.com>
> Reviewed-by: dpapad <dpapad@chromium.org>
> Reviewed-by: Martin Šrámek <msramek@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#749510}

TBR=dpapad@chromium.org,msramek@chromium.org,dullweber@chromium.org,sauski@google.com

Change-Id: I43acd7240282ed62e20f2321cd53bf6f2963d45a
No-Presubmit: true
No-Tree-Checks: true
Bug: 1032584
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2101389
Reviewed-by: Alan Cutter <alancutter@chromium.org>
Commit-Queue: Alan Cutter <alancutter@chromium.org>
Cr-Commit-Position: refs/heads/master@{#749986}