Revert of Update Crashpad to 6da9708e7cc93e2e1772439d51646e47583cb225
Reason for revert:
This CL causes a mac compile failure:
https://build.chromium.org/p/chromium.mac/buildstatus?builder=Mac%20Builder&number=61782

../../third_party/crashpad/crashpad/handler/handler_main.cc:166:7: error: unused variable 'rv' [-Werror,-Wunused-variable]
  int rv = sigaction(sig, &sa, nullptr);
      ^
../../third_party/crashpad/crashpad/handler/handler_main.cc:241:9: error: unused variable 'rv' [-Werror,-Wunused-variable]
    int rv = raise(sig);
        ^
../../third_party/crashpad/crashpad/handler/handler_main.cc:254:7: error: unused variable 'rv' [-Werror,-Wunused-variable]
  int rv = raise(sig);
      ^

Original issue's description:
> Update Crashpad to 6da9708e7cc93e2e1772439d51646e47583cb225
>
> 1f82c6cc8a35 Ensure Content-Length does not appear with Transfer-
>              Encoding
> c1b305244aba Update mig.py to take an explicit sdk argument
> d98a4de718d9 win: support native x86 CONTEXT structures with x87 but no
>              SSE context
> 0c322ecc3f71 Use zlib to gzip-compress uploads
> 546e64cd0b1b Centrally define CPUContextX86::Fsave and fsave↔︎fxsave
>              conversions
> 4c6f6e52e2d7 Remove vestigial support for in-Chromium GYP build
> f34ed66b93a0 metrics: Record handler lifetime milestone events
> c1af20f1aa8a metrics: Consistently comment about enums used for metrics
> 9c8407123796 Fix warning when building with clang on Windows
> 6da9708e7cc9 doc: Fix Doxygen errors
>
> BUG=crashpad:100,crashpad:157,crashpad:159,crashpad:161,crashpad:162
>
> Review-Url: https://codereview.chromium.org/2710663006
> Cr-Commit-Position: refs/heads/master@{#452387}

TBR=mark@chromium.org, isherman@chromium.org, scottmg@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=crashpad:100,crashpad:157,crashpad:159,crashpad:161,crashpad:162

Review-Url: https://codereview.chromium.org/2705373005
Cr-Commit-Position: refs/heads/master@{#452409}