Reland "Reland "[CR2023] Fix icons in app menu.""
This is a reland of commit 8cced2108482bfb126f33d39ce0f86ba0fe947f4

Third time is the charm...
This is the same issue again where AppMenuBrowserTestRefreshOnly pixel tests failed.

Test failures will have a link to the corresponding skia gold image.

For example
https://ci.chromium.org/ui/p/chromium/builders/ci/Win10%20Tests%20x64/82819/overview

will write in the failure the following link to triage the pixel image

```
[1556:1604:0717/034502.287:WARNING:skia_gold_pixel_diff.cc(244)] For committers not using @google.com account, triage using the following link: https://chrome-public-gold.skia.org/detail?grouping=name%3DCR2023_AppMenuBrowserTestRefreshOnly_InvokeUi_main_windows%26source_type%3Dgtest-pixeltests&digest=7b9ec227dbdd5cda46e0578c88c17283
..\..\chrome\browser\ui\test\test_browser_ui.cc(170): error: Value of: VerifyUi()
  Actual: false
Expected: true
```
Link:
https://chrome-public-gold.skia.org/detail?grouping=name%3DCR2023_AppMenuBrowserTestRefreshOnly_InvokeUi_main_windows%26source_type%3Dgtest-pixeltests&digest=7b9ec227dbdd5cda46e0578c88c17283

Google accounts can review the pixel test to confirm that the image is correct. I've already triaged images from the previous failures but will be monitoring the Windows test build page for any new failures. Note for Gardeners: feel free to approve the image first to see if that resolves any new failures. The changes should solely be with the icons.

Original change's description:
> Reland "[CR2023] Fix icons in app menu."
>
> This is a reland of commit 26dd7b6c8bc0dced8a4ef5c5db58ab4f4e31598d
>
> I forgot to approve the pixel gold images and didn't realize that would trigger a revert.
>
> Original change's description:
> > [CR2023] Fix icons in app menu.
> >
> > Adjusted some icons for 3 dot menu.
> >
> > Screenshots:
> > https://screenshot.googleplex.com/3jDxFBuqX8oEvAj
> >
> > Bug: 1463057
> > Change-Id: I69c74afcec436a0c2121f31c4ad9a1f2231ee9a8
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4684807
> > Reviewed-by: Avi Drissman <avi@chromium.org>
> > Commit-Queue: David Yeung <dayeung@chromium.org>
> > Code-Coverage: Findit <findit-for-me@appspot.gserviceaccount.com>
> > Cr-Commit-Position: refs/heads/main@{#1170240}
>
> Bug: 1463057
> Change-Id: I369e2585265e7e6341458f624fc3b15fb5ba2b67
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4684777
> Reviewed-by: Avi Drissman <avi@chromium.org>
> Commit-Queue: David Yeung <dayeung@chromium.org>
> Code-Coverage: Findit <findit-for-me@appspot.gserviceaccount.com>
> Cr-Commit-Position: refs/heads/main@{#1170762}

Bug: 1463057
Change-Id: I9b3efbde0691d267370fe5a9c66d8afdeee56b19
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4690602
Code-Coverage: Findit <findit-for-me@appspot.gserviceaccount.com>
Commit-Queue: David Yeung <dayeung@chromium.org>
Reviewed-by: Avi Drissman <avi@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1171798}