Reland "fix fetch_reclient_cfgs.py for windows"
This reverts commit 3d8620fa6b610ccf3497e78f5427e55cdfce138a.

Reason for revert:
 fix args to a string for shell=True

Original change's description:
> Revert "fix fetch_reclient_cfgs.py for windows"
>
> This reverts commit b824e59bdf4a62d6c3c030dd9ed53567b83406f0.
>
> Reason for revert: fetch_reclient_cfgs has started failing across many linux builders, e.g. 
> https://ci.chromium.org/ui/p/chromium/builders/ci/lacros-arm-generic-rel/42662/steps
>
> Original change's description:
> > fix fetch_reclient_cfgs.py for windows
> >
> > on windows dev machine, cipd is depot_tools/cipd.bat,
> > but it fails with
> >  FileNotFoundError: [WinError 2] The system cannot find the file specified.
> >
> > on windows builders, it works as cipd.exe can be found in %PATH%
> >
> > Use shell=True to work on both use case.
> >
> > Bug: 1346179
> > Change-Id: Iabf092ebcc4781d1a3c1801caf465b76cc00fd14
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3778907
> > Commit-Queue: Takuto Ikuta <tikuta@chromium.org>
> > Auto-Submit: Fumitoshi Ukai <ukai@google.com>
> > Commit-Queue: Fumitoshi Ukai <ukai@google.com>
> > Reviewed-by: Takuto Ikuta <tikuta@chromium.org>
> > Cr-Commit-Position: refs/heads/main@{#1026625}
>
> Bug: 1346179
> Change-Id: I98e4aeeb57452614e71556165331e6e269ddeacf
> No-Presubmit: true
> No-Tree-Checks: true
> No-Try: true
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3779087
> Commit-Queue: Tim Sergeant <tsergeant@chromium.org>
> Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
> Owners-Override: Tim Sergeant <tsergeant@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1026633}

Bug: 1346179
Change-Id: I841604d8215e67934cadcda541ec96b3d1543189
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3779438
Commit-Queue: Fumitoshi Ukai <ukai@google.com>
Reviewed-by: Takuto Ikuta <tikuta@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1027102}