GCC: Make DIPSDatabase::in_memory() not constexpr
GCC build fails because of using a non-constexpr inside a
constexpr:
chrome/browser/dips/dips_database.h:56:59: error:
call to non-'constexpr' function 'bool base::FilePath::empty() const'
Made DIPSDatabase::in_memory() not constexpr to resolve the issue.

Bug: 819294
Change-Id: Icd71df87943e88ca2e56df2f278b5107641d6e3a
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3916084
Reviewed-by: Joshua Hood <jdh@chromium.org>
Commit-Queue: Ivan Murashov <ivan.murashov@lge.com>
Cr-Commit-Position: refs/heads/main@{#1050638}