Revert "Split WebKit platform build file"
This reverts commit 080c70a7f837beb92ba1a6af71fd32098466656b.

Reason for revert: compile failure on "Google Chrome ChromeOS"

FAILED: obj/third_party/WebKit/Source/platform/network/network/MIMETypeRegistry.o
../../third_party/WebKit/Source/platform/network/mime/MIMETypeRegistry.cpp:17:10: fatal error: 'public/platform/mime_registry.mojom-blink.h' file not found
#include "public/platform/mime_registry.mojom-blink.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Original change's description:
> Split WebKit platform build file
> 
> A race condition was found in the build of //third_party/WebKit/Source/platform/loader.
> To resolve it necessary to extract targets  //third_party/WebKit/Source/platform/blob and //third_party/WebKit/Source/platform/network form //third_party/WebKit/Source/platform. And add correct dependencies where it is needed.
> All of these done in this CL.
> 
> Original author is apisarev@yandex-team.ru, and toyoshim@chromium.org takes over it
> to submit since it needs quick rebase works to catch up HEAD.
> 
> Bug: 754600
> Change-Id: I5f70348fac10f270df99b658608cf23685ed937e
> Test: gn check out/Release && ninja -C out/Release
> Reviewed-on: https://chromium-review.googlesource.com/612284
> Commit-Queue: Takashi Toyoshima <toyoshim@chromium.org>
> Reviewed-by: Daniel Bratell <bratell@opera.com>
> Reviewed-by: Takashi Toyoshima <toyoshim@chromium.org>
> Reviewed-by: Kinuko Yasuda <kinuko@chromium.org>
> Reviewed-by: Dimitri Glazkov <dglazkov@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#508661}

TBR=kinuko@chromium.org,toyoshim@chromium.org,bratell@opera.com,apisarev@yandex-team.ru,dglazkov@chromium.org

Change-Id: Ib68af601d53cd5f0f8fae621fb9324bf3b94880f
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 754600
Reviewed-on: https://chromium-review.googlesource.com/718516
Reviewed-by: Balazs Engedy <engedy@chromium.org>
Commit-Queue: Balazs Engedy <engedy@chromium.org>
Cr-Commit-Position: refs/heads/master@{#508665}