Revert "Roll DevTools Frontend from bf96586e7d27 to 33f773352d26 (12 revisions)"
This reverts commit bac8ef42cc1dd372503d5d2d6f6fda1ee39c873e.

Reason for revert: The autoroll seems to have broken the archive-rel builders.  See:

https://ci.chromium.org/ui/p/chromium/builders/ci/linux-archive-rel/46280/blamelist
https://ci.chromium.org/ui/p/chromium/builders/ci/mac-archive-rel/19384/blamelist
https://ci.chromium.org/ui/p/chromium/builders/ci/win32-archive-rel/20718/blamelist
https://ci.chromium.org/ui/p/chromium/builders/ci/win-archive-rel/22157/blamelist

In all cases, the archive step fails on the command:
python /b/s/w/ir/kitchen-checkout/depot_tools/gsutil.py -- -h x-goog-meta-Cr-Commit-Position:refs/heads/master@{#859471} -h x-goog-meta-Cr-Commit-Position-Number:859471 -h x-goog-meta-Cr-Git-Commit:58397316181a986f399895c628ecb5e1b568a8e7 cp -a public-read file:// gs://chromium-browser-snapshots/Linux_x64/859471/
CommandException: No URLs matched: file://

Where before it would execute:
python /b/s/w/ir/kitchen-checkout/depot_tools/gsutil.py -- -h x-goog-meta-Cr-Commit-Position:refs/heads/master@{#859461} -h x-goog-meta-Cr-Commit-Position-Number:859461 -h x-goog-meta-Cr-Git-Commit:476f0b1161508673068cf5b1b5ba721c4235b83a cp -a public-read file:///b/s/w/ir/cache/chrome_staging/devtools-frontend.zip gs://chromium-browser-snapshots/Linux_x64/859461/devtools-frontend.zip

Bug: 1184403

Original change's description:
> Roll DevTools Frontend from bf96586e7d27 to 33f773352d26 (12 revisions)
>
> https://chromium.googlesource.com/devtools/devtools-frontend.git/+log/bf96586e7d27..33f773352d26
>
> 2021-03-03 jacktfranklin@chromium.org Fix use_theme_colors rule incorrectly flagging background-image: var(...) usage
> 2021-03-03 pfaffe@chromium.org Opt more e2e tests into the mocha extension hooks
> 2021-03-03 tvanderlippe@chromium.org Remove resources/inspector output
> 2021-03-03 sigurds@chromium.org Optimize svg files
> 2021-03-03 tvanderlippe@chromium.org Remove copy_gen_to_resources
> 2021-03-03 jec@google.com Add keyboard shortcut to copy styles in the Elements panel
> 2021-03-03 jacktfranklin@chromium.org Parameterise run_lint_check_css script
> 2021-03-03 tvanderlippe@chromium.org Remove copy_sources_to_resources
> 2021-03-03 andoli@chromium.org Add Lighthouse's red, orange and green CSS colors to themeColors.css
> 2021-03-03 sigurds@chromium.org Fix DragHandler for usage in web components
> 2021-03-03 changhaohan@chromium.org Reland "Collapse whitespaces in DOM elements"
> 2021-03-03 sigurds@chromium.org [l18n] Fix wrong placeholder in DeveloperResourceView
>
> If this roll has caused a breakage, revert this CL and stop the roller
> using the controls here:
> https://autoroll.skia.org/r/devtools-frontend-chromium
> Please CC devtools-waterfall-sheriff-onduty@grotations.appspotmail.com on the revert to ensure that a human
> is aware of the problem.
>
> To report a problem with the AutoRoller itself, please file a bug:
> https://bugs.chromium.org/p/skia/issues/entry?template=Autoroller+Bug
>
> Documentation for the AutoRoller is here:
> https://skia.googlesource.com/buildbot/+doc/master/autoroll/README.md
>
> Bug: chromium:1163928,chromium:1174013,chromium:1174408,chromium:1175699,chromium:1177797,chromium:1181777,chromium:1184167,chromium:1184228
> Tbr: devtools-waterfall-sheriff-onduty@grotations.appspotmail.com
> Change-Id: Ib744c32d38ffa59f3ca78969de30e22f4acbab19
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2732748
> Commit-Queue: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>
> Bot-Commit: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>
> Cr-Commit-Position: refs/heads/master@{#859467}

Bug: chromium:1163928
Bug: chromium:1174013
Bug: chromium:1174408
Bug: chromium:1175699
Bug: chromium:1177797
Bug: chromium:1181777
Bug: chromium:1184167
Bug: chromium:1184228
Change-Id: I1cfaaf1091945964c8e765eda78de917c29fccec
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2736215
Reviewed-by: Gary Tong <gatong@chromium.org>
Commit-Queue: Gary Tong <gatong@chromium.org>
Cr-Commit-Position: refs/heads/master@{#859779}