Remove unused variable 'document'
When use old clang, such as clang-13 to build this code,
it will produce compile error like below:

error: unused variable 'document' [-Werror,-Wunused-variable]
  const WebDocument& document = GetMainDocument();
                     ^
so we should remove it.

Change-Id: Icf1b6e1a51439126033f9f1121098caec2539f7e
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5177791
Commit-Queue: Chris Harrelson <chrishtr@chromium.org>
Reviewed-by: Katie Dektar <katie@chromium.org>
Reviewed-by: Chris Harrelson <chrishtr@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1245002}