Reland "trigger_scripts: use log level for verbose output"
This reverts commit a2f76419f6b623707dea2636f6fb671eef2639a1.

Reason for revert:
fixed testing/trigger_scripts/chromeos_device_trigger.py

Original change's description:
> Revert "trigger_scripts: use log level for verbose output"
>
> This reverts commit 141a33df081a12eb31f2b49debcadcdce340e10a.
>
> Reason for revert: https://ci.chromium.org/p/chromium/builders/try/lacros-amd64-generic-rel/140827
> Traceback (most recent call last):
>   File "/b/s/w/ir/cache/builder/src/testing/trigger_scripts/chromeos_device_trigger.py", line 135, in <module>
>     sys.exit(main())
>   File "/b/s/w/ir/cache/builder/src/testing/trigger_scripts/chromeos_device_trigger.py", line 131, in main
>     args.shard_index or 0, args.shards)
>   File "/b/s/w/ir/cache/builder/src/testing/trigger_scripts/base_test_triggerer.py", line 239, in run_swarming_go
>     if 'tasks' not in merged_json:
> TypeError: argument of type 'int' is not iterable
> Argument not matching after deletion.
>
> Original change's description:
> > trigger_scripts: use log level for verbose output
> >
> > This is for https://crrev.com/c/3009392/7/testing/trigger_scripts/base_test_triggerer.py#165
> >
> > Bug: 984869
> > Change-Id: I7fc09fddbf13af3e7d28d4551e2356daf173eac5
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3033833
> > Auto-Submit: Takuto Ikuta <tikuta@chromium.org>
> > Commit-Queue: Brian Sheedy <bsheedy@chromium.org>
> > Reviewed-by: Brian Sheedy <bsheedy@chromium.org>
> > Cr-Commit-Position: refs/heads/master@{#903063}
>
> Bug: 984869, 1230770
> Change-Id: Ie25b4a240a38d2a0d8f734fad03f88ca2dd7b800
> No-Presubmit: true
> No-Tree-Checks: true
> No-Try: true
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3039721
> Owners-Override: Sven Zheng <svenzheng@chromium.org>
> Owners-Override: Elly Fong-Jones <ellyjones@chromium.org>
> Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
> Reviewed-by: Sven Zheng <svenzheng@chromium.org>
> Reviewed-by: Elly Fong-Jones <ellyjones@chromium.org>
> Commit-Queue: Elly Fong-Jones <ellyjones@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#903121}

Bug: 984869, 1230770
Cq-Include-Trybots: luci.chromium.try:lacros-amd64-generic-rel
Change-Id: Ic80fb497b571498d8ec5a20fdc95cdbd22770c28
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3038316
Auto-Submit: Takuto Ikuta <tikuta@chromium.org>
Commit-Queue: Brian Sheedy <bsheedy@chromium.org>
Reviewed-by: Elly Fong-Jones <ellyjones@chromium.org>
Reviewed-by: Brian Sheedy <bsheedy@chromium.org>
Cr-Commit-Position: refs/heads/master@{#903534}