Roll src/third_party/libvpx/source/libvpx/ b95d17572..eeb1be7f2 (26 commits)
https://chromium.googlesource.com/webm/libvpx.git/+log/b95d17572629..eeb1be7f23ee?first-parent=1

$ git log b95d17572..eeb1be7f2 --date=short --no-merges --format='%ad %ae %s'
2024-01-18 wtc Support VPX_IMG_FMT_NV12 in vpx_img_read/write
2024-01-18 wtc Make img_alloc_helper() fail on VPX_IMG_FMT_NONE
2024-01-18 jzern README: remove library version
2024-01-14 gerdazsejke.more Add SVE implementation of HBD MSE functions
2024-01-09 jianj Fix a typo in changelog for v1.14.0
2024-01-08 jianj Update version
2024-01-04 jianj Update changelog with vp9 ext rc
2024-01-02 jianj Update changelog
2023-12-15 jianj Remove VP9E_GET_TPL_STATS
2023-12-14 jianj Update AUTHORS and .mailmap
(...)
2023-12-05 marpan Add unittest for issue b/314857577
2023-12-05 wtc Remove SSE code for 128x* blocks
2023-09-28 wtc Use vpx_sse instead of vpx_mse to compute SSE
2023-12-06 jzern vp9_frame_scale.c,cosmetics: funnction -> function
2023-11-30 wtc Add the needed Android API level predicates.
2023-12-04 yunqingwang Fix a bug in frame scaling
2023-11-30 bohanli Fix edge case when downsizing to one.
2023-11-22 angiebird Set skip_recode=0 in nonrd_pick_sb_modes
2023-11-30 bohanli Fix scaled reference offsets.
2023-11-28 gerdazsejke.more configure: Add darwin23 support

Created with:
  roll-dep src/third_party/libvpx/source/libvpx

This contains the changes from https://crrev.com/c/5218204 &
https://crrev.com/c/5216352 which were reverted in
https://crrev.com/c/5220033, but disables SVE for Windows Arm64 due to a
clang-cl-18 failure:
..\..\third_party\llvm-build\Release+Asserts\lib\clang\18\include\arm_sve.h(271,1):
error: cannot mangle this built-in __SVInt8_t type yet

Bug: b:308446709, b:321595723
Change-Id: Ia270f080eafed95ed912d3e28dd4c3e4ca526264
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5225529
Commit-Queue: James Zern <jzern@google.com>
Reviewed-by: Wan-Teh Chang <wtc@google.com>
Cr-Commit-Position: refs/heads/main@{#1251619}