Revert of Roll Breakpad from 1345 to 1351. (https://codereview.chromium.org/400203002/)
Reason for revert:
Breaks android compile looks like: http://build.chromium.org/p/chromium.linux/builders/Android%20Builder%20%28dbg%29/builds/61939

FAILED: /b/build/goma/gomacc /b/build/slave/Android_Builder__dbg_/build/src/third_party/android_tools/ndk//toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++ -Wl,-z,now -Wl,-z,relro -Wl,--fatal-warnings -Wl,-z,noexecstack -fPIC -fuse-ld=gold -nostdlib -Wl,--no-undefined -Wl,--exclude-libs=ALL --sysroot=/b/build/slave/Android_Builder__dbg_/build/src/third_party/android_tools/ndk//platforms/android-14/arch-arm -Wl,--icf=safe -L/b/build/slave/Android_Builder__dbg_/build/src/third_party/android_tools/ndk//sources/cxx-stl/stlport/libs/armeabi-v7a -Bdynamic -Wl,--gc-sections -Wl,-z,nocopyreloc -pie -rdynamic /b/build/slave/Android_Builder__dbg_/build/src/third_party/android_tools/ndk//platforms/android-14/arch-arm/usr/lib/crtbegin_dynamic.o -Wl,--warn-shared-textrel -Wl,-O1 -Wl,--as-needed -o breakpad_unittests -Wl,--start-group obj/breakpad/src/client/linux/handler/breakpad_unittests.exception_handler_unittest.o obj/breakpad/src/client/linux/minidump_writer/breakpad_unittests.cpu_set_unittest.o obj/breakpad/src/client/linux/minidump_writer/breakpad_unittests.directory_reader_unittest.o obj/breakpad/src/client/linux/minidump_writer/breakpad_unittests.line_reader_unittest.o obj/breakpad/src/client/linux/minidump_writer/breakpad_unittests.linux_core_dumper_unittest.o obj/breakpad/src/client/linux/minidump_writer/breakpad_unittests.linux_ptrace_dumper_unittest.o obj/breakpad/src/client/linux/minidump_writer/breakpad_unittests.minidump_writer_unittest.o obj/breakpad/src/client/linux/minidump_writer/breakpad_unittests.minidump_writer_unittest_utils.o obj/breakpad/src/client/linux/minidump_writer/breakpad_unittests.proc_cpuinfo_reader_unittest.o obj/breakpad/src/common/linux/breakpad_unittests.elf_core_dump_unittest.o obj/breakpad/src/common/linux/breakpad_unittests.file_id_unittest.o obj/breakpad/src/common/linux/breakpad_unittests.linux_libc_support_unittest.o obj/breakpad/src/common/linux/breakpad_unittests.synth_elf.o obj/breakpad/src/common/linux/tests/breakpad_unittests.crash_generator.o obj/breakpad/src/common/breakpad_unittests.memory_unittest.o obj/breakpad/src/common/breakpad_unittests.simple_string_dictionary_unittest.o obj/breakpad/src/common/breakpad_unittests.test_assembler.o obj/breakpad/src/common/tests/breakpad_unittests.file_utils.o obj/breakpad/src/tools/linux/md2core/breakpad_unittests.minidump_memory_range_unittest.o obj/breakpad/src/common/android/breakpad_unittests.breakpad_getcontext_unittest.o obj/testing/libgtest.a obj/testing/libgtest_main.a obj/testing/libgmock.a obj/breakpad/libbreakpad_client.a obj/breakpad/libbreakpad_processor_support.a -Wl,--end-group  -llog -lstlport_static /b/build/slave/Android_Builder__dbg_/build/src/third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.8/libgcc.a -lc -ldl -lm /b/build/slave/Android_Builder__dbg_/build/src/third_party/android_tools/ndk//platforms/android-14/arch-arm/usr/lib/crtend_android.o
obj/breakpad/libbreakpad_client.a(obj/breakpad/src/client/linux/minidump_writer/breakpad_client.minidump_writer.o):minidump_writer.cc:function google_breakpad::TypedMDRVA<MDRawDirectory>::CopyIndex(unsigned int, MDRawDirectory*):error: undefined reference to 'google_breakpad::MinidumpFileWriter::Copy(unsigned int, void const*, int)'
obj/breakpad/libbreakpad_client.a(obj/breakpad/src/client/linux/minidump_writer/breakpad_client.minidump_writer.o):minidump_writer.cc:function google_breakpad::TypedMDRVA<unsigned int>::~TypedMDRVA():error: undefined reference to 'google_breakpad::MinidumpFileWriter::Copy(unsigned int, void const*, int)'
obj/breakpad/libbreakpad_client.a(obj/breakpad/src/client/linux/minidump_writer/breakpad_client.minidump_writer.o):minidump_writer.cc:function google_breakpad::TypedMDRVA<MDRawContextARM>::~TypedMDRVA():error: undefined reference to 'google_breakpad::MinidumpFileWriter::Copy(unsigned int, void const*, int)'
obj/breakpad/libbreakpad_client.a(obj/breakpad/src/client/linux/minidump_writer/breakpad_client.minidump_writer.o):minidump_writer.cc:function google_breakpad::TypedMDRVA<unsigned int>::CopyIndexAfterObject(unsigned int, void const*, unsigned int):error: undefined reference to 'google_breakpad::MinidumpFileWriter::Copy(unsigned int, void const*, int)'
collect2:error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

Original issue's description:
> Roll Breakpad from 1345 to 1351.
> 
> This pulls in the following CLs:
>  - r1346 Don't free pointer in BasicCodeModules::BasicCodeModules before possibly using it
>  - r1347 Stringify minidump stream_type constants in minidump_dump output
>  - r1348 Ensure C:/Dumps/ exists in crash_generation_app
>  - r1349 Change some ELF utils to return the length as a size_t
>  - r1350 Add frame pointer recovery to the AMD64 Stackwalker.
>  - r1351 [Android]: Remove __system_property_get(ro.build.fingerprint) from
> WriteOSInformation.
> 
> BUG=394841,393903
> 
> Committed: https://src.chromium.org/viewvc/chrome?view=rev&revision=284101

TBR=mark@chromium.org,rmcilroy@chromium.org
NOTREECHECKS=true
NOTRY=true
BUG=394841,393903

Review URL: https://codereview.chromium.org/401853002

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@284117 0039d316-1c4b-4281-b951-d872f2087c98