Revert "Roll devtools-internal from 168b9b7b891b to 68fdcc7b08c8 (1 revision)"
This reverts commit 36bc9b89cf7a28cd741155b2103e01348ec6f88b.

Reason for revert:
https://ci.chromium.org/ui/p/chrome/builders/try/linux-chrome-dbg-cog-cache-warmer/2207/overview

[617/9689] ACTION //content/browser/devtools:devtools_resources_grit(//build/toolchain/linux:clang_x64)
python3 ../../tools/grit/grit.py -i gen/third_party/devtools-frontend-internal/chrome_devtools_resources.grd build -o gen/content/browser/devtools --depdir . --depfile gen/content/browser/devtools/devtools_resources_grit.d --write-only-new=1 --depend-on-stamp -D DEVTOOLS_GRD_PATH=gen/third_party/devtools-frontend-internal/chrome_devtools_resources -D SHARED_INTERMEDIATE_DIR=gen -D _google_chrome=true -D _is_chrome_for_testing_branded=false -D chromeos_ash=false -D chromeos_lacros=false -D reven=false -D toolkit_views=true -D use_aura=true -D use_ozone=true -D use_titlecase=false -D scale_factors=2x -E branding_path_component=google_chrome -E root_gen_dir=gen -E root_src_dir=../../ -E CHROMIUM_BUILD=google_chrome -E protocol_file=gen/third_party/blink/public/devtools_protocol/protocol.json --brotli brotli -f gen/tools/gritsettings/default_resource_ids --assert-file-list obj/content/browser/devtools/devtools_resources_expected_outputs.txt
Traceback (most recent call last):
  File "../../tools/grit/grit.py", line 28, in <module>
    sys.exit(grit.grit_runner.Main(sys.argv[1:]))
  File "/b/s/w/ir/cache/builder/src/tools/grit/grit/grit_runner.py", line 313, in Main
    return toolobject.Run(options, args[1:])
  File "/b/s/w/ir/cache/builder/src/tools/grit/grit/tool/build.py", line 272, in Run
    self.Process()
  File "/b/s/w/ir/cache/builder/src/tools/grit/grit/tool/build.py", line 388, in Process
    self.res.InitializeIds()
  File "/b/s/w/ir/cache/builder/src/tools/grit/grit/node/misc.py", line 682, in InitializeIds
    self._id_map = _ComputeIds(self, predetermined_id_map)
  File "/b/s/w/ir/cache/builder/src/tools/grit/grit/node/misc.py", line 250, in _ComputeIds
    check_group_count()
  File "/b/s/w/ir/cache/builder/src/tools/grit/grit/node/misc.py", line 140, in check_group_count
    raise exception.IdRangeOverflow(msg)
grit.exception.IdRangeOverflow: ID range overflow.: Generated .grd file used more IDs (2502) than were allocated for it (2500) for type includes. You need to update ../../../gen/tools/gritsettings/default_resource_ids for this .grd.
exit=1
error: 1 steps failed


Original change's description:
> Roll devtools-internal from 168b9b7b891b to 68fdcc7b08c8 (1 revision)
>
> https://chrome-internal.googlesource.com/devtools/devtools-internal.git/+log/168b9b7b891b..68fdcc7b08c8
>
> Also rolling transitive DEPS:
>   https://chromium.googlesource.com/devtools/devtools-frontend.git/+log/030b8670cf6b3697f19a536191706106c8f89617..0585203198d69ad7f026edf138a1e873e38b79c9
>
> If this roll has caused a breakage, revert this CL and stop the roller
> using the controls here:
> https://skia-autoroll.corp.goog/r/devtools-internal-chromium
> Please CC devtools-waterfall-sheriff-onduty@rotations.google.com,liviurau@google.com on the revert to ensure that a human
> is aware of the problem.
>
> To report a problem with the AutoRoller itself, please file a bug:
> https://issues.skia.org/issues/new?component=1389291&template=1850622
>
> Documentation for the AutoRoller is here:
> https://skia.googlesource.com/buildbot/+doc/main/autoroll/README.md
>
> Cq-Include-Trybots: luci.chrome.try:linux-chromeos-chrome
> Bug: None
> Tbr: devtools-waterfall-sheriff-onduty@rotations.google.com
> Change-Id: I5e83aa3d60d52982db32179b718f3c1ade78cb13
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5662230
> Bot-Commit: chromium-internal-autoroll <chromium-internal-autoroll@skia-corp.google.com.iam.gserviceaccount.com>
> Commit-Queue: chromium-internal-autoroll <chromium-internal-autoroll@skia-corp.google.com.iam.gserviceaccount.com>
> Cr-Commit-Position: refs/heads/main@{#1320177}

Bug: None
Change-Id: I1dd7f4d7be7dfd2204a5f537f86dc344faeb86e4
Cq-Include-Trybots: luci.chrome.try:linux-chromeos-chrome
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5660205
Auto-Submit: Fumitoshi Ukai <ukai@google.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Cr-Commit-Position: refs/heads/main@{#1320180}