Revert "WebSQL: update policy expiration"
This reverts commit f259d74bfdf796db0eb590146052d1c89dbeb1e6.

Reason for revert: appears to break the build: chrome/browser/policy/configuration_policy_handler_list_factory.cc:2020:5: error: no member named 'kWebSQLAccess' in namespace 'policy::key'

Original change's description:
> WebSQL: update policy expiration
>
> This change updates the policy expiration to M123.
>
> Intent to Remove: https://groups.google.com/a/chromium.org/g/blink-dev/c/fWYb6evVA-w/m/4e3mN4G8AwAJ
> Blog: https://developer.chrome.com/blog/deprecating-web-sql#web_sql_deprecation_and_removal_steps
>
> Bug: 326228129
> Change-Id: Ie0be27ab0534f083706c209fca37b7208dae962b
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5310139
> Reviewed-by: Miriam Polzer <mpolzer@google.com>
> Commit-Queue: Ayu Ishii <ayui@chromium.org>
> Reviewed-by: Sergey Poromov <poromov@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1263422}

Bug: 326228129
Change-Id: I28d19818c46e139a332911c151cae05aa19a17ae
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5314883
Owners-Override: Daniel Cheng <dcheng@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Daniel Cheng <dcheng@chromium.org>
Auto-Submit: Daniel Cheng <dcheng@chromium.org>
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Cr-Commit-Position: refs/heads/main@{#1263427}