Revert "GWP-ASan: Add production flag"
This reverts commit 686ca1adcfa8c806c90395c2c101175612628ef3.

Reason for revert: This is causing build errors[1]

```
depfile=gen/android_webview/common_java__compile_j...(too long)
../../android_webview/java/src/org/chromium/android_webview/common/ProductionSupportedFlagList.java:16: error: package org.chromium.components.gwp_asan does not exist
import org.chromium.components.gwp_asan.GwpAsanFeatures;
^
../../android_webview/java/src/org/chromium/android_webview/common/ProductionSupportedFlagList.java:571: error: cannot find symbol
```

[1] https://ci.chromium.org/ui/p/chromium/builders/try/android_compile_dbg/1645739/overview

Original change's description:
> GWP-ASan: Add production flag
>
> This CL adds the production flag toggle for GWP-ASan in WebView.
>
> Bug: b/287426302
> Change-Id: Ie569538e061bfbfbc602cc465cac6ada8670e3c4
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4856191
> Reviewed-by: Keishi Hattori <keishi@chromium.org>
> Commit-Queue: Kalvin Lee <kdlee@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1196515}

Bug: b/287426302
Change-Id: Ie3d7264600b36c8e167e2e2e4aa4c61a6a5cb80a
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4867151
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Auto-Submit: Trevor Perrier <perrier@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1196746}