Typescript: Add definition files for more ui/webui/resources/.
 - Checking in .d.ts file for cr-toast-manager
 - Auto-generate .d.ts files during build time for
   cr_elements/action_link_css.m.js
   cr_elements/cr_page_host_style_css.js
   js/action_link.js

Also, switch PromiseResolver from auto-generating to checked-in, as the
auto-generated .d.ts was not sufficient, due to the fact that
PromiseResolver is defined using an assignment
"var PromiserResolver = class {...}"
which eventually resulted in the following error thrown by TSC.

"error TS2749: 'PromiseResolver' refers to a value, but is being used
as a type here. Did you mean 'typeof PromiseResolver'?"

This is in preparation of migrating Downloads to TypeScript.

Bug: 1189595
Change-Id: I529f1201af9e322963a9df48c5e61a2914f5da8b
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2909919
Auto-Submit: dpapad <dpapad@chromium.org>
Reviewed-by: Rebekah Potter <rbpotter@chromium.org>
Commit-Queue: dpapad <dpapad@chromium.org>
Cr-Commit-Position: refs/heads/master@{#886651}