Revert "Roll DevTools Frontend from 55154436a9c7 to dbe1b88bac53 (6 revisions)"
This reverts commit d04c01309dd6b8178bd59347258b5739db1d9aff.

Reason for revert: Probably caused the compilation error: https://ci.chromium.org/ui/p/chrome/builders/ci/mac64/232542/overview

Bug: chromium:40267668,chromium:407751668,chromium:415929737
Original change's description:
> Roll DevTools Frontend from 55154436a9c7 to dbe1b88bac53 (6 revisions)
>
> https://chromium.googlesource.com/devtools/devtools-frontend.git/+log/55154436a9c7..dbe1b88bac53
>
> 2025-05-26 dsv@chromium.org Introduce whitespace removal for lit templates
> 2025-05-26 yangguo@chromium.org Fix LighthousePanel unit tests
> 2025-05-26 samiyac@chromium.org Handle triggering of multiple toasts
> 2025-05-26 nvitkov@chromium.org [Changes] Use the file source if binding exists
> 2025-05-26 szuend@chromium.org [cleanup] Don't substitute variables when we have nothing to substitute
> 2025-05-26 szuend@chromium.org [formatter] Properly reject formatter tasks that failed
>
> If this roll has caused a breakage, revert this CL and stop the roller
> using the controls here:
> https://autoroll.skia.org/r/devtools-frontend-chromium
> Please CC devtools-waterfall-sheriff-onduty@rotations.google.com,liviurau@google.com on the revert to ensure that a human
> is aware of the problem.
>
> To report a problem with the AutoRoller itself, please file a bug:
> https://issues.skia.org/issues/new?component=1389291&template=1850622
>
> Documentation for the AutoRoller is here:
> https://skia.googlesource.com/buildbot/+doc/main/autoroll/README.md
>
> Bug: chromium:40267668,chromium:407751668,chromium:415929737
> Change-Id: I9d3cab7a91d45c9e28906eb2032a551641ed629a
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6587207
> Commit-Queue: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>
> Bot-Commit: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>
> Cr-Commit-Position: refs/heads/main@{#1465446}

Bug: chromium:40267668,chromium:407751668,chromium:415929737
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Change-Id: Idc11e950fdfefde29f2871e9ea606d5681c6b471
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6586691
Auto-Submit: Piotr Kotynia <piotrkotynia@google.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Cr-Commit-Position: refs/heads/main@{#1465450}