Revert "[webui] Re-Enable cr-lottie tests"
This reverts commit a0f7bda25443d1428e3b48e1bcaad48a64eab92f.

Reason for revert: Consistently failing on a bunch of Mac bots:

https://ci.chromium.org/p/chromium/builders/ci/Mac10.11%20Tests
https://ci.chromium.org/p/chromium/builders/ci/Mac10.12%20Tests
https://ci.chromium.org/p/chromium/builders/ci/Mac10.14%20Tests
https://ci.chromium.org/p/chromium/builders/ci/Mac10.15%20Tests

[18135:775:0725/170339.208790:ERROR:web_ui_browser_test.cc(537)] CONDITION FAILURE: encountered javascript console error(s):
[18135:775:0725/170339.208835:ERROR:web_ui_browser_test.cc(539)] JS ERROR: '[18135:775:0725/170337.110306:ERROR:CONSOLE(49)] "Mocha test failed: cr_lottie_test TestRenderFrame
AssertionError: expected 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCADIASwDASIAAhEBAxEB/8QAGAABAQEBAQAAAAAAAAAAAAAAAAMGBwX/xAAdEAEAAAYDAAAAAAAAAAAAAAAAAQIDBDRzBrHB/8QAGAEBAAMBAAAAAAAAAAAAAAAAAAIEBgX/xAAbEQEAAgIDAAAAAAAAAAAAAAAAAQIyMwQFgf/aAAwDAQACEQMRAD8A5+ADotlhW+uXpZGywrfXL0szNspY++UgCKIAAAAAAAAAAAAAAAAAAAAAAAAAAAAyfL82hr9i1jJ8vzaGv2K5wt0L3Xb49eAA7jSAAOi2WFb65elkbLCt9cvSzM2ylj75SAIogAAAAAAAAAAAAAAAAAAAAAAAAAAADJ8vzaGv2LWMny/Noa/YrnC3Qvddvj14ADuNIAA6LZYVvrl6WRssK31y9LMzbKWPvlIAiiAAAAAAAAAAAAAAAAAAAAAAAAAAAAMny/Noa/YtYyfL82hr9iucLdC912+PXgAO40gADotlhW+uXpZGywrfXL0szNspY++UgCKIAAAAAAAAAAAAAAAAAAAAAAAAAAAAyfL82hr9i1jJ8vzaGv2K5wt0L3Xb49eAA7jSAAOi2WFb65elkbLCt9cvSzM2ylj75SAIogAAAAAAAAAAAAAAAAAAAAAAAAAAADJ8vzaGv2LWMny/Noa/YrnC3Qvddvj14ADuNIAA6LZYVvrl6WRssK31y9LMzbKWPvlIAiiAAAAAAAAAAAAAAAAAAAAAAAAAAAAMny/Noa/YtYyfL82hr9iucLdC912+PXgAO40gADotlhW+uXpZGywrfXL0szNspY++UgCKIAAAAAAAAAAAAAAAAAAAAAAAAAAAAyfL82hr9i1jJ8vzaGv2K5wt0L3Xb49eAA7jSAAOi2WFb65elkbLCt9cvSzM2ylj75SAIogAAAAAAAAAAAAAAAAAAAAAAAAAAADJ8vzaGv2LWMny/Noa/YrnC3Qvddvj14ADuNIAA6LZYVvrl6WRssK31y9LMzbKWPvlIAiiAAAAAAAAAAAAAAAAAAAAAAAAAAAAMny/Noa/YtYyfL82hr9iucLdC912+PXgAO40gADotlhW+uXpZGywrfXL0szNspY++UgCKIAAAAAAAAAAAAAAAAAAAAAAAAAAAAyfL82hr9i1jJ8vzaGv2K5wt0L3Xb49eAA7jSAAOi2WFb65elkbLCt9cvSzM2ylj75SAIogAAAAAAAAAAAAAAAAAAAAAAAAAAADJ8vzaGv2LWMny/Noa/YrnC3Qvddvj14ADuNIAA6LZYVvrl6WRssK31y9LMzbKWPvlIAiiAAAAAAAAAAAAAAAAAAAAAAAAAAAAMny/Noa/YtYyfL82hr9iucLdC912+PXgAO40gADotlhW+uXpYGZtlLH3ykARRAAAAAAAAAAAAAAAAAAAAAAAAAAAAGT5fm0NfsQXOFuhe67fHrwAHcaR//Z' to equal 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCADIASwDASIAAhEBAxEB/8QAGAABAQEBAQAAAAAAAAAAAAAAAAMGBwX/xAAdEAEAAQMFAAAAAAAAAAAAAAAAAwE0cwIEBrHB/8QAGAEBAAMBAAAAAAAAAAAAAAAAAAIEBgX/xAAbEQEAAgIDAAAAAAAAAAAAAAAAAQIyMwQFgf/aAAwDAQACEQMRAD8A5+ADouysoMenpZHZWUGPT0szNspY++UgCKIAAAAAAAAAAAAAAAAAAAAAAAAAAAAyfL72DH7VrGT5fewY/arnC3Qvddvj14ADuNIAA6LsrKDHp6WR2VlBj09LMzbKWPvlIAiiAAAAAAAAAAAAAAAAAAAAAAAAAAAAMny+9gx+1axk+X3sGP2q5wt0L3Xb49eAA7jSAAOi7Kygx6elkdlZQY9PSzM2ylj75SAIogAAAAAAAAAAAAAAAAAAAAAAAAAAADJ8vvYMftWsZPl97Bj9qucLdC912+PXgAO40gADouysoMenpZHZWUGPT0szNspY++UgCKIAAAAAAAAAAAAAAAAAAAAAAAAAAAAyfL72DH7VrGT5fewY/arnC3Qvddvj14ADuNIAA6LsrKDHp6WR2VlBj09LMzbKWPvlIAiiAAAAAAAAAAAAAAAAAAAAAAAAAAAAMny+9gx+1axk+X3sGP2q5wt0L3Xb49eAA7jSAAOi7Kygx6elkdlZQY9PSzM2ylj75SAIogAAAAAAAAAAAAAAAAAAAAAAAAAAADJ8vvYMftWsZPl97Bj9qucLdC912+PXgAO40gADouysoMenpZHZWUGPT0szNspY++UgCKIAAAAAAAAAAAAAAAAAAAAAAAAAAAAyfL72DH7VrGT5fewY/arnC3Qvddvj14ADuNIAA6LsrKDHp6WR2VlBj09LMzbKWPvlIAiiAAAAAAAAAAAAAAAAAAAAAAAAAAAAMny+9gx+1axk+X3sGP2q5wt0L3Xb49eAA7jSAAOi7Kygx6elkdlZQY9PSzM2ylj75SAIogAAAAAAAAAAAAAAAAAAAAAAAAAAADJ8vvYMftWsZPl97Bj9qucLdC912+PXgAO40gADouysoMenpZHZWUGPT0szNspY++UgCKIAAAAAAAAAAAAAAAAAAAAAAAAAAAAyfL72DH7VrGT5fewY/arnC3Qvddvj14ADuNIAA6LsrKDHp6WR2VlBj09LMzbKWPvlIAiiAAAAAAAAAAAAAAAAAAAAAAAAAAAAMny+9gx+1axk+X3sGP2q5wt0L3Xb49eAA7jSAAOi7Kygx6elkdlZQY9PSzM2ylj75SAIogAAAAAAAAAAAAAAAAAAAAAAAAAAADJ8vvYMftWsZPl97Bj9qucLdC912+PXgAO40gADouysoMenpYGZtlLH3ykARRAAAAAAAAAAAAAAAAAAAAAAAAAAAAGT5fewY/agucLdC912+PXgAO40j//Z'
    at Function.assert.strictEqual (file:///opt/s/w/ir/third_party/chaijs/chai.js:2329:32)
    at assertEquals (file:///opt/s/w/ir/chrome/test/data/webui/test_api.js:726:15)
    at Context.<anonymous> (file:///opt/s/w/ir/chrome/test/data/webui/cr_elements/cr_lottie_tests.js:240:5)
", source: file:///opt/s/w/ir/chrome/test/data/webui/mocha_adapter.js (49)
'


Original change's description:
> [webui] Re-Enable cr-lottie tests
> 
> It's not clear if these tests will still be flaky on the CI or not. We
> made some changes that may have deflaked them.
> 
> Bug: 1103865, 1021474
> Change-Id: Icfe7ed6637868fc29e30c0d182f985a6b38aa000
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2311144
> Commit-Queue: Nina Satragno <nsatragno@chromium.org>
> Auto-Submit: Nina Satragno <nsatragno@chromium.org>
> Reviewed-by: dpapad <dpapad@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#791463}

TBR=dpapad@chromium.org,nsatragno@chromium.org

Change-Id: Idd9cfd301804197c09552f3cbc9ee75fb4c44e27
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 1103865
Bug: 1021474
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2319306
Reviewed-by: Avi Drissman <avi@chromium.org>
Commit-Queue: Avi Drissman <avi@chromium.org>
Cr-Commit-Position: refs/heads/master@{#791579}