Revert "Roll DevTools Frontend from 6b88848136d0 to 55154436a9c7 (4 revisions)"
This reverts commit a09e7f91aa975e3a876f409a716ac6c7f15c64f1.

Reason for revert: Probably caused the compilation error: https://ci.chromium.org/ui/p/chrome/builders/ci/mac64/232542/overview

Bug: chromium:358327120,chromium:40189975,chromium:407751856
Original change's description:
> Roll DevTools Frontend from 6b88848136d0 to 55154436a9c7 (4 revisions)
>
> https://chromium.googlesource.com/devtools/devtools-frontend.git/+log/6b88848136d0..55154436a9c7
>
> 2025-05-26 kimanh@chromium.org Re-enable breakpoint-javascript_test.ts test
> 2025-05-26 changhaohan@chromium.org Update (direct)?socket) l10n to be backticked
> 2025-05-26 alexrudenko@chromium.org Fix flaky memory test
> 2025-05-26 kimanh@chromium.org Prepare RequestResponseView for ui eng migration
>
> If this roll has caused a breakage, revert this CL and stop the roller
> using the controls here:
> https://autoroll.skia.org/r/devtools-frontend-chromium
> Please CC devtools-waterfall-sheriff-onduty@rotations.google.com,liviurau@google.com on the revert to ensure that a human
> is aware of the problem.
>
> To report a problem with the AutoRoller itself, please file a bug:
> https://issues.skia.org/issues/new?component=1389291&template=1850622
>
> Documentation for the AutoRoller is here:
> https://skia.googlesource.com/buildbot/+doc/main/autoroll/README.md
>
> Bug: chromium:358327120,chromium:40189975,chromium:407751856
> Change-Id: I94f5cdc3e45549385b1db219b757acd9ce6cfd7a
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6585132
> Commit-Queue: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>
> Bot-Commit: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>
> Cr-Commit-Position: refs/heads/main@{#1465427}

Bug: chromium:358327120,chromium:40189975,chromium:407751856
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Change-Id: I588e67a1d3d7316e4e3790d227bb1dbaf870a853
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6587047
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Auto-Submit: Piotr Kotynia <piotrkotynia@google.com>
Owners-Override: Piotr Kotynia <piotrkotynia@google.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Cr-Commit-Position: refs/heads/main@{#1465453}