registration_error: Process new connect failures from shill
If modem is not able to register to the network and if
modem manager could classify it into specific category
of failure, shill will return the specific error code
and these are the changes to map them to the new strings
instead of showing generic modems not registered messages.
(Strings will be replaced with actual strings after string review)

Bug=b:324323448
Test=Tested on Rusty and Lazor for MBIM and QMI coverage

Change-Id: Ia8b0819ac4431dddb086a9cc9fe1d57830128619
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5585192
Reviewed-by: Kyle Horimoto <khorimoto@chromium.org>
Reviewed-by: Gordon Seto <gordonseto@google.com>
Commit-Queue: Ujjwal Pande <ujjwalpande@google.com>
Cr-Commit-Position: refs/heads/main@{#1319943}