Revert "Pass -Zsanitizer=address to rust compile steps under ASAN."
This reverts commit 82c56fb51c699a47cc957b85e9a077b964907a94.

Reason for revert: Breaks compile on win-asan CI bot :(

See https://ci.chromium.org/ui/p/chromium/builders/ci/win-asan/32504

Error:
[17458/82104] RUST(BIN) cloud_authenticator_test_service.exe cloud_authenticator_test_service.exe.pdb
C:/b/s/w/ir/cipd_bin_packages/cpython3/bin/python3.exe ../../build/rust/rustc_wrapper.py --target-wi...(too long)
error: linking with `..\..\third_party\llvm-build\Release+Asserts\bin\lld-link.exe` failed: exit code: 1
  |
  = note: "..\\..\\third_party\\llvm-build\\Release+Asserts\\bin\\lld-link.exe" "-flavor" "link" "/N...(too long)
  = note: lld-link: ␛[0;31merror: ␛[0mcould not open 'C:\b\s\w\ir\cache\builder\src\third_party\rust-toolchain\lib\rustlib\x86_64-pc-windows-msvc\lib\librustc-dev_rt.asan.a': no such file or directory␍
          

error: aborting due to 1 previous error

exit=1

Original change's description:
> Pass -Zsanitizer=address to rust compile steps under ASAN.
>
> The `asan_flags` GN config adds ASAN to the compiler flags, but was
> forgetting to add -Zsanitizer to the rustflags, which meant that we
> failed to enable ASAN in Rust-compiled code on Windows. On other
> platforms the `default_sanitizer_ldflags` config seems to have been
> doing the job already.
>
> This enables ASAN integration in Rust but is not enough to catch
> UAF if the allocation was performed in Rust, on Windows. This is because
> Rust stdlib allocates through HeapAlloc() and ASAN on Windows does not
> hook and replace HeapAlloc(). And notably PartitionAlloc is _not_ used
> when ASAN is enabled, so our Rust allocator shims simply redirect back
> to the stdlib implementation.
>
> There is a runtime flag `ASAN_OPTIONS = 'windows_hook_rtl_allocators=1'`
> which makes ASAN hook the Win32 heap functions, however it appears to
> break CreateProcess which was quickly observed during compilation when
> protoc stopped working. So this CL does not enable this runtime flag
> by default yet in //build/sanitizers/sanitizer_options.cc.
>
>
> R=hans@chromium.org
>
> Bug: 368070343
> Change-Id: Ib1abe4579f7e40f52ad60bf837c0a7f8014cc574
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5908232
> Reviewed-by: Hans Wennborg <hans@chromium.org>
> Commit-Queue: danakj <danakj@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1364185}

Bug: 368070343
Change-Id: I941b4b207db954c5125c8087b59e184fdc033df7
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5908094
Auto-Submit: Ian Clelland <iclelland@chromium.org>
Commit-Queue: Ian Clelland <iclelland@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Owners-Override: Ian Clelland <iclelland@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1364240}