Revert "[ios] Disables TabGridTestCase.testTabGridBulkActionShare on device."
This reverts commit 304823aaf051c66ceedc837eff8e7ae0bc36fa7f.

Reason for revert: suspect compile failure on ios-device.

First build failure: https://ci.chromium.org/ui/p/chromium/builders/ci/ios-device/195558/overview

Sample Log: https://logs.chromium.org/logs/chromium/buildbucket/cr-buildbucket.appspot.com/8839233674417163504/+/u/compile/stdout?format=raw
---
[1220/1703] OBJCXX obj/ios/chrome/browser/ui/tab_switcher/tab_grid/eg2_tests/tab_grid_egtest.o
FAILED: obj/ios/chrome/browser/ui/tab_switcher/tab_grid/eg2_tests/tab_grid_egtest.o
/opt/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -...(too long)
../../ios/chrome/browser/ui/tab_switcher/tab_grid/tab_grid_egtest.mm:123:28: error: undeclared selector 'testTabGridBulkActionShare' [-Werror,-Wundeclared-selector]
[self isRunningTest:@selector(testTabGridBulkActionShare)]) {
^
1 error generated.
----

Original change's description:
> [ios] Disables TabGridTestCase.testTabGridBulkActionShare on device.
>
> BUG=1238501
>
> Change-Id: I2f0dbd330b48d62a66838acdc5bde8e54675eb78
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3088473
> Auto-Submit: Rohit Rao <rohitrao@chromium.org>
> Commit-Queue: Justin Cohen <justincohen@chromium.org>
> Reviewed-by: Justin Cohen <justincohen@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#910626}

Bug: 1238501
Change-Id: I5626e1f809d185f2203f51b05292466f9605f598
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3086887
Auto-Submit: Takashi Sakamoto <tasak@google.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Kentaro Hara <haraken@chromium.org>
Reviewed-by: Noel Gordon <noel@chromium.org>
Reviewed-by: Kentaro Hara <haraken@chromium.org>
Owners-Override: Kentaro Hara <haraken@chromium.org>
Cr-Commit-Position: refs/heads/master@{#910628}