Revert "[iOS][Waffle] Create three primary button UIs"
This reverts commit 7ce0b2bd42365bc636bb857bdef372189c95f5eb.

Reason for revert: compilation error on https://ci.chromium.org/ui/p/chromium/builders/ci/ios-asan/64580/overview :
ios/chrome/browser/ui/search_engine_choice/search_engine_choice_ui_util.mm:197:23: error: property 'titleLineBreakMode' not found on object of type 'UIButtonConfiguration *'
197 |   buttonConfiguration.titleLineBreakMode = NSLineBreakByTruncatingTail;

Original change's description:
> [iOS][Waffle] Create three primary button UIs
>
> The three UIs correspond to the three possible states:
> - The user needs to scroll to the bottom of the list
> - The user needs to select a row
> - The user has viewed the entire list and made a selection.
>
> We also move the view controller helper methods to a separate class.
>
> Bug: b/312913025
> Change-Id: I926bc323b980f9937ecc53cff00855dea76c57f5
> Fixed: b/312917516, b/312915469
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5070484
> Code-Coverage: findit-for-me@appspot.gserviceaccount.com <findit-for-me@appspot.gserviceaccount.com>
> Reviewed-by: Nicolas Dossou-Gbété <dgn@chromium.org>
> Reviewed-by: Jérôme Lebel <jlebel@chromium.org>
> Commit-Queue: Samar Chehade-Lepleux <samarchehade@google.com>
> Cr-Commit-Position: refs/heads/main@{#1230656}

Bug: b/312913025
Change-Id: Ief40e6800b2661f3e02962226e055c2a3242fc45
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5071133
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Auto-Submit: David Baron <dbaron@chromium.org>
Owners-Override: David Baron <dbaron@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1230672}