Revert "[Power Bookmarks] Add a compact version of the new bookmark row"
This reverts commit 8b96a67380bba0dac354d75b5afc542c589084e1.

Reason for revert: [Sheriff] Appears to break compile on android-marshmallow-x86-rel:

https://ci.chromium.org/p/chromium/builders/ci/android-marshmallow-x86-rel/13415?

[16143/34739] CXX obj/chrome/browser/browser/about_flags.o
FAILED: obj/chrome/browser/browser/about_flags.o
../../buildtools/reclient/rewrapper -cfg=../../buildtools/reclient_cfgs/chromium-browser-clang/rewra...(too long)
../../chrome/browser/about_flags.cc:2646:12: error: no member named 'size' in namespace 'base'
base::size(kBookmarksRefreshNormal), nullptr},
~~~~~~^
../../chrome/browser/about_flags.cc:2648:12: error: no member named 'size' in namespace 'base'
base::size(kBookmarksRefreshCompact), nullptr},
~~~~~~^
../../chrome/browser/about_flags.cc:2650:12: error: no member named 'size' in namespace 'base'
base::size(kBookmarksRefreshVisuals), nullptr},
~~~~~~^


Original change's description:
> [Power Bookmarks] Add a compact version of the new bookmark row
>
> Bug: 1300925
> Change-Id: I185b0ac99ba57b6379a492f94fe69dd51175501a
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3491145
> Reviewed-by: Matthew Jones <mdjones@chromium.org>
> Reviewed-by: Filip Gorski <fgorski@chromium.org>
> Commit-Queue: Brandon Wylie <wylieb@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#975989}

Bug: 1300925
Change-Id: I7ac333442d16f695a9d75c13875900519a94d774
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3496323
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Alex Moshchuk <alexmos@chromium.org>
Owners-Override: Alex Moshchuk <alexmos@chromium.org>
Cr-Commit-Position: refs/heads/main@{#975998}