Revert of Mark org.chromium.chrome.browser.payments.PaymentRequestIncompleteContactDetailsTest#testEditIncomp… (patchset #1 id:1 of https://codereview.chromium.org/2566173002/ )
Reason for revert:
The tree is closed:
../../chrome/android/javatests/src/org/chromium/chrome/browser/payments/PaymentRequestIncompleteContactDetailsTest.java:47: error: cannot find symbol
    @FlakyTest
     ^
  symbol:   class FlakyTest
  location: class PaymentRequestIncompleteContactDetailsTest
Note: Some input files additionally use or override a deprecated API.

Original issue's description:
> Mark org.chromium.chrome.browser.payments.PaymentRequestIncompleteContactDetailsTest#testEditIncompleteContactAndCancel as flaky
>
> BUG=673299
> TBR=grt@chromium.org
>
> Committed: https://chromium.googlesource.com/chromium/src/+/257f431c44c930193c082bf608c18282a063785e

TBR=grt@chromium.org,vasilii@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=673299

Review-Url: https://codereview.chromium.org/2574433002
Cr-Commit-Position: refs/heads/master@{#437883}