IWYU: missing <memory> include in payments android app description for std::unique_ptr
This fixes this build error:
./../components/payments/core/android_app_description.h:51:20: error: ‘unique_ptr’ is not a member of ‘std’
   51 |   std::vector<std::unique_ptr<AndroidActivityDescription>> activities;
      |                    ^~~~~~~~~~

Bug: 957519
Change-Id: I63cd3c3caa743c5b8a8ec0d91706d8655a1bbea6
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2360080
Reviewed-by: Sahel Sharify <sahel@chromium.org>
Commit-Queue: José Dapena Paz <jdapena@igalia.com>
Cr-Commit-Position: refs/heads/master@{#798673}