Revert of Add support for compressed GPU memory buffers. (patchset #7 id:120001 of https://codereview.chromium.org/916083002/)
Reason for revert:
Breaks ChromiumOS ozone compile: http://build.chromium.org/p/chromium.chromiumos/builders/Linux%20ChromiumOS%20Ozone%20Builder/builds/12286/steps/compile/logs/stdio

../../ui/ozone/gpu/gpu_memory_buffer_factory_ozone_native_buffer.cc:78:11: error: 5 enumeration values not handled in switch: 'ATC', 'ATCIA', 'DXT1'... [-Werror,-Wswitch]

Original issue's description:
> Add support for compressed GPU memory buffers.
>
> This CL adds support for compressed GPU buffer formats.
>
> BUG=434699
>
> Committed: https://crrev.com/3113db1250a2687c030585f6045f2ef242b98db6
> Cr-Commit-Position: refs/heads/master@{#317765}

TBR=reveman@chromium.org,jbauman@chromium.org,piman@chromium.org,christiank@opera.com
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=434699

Review URL: https://codereview.chromium.org/948323002

Cr-Commit-Position: refs/heads/master@{#317769}