Revert "[Offline indicator v2] Add Java animations"
This reverts commit b5018edfc1246f1486d7ddc4d9537a4ef11175e6.

Reason for revert: StatusBarColorControllerTest#testColorWithStatusIndicator() 
fails on Android L

Builder: Lollipop Phone Tester
https://ci.chromium.org/p/chromium/builders/ci/Lollipop%20Phone%20Tester
First failing build:
https://ci.chromium.org/p/chromium/builders/ci/Lollipop%20Phone%20Tester/24496

java.lang.AssertionError: Wrong status bar color for Android L. expected:<-16777063> but was:<-16777216>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.chromium.chrome.browser.ui.system.StatusBarColorControllerTest.testColorWithStatusIndicator(StatusBarColorControllerTest.java:149)

Original change's description:
> [Offline indicator v2] Add Java animations
> 
> This CL implements the color and text transition animations that run when
> showing or hiding the status indicator.
> 
> Show:
> 1- Transition the status bar color.
> 2- Wait for the browser controls animation in cc to finish.
> 3- Fade in text.
> 
> Hide:
> 1- Transition the status bar and the indicator color.
> 2- Wait 2 seconds.
> 3- Fade out text, and transition the status bar and indicator color back
> to the original status bar color.
> 4- Let the browser controls hide animation run in cc.
> 
> Bug: 989148
> Change-Id: If19a51e6c5091436d78e34ef50f11ffa0118ee0d
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2067095
> Commit-Queue: Sinan Sahin <sinansahin@google.com>
> Reviewed-by: Matthew Jones <mdjones@chromium.org>
> Reviewed-by: Theresa  <twellington@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#747080}

TBR=twellington@chromium.org,mdjones@chromium.org,sinansahin@google.com

Change-Id: If1a31818ad5cb887cf44399a8baaaeb56c619d1f
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 989148
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2089751
Reviewed-by: Alex Ilin <alexilin@chromium.org>
Commit-Queue: Alex Ilin <alexilin@chromium.org>
Cr-Commit-Position: refs/heads/master@{#747230}