Remove out/.../enhanced_network_tts/ from gn data
mb.py enforces that BUILD.gn "data" sections should not point to
subdirectories of the output directory [1].

This BUILD.gn file contains one such reference, which blocks the use of
mb.py when building browser_tests for ChromeOS [2]. Specifically, mb.py
shows the following error [3]:

    error: gn `data` items may not list generated directories; list files in directory instead for:
    //out/bug/resources/chromeos/accessibility/enhanced_network_tts/

The recommended fix is to either list specific files that are needed
(rather than an entire directory), or to simply remove the dependency if
no longer needed.

In this case, files in the directory seems to be depended on by
enhanced_network_tts_e2e_test_base.js, so this change makes BUILD.gn
refer to the specific files rather than the overall directory.

[1] https://source.chromium.org/chromium/chromium/src/+/main:tools/mb/mb.py;l=1577?q=tools%2Fmb%2Fmb.py%20-file:third_party%2F%20-file:gen%2F%20-file:go%2F%20-file:v8%2F%20-file:buildtools%20-file:%5C.js%20-file:native_client%20-file:ppapi%20-file:%5C.html%20-file:%5C.java%20-file:.mojo
[2] GN arguments used when the issue was encountered:

    is_chrome_branded = false
    is_component_build = true
    is_debug = true
    symbol_level = 2
    use_full_pdb_paths = true
    use_goma = true
    enable_nacl = false
    blink_symbol_level = 0
    v8_symbol_level = 0
    is_official_build = false
    target_os = "chromeos"
[3] full output:
     jessemckenna@jessemckenna-linux:~/chromium/src$ tools/run-swarmed.py out/bug browser_tests --swarming-os Ubuntu-18.04 -- --gtest_filter=*BreadcrumbManagerTabHelperBrowserTest.Download*
    error: gn `data` items may not list generated directories; list files in directory instead for:
    //out/bug/resources/chromeos/accessibility/enhanced_network_tts/
    Traceback (most recent call last):
    File "/usr/local/google/home/jessemckenna/chromium/src/tools/run-swarmed.py", line 354, in <module>
        sys.exit(main())
    File "/usr/local/google/home/jessemckenna/chromium/src/tools/run-swarmed.py", line 288, in main
        subprocess.check_call(mb_cmd, shell=os.name == 'nt')
    File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['tools/mb/mb', 'isolate', '--no-build', '//out/bug', 'browser_tests']' returned non-zero exit status 1.

Bug: 1002509, 1344663
Change-Id: I6c6e6256aa966fbe3d6b2065912aa3a06f5648fd
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4234488
Commit-Queue: Jesse McKenna <jessemckenna@google.com>
Reviewed-by: Akihiro Ota <akihiroota@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1103906}