Revert "assistant: Remove IsScreenContextQueryEnabled"
This reverts commit de6ebaa242f8d3746c25e2e0cb0fb094eec00120.

Reason for revert: causes compile failure on linux-chromeos-chrome

Sample build: https://ci.chromium.org/p/chrome/builders/ci/linux-chromeos-chrome/3372

Sample log: https://logs.chromium.org/logs/chrome/buildbucket/cr-buildbucket.appspot.com/8887878986181186864/+/steps/compile/0/stdout?format=raw
---
[34344/60074] CXX obj/chromeos/services/assistant/lib/assistant_manager_service_impl.o
FAILED: obj/chromeos/services/assistant/lib/assistant_manager_service_impl.o
/b/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF...(too long)
../../chromeos/services/assistant/assistant_manager_service_impl.cc:101:16: error: unused variable 'kScreenContextQuery' [-Werror,-Wunused-const-variable]
constexpr char kScreenContextQuery[] = "screen context";
^
1 error generated.
---

Original change's description:
> assistant: Remove IsScreenContextQueryEnabled
> 
> Remove unused code.
> 
> Bug: b/145218971
> Test: manual
> Change-Id: I54e08fc38e967517212b2f41fabe6bb872d17cf3
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2067938
> Commit-Queue: Tao Wu <wutao@chromium.org>
> Reviewed-by: Xiaohui Chen <xiaohuic@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#743408}

TBR=xiaohuic@chromium.org,wutao@chromium.org

Change-Id: I565b31eb10ecaf53d9adae452320de420b7f00db
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: b/145218971
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2067761
Reviewed-by: Takashi Sakamoto <tasak@google.com>
Commit-Queue: Takashi Sakamoto <tasak@google.com>
Cr-Commit-Position: refs/heads/master@{#743425}