IWYU: Add missing include for scoped_refptr<StaticBitmapImage> in webgl_rendering_context_webgpu_base.cc
In the CL https://crrev.com/c/6563818 was added
webgl_rendering_context_webgpu_base.cc with usage of
scoped_refptr<StaticBitmapImage> without include of static_bitmap_image.h. It
caused an error when compiling with GCC:
../../third_party/blink/renderer/modules/webgl/webgl_rendering_context_webgpu_base.cc:2407:10:   required from here
../../base/memory/scoped_refptr.h:410:8: error: invalid use of incomplete type ‘class blink::StaticBitmapImage’
  410 |   ptr->Release();
      |   ~~~~~^~~~~~~

Added missing include to fix the issue.

Bug: 41455655
Change-Id: Ie8413b605a31573a46f646680b6706ed645d1159
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6875297
Reviewed-by: Philip Rogers <pdr@chromium.org>
Commit-Queue: Philip Rogers <pdr@chromium.org>
Reviewed-by: Brandon Jones <bajones@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1505323}