Revert of Make media/capture gn and gyps produce components (patchset #7 id:580001 of https://codereview.chromium.org/2031073002/ )
Reason for revert:
Broke (at least)
https://build.chromium.org/p/chromium.webkit/builders/WebKit%20Mac%20Builder%20%28dbg%29/builds/157095/steps/compile/logs/stdio/text:

FAILED: libmedia.dylib libmedia.dylib.TOC
if [ ! -e "./libmedia.dylib" -o ! -e "./libmedia.dylib.TOC" ] || otool -l "./libmedia.dylib" | grep -q LC_REEXPORT_DYLIB ; then ../../build/toolchain/mac/linker_driver.py /b/build/slave/cache/cipd/goma/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -shared  -Wl,-install_name,@rpath/"libmedia.dylib" -stdlib=libc++ -arch x86_64 -isysroot /Applications/Xcode7.0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.7 -Wl,-rpath,@loader_path/. -Wl,-rpath,@loader_path/../../.. -o "./libmedia.dylib" -Wl,-filelist,"./libmedia.dylib.rsp" -framework CoreVideo -framework AVFoundation -framework AudioToolbox -framework AudioUnit -framework CoreAudio ./libshared_memory_support.dylib ./libffmpeg.dylib ./libbase.dylib ./libbase_i18n.dylib ./libcrcrypto.dylib ./libskia.dylib ./libevents_base.dylib ./libgfx.dylib ./libgeometry.dylib ./libgl_wrapper.dylib ./liburl.dylib ./libgpu.dylib ./libgles2_utils.dylib ./libicui18n.dylib ./libicuuc.dylib ./librange.dylib ./libui_base.dylib ./libplatform.dylib ./libgl_init.dylib ./libipc.dylib ./libboringssl.dylib && { otool -l "./libmedia.dylib" | grep LC_ID_DYLIB -A 5; nm -gP "./libmedia.dylib" | cut -f1-2 -d' ' | grep -v U$$; true; } > "./libmedia.dylib.TOC"; else ../../build/toolchain/mac/linker_driver.py /b/build/slave/cache/cipd/goma/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -shared  -Wl,-install_name,@rpath/"libmedia.dylib" -stdlib=libc++ -arch x86_64 -isysroot /Applications/Xcode7.0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.7 -Wl,-rpath,@loader_path/. -Wl,-rpath,@loader_path/../../.. -o "./libmedia.dylib" -Wl,-filelist,"./libmedia.dylib.rsp" -framework CoreVideo -framework AVFoundation -framework AudioToolbox -framework AudioUnit -framework CoreAudio ./libshared_memory_support.dylib ./libffmpeg.dylib ./libbase.dylib ./libbase_i18n.dylib ./libcrcrypto.dylib ./libskia.dylib ./libevents_base.dylib ./libgfx.dylib ./libgeometry.dylib ./libgl_wrapper.dylib ./liburl.dylib ./libgpu.dylib ./libgles2_utils.dylib ./libicui18n.dylib ./libicuuc.dylib ./librange.dylib ./libui_base.dylib ./libplatform.dylib ./libgl_init.dylib ./libipc.dylib ./libboringssl.dylib && { otool -l "./libmedia.dylib" | grep LC_ID_DYLIB -A 5; nm -gP "./libmedia.dylib" | cut -f1-2 -d' ' | grep -v U$$; true; } > "./libmedia.dylib.tmp" && if ! cmp -s "./libmedia.dylib.tmp" "./libmedia.dylib.TOC"; then mv "./libmedia.dylib.tmp" "./libmedia.dylib.TOC" ; fi; fi
Undefined symbols for architecture x86_64:
  "_CFArrayCreate", referenced from:
      media::video_toolbox::ArrayWithIntegers(int const*, unsigned long) in videotoolbox_helpers.o
      media::video_toolbox::ArrayWithIntegerAndFloat(int, float) in videotoolbox_helpers.o
  "_CFDictionaryCreate", referenced from:
      media::video_toolbox::DictionaryWithKeysAndValues(void const**, void const**, unsigned long) in videotoolbox_helpers.o
  "_CFGetTypeID", referenced from:
      media::VideoFrame::WrapCVPixelBuffer(__CVBuffer*, base::TimeDelta) in video_frame.o
  "_CFNumberCreate", referenced from:
      media::video_toolbox::ArrayWithIntegers(int const*, unsigned long) in videotoolbox_helpers.o
      media::video_toolbox::ArrayWithIntegerAndFloat(int, float) in videotoolbox_helpers.o
      media::video_toolbox::SessionPropertySetter::Set(__CFString const*, int) in videotoolbox_helpers.o
  "_CFRelease", referenced from:
      base::internal::ScopedCFTypeRefTraits<__CVBuffer*>::Release(__CVBuffer*) in video_frame_mac.o
      media::video_toolbox::ArrayWithIntegers(int const*, unsigned long) in videotoolbox_helpers.o
      media::video_toolbox::ArrayWithIntegerAndFloat(int, float) in videotoolbox_helpers.o
      base::internal::ScopedCFTypeRefTraits<__CFArray const*>::Release(__CFArray const*) in videotoolbox_helpers.o
      base::internal::ScopedCFTypeRefTraits<OpaqueCMBlockBuffer*>::Release(OpaqueCMBlockBuffer*) in videotoolbox_helpers.o
      base::internal::ScopedCFTypeRefTraits<OpaqueVTCompressionSession*>::Release(OpaqueVTCompressionSession*) in videotoolbox_helpers.o
      base::internal::ScopedCFTypeRefTraits<__CFNumber const*>::Release(__CFNumber const*) in videotoolbox_helpers.o
      ...
  "_CFRetain", referenced from:
      base::internal::ScopedCFTypeRefTraits<__CVBuffer*>::Retain(__CVBuffer*) in video_frame_mac.o
      base::internal::ScopedCFTypeRefTraits<__CFDictionary const*>::Retain(__CFDictionary const*) in videotoolbox_helpers.o
      base::internal::ScopedCFTypeRefTraits<__CFArray const*>::Retain(__CFArray const*) in videotoolbox_helpers.o
      base::internal::ScopedCFTypeRefTraits<OpaqueCMBlockBuffer*>::Retain(OpaqueCMBlockBuffer*) in videotoolbox_helpers.o
      base::internal::ScopedCFTypeRefTraits<OpaqueVTCompressionSession*>::Retain(OpaqueVTCompressionSession*) in videotoolbox_helpers.o
      base::internal::ScopedCFTypeRefTraits<__CFNumber const*>::Retain(__CFNumber const*) in videotoolbox_helpers.o
      base::internal::ScopedCFTypeRefTraits<__CFString const*>::Retain(__CFString const*) in audio_manager_mac.o
      ...
  "_CGEventSourceCounterForEventType", referenced from:
      media::(anonymous namespace)::UserInputMonitorMac::GetKeyPressCount() const in user_input_monitor_mac.o
  "_OBJC_CLASS_$_NSBundle", referenced from:
      objc-class-ref in coremedia_glue.o
      objc-class-ref in videotoolbox_glue.o
      objc-class-ref in avfoundation_glue.o
  "_OBJC_CLASS_$_NSObject", referenced from:
      _OBJC_CLASS_$_AVCaptureDeviceGlue in avfoundation_glue.o
      _OBJC_CLASS_$_AVCaptureDeviceInputGlue in avfoundation_glue.o
  "_OBJC_CLASS_$_NSThread", referenced from:
      objc-class-ref in avfoundation_glue.o
  "_OBJC_METACLASS_$_NSObject", referenced from:
      _OBJC_METACLASS_$_AVCaptureDeviceGlue in avfoundation_glue.o
      _OBJC_METACLASS_$_AVCaptureDeviceInputGlue in avfoundation_glue.o
  "___CFConstantStringClassReference", referenced from:
      CFString in coremedia_glue.o
      CFString in videotoolbox_glue.o
      CFString in avfoundation_glue.o
      CFString in avfoundation_glue.o
      CFString in avfoundation_glue.o
      CFString in avfoundation_glue.o
      CFString in avfoundation_glue.o
      ...
  "__objc_empty_cache", referenced from:
      _OBJC_METACLASS_$_AVCaptureDeviceGlue in avfoundation_glue.o
      _OBJC_CLASS_$_AVCaptureDeviceGlue in avfoundation_glue.o
      _OBJC_METACLASS_$_AVCaptureDeviceInputGlue in avfoundation_glue.o
      _OBJC_CLASS_$_AVCaptureDeviceInputGlue in avfoundation_glue.o
  "__objc_empty_vtable", referenced from:
      _OBJC_METACLASS_$_AVCaptureDeviceGlue in avfoundation_glue.o
      _OBJC_CLASS_$_AVCaptureDeviceGlue in avfoundation_glue.o
      _OBJC_METACLASS_$_AVCaptureDeviceInputGlue in avfoundation_glue.o
      _OBJC_CLASS_$_AVCaptureDeviceInputGlue in avfoundation_glue.o
  "_kCFAllocatorDefault", referenced from:
      media::WrapVideoFrameInCVPixelBuffer(media::VideoFrame const&) in video_frame_mac.o
      media::video_toolbox::DictionaryWithKeysAndValues(void const**, void const**, unsigned long) in videotoolbox_helpers.o
      media::video_toolbox::ArrayWithIntegers(int const*, unsigned long) in videotoolbox_helpers.o
      media::video_toolbox::ArrayWithIntegerAndFloat(int, float) in videotoolbox_helpers.o
      media::video_toolbox::CopySampleBufferToAnnexBBuffer(OpaqueCMSampleBuffer*, media::video_toolbox::AnnexBBuffer*, bool) in videotoolbox_helpers.o
  "_kCFBooleanFalse", referenced from:
      media::video_toolbox::SessionPropertySetter::Set(__CFString const*, bool) in videotoolbox_helpers.o
  "_kCFBooleanTrue", referenced from:
      media::video_toolbox::SessionPropertySetter::Set(__CFString const*, bool) in videotoolbox_helpers.o
  "_kCFRunLoopCommonModes", referenced from:
      media::PCMQueueInAudioInputStream::Open() in audio_input_mac.o
  "_kCFTypeArrayCallBacks", referenced from:
      media::video_toolbox::ArrayWithIntegers(int const*, unsigned long) in videotoolbox_helpers.o
      media::video_toolbox::ArrayWithIntegerAndFloat(int, float) in videotoolbox_helpers.o
  "_kCFTypeDictionaryKeyCallBacks", referenced from:
      media::video_toolbox::DictionaryWithKeysAndValues(void const**, void const**, unsigned long) in videotoolbox_helpers.o
  "_kCFTypeDictionaryValueCallBacks", referenced from:
      media::video_toolbox::DictionaryWithKeysAndValues(void const**, void const**, unsigned long) in videotoolbox_helpers.o
  "_objc_msgSend", referenced from:
      (anonymous namespace)::CoreMediaLibraryInternal::CoreMediaLibraryInternal() in coremedia_glue.o
      VideoToolboxGlue::Loader::Loader() in videotoolbox_glue.o
      AVFoundationGlue::InitializeAVFoundation() in avfoundation_glue.o
      (anonymous namespace)::LoadAVFoundationInternal() in avfoundation_glue.o
      AVFoundationGlue::AVCaptureSessionClass() in avfoundation_glue.o
      AVFoundationGlue::AVCaptureVideoDataOutputClass() in avfoundation_glue.o
      +[AVCaptureDeviceGlue devices] in avfoundation_glue.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Traceback (most recent call last):
  File "../../build/toolchain/mac/linker_driver.py", line 186, in <module>
    Main(sys.argv)
  File "../../build/toolchain/mac/linker_driver.py", line 68, in Main
    subprocess.check_call(compiler_driver_args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)

Original issue's description:
> Make media/capture gn and gyps produce components
> This CL separates media/capture into a component,
> to allow, in a subsequent CL, linking with mojo for using
> ImageCapture types.
>
> This basically reproduces the media/cast and media/midi
> structure.
>
> Windows import/export issues made necessary to add
> capture_export and associated CAPTURE_EXPORT macro,
> again, replicating media/midi.
>
> gn gen ... --check uncovered some transitive dependencies
> during the "analyze" phase of the bots and I had to make
> them explicit (e.g. media:gpu).
>
> BUG=518807
>
> Committed: https://crrev.com/f4683c359791bb0264cddddeca6b8bcae0e61817
> Cr-Commit-Position: refs/heads/master@{#399024}

TBR=xhwang@chromium.org,miu@chromium.org,avi@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=518807

Review-Url: https://codereview.chromium.org/2059493002
Cr-Commit-Position: refs/heads/master@{#399028}