mac arm64: add support for this new configuration to zlib
While compiling third_party/zlib/cpu_features.c, for example during
https://ci.chromium.org/p/chromium/builders/ci/mac-arm64/661:

../../third_party/zlib/cpu_features.c:83:13: error: unused function '_cpu_check_features' [-Werror,-Wunused-function]
static void _cpu_check_features(void)
            ^

macOS support for arm64 is expected to have a high baseline requirement
for extensions such as crc32, so rather than doing runtime feature
detection, assume presence. crc32 is mandatory in ARMv8.1-A per ARM DDI
0487F.b (current), and all Apple ARM A-series CPUs since A10 (2016)
implement at least ARMv8.1-A.

Bug: 1099892
Change-Id: I9d7a113b5c88f9779f95baf4ef0724aa4158c721
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2271018
Auto-Submit: Mark Mentovai <mark@chromium.org>
Commit-Queue: Adenilson Cavalcanti <cavalcantii@chromium.org>
Reviewed-by: Adenilson Cavalcanti <cavalcantii@chromium.org>
Cr-Commit-Position: refs/heads/master@{#783353}