Fix TwoClientWebAppsSyncTest.SyncFaviconOnly flakes
TwoClientWebAppsSyncTest.SyncFaviconOnly is flaking with
../../chrome/browser/sync/test/integration/sync_test.cc(895): error: Expected equality of these values:
  chrome::GetTotalBrowserCount()
    Which is: 3
  init_browser_count - browsers_.size()
    Which is: 2

This test needs to clean up the browser window that it opened to
satisfy the ASSERT.

Bug: 1097100
Change-Id: I84bb61211470560ba939f22abb4f43481534d514
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2269983
Commit-Queue: Alan Cutter <alancutter@chromium.org>
Commit-Queue: Alexey Baskakov <loyso@chromium.org>
Auto-Submit: Alan Cutter <alancutter@chromium.org>
Reviewed-by: Alexey Baskakov <loyso@chromium.org>
Cr-Commit-Position: refs/heads/master@{#783425}