Revert "Reland "Remove Deprecated ScopedBstr to BSTR Implicit Conversion Operator""
This reverts commit abb98639e3dfad39c33770f299d37cd6d4f04f94.

Reason for revert: Breaks on Chrome Branded Builds
https://ci.chromium.org/p/chrome/builders/ci/win64-builder-perf/155240

[5963/14947] CXX obj/chrome/browser/browser/browser_dm_token_storage_win.obj
FAILED: obj/chrome/browser/browser/browser_dm_token_storage_win.obj
c:\b\s\w\ir\cache\goma\client\gomacc.exe ..\..\third_party\llvm-build\Release+Asserts\bin\clang-cl.e...(too long)
../../chrome/browser/policy/browser_dm_token_storage_win.cc(89,39): error: no viable conversion from 'base::win::ScopedBstr' to 'BSTR' (aka 'wchar_t *')
hr = app_bundle->createInstalledApp(base::win::ScopedBstr(app_guid));
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gen\google_update/google_update_idl.h(3500,29): note: passing argument to parameter 'app_id' here
/* [in] */ BSTR app_id) = 0;
^

Original change's description:
> Reland "Remove Deprecated ScopedBstr to BSTR Implicit Conversion Operator"
> 
> This is a reland of afb8942063f388a60991539ab031d119627df64c
> 
> Original change's description:
> > Remove Deprecated ScopedBstr to BSTR Implicit Conversion Operator
> >
> > BUG=1034666
> >
> > Change-Id: I678af5925603de6f983e3d12da6832c0661f293c
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2042194
> > Auto-Submit: Robert Liao <robliao@chromium.org>
> > Commit-Queue: Will Harris <wfh@chromium.org>
> > Reviewed-by: Will Harris <wfh@chromium.org>
> > Cr-Commit-Position: refs/heads/master@{#739275}
> 
> Relanding http://crbug.com/739275
> 
> Bug: 1034666
> TBR: wfh@chromium.org
> Change-Id: I62a2d46993f107b18f758fec01af1828c48a3656
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2043859
> Reviewed-by: Robert Liao <robliao@chromium.org>
> Commit-Queue: Robert Liao <robliao@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#739534}

TBR=robliao@chromium.org,wfh@chromium.org

Change-Id: Ie50ca4b64bdd258637c5ba93c484196187624d67
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 1034666
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2044767
Reviewed-by: Robert Liao <robliao@chromium.org>
Commit-Queue: Robert Liao <robliao@chromium.org>
Cr-Commit-Position: refs/heads/master@{#739569}