usb_ids: Explicit ASCII, ignore codec errors
Specify the defaults of Python 2 explicitly, so it also works on Python 3.
Need to use codecs.open() because Python 2's open() doesn't support the "errors" argument.

Traceback (most recent call last):
  File "../../services/device/public/cpp/usb/tools/usb_ids.py", line 90, in <module>
    table = ParseTable(opts.input)
  File "../../services/device/public/cpp/usb/tools/usb_ids.py", line 20, in ParseTable
    input = input_file.read().split("\n")
  File "C:\Program Files\Python38\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb4 in position 544490: invalid start byte

Bug: 941669
Change-Id: Ie0789d68d574b7baa5c31d81ae846773630cd7b7
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2082511
Auto-Submit: Raul Tambre <raul@tambre.ee>
Reviewed-by: Ken Rockot <rockot@google.com>
Commit-Queue: Raul Tambre <raul@tambre.ee>
Cr-Commit-Position: refs/heads/master@{#746259}