Attempt to retry on transient SSLError and add logging
We're seeing randomly (some uploads succeed and some fail)
SSL related failures:

```
File "/usr/lib/python3.12/ssl.py", line 1103, in read
  return self._sslobj.read(len, buffer)

ssl.SSLError: [SYS] unknown error (_ssl.c:2571)
```

But since it does succeed on some rows try the following.
1) Just retry as is (perhaps it is transient
2) retry with out the error_msg/diff (assuming they are two
   large potentially for the upload)
3) Add logs so we can see this happening

Regardless of the outcome we continue the script (don't crash
on it). So we can evaluate other patches.

Change-Id: I39904a4f3b6694c5315923bb81f14f9e0655b246
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6415328
Reviewed-by: Kalvin Lee <kdlee@chromium.org>
Auto-Submit: Stephen Nusko <nuskos@chromium.org>
Commit-Queue: Stephen Nusko <nuskos@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1440784}