IWYU: usage of std::strcpy requires including cstring, in extension dialog auto confirm.
Fix build breakage with libstdc++:
    ../../extensions/browser/extension_dialog_auto_confirm.cc: In destructor ‘extensions::ScopedTestDialogAutoConfirm::~ScopedTestDialogAutoConfirm()’:
    ../../extensions/browser/extension_dialog_auto_confirm.cc:43:8: error: ‘strcpy’ is not a member of ‘std’
       43 |   std::strcpy(g_extension_dialog_justification, old_justification_.c_str());
          |        ^~~~~~
    ../../extensions/browser/extension_dialog_auto_confirm.cc: In member function ‘void extensions::ScopedTestDialogAutoConfirm::set_justification(const string&)’:
    ../../extensions/browser/extension_dialog_auto_confirm.cc:66:8: error: ‘strcpy’ is not a member of ‘std’
       66 |   std::strcpy(g_extension_dialog_justification, justification.c_str());
          |        ^~~~~~

Bug: 957519
Change-Id: I313c38f22cab599fb8f0e4a339e8143af5bda3ee
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3041001
Reviewed-by: David Bertoni <dbertoni@chromium.org>
Reviewed-by: Ben Wells <benwells@chromium.org>
Commit-Queue: José Dapena Paz <jdapena@igalia.com>
Cr-Commit-Position: refs/heads/master@{#905634}