Revert of Move static GL binding initialization to //ui/gl/init. (patchset #7 id:120001 of https://codereview.chromium.org/2094513002/ )
Reason for revert:
Suspected of breaking Official "win trunk" builder:
c:\b\build\slave\win_trunk\build\src\ui\gl\init\gl_initializer_win.cc(32): fatal error C1083: Cannot open include file: 'software_renderer.h': No such file or directory
Please see crbug.com/623657 for details.

Original issue's description:
> Move static GL binding initialization to //ui/gl/init.
>
> Static GL binding initialization needs to call out to the Ozone
> platform. Move this initialization code from //ui/gl to //ui/gl/init as
> part of larger effort to break //ui/gl dep on //ui/ozone. Also move
> InitializationDebugGLBindings() and ClearGLBindings() in a similar
> fashion as they are closely linked to static initialization.
>
> Unfortunately, dynamic GL binding initialization can't be moved
> //ui/gl/init. It would be nice to have all the initialization code in
> one target but dynamic GL binding initialization is used by GLContext.
>
> The existing InitializationStaticGLBindings() functions had grown to be
> very large for some platforms. Where appropriate the code for each
> implementation has been extracted into it's own method to improve
> readability.
>
> The PRESUBMIT.py script is modified slightly here. The existing static
> GL initialization uses ScopedAllowIO on some platforms. This function is
> banned so moving the code triggers presubmit errors. The GPU main thread
> can't continue until initialization is finished anyways so moving
> blocking code to a different thread isn't helpful. Add new exemptions to
> PRESUBMIT.py.
>
> BUG=611142
> CQ_INCLUDE_TRYBOTS=tryserver.chromium.linux:linux_optional_gpu_tests_rel;tryserver.chromium.mac:mac_optional_gpu_tests_rel;tryserver.chromium.win:win_optional_gpu_tests_rel
>
> Committed: https://crrev.com/507532e60d484704354edd17a7b51904e7a97d88
> Cr-Commit-Position: refs/heads/master@{#402259}

TBR=piman@chromium.org,dpranke@chromium.org,kylechar@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=611142

Review-Url: https://codereview.chromium.org/2099163003
Cr-Commit-Position: refs/heads/master@{#402287}