Revert "[coverage] Fix code coverage for sandboxed child processes on Windows"
This reverts commit a53cf7bac335d5f4e5efbd1769840445549ea9d3.

Reason for revert: Causing CI build failures
Traceback (most recent call last): 
  File "C:\b\s\w\ir\testing\test_env.py", line 541, in <module> 
    sys.exit(main()) 
             ^^^^^^ 
  File "C:\b\s\w\ir\testing\test_env.py", line 537, in main 
    return run_executable(sys.argv[1:], os.environ.copy()) 
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
  File "C:\b\s\w\ir\testing\test_env.py", line 463, in run_executable 
    common.set_lpac_acls(ROOT_DIR, is_test_script=True) 
  File "C:\b\s\w\ir\testing\scripts\common.py", line 127, in set_lpac_acls 
    _grant_acls(full_filename, [('S-1-15-2-2', '(RX)')]) 
  File "C:\b\s\w\ir\testing\scripts\common.py", line 66, in _grant_acls 
    os.makedirs(target_dir, exist_ok=True) 
  File "<frozen os>", line 225, in makedirs 
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\b\\s\\w\\ir\\out\\9f0d-Dawn_Win10_x64_\\chrome_100_percent.pak'

Failure Link: 
https://ci.chromium.org/ui/p/chromium/builders/ci/Dawn%20Win10%20x64%20Release%20(NVIDIA)/92435/overview 
https://chromium-swarm.appspot.com/task?id=79aed7d87b2b0c10 

Original change's description:
> [coverage] Fix code coverage for sandboxed child processes on Windows
>
> Continuous mode (%c) code coverage memory-maps profile files to record
> coverage data before early child process exit. On Windows, sandboxed
> processes running inside AppContainers (LPAC) failed to initialize
> continuous mode because they lacked write permissions to the profile
> directory.
>
> This CL updates testing/test_env.py and the XR test runner to grant
> Modify access on the LLVM profile directory to LPAC SIDs, enabling
> sandboxed child processes to write their coverage data.
>
> Look at bug comments for more information.
>
> Sibling CL:
> chromium-review.git.corp.google.com/c/chromium/src/+/8140266
> Control Build:
> ci.chromium.org/ui/p/chromium/builders/try/win-rel/1602109
> Fix Build:
> ci.chromium.org/ui/p/chromium/builders/try/win-rel/1602110
>
> TAG=agy
>
> Bug: 40917276
> Change-Id: I71f815c7af36911f7c21f02280bfcd74ef16c3a2
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/8140821
> Reviewed-by: Brian Sheedy <bsheedy@chromium.org>
> Reviewed-by: Ben Pastene <bpastene@chromium.org>
> Commit-Queue: Aadarsh Battula <aadarshb@google.com>
> Cr-Commit-Position: refs/heads/main@{#1668096}

Bug: 40917276
Change-Id: I67d3023ec154d49467484d2fc13b0787664fd5e4
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/8149139
Reviewed-by: Patricia Lor <patricialor@chromium.org>
Commit-Queue: Aadarsh Battula <aadarshb@google.com>
Bot-Commit: rubber-stamper@appspot.gserviceaccount.com <rubber-stamper@appspot.gserviceaccount.com>
Owners-Override: Patricia Lor <patricialor@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1668423}