Enable webkit_unit_tests for commit queue and EWS while tracking failures https://bugs.webkit.org/show_bug.cgi?id=83329
Unreviewed.  Add a missing import to unbreak all the Chromium EWS/CQ bots. :)

line 62, in _create_unit_test_results
 return UnitTestResults.results_from_string(results_xml)
 NameError: global name 'UnitTestResults' is not defined

* Scripts/webkitpy/tool/bot/layouttestresultsreader.py:
* Scripts/webkitpy/tool/bot/layouttestresultsreader_unittest.py:
(LayoutTestResultsReaderTest.test_create_unit_test_results):

git-svn-id: svn://svn.chromium.org/blink/trunk@113559 bbb929c8-8fbe-4397-9dbb-9b2b20218538