Revert of Reland: Geolocation: move from content/browser to device/ (patchset #2 id:20001 of https://codereview.chromium.org/2185993003/ )
Reason for revert:
Build failure:
FAILED: obj/device/geolocation/device_geolocation.network_location_request.obj
ninja -t msvc -e environment.x64 -- "C:\b\depot_tools\win_toolchain\vs_files\95ddda401ec5678f15eeed01d2bee08fcbc5ee97\VC\bin\amd64\cl.exe" /nologo /showIncludes /FC @obj\device\geolocation\device_geolocation.network_location_request.obj.rsp /c ..\..\device\geolocation\network_location_request.cc /Foobj\device\geolocation\device_geolocation.network_location_request.obj /Fdobj\device\geolocation\device_geolocation.cc.pdb
c:\b\build\slave\win64_trunk\build\src\device\geolocation\network_location_request.cc(119): error C2220: warning treated as error - no 'object' file generated
c:\b\build\slave\win64_trunk\build\src\device\geolocation\network_location_request.cc(119): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data

Original issue's description:
> Reland: Geolocation: move from content/browser to device/
>
> Original CL was reverted because it broke Win Gyp Component-build
> bot(s). This CL (PS2) defines the geolocation gyp component
> correctly.
>
> Original CL description ------------------------------------------------
> Geolocation: move from content/browser to device/
>
> This CL:
>
> - moves all of content/browser/geolocation to device/geolocation
> - the public geolocation files in content/common/{browser, public}
>  are also relocated to device/geolocation
> - the geolocation-specific unittests are compiled into
>  (already existing) device_unittests
> - adds new fancy new device/geolocation BUILD.gn  and
>  geolocation.gyp as well
> - makes a component of geolocation (at least for gn) and that forces
>  adding geolocation_export.h (like other //device/ folders).
> - Java Geolocation files are moved as well, and a new
>  geolocation_jni_registrar is added.
> - classes are moved to device namespace.
>
> All paths and include/call sites updated, DEPS, BUILD.gn files,
> gypi files etc.
>
> Some tricks:
> - can't use BrowserThread::CurrentlyOn, etc; instead, the
>  task runner is cached on constructor and used for both thread
>  checking and PostTask()ing (a few unittest and wifi_data_provider*
>  needed that substitution).
> - GeolocationServiceContext is moved to public/cpp so it can
>  be referenced from WebContentsImpl.
> - MockLocationProvider.java is also moved to device/geolocation.
>
> BUG=612334
> CQ_INCLUDE_TRYBOTS=master.tryserver.chromium.linux:linux_site_isolation
>
> TBR=pstew@chromium.org
> rationale:device/geolocation depends on dbus and this triggers
> a DEPS presubmit rule -- however, this CL adds no new dependencies,
> hence moving on in the interest of speed (and avoiding more rebases).
>
> Committed: https://crrev.com/cc322ebcb1c911072c8dc4fc38d41c1a41c426b7
> Cr-Commit-Position: refs/heads/master@{#408272}

TBR=pstew@chromium.org,mcasas@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=612334

Review-Url: https://codereview.chromium.org/2188933002
Cr-Commit-Position: refs/heads/master@{#408303}