Files app: Fix VolumeInfoImpl when filesystem is null
Change resolveDisplayRootImpl_() to always fail if there is no file
system, regardless of volume type. This fixes error when Drive volume
couldn't resolve file system:
TypeError: Cannot read property 'root' of null

Test: browser_tests --gtest_filter="FileManagerJsTest.VolumeManagerTest"
Bug: 1041340
Change-Id: I94bb3cb83ec6f5ede485e3090d1857f8895808fb
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1999893
Commit-Queue: Luciano Pacheco <lucmult@chromium.org>
Auto-Submit: Luciano Pacheco <lucmult@chromium.org>
Reviewed-by: Austin Tankiang <austinct@chromium.org>
Cr-Commit-Position: refs/heads/master@{#731117}