Revert of roll clang 255169:256316 (patchset #10 id:180001 of https://codereview.chromium.org/1539373005/ )
Reason for revert:
The Mac OS 10.7 Debug Blink bot is hitting the regression mentioned in the CL while running several Blink unittests:

dyld: lazy symbol binding failed: Symbol not found: __ZNSt3__114basic_iostreamIcNS_11char_traitsIcEEEC2EPNS_15basic_streambufIcS2_EE
  Referenced from: /Volumes/data/b/swarm_slave/work/isolated/runImpjEb/third_party/WebKit/Source/wtf/../../../../out/Debug/wtf_unittests
  Expected in: /usr/lib/libc++.1.dylib

dyld: Symbol not found: __ZNSt3__114basic_iostreamIcNS_11char_traitsIcEEEC2EPNS_15basic_streambufIcS2_EE
  Referenced from: /Volumes/data/b/swarm_slave/work/isolated/runImpjEb/third_party/WebKit/Source/wtf/../../../../out/Debug/wtf_unittests
  Expected in: /usr/lib/libc++.1.dylib

Full output:
https://build.chromium.org/p/chromium.webkit/builders/WebKit%20Mac10.7%20%28dbg%29/builds/26318/steps/steps/logs/stdio

Original issue's description:
> roll clang 255169:256316
>
> New:
> * /W4 in clang-cl enables -Wextra warnings
> * fix for link.exe /incremental build flakes
> * /Brepro suppresses timestamps for deterministic builds
>   (doesn't work with link.exe /incremental)
>
> Note that this brings in a libc++ regression on Mac [1]: some of the
> symbols that are hidden symbols in the system libc++ in OS X 10.8
> are marked as "inline" in the headers shipped with this compiler --
> this means that binaries produced by this compiler might not run
> on OS X 10.8 if these calls don't get inlined (or, if the 10.8 SDK is
> used, they won't link). That's ok for us though because production
> builds on OS X statically link a newer libc++ with these symbols
> exported, the iOS bots run newer OS X versions than 10.8, and
> so do the Mac bots that do component builds (which use the
> system libc++) or asan builds. And soon we'll roll in r257193 which
> fixes this again.
>
> 1: http://lists.llvm.org/pipermail/cfe-commits/Week-of-Mon-20160104/146428.html
>
> BUG=571691
> TBR=hans
>
> Committed: https://crrev.com/483df9304bb678dd50b435a41c063a3aed96d10f
> Cr-Commit-Position: refs/heads/master@{#368796}

TBR=hans@chromium.org,thakis@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=571691

Review URL: https://codereview.chromium.org/1575393003

Cr-Commit-Position: refs/heads/master@{#368900}