QuotaExceededError: Restore legacy exception code 22 to match spec
Reverts just the code value change from crrev.com/c/6516473
Matches resolution in https://github.com/whatwg/webidl/pull/1465
Tests updated in https://github.com/web-platform-tests/wpt/pull/53645

Bug: 406162261
Fixed: 434432288
Change-Id: I2fe06c29c1773fdbec5765a18d5c59a0aa2235f8
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6814000
Commit-Queue: Daniel Cheng <dcheng@chromium.org>
Reviewed-by: Daniel Cheng <dcheng@chromium.org>
Auto-Submit: Mike Wasserman <msw@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1496718}