chrome: Add missing deps to //chrome/browser/pref:impl
This fixes the following build error:

GN args
```
target_os = "android"
target_cpu = "arm64"
```

```
> autoninja -C out/android-arm64-rel android_clang_arm/obj/chrome/browser/prefs/impl/browser_prefs.o
...
In file included from ../../chrome/browser/prefs/browser_prefs.cc:293:
In file included from ../../components/feed/core/v2/ios_shared_prefs.h:8:
../../components/feed/core/v2/ios_shared_experiments_translator.h:14:10: fatal error: 'components/feed/core/proto/v2/wire/chrome_feed_response_metadata.pb.h' file not found
   14 | #include "components/feed/core/proto/v2/wire/chrome_feed_response_metadata.pb.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Bug: 346429448
Change-Id: If04516757861f18dd2fcd17bc3967da4f89e6b84
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/8033921
Auto-Submit: Junji Watanabe <jwata@google.com>
Reviewed-by: Gabriel Charette <gab@chromium.org>
Commit-Queue: Junji Watanabe <jwata@google.com>
Cr-Commit-Position: refs/heads/main@{#1656338}