GCC: do not use namespace linux in system memory pressure evaluator
GCC fails to compile system memory pressure evaluator, as the
linux implementation is in linux namespace. But in GCC, linux
is a reserved word, so it should not be used. To fix the
problem, we rename the new namespace to os_linux.

../../base/util/memory_pressure/system_memory_pressure_evaluator_linux.h:16:11: error: expected identifier before numeric constant
   16 | namespace linux {
      |           ^~~~~

Bug: 819294
Change-Id: I3edcbbbb91fe99aab8c0be952385bb38bb1e27e5
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2394158
Reviewed-by: Sébastien Marchand <sebmarchand@chromium.org>
Commit-Queue: José Dapena Paz <jdapena@igalia.com>
Cr-Commit-Position: refs/heads/master@{#807099}