Revert of Fix lifetime problems in AXPlatformNodeCocoa. (patchset #6 id:100001 of https://codereview.chromium.org/2944103005/ )
Reason for revert:
Compile issues with modern SDK:

../../ui/views/widget/native_widget_mac_accessibility_unittest.mm:176:34: error: null passed to a callee that requires a non-null argument [-Werror,-Wnonnull]
  EXPECT_EQ(NSNotFound, [ax_node accessibilityIndexOfChild:nil]);
                                 ^                         ~~~
../../third_party/googletest/src/googletest/include/gtest/gtest.h:1925:29: note: expanded from macro 'EXPECT_EQ'
                      val1, val2)
                            ^~~~
../../third_party/googletest/src/googletest/include/gtest/gtest_pred_impl.h:162:40: note: expanded from macro 'EXPECT_PRED_FORMAT2'
  GTEST_PRED_FORMAT2_(pred_format, v1, v2, GTEST_NONFATAL_FAILURE_)
                                       ^~
../../third_party/googletest/src/googletest/include/gtest/gtest_pred_impl.h:147:43: note: expanded from macro 'GTEST_PRED_FORMAT2_'
  GTEST_ASSERT_(pred_format(#v1, #v2, v1, v2), \
                                          ^~
../../third_party/googletest/src/googletest/include/gtest/gtest_pred_impl.h:77:52: note: expanded from macro 'GTEST_ASSERT_'
  if (const ::testing::AssertionResult gtest_ar = (expression)) \
                                                   ^~~~~~~~~~
../../ui/views/widget/native_widget_mac_accessibility_unittest.mm:217:34: error: null passed to a callee that requires a non-null argument [-Werror,-Wnonnull]
  EXPECT_EQ(NSNotFound, [ax_node accessibilityIndexOfChild:nil]);
                                 ^                         ~~~
../../third_party/googletest/src/googletest/include/gtest/gtest.h:1925:29: note: expanded from macro 'EXPECT_EQ'
                      val1, val2)
                            ^~~~
../../third_party/googletest/src/googletest/include/gtest/gtest_pred_impl.h:162:40: note: expanded from macro 'EXPECT_PRED_FORMAT2'
  GTEST_PRED_FORMAT2_(pred_format, v1, v2, GTEST_NONFATAL_FAILURE_)
                                       ^~
../../third_party/googletest/src/googletest/include/gtest/gtest_pred_impl.h:147:43: note: expanded from macro 'GTEST_PRED_FORMAT2_'
  GTEST_ASSERT_(pred_format(#v1, #v2, v1, v2), \
                                          ^~
../../third_party/googletest/src/googletest/include/gtest/gtest_pred_impl.h:77:52: note: expanded from macro 'GTEST_ASSERT_'
  if (const ::testing::AssertionResult gtest_ar = (expression)) \
                                                   ^~~~~~~~~~
In file included from ../../ui/views/widget/native_widget_mac_accessibility_unittest.mm:14:
In file included from ../../testing/gtest_mac.h:8:
In file included from ../../testing/gtest/include/gtest/gtest.h:10:
../../third_party/googletest/src/googletest/include/gtest/gtest.h:1392:11: error: comparison of integers of different signs: 'const long' and 'const unsigned long' [-Werror,-Wsign-compare]
  if (lhs == rhs) {
      ~~~ ^  ~~~
../../third_party/googletest/src/googletest/include/gtest/gtest.h:1421:12: note: in instantiation of function template specialization 'testing::internal::CmpHelperEQ<long, unsigned long>' requested here
    return CmpHelperEQ(lhs_expression, rhs_expression, lhs, rhs);
           ^
../../ui/views/widget/native_widget_mac_accessibility_unittest.mm:176:3: note: in instantiation of function template specialization 'testing::internal::EqHelper<false>::Compare<long, unsigned long>' requested here
  EXPECT_EQ(NSNotFound, [ax_node accessibilityIndexOfChild:nil]);
  ^
../../third_party/googletest/src/googletest/include/gtest/gtest.h:1924:63: note: expanded from macro 'EXPECT_EQ'
                      EqHelper<GTEST_IS_NULL_LITERAL_(val1)>::Compare, \
                                                              ^
3 errors generated.

Original issue's description:
> Fix lifetime problems in AXPlatformNodeCocoa.
>
> AXPlatformNodeCocoa needs to check in more places for its |node_| being
> detached. Fix and add test coverage.
>
> BUG=734939
>
> Review-Url: https://codereview.chromium.org/2944103005
> Cr-Commit-Position: refs/heads/master@{#484048}
> Committed: https://chromium.googlesource.com/chromium/src/+/bb756436f55c01c2066c17d5eec5aaeb1e52a120

TBR=dmazzoni@chromium.org,tapted@chromium.org
# Using NOTRY because iOS bots are failing for unrelated reasons, this is a Mac patch, and Mac bots are green.
NOTRY=true
BUG=734939

Review-Url: https://codereview.chromium.org/2969293002
Cr-Commit-Position: refs/heads/master@{#484331}