Revert "Roll Chromite from 8199e2bbaef8 to cca6a353a89b (8 revisions)"
This reverts commit e674d19cb8ad0b4aae9597348c05d1d58b735af0.

Reason for revert:
Possible cause of regressions starting on:
https://ci.chromium.org/ui/p/chrome/builders/ci/Lacros%20FYI%20Release%20(octopus)/4536
> ModuleNotFoundError: No module named 'boto.connection'
See crbug.com/341991534 for details.

Original change's description:
> Roll Chromite from 8199e2bbaef8 to cca6a353a89b (8 revisions)
>
> https://chromium.googlesource.com/chromiumos/chromite.git/+log/8199e2bbaef8..cca6a353a89b
>
> 2024-05-20 saklein@chromium.org lib: Add traceparent to CHROOT_ENVIRONMENT_ALLOWLIST.
> 2024-05-20 saklein@chromium.org cli: Simplify and expand cros telemetry tests.
> 2024-05-20 jrosenth@chromium.org scripts: cros_setup_toolchains: Drop hps-sdk
> 2024-05-20 vapier@chromium.org lib: cache: drop redundant entry lock
> 2024-05-20 vapier@chromium.org contrib: ebuild_housekeeping: add PYTHON_COMPAT upgrade helper
> 2024-05-20 vapier@chromium.org contrib: ebuild-housekeeping: clean up some internal APIs
> 2024-05-20 saklein@chromium.org lib: Publish portage telemetry.
> 2024-05-20 saklein@chromium.org lib: More aggressively skip non-googlers.
>
> If this roll has caused a breakage, revert this CL and stop the roller
> using the controls here:
> https://autoroll.skia.org/r/chromite-chromium-autoroll
> Please CC chrome-os-gardeners-reviews@google.com,chrome-os-gardeners@google.com,chromeos-velocity@google.com on the revert to ensure that a human
> is aware of the problem.
>
> To file a bug in Chromium: https://bugs.chromium.org/p/chromium/issues/entry
>
> To report a problem with the AutoRoller itself, please file a bug:
> https://issues.skia.org/issues/new?component=1389291&template=1850622
>
> Documentation for the AutoRoller is here:
> https://skia.googlesource.com/buildbot/+doc/main/autoroll/README.md
>
> Cq-Include-Trybots: luci.chrome.try:chromeos-betty-pi-arc-chrome
> Tbr: chrome-os-gardeners-reviews@google.com
> Change-Id: I8acd2fb95e4786a158f9f6e14a5a3ce547a423e6
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5552828
> Bot-Commit: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>
> Commit-Queue: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>
> Cr-Commit-Position: refs/heads/main@{#1303895}

Bug: 341991534
Change-Id: I4277355aa039b3b3eb814f3efe0416a9d9d3a419
Cq-Include-Trybots: luci.chrome.try:chromeos-betty-pi-arc-chrome
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5554488
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Reviewed-by: David Munro <davidmunro@google.com>
Commit-Queue: Kai Ninomiya <kainino@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1304252}