Revert "Highlight text fragment directives on page reload"
This reverts commit 8e1e2bb61d49553b3637e682b3c096140fd1fbc7.

Reason for revert: <INSERT REASONING HERE>
../../third_party/blink/renderer/core/page/scrolling/text_fragment_anchor_test.cc(8,10): fatal error: 'third_party/blink/renderer/bindings/core/v8/usv_string_or_trusted_url.h' file not found
#include "third_party/blink/renderer/bindings/core/v8/usv_string_or_trusted_url.h"
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.


Original change's description:
> Highlight text fragment directives on page reload
> 
> Fix the behavior where fragment anchors were only kept alive if a scroll
> was needed, as is the behavior of element fragment anchors. This caused
> text fragment anchors not to be kept alive and we didn't highlight on
> reload.
> 
> Note that *sometimes* we would highlight on reload, due to a race
> condition with fragment anchors, where we process the fragment before
> restoring scroll position (which is where should_scroll becomes false),
> see crbug/839292. This change makes it so we highlight on reload
> independent of whether a scroll is needed.
> 
> Bug: 932551
> Change-Id: I38cc82c4920255d8bcae9f8b55ac80f24d1465da
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1864714
> Commit-Queue: David Bokan <bokan@chromium.org>
> Reviewed-by: David Bokan <bokan@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#706847}

TBR=bokan@chromium.org,nburris@chromium.org

Change-Id: Ifa4ea6a04c62662a1ec0a7b611247ed16d9d979b
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 932551
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1866623
Reviewed-by: Lan Wei <lanwei@chromium.org>
Commit-Queue: Lan Wei <lanwei@chromium.org>
Cr-Commit-Position: refs/heads/master@{#706980}