Revert "[TaskIcon] Update tooltip text to match GlicButton"
This reverts commit d267c1bec1ab97f5324fab46e0d0f104d6dd6413.

Reason for revert: Believed to have broken compile in linux-cft and mac-arm64-dbg (possibly others):

[31/46] CXX obj/chrome/test/browser_tests/tab_strip_action_container_browsertest.o
../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/chrome/test/browser_tests/tab_strip_action_container_browsertest.o.d -DH...(too long)
../../chrome/browser/ui/views/tabs/tab_strip_action_container_browsertest.cc:632:48: error: no member named 'UiState' in 'actor::ui::ActorUiStateManagerInterface'
  632 |       actor::ui::ActorUiStateManagerInterface::UiState::kActive,
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
../../chrome/browser/ui/views/tabs/tab_strip_action_container_browsertest.cc:643:48: error: no member named 'UiState' in 'actor::ui::ActorUiStateManagerInterface'
  643 |       actor::ui::ActorUiStateManagerInterface::UiState::kActive,

Bug: 417759759
Original change's description:
> [TaskIcon] Update tooltip text to match GlicButton
>
> Bug: 417759759
> Change-Id: I1141645254b3ecf26d35d214c95fee6a5595db11
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6841538
> Reviewed-by: Erik Chen <erikchen@chromium.org>
> Commit-Queue: Maggie Jennings <mjenn@google.com>
> Cr-Commit-Position: refs/heads/main@{#1500880}

Bug: 417759759
Change-Id: I11874c10c09f726cec10dc4e9465fff6abff3faf
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6846027
Auto-Submit: Stephen McGruer <smcgruer@chromium.org>
Commit-Queue: Stephen McGruer <smcgruer@chromium.org>
Owners-Override: Stephen McGruer <smcgruer@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Reviewed-by: Maggie Jennings <mjenn@google.com>
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Cr-Commit-Position: refs/heads/main@{#1500897}