Revert of Fold UpdateModel into UpdateScreen. (patchset #3 id:40001 of https://codereview.chromium.org/2673943002/ )
Reason for revert:
Broke compile

FAILED: obj/chrome/browser/chromeos/chromeos/update_screen.o
/b/c/cipd/goma/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/chrome/browser/chromeos/chromeos/update_screen.o.d -DV8_DEPRECATION_WARNINGS -DUSE_UDEV -DUI_COMPOSITOR_IMAGE_TRANSPORT -DUSE_ASH=1 -DUSE_AURA=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DENABLE_WAYLAND_SERVER=1 -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DOFFICIAL_BUILD -DGOOGLE_CHROME_BUILD -DENABLE_MEDIA_ROUTER=1 -DCR_CLANG_REVISION=289944-2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DNO_UNWIND_TABLES -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -DOS_CHROMEOS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DGL_GLEXT_PROTOTYPES -DUSE_GLX -DUSE_EGL -DTOOLKIT_VIEWS=1 -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DHAVE_PTHREAD -DSK_IGNORE_DW_GRAY_FIX -DSK_IGNORE_LINEONLY_AA_CONVEX_PATH_OPTS -DSK_SUPPORT_GPU=1 -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DU_STATIC_IMPLEMENTATION -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_FILE -DV8_USE_EXTERNAL_STARTUP_DATA -DLEVELDB_PLATFORM_CHROMIUM=1 -DFEATURE_ENABLE_VOICEMAIL -DEXPAT_RELATIVE_PATH -DGTEST_RELATIVE_PATH -DNO_MAIN_THREAD_WRAPPING -DNO_SOUND_SYSTEM -DWEBRTC_CHROMIUM_BUILD -DWEBRTC_POSIX -DWEBRTC_LINUX -DCHROMEOS -DNO_MAIN_THREAD_WRAPPING -I../.. -Igen -I../../build/linux/ubuntu_precise_amd64-sysroot/usr/include/glib-2.0 -I../../build/linux/ubuntu_precise_amd64-sysroot/usr/lib/x86_64-linux-gnu/glib-2.0/include -I../../third_party/khronos -I../../gpu -I../../third_party/protobuf/src -Igen/protoc_out -I../../third_party/protobuf/src -Igen/ash/common/strings -Igen/ash/resources -Igen/chrome -Igen/chrome -Igen/chrome -Igen/chrome -I../../skia/config -I../../skia/ext -I../../third_party/skia/include/c -I../../third_party/skia/include/config -I../../third_party/skia/include/core -I../../third_party/skia/include/effects -I../../third_party/skia/include/images -I../../third_party/skia/include/lazy -I../../third_party/skia/include/pathops -I../../third_party/skia/include/pdf -I../../third_party/skia/include/pipe -I../../third_party/skia/include/ports -I../../third_party/skia/include/utils -I../../third_party/skia/include/gpu -I../../third_party/skia/src/gpu -I../../third_party/skia/src/sksl -Igen/ui/chromeos/resources -Igen/ui/chromeos/strings -Igen/ui/resources -Igen/ui/resources -Igen -I../../third_party/ced/src -I../../third_party/icu/source/common -I../../third_party/icu/source/i18n -I../../third_party/boringssl/src/include -Igen/components/metrics/proto -I../../build/linux/ubuntu_precise_amd64-sysroot/usr/include/nss -I../../build/linux/ubuntu_precise_amd64-sysroot/usr/include/nspr -Igen/components/strings -Igen/components/strings -Igen/components/strings -Igen/components/strings -I../../third_party/libwebm/source -Igen -I../../third_party/WebKit -Igen/third_party/WebKit -I../../v8/include -Igen/v8/include -I../../third_party/re2/src -I../../third_party/mesa/src/include -Igen/extensions -Igen/extensions -Igen/extensions -Igen -Igen/extensions/strings -I../../build/linux/ubuntu_precise_amd64-sysroot/usr/include/dbus-1.0 -I../../build/linux/ubuntu_precise_amd64-sysroot/usr/lib/x86_64-linux-gnu/dbus-1.0/include -Igen -Igen/components -Igen/components -I../../third_party/cacheinvalidation/overrides -I../../third_party/cacheinvalidation/src -I../../third_party/leveldatabase -I../../third_party/leveldatabase/src -I../../third_party/leveldatabase/src/include -I../../third_party/webrtc_overrides -I../../testing/gtest/include -I../../third_party -I../../third_party/webrtc_overrides -I../../third_party -I../../third_party/libusb/src/libusb -I../../third_party/zlib -Igen/ui/views/resources -Igen/ui/file_manager -I../../v8/include -Igen/v8/include -fno-strict-aliasing -fno-unwind-tables -fno-asynchronous-unwind-tables -fPIC -pipe -B../../third_party/binutils/Linux_x64/Release/bin -fcolor-diagnostics -fdebug-prefix-map=/b/c/b/Google_Chrome_ChromeOS/src=. -m64 -march=x86-64 -pthread -Wall -Werror -Wextra -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-covered-switch-default -Wno-deprecated-register -Wno-unneeded-internal-declaration -Wno-inconsistent-missing-override -Wno-shift-negative-value -Wno-undefined-var-template -Wno-nonportable-include-path -Wno-address-of-packed-member -O2 -fno-ident -fdata-sections -ffunction-sections -g2 --sysroot=../../build/linux/ubuntu_precise_amd64-sysroot -fvisibility=hidden -Xclang -load -Xclang ../../third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.so -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang check-ipc -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Wexit-time-destructors -Wno-header-guard -fvisibility-inlines-hidden -std=gnu++11 -Wno-reserved-user-defined-literal -fno-rtti -fno-exceptions -c ../../chrome/browser/chromeos/login/screens/update_screen.cc -o obj/chrome/browser/chromeos/chromeos/update_screen.o
../../chrome/browser/chromeos/login/screens/update_screen.cc:38:22: error: unused variable 'kUserActionCancelUpdateShortcut' [-Werror,-Wunused-const-variable]
constexpr const char kUserActionCancelUpdateShortcut[] = "cancel-update";
                     ^
../../chrome/browser/chromeos/login/screens/update_screen.cc:46:22: error: unused variable 'kContextKeyCancelUpdateShortcutEnabled' [-Werror,-Wunused-const-variable]
constexpr const char kContextKeyCancelUpdateShortcutEnabled[] =

Original issue's description:
> Fold UpdateModel into UpdateScreen.
>
> BUG=672142
>
> Review-Url: https://codereview.chromium.org/2673943002
> Cr-Commit-Position: refs/heads/master@{#448447}
> Committed: https://chromium.googlesource.com/chromium/src/+/eed833f5e4ec040342c08755bad3f45c3a0b8ab6

TBR=achuith@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=672142

Review-Url: https://codereview.chromium.org/2684473002
Cr-Commit-Position: refs/heads/master@{#448467}