Revert "CrOS HelpApp: Migrate to Mojo JS modules."
This reverts commit 97653e12032677e21951ebdd70fc614c5d8cb681.

Reason for revert: This CL likely caused test failures chromeos-betty-pi-arc-cfi-thin-lto-chrome builder.
First failure: https://ci.chromium.org/ui/p/chrome/builders/ci/chromeos-betty-pi-arc-cfi-thin-lto-chrome/45476/test-results?sortby=&groupby=

Failure Reason:
Failed to initialize local search service: context deadline exceeded during a poll with timeout 30s; last error follows: failed to run javascript to check LSS status: ReferenceError: ash is not defined

Failed to initialize local search service
	at chromiumos/tast/local/bundles/cros/apps.SearchInHelpApp (search_in_help_app.go:127)
	at chromiumos/tast/internal/planner.runTestWithConfig.func4.1 (run.go:843)
	at chromiumos/tast/internal/usercode.SafeCall.func2 (usercode.go:112)
	at runtime.goexit (asm_amd64.s:1598)
context deadline exceeded during a poll with timeout 30s; last error follows
	at chromiumos/tast/internal/testingutil.Poll (poll.go:90)
	at chromiumos/tast/testing.Poll (util.go:43)
	at chromiumos/tast/local/bundles/cros/apps.SearchInHelpApp (search_in_help_app.go:98)
	at chromiumos/tast/internal/planner.runTestWithConfig.func4.1 (run.go:843)
	at chromiumos/tast/internal/usercode.SafeCall.func2 (usercode.go:112)
	at runtime.goexit (asm_amd64.s:1598)
failed to run javascript to check LSS status
	at chromiumos/tast/local/bundles/cros/apps.SearchInHelpApp.func1 (search_in_help_app.go:114)
	at chromiumos/tast/internal/testingutil.Poll (poll.go:67)
	at chromiumos/tast/testing.Poll (util.go:43)
	at chromiumos/tast/local/bundles/cros/apps.SearchInHelpApp (search_in_help_app.go:98)
	at chromiumos/tast/internal/planner.runTestWithConfig.func4.1 (run.go:843)
	at chromiumos/tast/internal/usercode.SafeCall.func2 (usercode.go:112)
	at runtime.goexit (asm_amd64.s:1598)
ReferenceError: ash is not defined
	at chromiumos/tast/local/chrome/internal/cdputil.(*Conn).Eval (conn.go:134)
	at chromiumos/tast/local/chrome/internal/driver.(*Conn).Eval (conn.go:112)
	at chromiumos/tast/local/bundles/cros/apps.SearchInHelpApp.func1 (search_in_help_app.go:100)
	at chromiumos/tast/internal/testingutil.Poll (poll.go:67)
	at chromiumos/tast/testing.Poll (util.go:43)
	at chromiumos/tast/local/bundles/cros/apps.SearchInHelpApp (search_in_help_app.go:98)
	at chromiumos/tast/internal/planner.runTestWithConfig.func4.1 (run.go:843)
	at chromiumos/tast/internal/usercode.SafeCall.func2 (usercode.go:112)


Original change's description:
> CrOS HelpApp: Migrate to Mojo JS modules.
>
> Bug: 1179821
> Change-Id: I29bdf1c73edec1c1d2c0812b3048a4b291b23dd4
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4379260
> Reviewed-by: Thanh Nguyen <thanhdng@chromium.org>
> Reviewed-by: Callistus Tan <callistus@google.com>
> Commit-Queue: Demetrios Papadopoulos <dpapad@chromium.org>
> Reviewed-by: Robert Sesek <rsesek@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1125457}

Bug: 1179821
Change-Id: Ib6a157092a8fd6e7f79fe5be177a80391bf05b95
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4403053
Owners-Override: Maxim Kolosovskiy <kolos@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Reviewed-by: Maxim Kolosovskiy <kolos@chromium.org>
Commit-Queue: Maxim Kolosovskiy <kolos@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1126476}