Add //components/subresource_filter/browser:browser to //chrome/browser/devtools:devtools.
chrome/browser/devtools/protocol/page_handler.cc depends on //components/subresource_filter/browser:browser.

c.f. https://ci.chromium.org/p/chromium/builders/ci/win-archive-rel/9894

[51956/72454] CXX obj/chrome/browser/devtools/devtools/page_handler.obj

In file included from ../../chrome/browser/devtools/protocol/page_handler.cc:8:
In file included from ../..\chrome/browser/subresource_filter/chrome_subresource_filter_client.h:13:
../..\components/subresource_filter/content/browser/subresource_filter_client.h(10,10): fatal error: 'components/subresource_filter/core/mojom/subresource_filter.mojom.h' file not found

FAILED: obj/chrome/browser/devtools/devtools/page_handler.obj
C: \b\s\w\ir\cache\goma\client\gomacc.exe ..\..\third_party\llvm-build\Release+Asserts\bin\clang-cl.e...(too long)
Change-Id: I49d4fad36a3340fb0df6a758c64f49d9ac1efc54
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2007807
Auto-Submit: Takashi Sakamoto <tasak@google.com>
Commit-Queue: Andrey Kosyakov <caseq@chromium.org>
Reviewed-by: Andrey Kosyakov <caseq@chromium.org>
Cr-Commit-Position: refs/heads/master@{#734242}