Revert of [Oilpan] Migrate getUnderestimateStackSize (patchset #2 id:20001 of https://codereview.chromium.org/859153006/)
Reason for revert:
Broke Mac GN bots:

../../third_party/WebKit/Source/platform/heap/StackFrameDepth.cpp:47:37: error: use of undeclared identifier 'pthread_self'

Original issue's description:
> Migrate getUnderestimateStackSize function under StackFrameDepth class.
> 
> This CL is a preparation to expand eager tracing based on
> stack size.
> 
> BUG=420515
> TEST=None
> 
> Committed: https://src.chromium.org/viewvc/blink?view=rev&revision=189484

TBR=oilpan-reviews@chromium.org,kouhei@chromium.org,peria@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=420515

Review URL: https://codereview.chromium.org/899213002

git-svn-id: svn://svn.chromium.org/blink/trunk@189554 bbb929c8-8fbe-4397-9dbb-9b2b20218538