Revert "Fix unique_ptr<>() PRESUBMIT."
This reverts commit d3c37827ca1563f3039ea85a45b43bd1f7624895.

Reason for revert: git cl upload is failing:

Traceback (most recent call last):
  File "/usr/local/google/home/sky/depot_tools/git_cl.py", line 6174, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/google/home/sky/depot_tools/git_cl.py", line 6156, in main
    return dispatcher.execute(OptionParser(), argv)
  File "/usr/local/google/home/sky/depot_tools/subcommand.py", line 252, in execute
    return command(parser, args[1:])
  File "/usr/local/google/home/sky/depot_tools/git_cl.py", line 5007, in CMDupload
    return cl.CMDUpload(options, args, orig_args)
  File "/usr/local/google/home/sky/depot_tools/git_cl.py", line 1594, in CMDUpload
    change=change)
  File "/usr/local/google/home/sky/depot_tools/git_cl.py", line 1528, in RunHook
    gerrit_obj=self._codereview_impl.GetGerritObjForPresubmit())
  File "/usr/local/google/home/sky/depot_tools/presubmit_support.py", line 1421, in DoPresubmitChecks
    results += executer.ExecPresubmitScript(presubmit_script, filename)
  File "/usr/local/google/home/sky/depot_tools/presubmit_support.py", line 1328, in ExecPresubmitScript
    result = eval(function_name + '(*__args)', context)
  File "<string>", line 1, in <module>
  File "<string>", line 2840, in CheckChangeOnUpload
  File "<string>", line 2564, in _CommonChecks
  File "<string>", line 1419, in _CheckUniquePtr
NameError: global name 're' is not defined

I think you missed an import re
in PRESUBMIT.py. This is likely an easy fix, but I suspect by the time it takes me to submit a patch for review to make sure this is in fact
the problem someone will have already reverted. So, I'm reverting.

Original change's description:
> Fix unique_ptr<>() PRESUBMIT.
> 
> Three directories had a PRESUBMIT designed to catch "std::unique_ptr<T>()" and
> require nullptr instead.  In two directories, the match was overbroad, catching
> things like "std::vector<std::unique_ptr<T>>()".  In ui/, ricea attempted a fix
> (in https://codereview.chromium.org/2311783002 ) that made the regex too
> conservative, failing to catch std::unique_ptr<Foo<T>>().
> 
> Instead, fail to match std::unique_ptr<T>() if it's immediately preceded by '<'.
> 
> BUG=none
> TEST=none
> 
> Cq-Include-Trybots: master.tryserver.blink:linux_trusty_blink_rel;master.tryserver.chromium.android:android_optional_gpu_tests_rel
> Change-Id: Iac502bae48451b932e4a89119d80a16a04747359
> Reviewed-on: https://chromium-review.googlesource.com/927309
> Reviewed-by: Scott Violet <sky@chromium.org>
> Reviewed-by: Daniel Cheng <dcheng@chromium.org>
> Commit-Queue: Peter Kasting <pkasting@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#538461}

TBR=sky@chromium.org,pkasting@chromium.org,dcheng@chromium.org

Change-Id: I5377b0e045ab64242916a8aefb80590b1203247b
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: none
Cq-Include-Trybots: master.tryserver.blink:linux_trusty_blink_rel;master.tryserver.chromium.android:android_optional_gpu_tests_rel
Reviewed-on: https://chromium-review.googlesource.com/931842
Reviewed-by: Scott Violet <sky@chromium.org>
Commit-Queue: Scott Violet <sky@chromium.org>
Cr-Commit-Position: refs/heads/master@{#538467}