Revert "DPWA: Merge web_applications/components/BUILD.gn into web_applications/BUILD.gn"
This reverts commit e63e401a3f2942864983de094c2b74f5810146c2.

Reason for revert: suspect causing compile failure on mac-archive-rel

https://ci.chromium.org/ui/p/chromium/builders/ci/mac-archive-rel/22650/overview

FAILED: obj/chrome/browser/web_applications/preinstalled_web_apps/preinstalled_web_apps/preinstalled_web_apps.o
In file included from ../../chrome/browser/web_applications/preinstalled_web_apps/preinstalled_web_apps.cc:5:
In file included from ../../chrome/browser/web_applications/preinstalled_web_apps/preinstalled_web_apps.h:10:
In file included from ../../chrome/browser/web_applications/components/external_install_options.h:12:
In file included from ../../chrome/browser/web_applications/components/install_manager.h:14:
../../chrome/browser/web_applications/components/web_app_constants.h:11:10: fatal error: 'components/services/app_service/public/mojom/types.mojom-forward.h' file not found
#include "components/services/app_service/public/mojom/types.mojom-forward.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.


Original change's description:
> DPWA: Merge web_applications/components/BUILD.gn into web_applications/BUILD.gn
>
> This CL moves .cc/.h entries from web_applications/components/BUILD.gn
> to web_applications/BUILD.gn without moving actual files (no git mv).
>
> Bug: 1225132
> Change-Id: I560417d1a9bcc15a55afcbef0ee8de4b93259837
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3023729
> Reviewed-by: Alexey Baskakov <loyso@chromium.org>
> Reviewed-by: Scott Violet <sky@chromium.org>
> Commit-Queue: Fangzhen Song <songfangzhen@bytedance.com>
> Cr-Commit-Position: refs/heads/master@{#902306}

Bug: 1225132
Change-Id: I1e0236a3ecc323a694804347a1338025de7b4f0a
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3033217
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Reviewed-by: Takashi Sakamoto <tasak@google.com>
Reviewed-by: Kentaro Hara <haraken@chromium.org>
Owners-Override: Takashi Sakamoto <tasak@google.com>
Auto-Submit: Takashi Sakamoto <tasak@google.com>
Commit-Queue: Kentaro Hara <haraken@chromium.org>
Cr-Commit-Position: refs/heads/master@{#902333}