Add parentheses to DEPS conditions with double "and"s.
gsync error message from alexclarke@

(inside 'host_os == "linux" and checkout_fuchsia and checkout_fuchsia_for_arm64_host')

ValueError: invalid "and": exactly 2 operands required
Bug: 1000901
Change-Id: Iea261c3cbbc65c92a3c79a43c1abfdaa1e3e1411
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1893190
Reviewed-by: Scott Violet <sky@chromium.org>
Commit-Queue: Stephen Roe <steveroe@google.com>
Cr-Commit-Position: refs/heads/master@{#711476}