Revert of Loading screenshots and simple 1-to-1 comparison of screenshots (https://codereview.chromium.org/433873002/)
Reason for revert:
Compile failures: http://build.chromium.org/p/chromium.chromiumos/builders/Linux%20ChromiumOS%20Builder/builds/8151/steps/compile/logs/stdio#error1

From log:

FAILED: /b/build/goma/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/chrome/browser/chromeos/login/interactive_ui_tests.screenshot_tester.o.d -DV8_DEPRECATION_WARNINGS -DBLINK_SCALE_FILTERS_AT_RECORD_TIME -D_FILE_OFFSET_BITS=64 -DCHROMIUM_BUILD -DCR_CLANG_REVISION=214024 -DTOOLKIT_VIEWS=1 -DUI_COMPOSITOR_IMAGE_TRANSPORT -DUSE_AURA=1 -DUSE_ASH=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_GLIB=1 -DUSE_DEFAULT_RENDER_THEME=1 -DUSE_X11=1 -DUSE_XI2_MT=2 -DIMAGE_LOADER_EXTENSION=1 -DENABLE_REMOTING=1 -DENABLE_WEBRTC=1 -DUSE_PROPRIETARY_CODECS -DENABLE_PEPPER_CDMS -DENABLE_CONFIGURATION_POLICY -DENABLE_NOTIFICATIONS -DENABLE_HIDPI=1 -DUSE_UDEV -DENABLE_EGLIMAGE=1 -DENABLE_TASK_MANAGER=1 -DENABLE_EXTENSIONS=1 -DENABLE_PLUGINS=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_THEMES=1 -DENABLE_AUTOFILL_DIALOG=1 -DENABLE_BACKGROUND=1 -DENABLE_GOOGLE_NOW=1 -DCLD_VERSION=2 -DCLD2_DATA_SOURCE=static -DENABLE_FULL_PRINTING=1 -DENABLE_PRINTING=1 -DENABLE_SPELLCHECK=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_APP_LIST=1 -DENABLE_MANAGED_USERS=1 -DENABLE_MDNS=1 -DENABLE_SERVICE_DISCOVERY=1 -DHAS_OUT_OF_PROC_TEST_RUNNER -DGL_GLEXT_PROTOTYPES -DMOJO_USE_SYSTEM_IMPL -DLIBPEERCONNECTION_LIB=1 -DUSE_BRLAPI -DGTEST_HAS_POSIX_RE=0 -DNACL_WINDOWS=0 -DNACL_LINUX=1 -DNACL_OSX=0 -DNACL_ANDROID=0 -DNACL_TARGET_SUBARCH=64 -DNACL_TARGET_ARCH=x86 -DNACL_BUILD_SUBARCH=64 -DNACL_BUILD_ARCH=x86 -DAUTOFILL_ENABLE_SYNC -DSK_ENABLE_INST_COUNT=0 -DSK_SUPPORT_GPU=1 '-DGR_GL_CUSTOM_SETUP_HEADER="GrGLConfig_chrome.h"' -DSK_ENABLE_LEGACY_API_ALIASING=1 -DSK_ATTR_DEPRECATED=SK_NOTHING_ARG1 -DGR_GL_IGNORE_ES3_MSAA=0 -DSK_WILL_NEVER_DRAW_PERSPECTIVE_TEXT -DSK_SUPPORT_LEGACY_PICTURE_CLONE -DSK_SUPPORT_LEGACY_GETDEVICE -DSK_IGNORE_ETC1_SUPPORT -DSK_IGNORE_GPU_DITHER -DSK_USE_POSIX_THREADS -DSK_DEFERRED_CANVAS_USES_FACTORIES=1 -DPROTOBUF_USE_DLLS -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DUNIT_TEST -DGTEST_HAS_RTTI=0 -DHUNSPELL_STATIC -DHUNSPELL_CHROME_CLIENT -DUSE_HUNSPELL -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DU_STATIC_IMPLEMENTATION -DCHROME_PNG_WRITE_SUPPORT -DPNG_USER_CONFIG -DUSE_NSS=1 -DOS_CHROMEOS=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -Igen -I../.. -I../../skia/config -I../../third_party/khronos -I../../gpu -I../../third_party/WebKit/Source -I../../third_party/WebKit -Igen/chrome -I../../third_party/WebKit -I../../v8/include -I../../third_party/libwebp -I../../third_party/ots/include -I../../third_party/qcms/src -I../../third_party/iccjpeg -I../../third_party/libjpeg -Igen/policy -Igen/protoc_out -Igen/net -I../../third_party/skia/src/core -I../../third_party/skia/include/core -I../../third_party/skia/include/effects -I../../third_party/skia/include/pdf -I../../third_party/skia/include/gpu -I../../third_party/skia/include/lazy -I../../third_party/skia/include/pathops -I../../third_party/skia/include/pipe -I../../third_party/skia/include/ports -I../../third_party/skia/include/utils -I../../skia/ext -I../../third_party/protobuf -I../../third_party/protobuf/src -I../../testing/gmock/include -I../../testing/gtest/include -I../../third_party/icu/source/i18n -I../../third_party/icu/source/common -I../../third_party/libpng -I../../third_party/npapi -I../../third_party/npapi/bindings -I../../third_party/zlib -Igen/webkit -I../../net/third_party/nss/ssl -Igen/ash/resources -Werror -pthread -fno-exceptions -fno-strict-aliasing -Wall -Wno-unused-parameter -Wno-missing-field-initializers -fvisibility=hidden -pipe -fPIC -Wheader-hygiene -Wno-char-subscripts -Wno-unneeded-internal-declaration -Wno-covered-switch-default -Wstring-conversion -Wno-c++11-narrowing -Wno-reserved-user-defined-literal -Wno-deprecated-register -Xclang -load -Xclang /b/build/slave/Linux_ChromiumOS_Builder/build/src/tools/clang/scripts/../../../third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.so -Xclang -add-plugin -Xclang find-bad-constructs -fcolor-diagnostics -B/b/build/slave/Linux_ChromiumOS_Builder/build/src/third_party/binutils/Linux_x64/Release/bin -pthread -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/nss -I/usr/include/nspr -Wno-header-guard -m64 -march=x86-64 -O2 -fdata-sections -ffunction-sections -fno-slp-vectorize -funwind-tables -fno-rtti -fno-threadsafe-statics -fvisibility-inlines-hidden -Wsign-compare -std=gnu++11  -c ../../chrome/browser/chromeos/login/screenshot_tester.cc -o obj/chrome/browser/chromeos/login/interactive_ui_tests.screenshot_tester.o
../../chrome/browser/chromeos/login/screenshot_tester.cc:33:37:error: expected ';' after top level declarator
const char kUpdateMode[] = "update;"
                                    ^
                                    ;
../../chrome/browser/chromeos/login/screenshot_tester.cc:167:30:error: comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'int' [-Werror,-Wsign-compare]
  if (golden_screenshot_size == -1) {
      ~~~~~~~~~~~~~~~~~~~~~~ ^  ~~
../../chrome/browser/chromeos/login/screenshot_tester.cc:194:26:error: no member named 'config' in 'SkBitmap'
  ASSERT_EQ(model_bitmap.config(), sample_bitmap.config());
            ~~~~~~~~~~~~ ^
../../testing/gtest/include/gtest/gtest.h:1954:48: note: expanded from macro 'ASSERT_EQ'
# define ASSERT_EQ(val1, val2) GTEST_ASSERT_EQ(val1, val2)
                                               ^
../../testing/gtest/include/gtest/gtest.h:1937:55: note: expanded from macro 'GTEST_ASSERT_EQ'
                      EqHelper<GTEST_IS_NULL_LITERAL_(expected)>::Compare, \
                                                      ^
.

Original issue's description:
> Continues https://codereview.chromium.org/405093003, so general description is there.
> Now the testing mode has appeared: ScreenshotTester can now load the golden 
> screenshot from the disk and compare it to the screenshot taken right now.
> It still should be turned on with switches. To turn testing with screenshots on, 
> --enable-screenshot-testing-with-mode=MODE is used, where MODE can be "test" or "update". 
> "update" updates golden screenshot and requires --golden-screenshots-dir=DIR: place to store golden screenshots. "test" runs comparing golden 
> screenshot with current one, and --artifacts-dir=DIR can be used, where DIR is 
> the place to store screenshots that are different from golden ones if they exist,
>  and also an image representing difference between screenshots. If no 
> --artifacts-dir switch is found, these bugproofs are saved to the directory with 
> golden screenshots.
> 
> BUG=395653
> 
> Committed: https://src.chromium.org/viewvc/chrome?view=rev&revision=286880

TBR=ygorshenin@chromium.org,elizavetai@chromium.org
NOTREECHECKS=true
NOTRY=true
BUG=395653

Review URL: https://codereview.chromium.org/423713006

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@286886 0039d316-1c4b-4281-b951-d872f2087c98