Revert "Dismiss change password card conditionally"
This reverts commit 1d601d98917aacdd65072497f1e1f69801c220e7.

Reason for revert: Reason for revert: ChromePasswordProtectionServiceBrowserTest.VeriryUnhandledPasswordReuse
 failing on Win10 Tests x64:
[ RUN      ] ChromePasswordProtectionServiceBrowserTest.VeriryUnhandledPasswordReuse
[752:2488:0915/161445.604:WARNING:chrome_browser_main_win.cc(610)] Command line too long for RegisterApplicationRestart:  --brave-new-test-launcher --cfi-diag=0 --disable-browser-side-navigation --gtest_also_run_disabled_tests --gtest_filter=ChromePasswordProtectionServiceBrowserTest.VeriryUnhandledPasswordReuse --single_process --test-launcher-bot-mode --test-launcher-summary-output="C:\b\s\w\io0e96f7\output.json" --user-data-dir="C:\Users\CHROME~1\AppData\Local\Temp\scoped_dir5472_20927\d5472_6301" --disable-offline-auto-reload --no-first-run --no-default-browser-check --enable-logging=stderr --safebrowsing-disable-auto-update --disable-default-apps --wm-window-animations-disabled --disable-component-update --test-type=browser --force-color-profile=srgb --disable-zero-browsers-open-for-tests --ipc-connection-timeout=30 --allow-file-access-from-files --dom-automation --log-gpu-control-list-decisions --disable-backgrounding-occluded-windows --disable-gl-drawing-for-tests --override-use-software-gl-for-tests --force-color-profile=srgb --enable-features=PasswordProtectionGoogleBrandedPhishingWarning --disable-features=NetworkPrediction --flag-switches-begin --flag-switches-end --restore-last-session about:blank
[752:5528:0915/161446.715:WARNING:embedded_test_server.cc(229)] Request not handled. Returning 404: /
[752:5528:0915/161446.861:WARNING:embedded_test_server.cc(229)] Request not handled. Returning 404: /
../../chrome/browser/safe_browsing/chrome_password_protection_service_browsertest.cc(84): error:       Expected: 2u
      Which is: 2
To be equal to: service->unhandled_password_reuses().size()
      Which is: 1
../../chrome/browser/safe_browsing/chrome_password_protection_service_browsertest.cc(97): error: Value of: histograms_.GetAllSamples(kGaiaPasswordChangeHistogramName)
Expected: has 1 element that is equal to Bucket 2: 1
  Actual: { Bucket 1: 1 }, whose element #0 doesn't match
[752:2488:0915/161446.977:INFO:chrome_cryptauth_service.cc(222)] Profile is not authenticated yet; waiting before starting CryptAuth managers.
[  FAILED  ] ChromePasswordProtectionServiceBrowserTest.VeriryUnhandledPasswordReuse, where TypeParam =  and GetParam() =  (1779 ms)

Original change's description:
> Dismiss change password card conditionally
> 
> Change password card should be dismissed if there is no more unhandled
> password reuses. This could happen if:
> (1) user changed their Gaia password
> (2) user whitelisted all password reuses.
> 
> Bug: 761116
> Cq-Include-Trybots: master.tryserver.chromium.linux:closure_compilation
> Change-Id: Id36a463f87d468d5056c93c3778141e350816a06
> Reviewed-on: https://chromium-review.googlesource.com/653721
> Commit-Queue: Jialiu Lin <jialiul@chromium.org>
> Reviewed-by: Dave Schuyler <dschuyler@chromium.org>
> Reviewed-by: Ilya Sherman <isherman@chromium.org>
> Reviewed-by: Varun Khaneja <vakh@chromium.org>
> Reviewed-by: Nathan Parker <nparker@chromium.org>
> Reviewed-by: Luke Z <lpz@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#502397}

TBR=isherman@chromium.org,nparker@chromium.org,dschuyler@chromium.org,vakh@chromium.org,jialiul@chromium.org,lpz@chromium.org

# Not skipping CQ checks because original CL landed > 1 day ago.

Bug: 761116
Change-Id: I365ef41dd535a3a43b3dce8a2d0c68af91ef4d0b
Cq-Include-Trybots: master.tryserver.chromium.linux:closure_compilation
Reviewed-on: https://chromium-review.googlesource.com/670321
Commit-Queue: Max Morin <maxmorin@chromium.org>
Reviewed-by: Max Morin <maxmorin@chromium.org>
Cr-Commit-Position: refs/heads/master@{#502539}