Componentization: fix MultiColumnFragmentainerGroup.cpp's compile error when using msvc 2015.
Fixed error C2280: 'blink::MultiColumnFragmentainerGroup &blink::MultiColumnFragmentainerGroup::operator =(const blink::MultiColumnFragmentainerGroup &)': attempting to reference a deleted function.
This error is caused by auto-generated destructor of dll-exported class MultiColumnFragmentainerGroupList.
So explicitly implementing the destuctor fixes this compile error.

BUG=491988

Review URL: https://codereview.chromium.org/1159053002

git-svn-id: svn://svn.chromium.org/blink/trunk@196038 bbb929c8-8fbe-4397-9dbb-9b2b20218538