chrome_render_frame_observer clean up
ChromeRenderFrameObserver::OnRequestThumbnailForContextNode
renamed to RequestThumbnailForContextNode and moved to the mojom file,
but forgot to delete from chrome_render_frame_observer.h.
cl: https://codereview.chromium.org/2737893002/

Same thing happened on
ChromeRenderFrameObserver::OnSetClientSidePhishingDetection
in cl https://chromium-review.googlesource.com/c/chromium/src/+/584152/

ChromeRenderFrameObserver::CapturePageTextLater
https://codereview.chromium.org/1398823004/

Also clean up some compiler errors after delete functions above.
error: private field 'phishing_classifier_' is not used [-Werror,-Wunused-private-field]
  safe_browsing::PhishingClassifierDelegate* phishing_classifier_;

 error: function-like macro 'BUILDFLAG_INTERNAL_SAFE_BROWSING_CSD' is not defined

And also clean up some lint warnings.





clean up

Change-Id: Ie5e2409c6ff1ca1d9379b425ecac03c5d7183f79
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2115801
Reviewed-by: Scott Violet <sky@chromium.org>
Commit-Queue: Gang Wu <gangwu@chromium.org>
Cr-Commit-Position: refs/heads/master@{#752969}