Revert "Reland "RC: Connect the Local DB to TabHelper and add browsertests.""
This reverts commit bdb95bb929f0a6522d21fac95d1687e86ca3431a.

Reason for revert: crbug.com/855107

../../chrome/browser/resource_coordinator/local_site_characteristics_database_browsertest.cc:15:10: fatal error: 'chrome/browser/notifications/desktop_notification_profile_util.h' file not found
#include "chrome/browser/notifications/desktop_notification_profile_util.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Original change's description:
> Reland "RC: Connect the Local DB to TabHelper and add browsertests."
> 
> This is a reland of 8f4ffc9aee7851b534ff57b9a1a231c410673d9a with a fix
> for a flakiness in LocalSiteCharacteristicsDatabaseTest.PRE_ClearHistory,
> the HistoryService::Delete task didn't always had time to run before we
> assumed that the entry had been removed from the history, this fix this
> by running RunUntilIdle() several time (until the deletion has
> complete)
> 
> 
> 
> Original change's description:
> > RC: Connect the Local DB to TabHelper and add browsertests.
> >
> > Bug: 773382
> > Change-Id: Ie7cbbf2c74bfbf1f1522b2a1f775a392545ad0a9
> > Reviewed-on: https://chromium-review.googlesource.com/1088196
> > Commit-Queue: Sébastien Marchand <sebmarchand@chromium.org>
> > Reviewed-by: François Doray <fdoray@chromium.org>
> > Cr-Commit-Position: refs/heads/master@{#568519}
> 
> Bug: 773382
> Change-Id: I05072f974d70c200fff87e0239c8537c8d0bcfc8
> Reviewed-on: https://chromium-review.googlesource.com/1106940
> Commit-Queue: François Doray <fdoray@chromium.org>
> Reviewed-by: François Doray <fdoray@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#569311}

TBR=fdoray@chromium.org,sebmarchand@chromium.org

Change-Id: I7d78bd84033e6ad7ea2ff30be3f4b28d86ababd1
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 773382
Reviewed-on: https://chromium-review.googlesource.com/1110417
Reviewed-by: weiliangc <weiliangc@chromium.org>
Commit-Queue: weiliangc <weiliangc@chromium.org>
Cr-Commit-Position: refs/heads/master@{#569312}