Revert "WebUI: Enable running mocha-based automated tests on Android"
This reverts commit 507b2266cf1b0a639e54de0332fef6060db62a9f.

Reason for revert: compilation error

See: https://ci.chromium.org/ui/p/chrome/builders/ci/android-arm/43731/overview

ERROR at //chrome/test/data/webui/media_router/BUILD.gn:8:1: Assertion failed.
assert(!is_android)
^-----
See //chrome/test/data/webui/BUILD.gn:597:15: which caused the file to be included.
    deps += [ "media_router:build_grdp" ]
              ^------------------------
GN gen failed: 1


Original change's description:
> WebUI: Enable running mocha-based automated tests on Android
>
> Update WebUIMochaBrowserTest and build files as needed to support
> running mocha-based WebUI tests on Android builds, and add tests
> for the cross-platform chrome://flags UI to such builds.
>
> Bug: 40108641
> Change-Id: Ifda1209760a8b3d82569a47de1e23768f5bde8b8
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6237021
> Reviewed-by: Demetrios Papadopoulos <dpapad@chromium.org>
> Reviewed-by: Andrew Grieve <agrieve@chromium.org>
> Commit-Queue: Rebekah Potter <rbpotter@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1418688}

Bug: 40108641
Change-Id: Ib5c498e46e4b183ae781f497e8931df1ae7191a2
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6254477
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Owners-Override: Lijin Shen <lazzzis@google.com>
Commit-Queue: Lijin Shen <lazzzis@google.com>
Cr-Commit-Position: refs/heads/main@{#1418728}