libstdc++: do not use const type as member of std::vector in messaging layer report client.
Fix the error found compiling with libstdc++:
../../chrome/browser/policy/messaging_layer/public/report_client.cc:174:38:   required from here
/usr/include/c++/9/bits/stl_vector.h:398:66: error: static assertion failed: std::vector must have a non-const, non-volatile value_type

Bug: 957519
Change-Id: I8b8a306d841636882c7563edf9cdfc58464bc545
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2358737
Reviewed-by: Zach Trudo <zatrudo@google.com>
Commit-Queue: José Dapena Paz <jdapena@igalia.com>
Cr-Commit-Position: refs/heads/master@{#798672}