Revert "Make protobuf enums canonical for ReadState/WriteState/ConnectState."
This reverts commit f1624ddce4b88a5a950f65b511677b914c9caefb.

Broke Google Chrome ChromeOS compile:

http://build.chromium.org/p/chromium.chrome/builders/Google%20Chrome%20ChromeOS/builds/72048/steps/compile/logs/stdio

In file included from gen/extensions/browser/api/generated_api_registration.cc:20:
In file included from ../../extensions/browser/api/cast_channel/cast_channel_api.h:16:
../../extensions/browser/api/cast_channel/cast_socket.h:19:10: fatal error: 'extensions/browser/api/cast_channel/logging.pb.h' file not found
         ^

(Manually reverted because of file add.)

TBR=kmarshall@chromium.org
BUG=

Review URL: https://codereview.chromium.org/588433002

Cr-Commit-Position: refs/heads/master@{#295611}