Revert "Reland "Android: Merge filter_zip.py step into compile_java.py step""
This reverts commit 560a6781b2bb987d385cc9f7d69bd53f838c28aa.

Reason for revert: Dex error still happening:
com.android.tools.r8.errors.CompilationError: Absent Code attribute in method that is not native or abstract


Bug: 398002893
Original change's description:
> Reland "Android: Merge filter_zip.py step into compile_java.py step"
>
> This reverts commit 5840f11d9ac58b39f3f934aaddb078429260511a.
>
> Reason for reland: Fixed prebuilts with filters.
>
> Bug: 398002893
> Original change's description:
> > Revert "Android: Merge filter_zip.py step into compile_java.py step"
> >
> > This reverts commit 57825c3bb5083df80f4999ac78f1613c69fc906c.
> >
> > Reason for revert: Internal bots failing on R8 step with:
> > com.android.tools.r8.errors.CompilationError: Absent Code attribute in method that is not native or abstract
> >
> > E.g.:
> > https://ci.chromium.org/ui/p/chrome/builders/ci/android-arm64-high/29753/overview
> >
> > Bug: 398002893
> > Original change's description:
> > > Android: Merge filter_zip.py step into compile_java.py step
> > >
> > > Saves an action for every android_library target.
> > >
> > > Number of GN targets for debug android: 58689 -> 57994
> > > Size of build.ninja: 806741686 -> 798996799 (about -7.5mb)
> > >
> > > Might break "bytecode_rewriter_target", but there are no current
> > > uses of it to test it...
> > >
> > > This combines "device_jar_path" and "host_jar_path" into a single
> > > "processed_jar_path", since the processing of both are identical.
> > >
> > > Bug: 398002893
> > > Change-Id: Ia5ad8a136edd64175e04ab069762862d8c5abba9
> > > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6443997
> > > Reviewed-by: Sam Maier <smaier@chromium.org>
> > > Commit-Queue: Andrew Grieve <agrieve@chromium.org>
> > > Cr-Commit-Position: refs/heads/main@{#1450203}
> >
> > Bug: 398002893
> > No-Presubmit: true
> > No-Tree-Checks: true
> > No-Try: true
> > Change-Id: I8ce76363a3488ada3a920bc874301d5f85c6f449
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6481068
> > Auto-Submit: Andrew Grieve <agrieve@chromium.org>
> > Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
> > Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
> > Cr-Commit-Position: refs/heads/main@{#1450313}
>
> Bug: 398002893
> Change-Id: I508d26db4437fff615a82f80a7d711a6e532d4b8
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6479447
> Commit-Queue: Andrew Grieve <agrieve@chromium.org>
> Reviewed-by: Yaron Friedman <yfriedman@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1450525}

Bug: 398002893
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Change-Id: Ia0469e6e97c6044509e469fb560f7a96bc7ebd88
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6485453
Auto-Submit: Andrew Grieve <agrieve@chromium.org>
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Cr-Commit-Position: refs/heads/main@{#1450899}