Remove trailing garbage from bisect-builds.py
  File "tools/bisect-builds.py", line 897
    return m.group(1)]
                     ^
SyntaxError: invalid syntax

(introduced in http://crrev.com/2136353002)

R=dpranke@chromium.org,thakis@chromium.org
NOTRY=true

Review-Url: https://codereview.chromium.org/2146583002
Cr-Commit-Position: refs/heads/master@{#404847}