[Fuzzing] Set a value for android_static_analysis on fuzzing builders
Builds are failing since android_static_analysis is not explicitely set,
see
ci.chromium.org/ui/p/chromium/builders/ci/android-x64-libfuzzer-asan/7490/overview
We set it to false for a faster build.

Additionally, when testing this, we discovered the try bots wasn't
applying the proper recipe.

And another error, which is due to the minimum android sdk version we
force (and is not anymore defaulted to 29).
../../base/containers/vector_buffer.h:126:9: error: '~PendingEncode' is
only available on Android 29 or newer [-Werror,-Wunguarded-availability]

[1] https://cr-buildbucket.appspot.com/build/8703533368392085041

Bug: 328559555
Change-Id: I2161dd9ff5b9bec026f63bcf3ab2f515ff8d7288
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6948065
Commit-Queue: Yuly Novikov <ynovikov@chromium.org>
Auto-Submit: Pâris Meuleman <pmeuleman@chromium.org>
Reviewed-by: Yuly Novikov <ynovikov@chromium.org>
Reviewed-by: Ali Hijazi <ahijazi@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1517466}