Gracefully handle `manual` mode when only minor version updates happen.
We recommend to use `single` mode to update a minor version of a single
crate, but in some scenarios `manual` mode may be more appropriate
(e.g. when updating minor versions of multiple crates in a single CL).
Before this CL, using `manual` mode in this way may have resulted in
a non-zero exit code from `git commit` when the commit is empty:

```
  Removing //third_party/rust/.../<old_epoch> ...
ERROR: Failure when running: git commit -m Removing //third_party/rust/.../<old_epoch>
On branch rollFontationsShapingAutohint
Your branch is ahead of 'origin/main' by 3 commits.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean

Traceback (most recent call last):
  File "tools/crates/create_update_cl.py", line 779, in <module>
    sys.exit(main())
  File "tools/crates/create_update_cl.py", line 773, in main
    args.func(args)
  File "tools/crates/create_update_cl.py", line 697, in ManualUpdate
    GitCommit(args, "Removing //third_party/rust/.../<old_epoch>")
  File "tools/crates/create_update_cl.py", line 567, in GitCommit
    Git("commit", "-m", title)
  File "tools/crates/create_update_cl.py", line 92, in Git
    return RunCommandAndCheckForErrors(['git'] + list(args),
  File "tools/crates/create_update_cl.py", line 86, in RunCommandAndCheckForErrors
    raise RuntimeError(f"Failure when running {args[0]}")
RuntimeError: Failure when running git
```

After this CL, the error above should be avoided.

This CL has been tested manually (this script doesn't have CI coverage):

* Run `tools/crates/create_update_cl_unittests.py`
* Tried the following steps:
    - `git checkout -b skrifa-test`
    - Edit `chromium_crates_io/Cargo.toml` to change the required version
      of `read-fonts` and `skrifa` from `0.22` to `0.22.1`
    - `git commit -m .'
    - `tools/crates/create_update_cl.py
      --no-upload manual --title 'Skrifa test'`

Bug: None
Change-Id: Ida4b1606294da29a12e2d26a2a4bc3d293552110
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5901117
Reviewed-by: danakj <danakj@chromium.org>
Commit-Queue: Łukasz Anforowicz <lukasza@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1362592}