Revert "Stop sending XRDeviceId with VRDisplayInfo"
This reverts commit 67468f6697ae537535f28b9ca9a1f0aaeab7ed51.

Reason for revert: causes win-chrome builds to fail:
[10171/23886] CXX obj/device/vr/vr/oculus_device.obj
FAILED: obj/device/vr/vr/oculus_device.obj
c:\b\s\w\ir\cache\goma\client\gomacc.exe ..\..\third_party\llvm-build\Release+Asserts\bin\clang-cl.e...(too long)
../../device/vr/oculus/oculus_device.cc(65,17): error: no member named 'id' in 'device::mojom::VRDisplayInfo'
display_info->id = id;
~~~~~~~~~~~~~~^
1 error generated.

https://ci.chromium.org/p/chrome/builders/ci/win-chrome

Original change's description:
> Stop sending XRDeviceId with VRDisplayInfo
>
> This value is not used by Blink, and does not need to be communicated
> over the mojo interface. The XRDeviceId enum should not be removed
> because it is used for usage stats.
>
> Bug: 1017477
> Change-Id: I5e8cfff00c374f48495290c5dfb8911a1824a2de
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2424684
> Reviewed-by: Alexander Cooper <alcooper@chromium.org>
> Reviewed-by: Chris Palmer <palmer@chromium.org>
> Auto-Submit: Brandon Jones <bajones@chromium.org>
> Commit-Queue: Brandon Jones <bajones@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#810958}

TBR=palmer@chromium.org,bajones@chromium.org,bialpio@chromium.org,alcooper@chromium.org

# Not skipping CQ checks because original CL landed > 1 day ago.

Bug: 1017477
Change-Id: Ic5db77eb272086c7e51c900e8f23f722209dedb3
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2434019
Commit-Queue: Balazs Engedy <engedy@chromium.org>
Reviewed-by: Johann Koenig <johannkoenig@google.com>
Cr-Commit-Position: refs/heads/master@{#811183}