schema_org: Replace uses of has_key() with 'in' operator
has_key() has been removed in Python 3.
Use the 'in' operator which works in both Python 2 and 3.

Traceback (most recent call last):
  File "../../components/schema_org/generate_schema_org_code.py", line 148, in <module>
    sys.exit(main())
  File "../../components/schema_org/generate_schema_org_code.py", line 139, in main
    template_vars = get_template_vars(args.schema_file)
  File "../../components/schema_org/generate_schema_org_code.py", line 111, in get_template_vars
    template_vars['properties'].append(parse_property(thing, schema))
  File "../../components/schema_org/generate_schema_org_code.py", line 72, in parse_property
    if not prop.has_key(schema_org_id('rangeIncludes')):
AttributeError: 'dict' object has no attribute 'has_key'

Bug: 941669
Change-Id: I29f7ac1e7c1aca7275412c068a59070f4c18f69b
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2124609
Auto-Submit: Raul Tambre <raul@tambre.ee>
Commit-Queue: Tommy Steimel <steimel@chromium.org>
Reviewed-by: Tommy Steimel <steimel@chromium.org>
Cr-Commit-Position: refs/heads/master@{#754630}