Revert "Add edit and remix support."
This reverts commit a6d04bdca966f1b1e1cb4fc9144b95833c753196.

Reason for revert: Suspected of causing compile failures on multiple bots: https://ci.chromium.org/ui/p/chromium/builders/ci/Linux%20MSan%20Builder/114933/overview, https://ci.chromium.org/ui/p/chromium/builders/ci/linux-archive-rel/170104/overview:

gen/chrome/test/data/webui/skills/preprocessed/skills_dialog_test.ts:30:11 - error TS2741: Property 'description' is missing in type '{ id: string; name: string; icon: string; prompt: string; source: SkillSource.MIN_VALUE; creationTime: { internalValue: bigint; }; lastUpdateTime: { internalValue: bigint; }; }' but required in type 'SkillMojoType'.

Original change's description:
> Add edit and remix support.
>
> If the initial skill doesn't have an id (empty skill) or is from a first
> party source, the user is creating a new skill. In other cases, they are
> editing an existing skill of theirs.
>
> Set dialog header and submitSkill's ID accordingly.
>
> Bug: b:477385216
> Change-Id: Ia785442760fe31c20113d3b47cd4f9c8621d0c0d
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7529321
> Commit-Queue: marissa shen <marissashen@google.com>
> Reviewed-by: Christine Ying <chrstne@google.com>
> Reviewed-by: Michelle Abreo <michelleabreo@google.com>
> Cr-Commit-Position: refs/heads/main@{#1580245}

No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: b:477385216
Change-Id: Ic291d9b5bfb246e79683aaf3a6ac47d8a960929f
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7547829
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Stephen McGruer <smcgruer@chromium.org>
Auto-Submit: Stephen McGruer <smcgruer@chromium.org>
Owners-Override: Stephen McGruer <smcgruer@chromium.org>
Commit-Queue: Khalid Peer <khalidpeer@chromium.org>
Reviewed-by: Khalid Peer <khalidpeer@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1580263}