Revert of Use template specialization to generate WindowProperty code (patchset #8 id:330001 of https://codereview.chromium.org/801953002/)
Reason for revert:
This is breaking chrome on chrome os builds:

In file included from ../../ui/aura/client/screen_position_client.cc:7:0:
../../ui/aura/window_property.h:115:58: error: specialization of 'template<class T> void aura::Window::SetProperty(const aura::WindowProperty<T>*, T)' in different namespace [-fpermissive]
         const aura::WindowProperty<T >* property, T value) {  \
                                                          ^
../../ui/aura/window_property.h:127:5: note: in expansion of macro 'DECLARE_EXPORTED_WINDOW_PROPERTY_TYPE'
     DECLARE_EXPORTED_WINDOW_PROPERTY_TYPE(, T)
     ^
../../ui/aura/client/screen_position_client.cc:9:1: note: in expansion of macro 'DECLARE_WINDOW_PROPERTY_TYPE'
 DECLARE_WINDOW_PROPERTY_TYPE(aura::client::ScreenPositionClient*)
 ^
In file included from ../../ui/aura/client/screen_position_client.h:9:0,
                 from ../../ui/aura/client/screen_position_client.cc:5:
../../ui/aura/window.h:297:8: error:   from definition of 'template<class T> void aura::Window::SetProperty(const aura::WindowProperty<T>*, T)' [-fpermissive]
   void SetProperty(const WindowProperty<T>* property, T value);
        ^

Original issue's description:
> Use template specialization to generate WindowProperty code.
>
> They used to be a inlined function in the header, which led to code generation when method is used. This changes the code generation only in DECLARE_WINDOW_PROPERTY_TYPE().
>
> BUG=None
> R=sadrul@chromium.org
>
> Committed: https://crrev.com/f62e152bb7a13135a597d9766eb79551d3a24a73
> Cr-Commit-Position: refs/heads/master@{#309252}

TBR=sadrul@chromium.org,sky@chromium.org,oshima@chromium.org
NOTREECHECKS=true
NOTRY=true
BUG=None

Seems like nobody is around. LGTM. I'm broken by this as well.

Review URL: https://codereview.chromium.org/814313002

Cr-Commit-Position: refs/heads/master@{#309285}