Revert "Add show notification performer."
This reverts commit 999cdb18f1699fab03c862f17e360b023b80a0aa.

Reason for revert: 
Compile failure: https://ci.chromium.org/ui/p/chromium/builders/ci/Linux%20Chromium%20OS%20ASan%20LSan%20Builder/86754/overview
CXX obj/chrome/browser/ash/unit_tests/show_notification_action_performer_unittest.o
../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/chrome/browser/ash/unit_tests/...(too long)
../../chrome/browser/ash/growth/show_notification_action_performer_unittest.cc:48:3: error: non-virtual member function marked 'override' hides virtual member function
   48 |   MOCK_METHOD(void, OnButtonPressed, (int, CampaignButtonId), (override));
      |   ^
../../third_party/googletest/src/googlemock/include/gmock/gmock-function-mocker.h:115:3: note: expanded from macro 'MOCK_METHOD'
  115 |   GMOCK_PP_VARIADIC_CALL(GMOCK_INTERNAL_MOCK_METHOD_ARG_, __VA_ARGS__) \
      |   ^


Original change's description:
> Add show notification performer.
>
> This CL added basic tests. More tests will be added in a follow up CL.
>
> Bug: b/330245345
> Change-Id: Ie74cd7a7c8bce21d5c657ecfd3f763cf5c14c9a0
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5399131
> Reviewed-by: Tao Wu <wutao@chromium.org>
> Commit-Queue: Li Lin <llin@chromium.org>
> Reviewed-by: Yoshiki Iguchi <yoshiki@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1280948}

Bug: b/330245345
Change-Id: Ic4a217e1b42bf571005ea60c992d4bea43f284ba
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5401510
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Auto-Submit: Alan Cutter <alancutter@google.com>
Owners-Override: Alan Cutter <alancutter@google.com>
Commit-Queue: Alan Cutter <alancutter@google.com>
Cr-Commit-Position: refs/heads/main@{#1280950}