Revert of Remove scoped styles. (https://codereview.chromium.org/310443002/)
Reason for revert:
Broke every incremental compile bot on the waterfall:

InternalRuntimeFlags.h: In member function 'bool WebCore::InternalRuntimeFlags::styleScopedEnabled()':
InternalRuntimeFlags.h:110:40: error: 'styleScopedEnabled' is not a member of 'WebCore::RuntimeEnabledFeatures'
     bool styleScopedEnabled() { return RuntimeEnabledFeatures::styleScopedEnabled(); }

While a clobber build indeed fixes the problem, it also breaks local
builds, which increases the cost of this CL significantly. Let's try
to find a proper solution in the bug.

BUG=381111

Original issue's description:
> Remove scoped styles.
> 
> Removes <style scoped>.
> 
> This was discussed and approved with LGTMs in blink-dev:
> https://groups.google.com/a/chromium.org/d/msg/blink-dev/R1x18ZLS5qQ/Bjuh_cENhlQJ
> 
> Chrome status dashboard entry:
> http://www.chromestatus.com/features/5374137958662144
> 
> Note:
> this is based on esprehn's original cl:
> https://codereview.chromium.org/214693002/
> 
> BUG=379096
> TEST=pass all layout tests
> 
> Committed: https://src.chromium.org/viewvc/blink?view=rev&revision=175555

TBR=esprehn@chromium.org,tasak@google.com,kochi@chromium.org
NOTREECHECKS=true
NOTRY=true
BUG=379096

Review URL: https://codereview.chromium.org/315173002

git-svn-id: svn://svn.chromium.org/blink/trunk@175561 bbb929c8-8fbe-4397-9dbb-9b2b20218538