[Files F2] Fix "Play files has no expand icon after mounting" bug
Previously we only did partial scan for navigation root items
because usually non-root item's partial scan will be handled when
root item is expanded. However, "Play files/Crostini" is an
exception: they can be mounted when MyFiles is already expanded.
This CL adds another condition to scan non-root items: only when
their parent item is expanded.

A browser test is added to test Crostini.

Bug: b:318785091
Test: browser_tests --gtest_filter="*mountCrostiniWithSubFolder*"
Change-Id: I095898ceabe67a290e2cc2f5af73a02b4871fe31
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5171956
Reviewed-by: Luciano Pacheco <lucmult@chromium.org>
Commit-Queue: Wenbo Jie <wenbojie@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1243913}