chromecast: Fix warnings [unused-function]
../../chromecast/media/cma/backend/volume_control.cc:57:7: error: unused function 'DbFsToScale' [-Werror,-Wunused-function]
float DbFsToScale(float db) {
      ^
1 error generated.

Bug: b/152723969
Test: Cast CQ
Change-Id: Ie8553fbf2c5b537d8e493d652e442bb6199030a0
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2130772
Reviewed-by: Daniel Nicoara <dnicoara@chromium.org>
Commit-Queue: Michael Spang <spang@chromium.org>
Cr-Commit-Position: refs/heads/master@{#755093}