[DSE] Fix browser_test failures from NewTabUrlSearchEngineUrlAndroid experiment.
Recently multiple tests in browser_test has failing with the message
  java.lang.AssertionError: Unexpected call of recreate() in
browser_test.

Per crbug.com/1359066, this is due to ChromeTabbedActivity#recreate()
being called by ToolbarManger when the Start Surface is enabled,
followed by change in a11y or homepage status. The problem is also
flakily triggered by recent NewTabUrlSearchEngineUrlAndroid experiment
(crrev.com/c/4998547), and admits local repro by forcing
  DseNewTabUrlManager.isNewTabSearchEngineUrlAndroidEnabled()
to always return true.

This CL fixes the failures by disabling the recreate() on Android (per
crbug.com/1359066) for:
  InstallableManagerBrowserTest

crrev.com/c/5007820 fixes the following:
  SearchPreloadUnifiedBrowserTest
  SearchPreloadUnifiedFallbackBrowserTest

crrev.com/c/5008115 fixes the following:
  PrerenderOmniboxSearchSuggestionExpiryBrowserTest
  PrerenderOmniboxSearchSuggestionReloadBrowserTest

Fixed: 1499299
Change-Id: I5d1176e5550c123016a2962b2e6373a7641e1b55
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5009734
Reviewed-by: Xi Han <hanxi@chromium.org>
Reviewed-by: Mike Wasserman <msw@chromium.org>
Commit-Queue: Xi Han <hanxi@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1221351}