Revert of Make character composition platform-independent. (patchset #5 id:50001 of https://codereview.chromium.org/1215723003/)
Reason for revert:
Caused compile error on "Linux ChromiumOS GN" bot:

[2174/2427] STAMP obj/media/test/pipeline_integration_tests.stamp
FAILED: /b/build/goma/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -shared -Wl,--fatal-warnings -m64 -fPIC -Wl,-z,noexecstack -Wl,-z,now -Wl,-z,relro -Wl,-z,defs -pthread -B../../third_party/binutils/Linux_x64/Release/bin -fuse-ld=gold -Wl,--icf=all -o ./libui_base_ime.so -Wl,-soname=libui_base_ime.so @./libui_base_ime.so.rsp && { readelf -d ./libui_base_ime.so | grep SONAME ; nm -gD -f p ./libui_base_ime.so | cut -f1-2 -d' '; } > ./libui_base_ime.so.tmp && if ! cmp -s ./libui_base_ime.so.tmp ./libui_base_ime.so.TOC; then mv ./libui_base_ime.so.tmp ./libui_base_ime.so.TOC; fi
../../ui/base/ime/chromeos/character_composer.cc:79: error: undefined reference to 'ui::KeycodeConverter::IsDomKeyForModifier(ui::DomKey)'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

Original issue's description:
> Make character composition platform-independent.
>
> Replaces composition based on X11 KeySym using GTK tables, with
> composition based on DOM UI Events |key| using in-tree tables.
>
> The source form of composition data is |character_composer_sequences.txt|,
> which was constructed from the previous GTK data array, converted from
> X11 KeySym values to DOM UI Events |key| and Unicode character values,
> modified according to the previously-hardcoded exceptions (e.g. cedilla).
>
> The composition data is converted to a tree stored in a compact array.
> This representation is simpler to test than the GTK data, and actually
> ends up slightly smaller.
>
> After this, it should be possible to remove //third_party/gtk+/.
>
> BUG=442757
> TEST=unit tests and manual tests on Ozone/Freon and X11.
>
> Committed: https://crrev.com/277dc707035a2a88d63ab8f1d60739ee90adbae6
> Cr-Commit-Position: refs/heads/master@{#338168}

TBR=shuchen@chromium.org,yukishiino@chromium.org,sadrul@chromium.org,kpschoedel@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=442757

Review URL: https://codereview.chromium.org/1231843004

Cr-Commit-Position: refs/heads/master@{#338181}