Revert "Migrate PolicyConversionClient to use Value::Dict and Value::List"
This reverts commit 139e9b763cf15e9c5c363eb20d9e5880142f64c1.

Reason for revert: Windows builders on perf waterfall started failing. 
E.g.: https://ci.chromium.org/ui/p/chrome/builders/ci/win64-builder-perf/421215/overview

../../components/policy/core/browser/policy_conversions_client.cc(429,32): error: return type of out-of-line definition of 'policy::PolicyConversionsClient::GetUpdaterPolicies' differs from that in the declaration
Value PolicyConversionsClient::GetUpdaterPolicies() {
~~~~~                          ^
../..\components/policy/core/browser/policy_conversions_client.h(72,21): note: previous declaration is here
  base::Value::Dict GetUpdaterPolicies();
  ~~~~~~~~~~~~~~~~~ ^
../../components/policy/core/browser/policy_conversions_client.cc(431,14): error: incompatible operand types ('Value::Dict' and 'base::Value')
             ? GetPolicyValues(*updater_policies_, nullptr, PoliciesSet(),
             ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.

Original change's description:
> Migrate PolicyConversionClient to use Value::Dict and Value::List
>
> Migrate PolicyConversion and PolicyConversionClient to use
> base::Value::Dict and base::Value::List as they were using deprecated
> base::Value::Type. Update the return types of the functions from
> base::Value to more specific types as suggested by new base/values.h
> documentation.
>
> Bug: chromium:1319360
> Change-Id: I17a004e2a22d02ac62d74097d1c1edd8ee73cac1
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3613733
> Reviewed-by: Roland Bock <rbock@google.com>
> Reviewed-by: Pavol Marko <pmarko@chromium.org>
> Commit-Queue: Irem Uguz <iremuguz@google.com>
> Cr-Commit-Position: refs/heads/main@{#998414}

Bug: chromium:1319360
Change-Id: I3369625fff307963afc308b1e6269eb4d2ab0ac7
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3621734
Auto-Submit: Wenbin Zhang <wenbinzhang@google.com>
Reviewed-by: Erik Chen <erikchen@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Reviewed-by: Nicolas Ouellet-Payeur <nicolaso@chromium.org>
Commit-Queue: Erik Chen <erikchen@chromium.org>
Cr-Commit-Position: refs/heads/main@{#998496}