Android: Better error messages for ABI mismatch (reland)
Fix:
- When an app's supported lib list is empty, it means that it does not
  have a native library. Allow all devices in that case.

Instead of relying on catapult or adb to raise errors, most of which are
not easily translated to an ABI mismatch issue, manually filter devices
in apk_operations.py in order to provide informative error messages when
there are no valid devices to install a given apk or bundle. Some
combinations are listed below, as well as whether they work or have an
error message.

Example devices (ABI lists via ro.product.cpu.abilist):
- emulator API 28 for x86 device, supports: ['x86', 'armeabi-v7a', 'armeabi']
  - filtered to just ['x86']
- emulator API 33 for x64 device, supports: ['x86_64']
- pixel 4A for arm64 device, supports: ['arm64-v8a', 'armeabi-v7a', 'armeabi']

Example: Installing trichrome_chrome_bundle with target_cpu="arm" to x86 device
Exception: Cannot find any supported devices for this app.

The device (serial=emulator-5554) is not supported because none of the app's ABIs (arm64-v8a,armeabi-v7a) match this device's ABIs (x86), you may need to set target_cpu="x86" in your args.gn.

Bug: 1335139
Change-Id: Ibd33f274309c62fbb0c33f9d31346be86629745e
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4883389
Commit-Queue: Andrew Grieve <agrieve@chromium.org>
Commit-Queue: Peter Wen <wnwen@chromium.org>
Auto-Submit: Peter Wen <wnwen@chromium.org>
Reviewed-by: Andrew Grieve <agrieve@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1199563}