Revert of Replace ICU with CED for auto encoding detection (patchset #4 id:120001 of https://codereview.chromium.org/2081653007/ )
Reason for revert:
This seems to have broken compile on Windows 8:

[46/8396] CXX obj\third_party\ced\src\compact_enc_det\ced.compact_enc_det_hint_code.obj
FAILED: obj/third_party/ced/src/compact_enc_det/ced.compact_enc_det_hint_code.obj
ninja -t msvc -e environment.x86 -- C:\b\build\slave\cache\cipd\goma/gomacc "C:\b\depot_tools\win_toolchain\vs_files\95ddda401ec5678f15eeed01d2bee08fcbc5ee97\VC\bin\amd64_x86\cl.exe" /nologo /showIncludes /FC @obj\third_party\ced\src\compact_enc_det\ced.compact_enc_det_hint_code.obj.rsp /c ..\..\third_party\ced\src\compact_enc_det\compact_enc_det_hint_code.cc /Foobj\third_party\ced\src\compact_enc_det\ced.compact_enc_det_hint_code.obj /Fdobj\third_party\ced\ced.cc.pdb
c:\b\build\slave\win8_gyp\build\src\third_party\ced\src\compact_enc_det\compact_enc_det_hint_code.cc(122): error C2220: warning treated as error - no 'object' file generated
c:\b\build\slave\win8_gyp\build\src\third_party\ced\src\compact_enc_det\compact_enc_det_hint_code.cc(122): warning C4018: '<': signed/unsigned mismatch
c:\b\build\slave\win8_gyp\build\src\third_party\ced\src\compact_enc_det\compact_enc_det_hint_code.cc(151): warning C4018: '<': signed/unsigned mismatch
c:\b\build\slave\win8_gyp\build\src\third_party\ced\src\compact_enc_det\compact_enc_det_hint_code.cc(169): warning C4018: '<': signed/unsigned mismatch

https://build.chromium.org/p/chromium.win/builders/Win8%20GYP/builds/89

Original issue's description:
> Replace ICU with CED for auto encoding detection
>
> This is a drop-in replacement of ICU library performing automatic text
> encoding detection with CED (Compact Encdoing Detection).
>
> CED is used extensively in Google for every crawled web page,
> email message, query string, etc., and recently open-sourced for
> public use. (https://github.com/google/compact_enc_det)
>
> Also it is a much better alternative to ICU in terms of speed.
> ICU introduces significant regression in page loading (up to 30%):
>
> = ICU auto-detection vs. TOT =
> page_cycler.typical_25:cold_times.page_load_time 1085.13±9.31% 754.28±12.03% (30.49%)
>
> http://storage.googleapis.com/chromium-telemetry/html-results/results-2016-05-08_21-20-58
>
> while CED adds virtually no additional loading time (delta < sigma):
>
> = CED auto-detection vs. TOT =
> page_cycler.typical_25:cold_times.page_load_time ms 705.70±9.49% vs. 760.31±11.90% (-7.74%)
>
> http://storage.googleapis.com/chromium-telemetry/html-results/results-2016-05-08_20-37-54
>
> With CED, it is feasible to turn on auto encoding detection by default
> so that web pages without encoding label can be taken care of. It will be
> done in a follow-up CL.
>
> BUG=597488
>
> Committed: https://crrev.com/13510755ac11e6e1f58c34ef8c9bd4cf925c8d70
> Cr-Commit-Position: refs/heads/master@{#402622}

TBR=tkent@chromium.org,jshin@chromium.org,jinsukkim@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=597488

Review-Url: https://codereview.chromium.org/2109633003
Cr-Commit-Position: refs/heads/master@{#402652}