LayoutNG: Move algorithm output stuff out from layout/ng/
This CL moves the following files from layout/ng/ to layout/, with
removing "ng_" prefixes:

* ng_ink_overflow*.*
* ng_layout_overflow_calculator.*
  Exception: renamed to scrollable_overflow_calculator.*
* ng_layout_result*.*
* ng_link.h
  Exception: renamed to physical_fragment_link.h
* ng_outline_type.h
* ng_outline_utils.*
* ng_physical_box_fragment*.*
* ng_physical_fragment*.*
* ng_text_decoration_offset.*
* physical_fragment_rare_data.*

This CL has no behavior changes.

Bug: 1492009
Change-Id: I3e03aa7610d5715b704212cd0f44a52c47082135
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5075374
Reviewed-by: Koji Ishii <kojii@chromium.org>
Commit-Queue: Kent Tamura <tkent@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1231170}