Fix third_party/blink/renderer/platform/heap:test_support DEPS
test_support depends on third_party/blink/renderer/platform:bindings_buildflags,
because (snip)/platform/heap/name_traits.h includes bindings/name_client.h and the name_client.h includes (snip)/platform/bindings/buildflags.h.

Sample build to be fixed by this CL: https://ci.chromium.org/p/chromium/builders/ci/mac-archive-rel/5277

Sample log:
https://logs.chromium.org/logs/chromium/buildbucket/cr-buildbucket.appspot.com/8900748397429231616/+/steps/compile/0/stdout?format=raw

In file included from ../../third_party/blink/renderer/platform/heap/heap_test_utilities.cc:7:
In file included from ../../third_party/blink/renderer/platform/heap/heap_test_utilities.h:15:
In file included from ../../third_party/blink/renderer/platform/heap/handle.h:35:
In file included from ../../third_party/blink/renderer/platform/heap/heap.h:40:
In file included from ../../third_party/blink/renderer/platform/heap/gc_info.h:11:
In file included from ../../third_party/blink/renderer/platform/heap/name_traits.h:9:
../../third_party/blink/renderer/platform/bindings/name_client.h:9:10: fatal error: 'third_party/blink/renderer/platform/bindings/buildflags.h' file not found
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         1 error generated.

Change-Id: Ib8b63d59fff2d9c828644e470101d9202453e5a8
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1833348
Reviewed-by: Kentaro Hara <haraken@chromium.org>
Commit-Queue: Takashi Sakamoto <tasak@google.com>
Cr-Commit-Position: refs/heads/master@{#701904}