Revert 173994
Broke build on Chromium OS (amd64) ASAN and Chromium OS (x86) ASAN

chromeos-chrome-26.0.1366.0_alpha-r1: /usr/x86_64-pc-linux-gnu/i686-pc-linux-gnu/binutils-bin/2.21/ld.gold.real: c/Release/obj.target/content/libcontent_common.a(c/Release/obj.target/content/../content_common/content/common/sandbox_linux.o): in function content::LinuxSandbox::PreinitializeSandboxBegin():content/common/sandbox_linux.cc:106: error: undefined reference to '__sanitizer_sandbox_on_notify'

> Use __sanitizer_sandbox_on_notify() to tell ASan the sandbox is about to be turned on.
> 
> Review URL: https://chromiumcodereview.appspot.com/11565013

TBR=glider@chromium.org
Review URL: https://codereview.chromium.org/11635040

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@174109 0039d316-1c4b-4281-b951-d872f2087c98