Revert "Add config for WebViewOriginTrial before going to beta"
This reverts commit 95d1afd8b26d5beab5a8d53f034364b5eb2f5a3c.

Reason for revert:
https://ci.chromium.org/ui/p/chrome/builders/ci/android-go_webview-perf/35612/overview
Builds started failing on this exception:
Exception: Conflicting features set as both enabled and disabled: WebViewEmptyComponentLoaderPolicy

More logs in:
https://cas-viewer.appspot.com/projects/chrome-swarming/instances/default_instance/blobs/d95077eed77dbf7549061590c3edea1279e6f4a1048a28f0a9a299549454c4bb/8386?filename=benchmark_log.txt

Original change's description:
> Add config for WebViewOriginTrial before going to beta
>
> Bug: 1308425
> Change-Id: Ieed51060ee575f8453824e0c78c41878167d7a6f
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3627652
> Commit-Queue: Peter Pakkenberg <pbirk@chromium.org>
> Commit-Queue: Michael van Ouwerkerk <mvanouwerkerk@chromium.org>
> Reviewed-by: Michael van Ouwerkerk <mvanouwerkerk@chromium.org>
> Auto-Submit: Peter Pakkenberg <pbirk@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1000303}

Bug: 1308425
Change-Id: I6cce8949d2b7c446526b20b2daccc7810ec0da4e
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3630875
Auto-Submit: Wenbin Zhang <wenbinzhang@google.com>
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Cr-Commit-Position: refs/heads/main@{#1000598}