Revert of Revert of [Blink] XMLTreeViewer should load resources from blink_resources.grd instead of relying upon xxd.py… (https://codereview.chromium.org/397893002/)
Reason for revert:
The revert didn't fix the problem. It turns out a clobber healed the bot.

Original issue's description:
> Revert of [Blink] XMLTreeViewer should load resources from blink_resources.grd instead of relying upon xxd.py… (https://codereview.chromium.org/394003002/)
> 
> Reason for revert:
> I think this probably caused a build failure on Android GN:
> http://build.chromium.org/p/chromium.webkit/builders/Android%20GN/builds/3213
> http://build.chromium.org/p/chromium.webkit/builders/Android%20GN/builds/3212
> 
> Excerpt from log:
> FAILED: python ../../build/android/gyp/process_resources.py --depfile
> gen/ui/android/ui_java_res__process_resources.d --android-sdk
> ../../third_party/android_tools/sdk/platforms/android-19 --android-sdk-tools
> ../../third_party/android_tools/sdk/build-tools/19.0.0 --non-constant-id
> --android-manifest ../../build/android/AndroidManifest.xml
> --resource-dirs=\[\"../../ui/android/java/res\"\] --srcjar-out
> gen/ui/android/ui_java_res.srcjar --resource-zip-out
> gen/ui/android/ui_java_res.resources.zip
> --dependencies-res-zips=@\(gen/ui/android/ui_java_res.build_config:resources:dependency_zips\)
> --custom-package org.chromium.ui
> Traceback (most recent call last):
>   File "../../build/android/gyp/process_resources.py", line 260, in <module>
>     main()
>   File "../../build/android/gyp/process_resources.py", line 215, in main
>     build_utils.CheckOutput(package_command, print_stderr=False)
>   File
> "/mnt/data/b/build/slave/Android_GN/build/src/build/android/gyp/util/build_utils.py",
> line 154, in CheckOutput
>     raise CalledProcessError(cwd, args, stdout + stderr)
> util.build_utils.CalledProcessError: Command failed: ( cd
> /mnt/data/b/build/slave/Android_GN/build/src/out/Release;
> ../../third_party/android_tools/sdk/build-tools/19.0.0/aapt package -m -M
> ../../build/android/AndroidManifest.xml --auto-add-overlay -I
> ../../third_party/android_tools/sdk/platforms/android-19/android.jar
> --output-text-symbols /tmp/tmpX2vkJ3/gen -J /tmp/tmpX2vkJ3/gen -S
> ../../ui/android/java/res -S /tmp/tmpX2vkJ3/deps/ui_strings_grd.resources.zip
> --non-constant-id --custom-package org.chromium.ui )
> ../../third_party/android_tools/sdk/build-tools/19.0.0/aapt: error while loading
> shared libraries: libz.so.1: cannot open shared object file: No such file or
> directory
> 
> ninja: build stopped: subcommand failed.
> 
> Original issue's description:
> > [Blink] XMLTreeViewer should load resources from blink_resources.grd instead of relying upon xxd.py (Part-1)
> > 
> > Blink should make use of blink_resources.grd for the inline resources for displaying XML tree view.
> > This removes the dependency upon using xxd.py which embeds the resources as strings.
> > 
> > BUG=312586
> > 
> > Committed: https://src.chromium.org/viewvc/blink?view=rev&revision=178214
> 
> TBR=abarth@chromium.org,vivekg@chromium.org,vivek.vg@samsung.com
> NOTREECHECKS=true
> NOTRY=true
> BUG=312586
> 
> Committed: https://src.chromium.org/viewvc/blink?view=rev&revision=178230

TBR=abarth@chromium.org,vivekg@chromium.org,vivek.vg@samsung.com
NOTREECHECKS=true
NOTRY=true
BUG=312586

Review URL: https://codereview.chromium.org/393213002

git-svn-id: svn://svn.chromium.org/blink/trunk@178239 bbb929c8-8fbe-4397-9dbb-9b2b20218538