Revert "[FDT] Improve subsetting"
This reverts commit 14e6733adf8b0d8c3ecdb5154f9604f700a91380.

Reason for revert:
https://ci.chromium.org/ui/p/chromium/builders/ci/Win%207%20Tests%20x64%20(1)/81137/test-results?q=ExactID%3Aninja%3A%2F%2Fcomponents%3Acomponents_unittests%2FPaintPreviewSubsetFontTest.TestVariantSubset+VHash%3A6ca0d7c785d5abee

[ RUN      ] PaintPreviewSubsetFontTest.TestVariantSubset
../../components/paint_preview/common/subset_font_unittest.cc(81): error: Expected equality of these values:
  3
  typeface->getVariationDesignPosition(nullptr, 0)
    Which is: -1
Stack trace:
Backtrace:
	paint_preview::PaintPreviewSubsetFontTest_TestVariantSubset_Test::TestBody [0x0000000141975BB8+2856] (o:\components\paint_preview\common\subset_font_unittest.cc:81)

[  FAILED  ] PaintPreviewSubsetFontTest.TestVariantSubset (1362 ms)

Original change's description:
> [FDT] Improve subsetting
>
> Improve subsetting by
>
> * Skipping system fonts on Android (workaround for crbug/1249178).
>   * Note: this makes the output non-portable!
> * Include Font Layout/Variation information in subsetted output to
>   properly support some usecases.
>
> Bug: 1250364
> Change-Id: I066af33a86c20af8c483b3020c3609622b528602
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3163042
> Reviewed-by: Yashar Dabiran <yashard@chromium.org>
> Commit-Queue: Calder Kitagawa <ckitagawa@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#922322}

Bug: 1250364, 1250606
Change-Id: I3e756593e1c540c04c5160cdcaffbe3604bbb375
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3167257
Auto-Submit: Alan Cutter <alancutter@google.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Alan Cutter <alancutter@google.com>
Owners-Override: Alan Cutter <alancutter@google.com>
Cr-Commit-Position: refs/heads/main@{#922438}