mojo: Hash bytestrings for Python 3 compatibility
Python 3 only accepts bytes and bytestrings as input for hashing.
encode() so it works on both Python 2 and Python 3.

Traceback (most recent call last):
  File "../../mojo/public/tools/bindings/mojom_bindings_generator.py", line 557, in <module>
    sys.exit(main())
  File "../../mojo/public/tools/bindings/mojom_bindings_generator.py", line 552, in main
    return args.func(args, remaining_args)
  File "../../mojo/public/tools/bindings/mojom_bindings_generator.py", line 268, in _Generate
    processor._GenerateModule(args, remaining_args, generator_modules,
  File "../../mojo/public/tools/bindings/mojom_bindings_generator.py", line 213, in _GenerateModule
    ScrambleMethodOrdinals(module.interfaces, salt)
  File "../../mojo/public/tools/bindings/mojom_bindings_generator.py", line 132, in ScrambleMethodOrdinals
    sha256.update(interface.mojom_name)
TypeError: Unicode-objects must be encoded before hashing

Bug: 941669
Change-Id: Icfb5d7b9762763b12c7795ac23261fb614eef014
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2044078
Reviewed-by: Ken Rockot <rockot@google.com>
Commit-Queue: Raul Tambre <raul@tambre.ee>
Cr-Commit-Position: refs/heads/master@{#740204}