gpu_init: Stop inlining GpuInit::TakeDefaultOffscreenSurface()
This fixes the GCC build after commit b6ef3ba2a3 ("Pass GpuPreferences to
in-process GPU in Mash"):

    In file included from ../../content/utility/utility_service_factory.h:12,
                     from ../../content/utility/utility_service_factory.cc:5:
    ../../base/memory/scoped_refptr.h: In instantiation of ‘static void scoped_refptr<T>::Release(T*) [with T = gl::GLSurface]’:
    ../../base/memory/scoped_refptr.h:208:14:   required from ‘scoped_refptr<T>::~scoped_refptr() [with T = gl::GLSurface]’
    ../../gpu/ipc/service/gpu_init.h:70:48:   required from here
    ../../base/memory/scoped_refptr.h:284:8: error: invalid use of incomplete type ‘class gl::GLSurface’
       ptr->Release();
       ~~~~~^~~~~~~
    In file included from ../../services/viz/service.h:8,
                     from ../../content/utility/utility_service_factory.cc:35:
    ../../gpu/ipc/service/gpu_init.h:22:7: note: forward declaration of ‘class gl::GLSurface’
     class GLSurface;
           ^~~~~~~~~

gpu_init.h forward-declares gl::GLSurface but using std::move() with GCC
seems to require a full declaration for things to work.

Bug: 819294
Change-Id: Ib22ca2f8af6977869571292acf780042507a8afd
Reviewed-on: https://chromium-review.googlesource.com/c/1365249
Reviewed-by: Jonathan Backer <backer@chromium.org>
Commit-Queue: Raphael Kubo da Costa <raphael.kubo.da.costa@intel.com>
Cr-Commit-Position: refs/heads/master@{#614358}