IWYU: strcmp requires cstring include in ax_api_type.cc
Fix build error with libstdc++ and GCC:
    ../../ui/accessibility/platform/inspect/ax_api_type.cc: In static member function ‘static ui::AXApiType::Type ui::AXApiType::From(std::string&)’:
    ../../ui/accessibility/platform/inspect/ax_api_type.cc:42:14: error: ‘strcmp’ is not a member of ‘std’
       42 |     if (std::strcmp(info.type_str, c_type_str) == 0) {
          |              ^~~~~~

Bug: 957519
Change-Id: I6367b8e0bf4f4d7a70b93bd24e37637723446707
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3344530
Reviewed-by: Joanmarie Diggs <jdiggs@igalia.com>
Commit-Queue: José Dapena Paz <jdapena@igalia.com>
Cr-Commit-Position: refs/heads/main@{#956536}