LayoutNG: Rename symbols defined in layout/ng/exclusions/
'NG' is removed from symbols.
Exception: NGExclusion is renamed to ExclusionArea.

This CL has no behavior changes.

Bug: 1492009
Change-Id: I15c18d26b8a41b88594d312e726363d3dba32cfd
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4944751
Auto-Submit: Kent Tamura <tkent@chromium.org>
Reviewed-by: Koji Ishii <kojii@chromium.org>
Commit-Queue: Koji Ishii <kojii@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1210721}