GCC: fix clash between type and method SourceType in media_message_center::MediaNotificationItem.
Fix GCC compilation issue:
../../components/media_message_center/media_notification_item.h:69:22: error: declaration of ‘virtual media_message_center::SourceType media_message_center::MediaNotificationItem::SourceType()’ changes meaning of ‘SourceType’ [-fpermissive]
   69 |   virtual SourceType SourceType() = 0;
      |                      ^~~~~~~~~~
../../components/media_message_center/media_notification_item.h:19:12: note: ‘SourceType’ declared here as ‘enum class media_message_center::SourceType’
   19 | enum class SourceType {
      |            ^~~~~~~~~~

To avoid the type clash, add explicit namespace in the declaration of the return type.

Bug: 819294
Change-Id: I2d1e2f1feb5ddcb210c7df7a3762ae962d90167e
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2485175
Reviewed-by: Becca Hughes <beccahughes@chromium.org>
Commit-Queue: José Dapena Paz <jdapena@igalia.com>
Cr-Commit-Position: refs/heads/master@{#819008}