GCC: another std::move to return to base::Optional
GCC fails to implicitely move an T to a base::Optional<T> in return. So
this causes a build error. Explicitely std::move(). In this case the
issue happened in AuthenticatorGetAssertionResponse.

../../device/fido/authenticator_get_assertion_response.cc: In static member function ‘static base::Optional<device::AuthenticatorGetAssertionResponse> device::AuthenticatorGetAssertionResponse::CreateFromU2fSignResponse(base::span<const unsigned char, 32ul>, base::span<const unsigned char>, base::span<const unsigned char>)’:
../../device/fido/authenticator_get_assertion_response.cc:48:10: error: could not convert ‘response’ from ‘device::AuthenticatorGetAssertionResponse’ to ‘base::Optional<device::AuthenticatorGetAssertionResponse>’
   return response;
          ^~~~~~~~

Bug: 819294
Change-Id: I6410e3d4b10a9e50cae06f5a0b3dfe75d61d8b5d
Reviewed-on: https://chromium-review.googlesource.com/1101684
Commit-Queue: Balazs Engedy <engedy@chromium.org>
Reviewed-by: Balazs Engedy <engedy@chromium.org>
Cr-Commit-Position: refs/heads/master@{#567600}