Revert 272740 "Refactor and move ash independent accelerator han..."
Causing compile failures on Windows.  Possible comatability issue
with https://codereview.chromium.org/298703007

Sample errors:

FAILED: ninja -t msvc -e environment.x86 -- C:\b\build\goma/gomacc "C:\b\depot_tools\win_toolchain\vs2013_files\VC\bin\amd64_x86\cl.exe" /nologo /showIncludes /FC @obj\ui\wm\core\wm_unittests.nested_accelerator_controller_unittest.obj.rsp /c ..\..\ui\wm\core\nested_accelerator_controller_unittest.cc /Foobj\ui\wm\core\wm_unittests.nested_accelerator_controller_unittest.obj /Fdobj\ui\wm\wm_unittests.cc.pdb 
c:\b\build\slave\win\build\src\ui\wm\core\nested_accelerator_controller_unittest.cc(83) : error C2039: 'host' : is not a member of 'aura::Window'
        c:\b\build\slave\win\build\src\ui\aura\window.h(62) : see declaration of 'aura::Window'
c:\b\build\slave\win\build\src\ui\wm\core\nested_accelerator_controller_unittest.cc(83) : error C2227: left of '->PostNativeEvent' must point to class/struct/union/generic type
c:\b\build\slave\win\build\src\ui\wm\core\nested_accelerator_controller_unittest.cc(85) : error C2039: 'host' : is not a member of 'aura::Window'
        c:\b\build\slave\win\build\src\ui\aura\window.h(62) : see declaration of 'aura::Window'
c:\b\build\slave\win\build\src\ui\wm\core\nested_accelerator_controller_unittest.cc(85) : error C2227: left of '->PostNativeEvent' must point to class/struct/union/generic type
ninja: build stopped: subcommand failed.


> Refactor and move ash independent accelerator handling code in nested loop to ui/wm/core
> 
> I also renamed classes to NestedAcceleratorXxx. I felt this is a bit more clearer than NestedDispatcher, especially in ui/wm/core. Please let me know if you disagree or have better suggestion. I'm happy to rename them.
> 
> BUG=None
> 
> Review URL: https://codereview.chromium.org/298703007

TBR=oshima@chromium.org

Review URL: https://codereview.chromium.org/300093002

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@272759 0039d316-1c4b-4281-b951-d872f2087c98