Revert "[about this site] Add proto for "About this site" info"
This reverts commit 2f29884b77bcc4041718690930a34aaba71c036f.

Reason for revert: broke Android compile

Exception: Proto files for java must contain a "java_package" line: ../../components/page_info/proto/about_this_site_metadata.proto

https://logs.chromium.org/logs/chromium/buildbucket/cr-buildbucket/8834920944190013473/+/u/compile/stdout

Original change's description:
> [about this site] Add proto for "About this site" info
>
> Create a proto and replace the test strings with proto objects in the
> service and desktop UI.
>
> Bug: 1250653
> Change-Id: I4dc26bc8aa6083e8e721be4ff1c1e9fc5be88f62
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3172842
> Commit-Queue: Olesia Marukhno <olesiamarukhno@google.com>
> Reviewed-by: Sophie Chang <sophiechang@chromium.org>
> Reviewed-by: Christian Dullweber <dullweber@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#925285}

Bug: 1250653
Change-Id: I8ea920faadd9d1785304eebb247cebb473ecb5b9
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3187379
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Owners-Override: Evan Stade <estade@chromium.org>
Auto-Submit: Evan Stade <estade@chromium.org>
Commit-Queue: Evan Stade <estade@chromium.org>
Cr-Commit-Position: refs/heads/main@{#925290}