Reland "Don't build //chrome:linux_symbols if use_debug_fission"
This reverts commit 76dcddffaca45f220d84234a9c3ee7a0d4f7e8b5.

Reason for revert:
add //chrome:linux_symbols if not (is_debug && use_debug_fission).

is_official_build=true is is_debug=false, but symbol_level=2
and use_debug_fission=true


Original change's description:
> Revert "Don't build //chrome:linux_symbols if use_debug_fission"
>
> This reverts commit 28769efbb4b18d423ce3d07da37ee71d42c8a00f.
>
> Reason for revert: breaks linux-official builder: https://ci.chromium.org/ui/p/chromium/builders/ci/linux-official/11772/overview
>
> Original change's description:
> > Don't build //chrome:linux_symbols if use_debug_fission
> >
> > It seems dumpsym doesn't work with use_debug_fission
> >
> > [6/56343] ACTION //chrome:angle_gles_symbols(//build/toolchain/linux:clang_x64)
> > python3 ../../build/linux/dump_app_syms.py ./clang_x64_host_with_system_allocator/dump_syms 0 libGLESv2.so angle_libgles.breakpad.x64
> > Traceback (most recent call last):
> >   File "../../build/linux/dump_app_syms.py", line 27, in <module>
> >     subprocess.check_call([dumpsyms, '-m', '-d', infile], stdout=outfileobj)
> >   File "/b/s/w/ir/cipd_bin_packages/cpython3/lib/python3.8/subprocess.py", line 364, in check_call
> >     raise CalledProcessError(retcode, cmd)
> > subprocess.CalledProcessError: Command '['./clang_x64_host_with_system_allocator/dump_syms', '-m', '-d', 'libGLESv2.so']' died with <Signals.SIGABRT: 6>.
> > exit=1
> >
> > Bug: 372565363
> > Change-Id: I6e1a0657fdf92b9820a387b770addd576837efaa
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5920048
> > Commit-Queue: Fumitoshi Ukai <ukai@google.com>
> > Reviewed-by: Takuto Ikuta <tikuta@chromium.org>
> > Auto-Submit: Fumitoshi Ukai <ukai@google.com>
> > Reviewed-by: Junji Watanabe <jwata@google.com>
> > Cr-Commit-Position: refs/heads/main@{#1366637}
>
> Bug: 372565363
> Change-Id: I44919376751a861903631c0dedc4e10616082322
> No-Presubmit: true
> No-Tree-Checks: true
> No-Try: true
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5919967
> Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
> Owners-Override: Alexander Bolodurin <alexbn@google.com>
> Auto-Submit: Alexander Bolodurin <alexbn@chromium.org>
> Commit-Queue: Alexander Bolodurin <alexbn@google.com>
> Cr-Commit-Position: refs/heads/main@{#1366640}

Bug: 372565363
Change-Id: I68ea3a55402f1129aa058d965b7b63b3ed921ed9
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5919968
Reviewed-by: Junji Watanabe <jwata@google.com>
Reviewed-by: Alexander Bolodurin <alexbn@chromium.org>
Commit-Queue: Fumitoshi Ukai <ukai@google.com>
Auto-Submit: Fumitoshi Ukai <ukai@google.com>
Cr-Commit-Position: refs/heads/main@{#1366655}