[rust] Stop injecting `-I` / `-isystem` in `rust_bindgen_generator.gni`.
Motivation for this change: injecting the extra include path leads to
`bindgen` errors reported in https://crbug.com/411418184#comment6:

```
[1409/119441] ACTION //build/rust/allocator:allocator_impls_ffi_generator(//build/toolchain/mac:clang_arm64_v8_x64)
python3 ../../build/rust/run_bindgen.py \
    --exe ../../third_party/rust-toolchain/bin/bindgen \
    --header ../../build/rust/allocator/allocator_impls.h \
    ... \
    -isystem ../../build/mac_files/xcode_binaries/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.4.sdk/usr/include/ \
    ...
...
../../build/mac_files/xcode_binaries/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.4.sdk/usr/include/arm/_types.h:75:9: error: unknown type name 'ptrdiff_t'
../../build/mac_files/xcode_binaries/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.4.sdk/usr/include/arm/_types.h:85:9: error: unknown type name 'size_t'
../../build/rust/allocator/allocator_impls.h:14:22: error: unknown type name 'size_t'
...
```

This CL is speculative - I don't have a concrete reasons to believe that
the old change/fix is no longer needed. I hope that
`--no-include-path-detection` from b/328510249#comment36 is sufficient
(because in the meantime clang libraries were fixed? because of some
other changes?). I wondered whether https://crrev.com/c/6471409 could
possibly help, but this doesn't affect `deps` of the
`rust_bindgen_generator` template. FWIW I have included the
`chromeos-arm-generic-rel` bot, because this is how we have verified the
previous fix in b/328510249#comment40. And the Mega CQ seems to build
okay (this CL should only affect build steps - the test failures on some
bots can be ignored).

Bug: chromium:411418184
Bug: b/328510249
Change-Id: I0fc9f4b6cd7df5ad8a3c999ce813fb380e0a518f
Cq-Include-Trybots: luci.chromium.try:chromeos-arm-generic-rel
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6509525
Reviewed-by: Junji Watanabe <jwata@google.com>
Commit-Queue: Łukasz Anforowicz <lukasza@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1456743}