Revert of Remove unused parameter in DOMUtil APIs (patchset #4 id:60001 of https://codereview.chromium.org/2706903003/ )
Reason for revert:
Build broken

https://build.chromium.org/p/chromium.linux/builders/Android%20Builder/builds/79560

https://build.chromium.org/p/chromium.linux/builders/Android%20Builder/builds/79560/steps/compile/logs/stdio

../../chrome/android/javatests/src/org/chromium/chrome/browser/TabsTest.java:345: error: method clickNode in class DOMUtils cannot be applied to given types;
                DOMUtils.clickNode(
                        ^
  required: ContentViewCore,String
  found: TabsTest,ContentViewCore,String
  reason: actual and formal argument lists differ in length

Original issue's description:
> Remove unused parameter in DOMUtil APIs
>
> ActivityInstrumentationTestCase2 is not needed in DOMUtils.java and is
> now deprecated in favor of JUnit4
>
> BUG=640116
>
> Review-Url: https://codereview.chromium.org/2706903003
> Cr-Commit-Position: refs/heads/master@{#452117}
> Committed: https://chromium.googlesource.com/chromium/src/+/c088d17506c14fbfbab1d34538dcca64a561e315

TBR=boliu@chromium.org,jbudorick@chromium.org,dfalcantara@chromium.org,yolandyan@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=640116

Review-Url: https://codereview.chromium.org/2709273002
Cr-Commit-Position: refs/heads/master@{#452134}