Revert "[VCN] Fix challenge option parsing logic"
This reverts commit 2aef0c38f4816cb4f79ef3b599070a19f248b2fa.

Reason for revert: Suspected cause of compile errors:

https://ci.chromium.org/ui/p/chromium/builders/ci/mac-arm64-rel/8660/overview

[1856/2115] CXX obj/components/autofill/core/browser/unit_tests/credit_card_access_manager_unittest.o
FAILED: obj/components/autofill/core/browser/unit_tests/credit_card_access_manager_unittest.o
/opt/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -...(too long)
../../components/autofill/core/browser/payments/credit_card_access_manager_unittest.cc:2185:29: error: no matching constructor for initialization of 'autofill::CardUnmaskChallengeOption'
CardUnmaskChallengeOption challenge_option{
^               ~


Original change's description:
> [VCN] Fix challenge option parsing logic
>
> Patching Sujie's code.
>
> Now it makes sure to only parse SMS OTP challenge option.
>
> Bug: 1243475
> Change-Id: I0371ca50e1d48f7e515c1813f25652435e2d6daa
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3198805
> Reviewed-by: Jared Saul <jsaul@google.com>
> Commit-Queue: Siyu An <siyua@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#927477}

Bug: 1243475
Change-Id: I14615a4cde499c520f5a6383a279e039eb9328f0
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3200693
Auto-Submit: James Cook <jamescook@chromium.org>
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Owners-Override: James Cook <jamescook@chromium.org>
Cr-Commit-Position: refs/heads/main@{#927481}