Revert of Properly escape node names in DependencyGraph Graphviz export (patchset #4 id:80001 of https://codereview.chromium.org/1414053004/ )
Reason for revert:
Broke win 64 builds:

e:\b\build\slave\win_x64_gn__dbg_\build\src\components\keyed_service\core\dependency_graph_unittest.cc(175) : error C2220: warning treated as error - no 'object' file generated
e:\b\build\slave\win_x64_gn__dbg_\build\src\components\keyed_service\core\dependency_graph_unittest.cc(175) : warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data
e:\b\build\slave\win_x64_gn__dbg_\build\src\components\keyed_service\core\dependency_graph_unittest.cc(184) : warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data

http://build.chromium.org/p/chromium.win/builders/Win%20x64%20GN%20%28dbg%29/builds/12333

Original issue's description:
> Properly escape node names in DependencyGraph Graphviz export
>
> BUG=546954
>
> Committed: https://crrev.com/6918fc7520a841b427e97f45f2f250480b93556b
> Cr-Commit-Position: refs/heads/master@{#356255}

TBR=erg@chromium.org,tfarina@chromium.org,vabr@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=546954

Review URL: https://codereview.chromium.org/1419843006

Cr-Commit-Position: refs/heads/master@{#356355}