Revert of Ensure navigator.getVRDisplays always resolves. (patchset #6 id:100001 of https://codereview.chromium.org/2614873002/ )
Reason for revert:
Caused builder failures(e.g. https://uberchromegw.corp.google.com/i/internal.client.clank/builders/x64-builder) when building blimp.

undefined reference to `device::mojom::VRService::Name_'

Original issue's description:
> Ensure navigator.getVRDisplays always resolves.
>
> In the case that the backing VR service is not available the call will now
> resolve to an empty array.
>
> BUG=678283
> CQ_INCLUDE_TRYBOTS=master.tryserver.chromium.linux:linux_site_isolation
>
> Review-Url: https://codereview.chromium.org/2614873002
> Cr-Commit-Position: refs/heads/master@{#442117}
> Committed: https://chromium.googlesource.com/chromium/src/+/d83aedbf719e5346d2de69a79b5a1d7e9b6c8462

TBR=rockot@chromium.org,alexmos@chromium.org,ddorwin@chromium.org,bajones@chromium.org
# Not skipping CQ checks because original CL landed more than 1 days ago.
BUG=678283

Review-Url: https://codereview.chromium.org/2614353002
Cr-Commit-Position: refs/heads/master@{#442244}