Revert of Simplify landmines code a bit now that all branches of all platforms are on ninja (patchset #2 id:20001 of https://codereview.chromium.org/2071463002/ )
Reason for revert:
I just synced on Windows and this is giving me:

________ running 'D:\depot_tools\python276_bin\python.exe src/build/landmines.py
' in 'D:\src\src1'
Traceback (most recent call last):
  File "D:\src\src1\src\build\get_landmines.py", line 16, in <module>
    builder = landmine_utils.builder
AttributeError: 'module' object has no attribute 'builder'
Clobbering due to:
--- old_landmines       Tue Aug 12 16:34:51 2014
+++ new_landmines       Fri Jul 29 15:16:56 2016
@@ -1,17 +0,0 @@
-Compile on cc_unittests fails due to symbols removed in r185063.
-Improper dependency for create_nmf.py broke in r240802, fixed in r240860.
-Switch to VS2015 Update 2
-Need to clobber everything due to an IDL change in r154579 (blink)
-Need to clobber everything due to gen file moves in r175513 (Blink)
-Clobber to get rid of obselete test plugin after r248358
-Clobber to rebuild GN files for V8
-Clobber to get rid of stale generated mojom.h files
-Need to clobber everything due to build_nexe change in nacl r13424
-[chromium-dev] PSA: clobber build needed for IDR_INSPECTOR_* compil...
-blink_resources.grd changed: crbug.com/400860
-ninja dependency cycle: crbug.com/408192
-Clobber to fix missing NaCl gyp dependencies (crbug.com/427427).
-Another clobber for missing NaCl gyp deps (crbug.com/427427).
-Clobber to fix GN not picking up increased ID range (crbug.com/444902)
-Remove NaCl toolchains from the output dir (crbug.com/456902)
-Clobber to delete stale generated files (crbug.com/510086)

Original issue's description:
> Simplify landmines code a bit now that all branches of all platforms are on ninja
>
> BUG=none
>
> Committed: https://crrev.com/7491d14275670fad399837445b6c1e76ff498a50
> Cr-Commit-Position: refs/heads/master@{#408739}

TBR=iannucci@chromium.org,thakis@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=none

Review-Url: https://codereview.chromium.org/2198583002
Cr-Commit-Position: refs/heads/master@{#408784}