Revert "Headless: deprecate and remove the tab socket transport."
This reverts commit 54fe82667f8cd11b9acd7560addaad4f3baf3c0b.

Reason for revert: Caused windows build failure:
https://ci.chromium.org/buildbot/chromium/Win/67289
https://logs.chromium.org/v/?s=chromium%2Fbb%2Fchromium%2FWin%2F67289%2F%2B%2Frecipes%2Fsteps%2Fcompile%2F0%2Fstdout

FAILED: gen/headless/resources_stamp.d.stamp gen/headless/grit/headless_lib_resources.h gen/headless/headless_lib_resources.pak gen/headless/headless_lib_resources.pak.info 
C:/b/depot_tools/win_tools-2_7_6_bin/python/bin/python.exe ../../tools/grit/grit.py -i ../../headless/lib/resources/headless_lib_resources.grd build -o gen/headless --depdir . --depfile gen/headless/resources_stamp.d --write-only-new=1 --depend-on-stamp -D _chromium -E CHROMIUM_BUILD=chromium -D toolkit_views -D use_aura -E mojom_root=gen -f ../../tools/gritsettings/resource_ids -p ../../tools/gritsettings/startup_resources_win.txt --assert-file-list=obj/headless/resources_expected_outputs.txt
Error processing node <?xml version="1.0" encoding="UTF-8"?>
<include file="${mojom_root}/headless/lib/tab_socket.mojom.js" name="IDR_HEADLESS_TAB_SOCKET_MOJOM_JS" type="BINDATA" use_base_dir="false" />
Traceback (most recent call last):
  File "../../tools/grit/grit.py", line 15, in <module>
    grit.grit_runner.Main(sys.argv[1:])
  File "C:\b\c\b\win\src\tools\grit\grit\grit_runner.py", line 249, in Main
    toolobject.Run(options, args[1:])
  File "C:\b\c\b\win\src\tools\grit\grit\tool\build.py", line 256, in Run
    self.Process()
  File "C:\b\c\b\win\src\tools\grit\grit\tool\build.py", line 397, in Process
    self.ProcessNode(self.res, output, outfile)
  File "C:\b\c\b\win\src\tools\grit\grit\tool\build.py", line 320, in ProcessNode
    formatted = formatter(node, output_node.GetLanguage(), output_dir=base_dir)
  File "C:\b\c\b\win\src\tools\grit\grit\format\data_pack.py", line 83, in Format
    value = node.GetDataPackValue(lang, UTF8)
  File "C:\b\c\b\win\src\tools\grit\grit\node\include.py", line 87, in GetDataPackValue
    data = util.ReadFile(filename, util.BINARY)
  File "C:\b\c\b\win\src\tools\grit\grit\util.py", line 207, in ReadFile
    with open(filename, mode) as f:
IOError: [Errno 2] No such file or directory: u'..\\..\\out\\Release\\gen\\headless\\lib\\tab_socket.mojom.js'

Original change's description:
> Headless: deprecate and remove the tab socket transport.
> 
> Change-Id: Ifc9831e573697d3a75370cdee487b1d3238f0a5d
> Reviewed-on: https://chromium-review.googlesource.com/1056055
> Reviewed-by: Eric Seckler <eseckler@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#558573}

TBR=pfeldman@chromium.org,alexclarke@chromium.org,eseckler@chromium.org

Change-Id: I0e49742f252ef8e0f29d499d56b2654044bab1ba
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/1058847
Reviewed-by: Tsuyoshi Horo <horo@chromium.org>
Commit-Queue: Tsuyoshi Horo <horo@chromium.org>
Cr-Commit-Position: refs/heads/master@{#558577}