Revert "[vr] On-demand install VR DFM on N+"
This reverts commit 3e6d27f2d89227b59b81f75cb3a396a01512595c.

Reason for revert: Causing a compile failure on the builder: https://ci.chromium.org/p/chromium/builders/luci.chromium.ci/Android%20x64%20Builder%20%28dbg%29/31519

VrIntentDelegate.java:55: error: cannot find symbol
        int animation = VrDelegate.USE_HIDE_ANIMATION ? R.anim.stay_hidden : 0;

  symbol:   variable stay_hidden
  location: class anim
1 error


Original change's description:
> [vr] On-demand install VR DFM on N+
> 
> This requires handling the case when Chrome is started from VR before
> the module is installed. For this, move code that is required to
> identify VR intents and prevent 2D UI showing up in headset back to the
> base module. Furthermore, request VR module install when entering Chrome
> from VR and set up VR appropriately once the module install was
> successful. If the module cannot be installed within a timeout (we need
> a timeout so that Daydream does not kick us out of VR because we don't
> active VR mode in time) close Chrome on smartphones or launch it in
> 2D-in-VR mode on standalones.
> 
> NOTE: The VR DFM is still not activated in Monochrome. So, this change
> won't be active yet.
> 
> Bug: 914494
> Change-Id: If37544f3a35b4d01ac924ee874618348d4b6004d
> Reviewed-on: https://chromium-review.googlesource.com/c/1372227
> Reviewed-by: agrieve <agrieve@chromium.org>
> Reviewed-by: Michael Thiessen <mthiesse@chromium.org>
> Commit-Queue: Tibor Goldschwendt <tiborg@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#616442}

TBR=mthiesse@chromium.org,agrieve@chromium.org,tiborg@chromium.org

Change-Id: I25c203f54e9b8be8371d882133b3123ef233adad
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 914494
Reviewed-on: https://chromium-review.googlesource.com/c/1377289
Reviewed-by: David Trainor <dtrainor@chromium.org>
Commit-Queue: David Trainor <dtrainor@chromium.org>
Cr-Commit-Position: refs/heads/master@{#616478}