Revert "Roll Dawn from 0b17eb8e19c8 to 1b31dc0bb200 (4 revisions)"
This reverts commit 35239e96e48a885981479d7b763a93e1e2d156fa.

Reason for revert: 
Step compile failed. Error logs are shown below:
[22519/109920] CXX obj/third_party/dawn/src/dawn_wire/dawn_wire_shared/Wire.obj
FAILED: obj/third_party/dawn/src/dawn_wire/dawn_wire_shared/Wire.obj
C:\b\s\w\ir\cache\goma\client\gomacc.exe ..\..\third_party\llvm-build\Release+Asserts\bin\clang-cl.e...(too long)
In file included from ../../third_party/dawn/src/dawn_wire/Wire.cpp:15:
../../third_party/dawn/src/include\dawn_wire/Wire.h(28,17): error: definition of implicit copy assignment operator for 'CommandSerializer' is deprecated because it has a user-declared destructor [-Werror,-Wdeprecated-copy-dtor]
virtual ~CommandSerializer();
^

Original change's description:
> Roll Dawn from 0b17eb8e19c8 to 1b31dc0bb200 (4 revisions)
>
> https://dawn.googlesource.com/dawn.git/+log/0b17eb8e19c8..1b31dc0bb200
>
> 2021-02-17 enga@chromium.org Add a BufferConsumer primitive for wire [de]serialization
> 2021-02-17 senorblanco@chromium.org Implement a --backend= flag for DawnTest.
> 2021-02-17 cwallez@chromium.org Rolling 2 dependencies
> 2021-02-17 dawn-autoroll@skia-public.iam.gserviceaccount.com Roll Tint from c8fa020a5e97 to 52296de52893 (18 revisions)
>
> Also rolling transitive DEPS:
>   https://dawn.googlesource.com/tint from c8fa020a5e97 to 52296de52893
>
> If this roll has caused a breakage, revert this CL and stop the roller
> using the controls here:
> https://autoroll.skia.org/r/dawn-chromium-autoroll
> Please CC enga@google.com on the revert to ensure that a human
> is aware of the problem.
>
> To report a problem with the AutoRoller itself, please file a bug:
> https://bugs.chromium.org/p/skia/issues/entry?template=Autoroller+Bug
>
> Documentation for the AutoRoller is here:
> https://skia.googlesource.com/buildbot/+doc/master/autoroll/README.md
>
> Cq-Include-Trybots: luci.chromium.try:dawn-linux-x64-deps-rel;luci.chromium.try:dawn-mac-x64-deps-rel;luci.chromium.try:dawn-win10-x64-deps-rel;luci.chromium.try:dawn-win10-x86-deps-rel
> Bug: None
> Tbr: enga@google.com
> Change-Id: Ic6afeba53ed11aaa5231a859d72bc25a3ae91231
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2702674
> Commit-Queue: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>
> Bot-Commit: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>
> Cr-Commit-Position: refs/heads/master@{#855044}

Bug: None
Change-Id: Icf6a392df00b4fcc069a7782d10d58a81731b786
Cq-Include-Trybots: luci.chromium.try:dawn-linux-x64-deps-rel;luci.chromium.try:dawn-mac-x64-deps-rel;luci.chromium.try:dawn-win10-x64-deps-rel;luci.chromium.try:dawn-win10-x86-deps-rel
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2703294
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Reviewed-by: Johann Koenig <johannkoenig@google.com>
Commit-Queue: Johann Koenig <johannkoenig@google.com>
Cr-Commit-Position: refs/heads/master@{#855071}