Roll src/third_party/SPIRV-Tools/src a006cbc1d04c..37b584a73669 (1 commits)
https://chromium.googlesource.com/external/github.com/KhronosGroup/SPIRV-Tools.git/+log/a006cbc1d04c..37b584a73669


git log a006cbc1d04c..37b584a73669 --date=short --no-merges --format='%ad %ae %s'
2019-02-25 43968114+francoisbertelatschrodinger@users.noreply.github.com Fixed undefined reference to 'clock_gettime' by linking rt library (#2409)


Created with:
  gclient setdep -r src/third_party/SPIRV-Tools/src@37b584a73669

The AutoRoll server is located here: https://autoroll.skia.org/r/spirv-tools-chromium-autoroll

Documentation for the AutoRoller is here:
https://skia.googlesource.com/buildbot/+/master/autoroll/README.md

If the roll is causing failures, please contact the current sheriff, who should
be CC'd on the roll, and stop the roller if necessary.


TBR=dsinclair@chromium.org

Change-Id: I86c23a7e0bf84b69598e2fc65b3c1fd1b223c8f3
Reviewed-on: https://chromium-review.googlesource.com/c/1486057
Reviewed-by: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>
Commit-Queue: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>
Cr-Commit-Position: refs/heads/master@{#635106}