Revert "[pgo] pull only the artifact for PGO"
This reverts commit 589033a9e519b7ee22fcb527b9373b10eb3837bb.

Reason for revert: Fails to pull PGO profiles when there are slashes.

________ running 'vpython src/tools/update_pgo_profiles.py --target=mac update --gs-url-base=chromium-optimization-profiles/pgo_profiles' in '/Users/liaoyuke/chromium'
CommandException: No URLs matched: gs://chromium-optimization-profiles/pgo_profiles/chrome-mac-8c2b291de3b59368e5a28ae675d46ef7ea5d4a8b-1588500294.profdata
Traceback (most recent call last):
  File "src/tools/update_pgo_profiles.py", line 145, in <module>
    sys.exit(main())
  File "src/tools/update_pgo_profiles.py", line 141, in main
    return args.func(args)
  File "src/tools/update_pgo_profiles.py", line 93, in _update
    raise RuntimeError('gsutil failed to download "%s"' % gs_path)
RuntimeError: gsutil failed to download "gs://chromium-optimization-profiles/pgo_profiles/chrome-mac-8c2b291de3b59368e5a28ae675d46ef7ea5d4a8b-1588500294.profdata"
Error: Command 'vpython src/tools/update_pgo_profiles.py --target=mac update --gs-url-base=chromium-optimization-profiles/pgo_profiles' returned non-zero exit status 1 in /Users/liaoyuke/chromium

Original change's description:
> [pgo] pull only the artifact for PGO
> 
> PGO profiles are uploaded into folders (ie/ master/chrome-*.profdata.
> We only want to pull the profile, not the path as well, so we exclude
> it as part of the cp command.
> 
> Bug: 1071576
> Change-Id: I327a4f8c3d5ed324b81b88c5afd8bacac2afa578
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2176567
> Commit-Queue: Jeff Yoon <jeffyoon@chromium.org>
> Reviewed-by: Yuke Liao <liaoyuke@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#764964}

TBR=liaoyuke@chromium.org,jeffyoon@chromium.org

Change-Id: I14e6b7bd2536c866851fb05efd7c4e262365c0fa
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 1071576
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2177731
Reviewed-by: Yuke Liao <liaoyuke@chromium.org>
Commit-Queue: Yuke Liao <liaoyuke@chromium.org>
Cr-Commit-Position: refs/heads/master@{#764966}