[gcc 4.x] Fix the build failure due to -Werror=char-subscripts
Make the 'char' to 'unsigned char' to fix the following build failure.

device/hid/hid_connection_unittest.cc: In member function ‘virtual void device::HidConnectionTest_ReadWrite_Test::TestBody()’:
device/hid/hid_connection_unittest.cc:166:23: error: array subscript has type ‘char’ [-Werror=char-subscripts]
       buffer->data()[j] = i + j - 1;
                       ^
device/hid/hid_connection_unittest.cc:179:285: error: array subscript has type ‘char’ [-Werror=char-subscripts]
       ASSERT_EQ(i + j - 1, read_callback.buffer()->data()[j])

Review URL: https://codereview.chromium.org/664983002

Cr-Commit-Position: refs/heads/master@{#300238}