Revert "Tab Search: Add chrome://flags entry for Tab Search"
This reverts commit 5da77d649b71bdf592cd15224678b1926acf809c.

Reason for revert: Caused compile error.
https://ci.chromium.org/p/chrome/builders/ci/win64-chrome/5437

[9650/14917] CXX obj/chrome/browser/browser/about_flags.obj
FAILED: obj/chrome/browser/browser/about_flags.obj
c:\b\s\w\ir\cache\goma\client\gomacc.exe ..\..\third_party\llvm-build\Release+Asserts\bin\clang-cl.e...(too long)
../../chrome/browser/about_flags.cc(6186,46): error: no member named 'kEnableTabSearchName' in namespace 'flag_descriptions'; did you mean 'kEnableSaveDataName'?
{"enable-tab-search", flag_descriptions::kEnableTabSearchName,
~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
kEnableSaveDataName
../..\chrome/browser/flag_descriptions.h(358,19): note: 'kEnableSaveDataName' declared here
extern const char kEnableSaveDataName[];
^

Bug: 1113076

Original change's description:
> Tab Search: Add chrome://flags entry for Tab Search
>
> This addition is necessary to allow users to disable the feature once
> the experiment is enabled.
>
> Bug: 1099917
> Change-Id: I4e537a1fe92d1329c75ff8c190f92ce7f1cde8b7
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2336020
> Reviewed-by: Robert Liao <robliao@chromium.org>
> Commit-Queue: Thomas Lukaszewicz <tluk@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#794867}

TBR=robliao@chromium.org,tluk@chromium.org

Change-Id: I9e4778e201b2e61e1966ebb887930571e670dbdb
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 1099917
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2337049
Commit-Queue: Tsuyoshi Horo <horo@chromium.org>
Reviewed-by: Tsuyoshi Horo <horo@chromium.org>
Cr-Commit-Position: refs/heads/master@{#794884}