RELAND: Vaapi: extract a new BUILD.gn
Original CL got reverted after breaking linux-chromeos-dbg:
FAILED: viz.service
...
error: undefined reference to 'media::VaapiWrapper::PreSandboxInitialization()'

because the original CL was missing a
  defines = [ "MEDIA_GPU_IMPLEMENTATION" ]
inside the new BUILD.gn

Also this CL removes an extra level of vaapi/ folder in the auto
generated stub files.

Cq-Include-Trybots: master.tryserver.chromium.chromiumos:linux-chromeos-dbg
TBR=dalecurtis@chromium.org (minor changes)

Original CL description -----------------------------------------------

This CL adds a new //media/gpu/vaapi/BUILD.gn and extracts the necesary
parts of //media/gpu/BUILD.gn into it.  The files in ...vaapi/ include
a few of //media/gpu, so I extracted those into a //media/gpu:common
source_set.

TEST= simplechrome on soraka; CQ should cover this changes nonetheless.

Bug: 811912
Change-Id: I76a24913c48cd407131712ff6d573c5ee94fe14e
Cq-Include-Trybots: master.tryserver.chromium.android:android_optional_gpu_tests_rel;master.tryserver.chromium.linux:linux_optional_gpu_tests_rel;master.tryserver.chromium.mac:mac_optional_gpu_tests_rel;master.tryserver.chromium.win:win_optional_gpu_tests_rel
Reviewed-on: https://chromium-review.googlesource.com/919301
Reviewed-by: Dale Curtis <dalecurtis@chromium.org>
Commit-Queue: Miguel Casas <mcasas@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#536825}
Reviewed-on: https://chromium-review.googlesource.com/919971
Reviewed-by: Miguel Casas <mcasas@chromium.org>
Cr-Commit-Position: refs/heads/master@{#537007}