Ensures the minimum font size on Windows
PlatformFontWin is enforcing a minimal font size.
see: https://cs.chromium.org/chromium/src/ui/gfx/platform_font_win.cc?l=292

The PlatformFontSkiaOnWindows experiment is using the PlatformFontSkia
on Windows. But this implementation doesn't enfore the minimal font size.
This CL is adding the call to win::AdjustFontSize(...) which is responsible
to ensure the minimal size is respected.


This CL is fixing the unittest |FontTest.DeriveResizesIfSizeTooSmall| when
running with the PlatformFontSkiaOnWindows experiment.

  [ RUN      ] FontTest.DeriveResizesIfSizeTooSmall
  ../../ui/gfx/font_unittest.cc(152): error: Expected equality of these values:
    5
    derived_font.GetFontSize()
      Which is: 4


R=robliao@chromium.org, asvitkine@chromium.org

Bug: 944227
Change-Id: I99ad1ce651183cd488719b48791f9f056e6471e2
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1710013
Reviewed-by: Dana Fried <dfried@chromium.org>
Reviewed-by: Robert Liao <robliao@chromium.org>
Reviewed-by: Alexei Svitkine <asvitkine@chromium.org>
Commit-Queue: Etienne Bergeron <etienneb@chromium.org>
Cr-Commit-Position: refs/heads/master@{#681829}