Revert of Add show() methods for debugging to FloatRoundedRect. (patchset #2 id:20001 of https://codereview.chromium.org/885193002/)
Reason for revert:
Broke a bunch of lkgr bots (http://crbug.com/454121): http://build.chromium.org/p/chromium.lkgr/console

../../third_party/WebKit/Source/platform/geometry/FloatRoundedRect.cpp:131:13:error: use of undeclared identifier 'stderr'
    fprintf(stderr, "topLeft=[%f,%f], topRight=[%f,%f], bottomLeft=[%f,%f], bottomRight=[%f,%f]\n",
            ^

Probably needs an include of stdio.h. Also, I think we usually call these methods dump() in blink land.

Original issue's description:
> Add show() methods for debugging to FloatRoundedRect.
> 
> Committed: https://src.chromium.org/viewvc/blink?view=rev&revision=189227

TBR=jbroman@chromium.org,chrishtr@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true

Review URL: https://codereview.chromium.org/889133003

git-svn-id: svn://svn.chromium.org/blink/trunk@189303 bbb929c8-8fbe-4397-9dbb-9b2b20218538