Revert "Change std::adjacent_find() to use base:: functions."
This reverts commit b68638c6b28931a4b1e5d77323871c06b3d8ce94.

Reason for revert: Fails to compile on some builders:  Details 
in the bug here: https://bugs.chromium.org/p/chromium/issues/detail?id=1374976

[67685/87673] CXX obj/chrome/browser/win/conflicts/unit_tests/installed_applications_unittest.obj
FAILED: obj/chrome/browser/win/conflicts/unit_tests/installed_applications_unittest.obj
C:\b\s\w\ir\cache\goma\client\gomacc.exe ..\..\third_party\llvm-build\Release+Asserts\bin\clang-cl.e...(too long)
../../chrome/browser/win/conflicts/installed_applications_unittest.cc(401,31): error: no matching function for call to 'equal'
applications, std::equal<>(), [](const auto& app) {
^~~~~~~~~~~~
../..\third_party/googletest/src/googletest/include/gtest/gtest.h(1840,69): note: expanded from macro 'EXPECT_EQ'
EXPECT_PRED_FORMAT2(::testing::internal::EqHelper::Compare, val1, val2)

Original change's description:
> Change std::adjacent_find() to use base:: functions.
>
> Simplifies code slightly.
>
> Bug: 1368812
> Change-Id: If642caa93e99f178cdf8832846649a076976471c
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3953856
> Reviewed-by: Reilly Grant <reillyg@chromium.org>
> Reviewed-by: Charlie Reis <creis@chromium.org>
> Reviewed-by: Justin Novosad <junov@chromium.org>
> Reviewed-by: Ted Choc <tedchoc@chromium.org>
> Auto-Submit: Peter Kasting <pkasting@chromium.org>
> Commit-Queue: Justin Novosad <junov@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1059394}

Bug: 1368812
Change-Id: Ie4223f306e4c8dd749a09271a881d214294f5f93
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3956667
Commit-Queue: Peter Williamson <petewil@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Reviewed-by: Ted Choc <tedchoc@chromium.org>
Owners-Override: Peter Williamson <petewil@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1059528}