Revert "Reland "[CrOS PhoneHub] Add setter functions to various manager classes""
This reverts commit 26aa33d258669d2e88b48253dfb001b4928c3b72.

Reason for revert: trybots are failing

https://ci.chromium.org/p/chromium/builders/try/linux-chromeos-rel/685012

[4694/19597] CXX obj/ash/ash/silence_phone_quick_action_controller.o
FAILED: obj/ash/ash/silence_phone_quick_action_controller.o
../../build/toolchain/clang_code_coverage_wrapper.py --target-os=chromeos --files-to-instrument=../....(too long)
../../ash/system/phonehub/silence_phone_quick_action_controller.cc:35:20: error: no member named 'SetDoNotDisturbState' in 'chromeos::phonehub::DoNotDisturbController'
dnd_controller_->SetDoNotDisturbState(!is_now_enabled);
~~~~~~~~~~~~~~~  ^
1 error generated.

In renaming SetDoNotDisturbState you missed the call in ash/ash/silence_phone_quick_action_controller

Original change's description:
> Reland "[CrOS PhoneHub] Add setter functions to various manager classes"
>
> This is a reland of 6a3c229fa0dc87064c6d40f9d18a9d993d6cf889
>
> Original change's description:
> > [CrOS PhoneHub] Add setter functions to various manager classes
> >
> > The added setters are going to be used by a future Cl that implements
> > the PhoneStatusProcessor class.
> >
> > Bug: 1106937
> > Change-Id: Ie95210cfcedbba2ad3ed5875a34ef21a7486b13f
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2423346
> > Commit-Queue: Jimmy Gong <jimmyxgong@chromium.org>
> > Reviewed-by: Kyle Horimoto <khorimoto@chromium.org>
> > Cr-Commit-Position: refs/heads/master@{#810084}
>
> Bug: 1106937
> Change-Id: I02ac4d496d9493c7b52de7d6bb36eb61517caa16
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2429290
> Commit-Queue: Jimmy Gong <jimmyxgong@chromium.org>
> Reviewed-by: Kyle Horimoto <khorimoto@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#811479}

TBR=khorimoto@chromium.org,jimmyxgong@chromium.org

Change-Id: I4d5edab201fa06caa630678a9b18d4d85f235e0d
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 1106937
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2437016
Reviewed-by: Avi Drissman <avi@chromium.org>
Commit-Queue: Avi Drissman <avi@chromium.org>
Cr-Commit-Position: refs/heads/master@{#811490}