Revert "[X11] Split PutImage requests into multiple requests if necessary"
This reverts commit 3fe154df4adc9d4c405e4cde0ce85bb23ade367a.

Reason for revert: Appears to have caused compile failure: https://ci.chromium.org/p/chromium/builders/ci/Linux%20Builder%20(dbg)(32)/166101?

[1052/1665] CXX obj/ui/base/x/x/selection_owner.o
FAILED: obj/ui/base/x/x/selection_owner.o
/b/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF...(too long)
../../ui/base/x/selection_owner.cc:46:10: error: no matching function for call to 'min'
return std::min(size - 100, 0x100000l);
^~~~~~~~
../../buildtools/third_party/libc++/trunk/include/algorithm:2532:1: note: candidate template ignored: deduced conflicting types for parameter '_Tp' ('int' vs. 'long')
min(const _Tp& __a, const _Tp& __b)
^

Original change's description:
> [X11] Split PutImage requests into multiple requests if necessary
>
> R=​sky
>
> Change-Id: I1befaef494c74797333d6bf02e204bcdc721e752
> Bug: 1164669
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2643711
> Commit-Queue: Thomas Anderson <thomasanderson@chromium.org>
> Commit-Queue: Scott Violet <sky@chromium.org>
> Reviewed-by: Scott Violet <sky@chromium.org>
> Auto-Submit: Thomas Anderson <thomasanderson@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#846344}

TBR=sky@chromium.org,thomasanderson@chromium.org,chromium-scoped@luci-project-accounts.iam.gserviceaccount.com

Change-Id: I3989bb05bc58bfadf33f7b67bae0ac2c4a5402e7
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 1164669
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2644744
Reviewed-by: Katie Dektar <katie@chromium.org>
Commit-Queue: Katie Dektar <katie@chromium.org>
Cr-Commit-Position: refs/heads/master@{#846351}