Revert "webauthn: log on macOS if we believe that Bluetooth permission is missing."
This reverts commit d0b1052875aa73d630314950c1959427bdd2e153.

Reason for revert: Breaking Mac10.11 Tests: dyld: Symbol not found: _SecTaskCopySigningIdentifier


Sample failure: https://ci.chromium.org/ui/p/chromium/builders/ci/Mac10.11%20Tests/71675/overview

Original change's description:
> webauthn: log on macOS if we believe that Bluetooth permission is missing.
>
> The `authorization` property of CBManager[1] is not a reliable
> indication of whether Bluetooth will work. Specifically, sometimes
> Bluetooth works fine for a process even though `authorization` reports
> `CBManagerAuthorizationDenied`.
>
> I _think_ it's reliable if the process is code signed, however. If so,
> Chrome could show some UI if the user has denied Bluetooth permission
> yet is trying to use Bluetooth. As a first step, just log. This may help
> diagnose reports and will allow me to check with Canary whether this
> signal seems to be accurate.
>
> [1]
> https://developer.apple.com/documentation/corebluetooth/cbmanager/3377595-authorization?language=objc
>
> Change-Id: I1c89be1aca3ceb43f476e56ae10f6a75614aafe5
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3551639
> Reviewed-by: Mark Mentovai <mark@chromium.org>
> Commit-Queue: Adam Langley <agl@chromium.org>
> Auto-Submit: Adam Langley <agl@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#987213}

Change-Id: Iefdd6c0423a2f84eba78daf81bc1f3016257fbc1
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3562158
Auto-Submit: Jiewei Qian <qjw@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Reviewed-by: Adam Langley <agl@chromium.org>
Commit-Queue: Adam Langley <agl@chromium.org>
Cr-Commit-Position: refs/heads/main@{#987266}