Reland "Nearby Share: Consolidate and autogenerate grd files"
This reverts commit 6731728614bf6b6cb060d51eba1770ba09847069.

Reason for revert: Compile failure not (or only very loosely) related to this CL. Local reland doesn't seem to affect reproduction of compile failure.

Original change's description:
> Revert "Nearby Share: Consolidate and autogenerate grd files"
>
> This reverts commit 5c7c88d7322f8f40b371776355959930f0f3b828.
>
> Reason for revert: Most-likely suspect for CrOS compile failure:
> https://ci.chromium.org/p/chromium/builders/ci/linux-chromeos-rel/42591
>
> Log:
> [5898/61571] ACTION //ui/file_manager/file_manager/test:create_test_main(//build/toolchain/linux:clang_x64)
>  FAILED: gen/ui/file_manager/file_manager/test.html 
>  /b/s/w/ir/cipd_bin_packages/cpython/bin/python ../../ui/file_manager/file_manager/test/scripts/create_test_main.py --output=gen/ui/file_manager/file_manager/test.html
>  Traceback (most recent call last):
>    File "../../ui/file_manager/file_manager/test/scripts/create_test_main.py", line 144, in <module>
>      write(GEN + R_GEN + colors, open(GEN + '../../' + colors).read())
>  IOError: [Errno 2] No such file or directory: '/b/s/w/ir/cache/builder/src/out/Release/gen/ui/file_manager/file_manager/../../chromeos/colors/cros_colors.generated.css'
>
> Original change's description:
> > Nearby Share: Consolidate and autogenerate grd files
> >
> > Bug: 1132403
> > Change-Id: I809b1a97e43457b92ac67fde208b200bfbf37d58
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2507400
> > Commit-Queue: Rebekah Potter <rbpotter@chromium.org>
> > Reviewed-by: Avi Drissman <avi@chromium.org>
> > Reviewed-by: dpapad <dpapad@chromium.org>
> > Cr-Commit-Position: refs/heads/master@{#824322}
>
> TBR=avi@chromium.org,dpapad@chromium.org,rbpotter@chromium.org
>
> Change-Id: I275146470b9fc70dbff9203ee8f951eda7e624d8
> No-Presubmit: true
> No-Tree-Checks: true
> No-Try: true
> Bug: 1132403
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2517734
> Reviewed-by: Friedrich [CET] <fhorschig@chromium.org>
> Commit-Queue: Friedrich [CET] <fhorschig@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#824345}

TBR=avi@chromium.org,dpapad@chromium.org,rbpotter@chromium.org,fhorschig@chromium.org

# Not skipping CQ checks because this is a reland.

Bug: 1132403
Change-Id: If7466f38cc0114c50adeef011c22c0c0cf2f437a
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2517446
Reviewed-by: dpapad <dpapad@chromium.org>
Commit-Queue: Friedrich [CET] <fhorschig@chromium.org>
Cr-Commit-Position: refs/heads/master@{#824401}