Revert of components: build fix about GenericChangeProcessor (patchset #1 id:1 of https://codereview.chromium.org/1579533002/ )
Reason for revert:
This issue is known in crbug.com/506663 and we want to fix c++ spec and clang rather than making chromium code silly.
Nico asked to revert it.

Original issue's description:
> components: build fix about GenericChangeProcessor
>
> clang complains it doesn't initialize const member, so this CL calls the
> default constructor explicitly.
>
> ../../components/sync_driver/generic_change_processor.cc:157:38: error: default initialization of an object of const type 'const syncer::AttachmentIdList' (aka 'const vector<syncer::AttachmentId>') without a user-provided default constructor
>       const syncer::AttachmentIdList empty_list_of_attachment_ids;
>                                      ^
>                                                                  {}
> 1 error generated.
>
> Committed: https://crrev.com/8fe05e777f1b8be62cb2caeab59ccb292868eed6
> Cr-Commit-Position: refs/heads/master@{#368627}

TBR=pavely@chromium.org
# Not skipping CQ checks because original CL landed more than 1 days ago.

Review URL: https://codereview.chromium.org/1577323004

Cr-Commit-Position: refs/heads/master@{#369133}