Revert "Replace EmptyTabModelSelectorObserver with default methods."
This reverts commit 0b50506149ac335203709fa0ad1ea3dd43cb6fc6.

Reason for revert: Trybots are failing with:
../../chrome/android/java/src/org/chromium/chrome/browser/tabmodel/TabModelFilterProvider.java:20: error: could not resolve EmptyTabModelSelectorObserver

e.g.: https://ci.chromium.org/p/chromium/builders/try/android-marshmallow-arm64-rel/555380

Original change's description:
> Replace EmptyTabModelSelectorObserver with default methods.
> 
> Bug: 1082248
> Change-Id: I51b883c8fbefcf391750110b3477ea84c78f7a5b
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2199890
> Reviewed-by: David Trainor <dtrainor@chromium.org>
> Commit-Queue: Henrique Nakashima <hnakashima@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#768767}

TBR=dtrainor@chromium.org,hnakashima@chromium.org

Change-Id: I220287bc7077ab590c6e9d4272784ef3a958bf6a
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 1082248
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2202118
Reviewed-by: Andrew Grieve <agrieve@chromium.org>
Commit-Queue: Andrew Grieve <agrieve@chromium.org>
Cr-Commit-Position: refs/heads/master@{#768782}