Fix linker error due to missing MESSAGE_CENTER_EXPORT
Not sure in which condition this can be triggered, my environment is linux x64 with plain "component=shared_library clang=1", the actual linker invoked is "third_party/binutils/Linux_x64/Release/bin/ld.gold"

Here is the error log from linker:
/usr/lib64/gcc/x86_64-unknown-linux-gnu/4.9.1/../../../../include/c++/4.9.1/bits/stl_tree.h:1543: error: undefined reference to 'message_center::CompareTimestampSerial::operator()(message_center::Notification*, message_center::Notification*)'
clang: error: linker command failed with exit code 1 (use -v to see invocation)

BUG=None

Review URL: https://codereview.chromium.org/654093003

Cr-Commit-Position: refs/heads/master@{#299933}