Revert "Roll vulkan-deps from 36456846a4af to bbd1a7b068ea (6 revisions)"
This reverts commit e1955e7bddba1f2b7a6e5ca6978e64a441b43104.

Reason for revert: failures on Win7 FYI angle_gles1_conformance_tests

../../third_party/angle/src/tests/test_utils/ANGLETest.cpp(64): error: vk_utils.cpp:300 (GetAvailableValidationLayers): Vulkan validation layers are missing.

Original change's description:
> Roll vulkan-deps from 36456846a4af to bbd1a7b068ea (6 revisions)
>
> https://chromium.googlesource.com/vulkan-deps.git/+log/36456846a4af..bbd1a7b068ea
>
> Changed dependencies:
> * spirv-tools: https://chromium.googlesource.com/external/github.com/KhronosGroup/SPIRV-Tools.git/+log/c26baf4c93..d432bebb11
> * vulkan-loader: https://chromium.googlesource.com/external/github.com/KhronosGroup/Vulkan-Loader.git/+log/3bdb32d29f..550b23a566
>
> If this roll has caused a breakage, revert this CL and stop the roller
> using the controls here:
> https://autoroll.skia.org/r/vulkan-deps-chromium-autoroll
> Please CC radial-bots+chrome-roll@google.com,cnorthrop@google.com,kainino@google.com on the revert to ensure that a human
> is aware of the problem.
>
> To report a problem with the AutoRoller itself, please file a bug:
> https://bugs.chromium.org/p/skia/issues/entry?template=Autoroller+Bug
>
> Documentation for the AutoRoller is here:
> https://skia.googlesource.com/buildbot/+doc/main/autoroll/README.md
>
> Cq-Include-Trybots: luci.chromium.try:android_optional_gpu_tests_rel;luci.chromium.try:linux_optional_gpu_tests_rel;luci.chromium.try:mac_optional_gpu_tests_rel;luci.chromium.try:win_optional_gpu_tests_rel;luci.chromium.try:linux-swangle-try-x64;luci.chromium.try:win-swangle-try-x86;luci.chromium.try:dawn-linux-x64-deps-rel;luci.chromium.try:win-asan;luci.chromium.try:linux_chromium_cfi_rel_ng
> Bug: None
> Tbr: radial-bots+chrome-roll@google.com,cnorthrop@google.com,kainino@google.com
> Change-Id: If80a0cb15b727d905b66301fa2aa1f202b7539b4
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3022600
> Commit-Queue: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>
> Bot-Commit: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>
> Cr-Commit-Position: refs/heads/master@{#901006}

Bug: None
Change-Id: Ia78efa3e641448583e3ca50c4f21b73df6bf1bb8
Cq-Include-Trybots: luci.chromium.try:android_optional_gpu_tests_rel;luci.chromium.try:linux_optional_gpu_tests_rel;luci.chromium.try:mac_optional_gpu_tests_rel;luci.chromium.try:win_optional_gpu_tests_rel;luci.chromium.try:linux-swangle-try-x64;luci.chromium.try:win-swangle-try-x86;luci.chromium.try:dawn-linux-x64-deps-rel;luci.chromium.try:win-asan;luci.chromium.try:linux_chromium_cfi_rel_ng
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3025545
Auto-Submit: Kai Ninomiya <kainino@chromium.org>
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Cr-Commit-Position: refs/heads/master@{#901179}