Revert of [Mac] Switch from NSObject categories to forward declarations for Touch Bar support. (patchset #4 id:100001 of https://codereview.chromium.org/2519563002/ )
Reason for revert:
Persistent build failures on official.desktop (see http://crbug.com/667830)

Breaks compilation with the 10.12.1 SDK:
bridged_content_view_touch_bar.mm:50:4: error: 'NSTouchBarItem' is partial: introduced in macOS 10.12.1 [-Werror,-Wunguarded-availability]

Also tapted doesn't like the macros.

Original issue's description:
> [Mac] Switch from NSObject categories to forward declarations for Touch Bar support.
>
> This fixes a crash when -[BridgedContentView touchBar:] calls
> -[NSGroupTouchBarItem groupItemWithIdentifier:items:], because
> NSGroupTouchBarItem was typedef'd to NSObject.
>
> BUG=666893
>
> Committed: https://crrev.com/799f1635ddedf7fd2f69f7dca26b0f2bf6399cba
> Cr-Commit-Position: refs/heads/master@{#433558}

TBR=sdy@chromium.org
# Not skipping CQ checks because original CL landed more than 1 days ago.
BUG=666893, 667830

Review-Url: https://codereview.chromium.org/2526723002
Cr-Commit-Position: refs/heads/master@{#434125}