Revert 187677 "This patch enables pulse as the default IO handli..."
This broke the ChromeOS bots. See:
http://build.chromium.org/p/chromium.chromiumos/builders/ChromiumOS%20%28daisy%29/builds/7853/steps/cbuildbot/logs/stdio
chromeos-chrome-27.0.1439.0_alpha-r1: In file included from media/audio/pulse/audio_manager_pulse.cc:5:0:
chromeos-chrome-27.0.1439.0_alpha-r1: ./media/audio/pulse/audio_manager_pulse.h:8:30: fatal error: pulse/pulseaudio.h: No such file or directory


> This patch enables pulse as the default IO handling in Chrome.
> 
> Right now we have the dynamic linking for pulse library, for the machine without pulse, it will automatically fall back to ALSA.
> 
> In order to enable pulse as the default IO, libpulse-dev package is required to build Chrome on linux. Previously libpulse-dev is only required if building chromeOS, right now it is also required by building chrome.
> 
> 
> Note, we still have some small issues for the pulse implementations, so this patch needs to be landed after https://codereview.chromium.org/12328097/,
> https://codereview.chromium.org/12316131/, https://codereview.chromium.org/12310102/ and
> https://codereview.chromium.org/12613005/
> 
> 
> BUG=178101
> TEST=compile on linux
> 
> Review URL: https://chromiumcodereview.appspot.com/12310101

TBR=xians@chromium.org
Review URL: https://codereview.chromium.org/12567014

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@187701 0039d316-1c4b-4281-b951-d872f2087c98