Revert "Add chrome_cleaner/json_parser"
This reverts commit 86ba94de312026b0488f0e73d91c1b018952309d.

Reason for revert: Compile failure: https://ci.chromium.org/p/chromium/builders/luci.chromium.ci/win32-rel/1338

log: https://logs.chromium.org/logs/chromium/buildbucket/cr-buildbucket.appspot.com/8937424896625406016/+/steps/compile/0/stdout

In file included from gen\chrome/chrome_cleaner/interfaces/pup.mojom-blink.h:25:
../..\mojo/public/cpp/bindings/struct_ptr.h(96,18):  error: no member named 'Hash' in 'chrome_cleaner::mojom::blink::FilePath'
    return ptr_->Hash(seed);




Original change's description:
> Add chrome_cleaner/json_parser
> 
> This does not use services/data_decoder because it's closely tied to
> the service manager, which chrome_cleaner does not support.
> 
> R=​csharp
> 
> Bug: 830892
> Change-Id: Ia3138624c9d723916fdf1ba174c89cbcc6e71401
> Reviewed-on: https://chromium-review.googlesource.com/1180349
> Reviewed-by: Joe Mason <joenotcharles@chromium.org>
> Reviewed-by: Chris Sharp <csharp@chromium.org>
> Reviewed-by: Tom Sepez <tsepez@chromium.org>
> Commit-Queue: Joe Mason <joenotcharles@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#585408}

TBR=csharp@chromium.org,tsepez@chromium.org,joenotcharles@chromium.org

Change-Id: I10a119dfbdbc34ba06ad3d5c3d18ef4a8a5d09a8
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 830892
Reviewed-on: https://chromium-review.googlesource.com/1186241
Reviewed-by: Hayato Ito <hayato@chromium.org>
Commit-Queue: Hayato Ito <hayato@chromium.org>
Cr-Commit-Position: refs/heads/master@{#585413}