Fixes ChromeVox panel errors on load
Error: Refused to load the stylesheet 'http://fonts.googleapis.com/css?family=Droid+Sans+Mono|Roboto:400,700,700italic' because it violates the following Content Security Policy directive: "style-src 'unsafe-inline' chrome://resources". Note that 'style-src-elem' was not explicitly set, so 'style-src' is used as a fallback.
Fixed by removing the reference (panel.css suffices).

Error: endpoint does not exist
Caused by access to chrome.extension.getBackgroundPage() prior to actual
ChromeVox background page load.

Fixed by removing unused dependencies required in panel.js. It is
generally bad to depend on things that are unused as it pulls those
files into the compiled js for the panel.

R=akihiroota@chromium.org

AX-Relnotes: n/a
Bug: none
Test: existing browser_tests; verify no errors on panel page.
Change-Id: Ie92fdb2b498f8ddafb20b01203256a8e47a6d46c
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2648836
Reviewed-by: Akihiro Ota <akihiroota@chromium.org>
Commit-Queue: David Tseng <dtseng@chromium.org>
Cr-Commit-Position: refs/heads/master@{#847298}