Fix the ChromeOS Variations Smoke Tests builder.
Currently the builder is failing with message

Added a commandline argument that will allow this origin. Since
every time we use slightly different port for debugging purposes
I've added '*' to allow all possible values.

WebSocketBadStatusException: Handshake status 403 Forbidden
Bug: 433687745
Change-Id: If74d387cf14f22f32db3ebce63e8b32208c3f03b
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6781087
Reviewed-by: Ramon Cano Aparicio <rcanoaparicio@google.com>
Reviewed-by: Luc Nguyen <lucnguyen@google.com>
Commit-Queue: Arkadiusz Tomczak <artomczak@google.com>
Cr-Commit-Position: refs/heads/main@{#1490787}