Manual roll Chromite from 6e88b03636a2 to bf1a19021440 (188 revisions)
Manual roll requested by yoshiki@google.com

https://chromium.googlesource.com/chromiumos/chromite.git/+log/6e88b03636a2..bf1a19021440

2023-10-25 semenzato@google.com service: tiny release name change
2023-10-25 saklein@chromium.org chromite_config: Missing pwd entry handling.
2023-10-25 hungmn@google.com api: roll proto bindings
2023-10-25 chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com Automated Commit: Updated config generated by config-updater builder.
2023-10-25 allenwebb@google.com scripts: package_has_missing_deps.py: add --format
2023-10-25 tapted@chromium.org api: Add missing gen_sdk generated protos.
2023-10-25 hscham@chromium.org ide: add hover for ebuild phase functions
2023-10-25 jrosenth@chromium.org api: message_util: Compactify JSON messages
2023-10-25 yamaguchi@chromium.org ide: Bump the version to 0.23.3 for pre-release
2023-10-25 kimjae@chromium.org OWNERS.au: Update owners
2023-10-24 hashimoto@chromium.org service: Add --keep_going for the CI builders
2023-10-24 briannorris@chromium.org service: sdk: Selectively remount chroot read/write
2023-10-24 briannorris@chromium.org lib: cros_sdk_lib: Mount chroot/run from out/sdk/run
2023-10-24 tbain@google.com service: Specify --profile for app-crypt/nss
2023-10-24 vapier@chromium.org scripts: deploy_chrome: move pkill from shell command to argv list
2023-10-24 briannorris@chromium.org Revert "Generate /etc/os-release in SDK tarballs"
2023-10-24 ttylenda@chromium.org ide: add tooltips to short links
2023-10-24 ttylenda@chromium.org ide: use jasmine assertions in short_link_provider.test.ts
2023-10-24 ttylenda@chromium.org ide: turn short_link_provider.test.ts into a unit test
2023-10-24 tapted@chromium.org api: sdk_subtools: Map bundle output to an SDK output path.
2023-10-24 tapted@chromium.org api: Implement the chromiumos.common.ResultPath.Transfer option.
2023-10-24 tbain@google.com lib: Pass outside path to UpdateEbuildManifest()
2023-10-23 tapted@chromium.org api: Check if ./compile_build_api_proto is run on stale src/config protos
2023-10-23 semenzato@google.com service: starbase: fix tarfile name
2023-10-23 briannorris@chromium.org lib: cros_sdk_lib: Migrate chroot/usr/local/bin to out/
2023-10-23 briannorris@chromium.org scripts: cros_sdk: --force is not a command
2023-10-23 briannorris@chromium.org scripts: cros_sdk: Add options-handling tests
2023-10-23 vapier@chromium.org scripts: deploy_chrome: move test find from shell command to argv list
2023-10-23 vapier@chromium.org scripts: deploy_chrome: move service restart from shell command to argv list
2023-10-23 mpolzer@google.com cros: Add rollback_cleanup to usergroup_baseline
2023-10-23 hscham@chromium.org ide: fix compilation error committed in crrev.com/c/4963088
2023-10-23 oka@chromium.org Revert "ide: run tast tests: Unit test cancellation"
2023-10-23 oka@chromium.org Revert "ide: Make commonUtil.CancelledError extend vscode.CancellationError"
2023-10-23 hscham@chromium.org ide: ParsedEbuild provides variable assignment getter method
2023-10-23 nya@chromium.org service: BazelTest: Support --output_user_root
2023-10-23 nya@chromium.org api: roll proto bindings
2023-10-23 yamaguchi@chromium.org ide: update packages to resolve high severity issue
2023-10-21 chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com Automated Commit: Updated config generated by config-updater builder.
2023-10-21 chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com Automated Commit: Updated config generated by config-updater builder.
2023-10-21 vapier@chromium.org Revert "cbuildbot: deleted managed_chrome logic"
2023-10-21 tbain@google.com lib: Don't default chroot for UpdateEbuildManifest
2023-10-21 zland@google.com cli: Reconnect to network after images are built
2023-10-20 chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com Automated Commit: Updated config generated by config-updater builder.
2023-10-20 semenzato@google.com service: fix typo
2023-10-20 tbain@google.com service: Handle Bazel artifacts in /tmp
2023-10-20 timvp@google.com cli: cros lint: support make.defaults files
2023-10-20 srinivashegde@google.com scripts: Add a script for generating coverage artifacts.
2023-10-20 tbain@google.com utils: Split utils.gs_urls_util from lib.gs
2023-10-20 semenzato@google.com service: use chroot path in UpdateEbuildManifest
2023-10-20 vapier@chromium.org scripts: cros_uprev: drop unused script
2023-10-20 treapking@chromium.org Revert "scripts: cros_run_unit_tests install testonly deps"
2023-10-20 chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com Automated Commit: Updated config generated by config-updater builder.
2023-10-20 semenzato@google.com service: starbase: fix arg to UpdateEbuildManifest
2023-10-20 sfrolov@google.com scripts: cros_run_unit_tests install testonly deps
2023-10-20 matthewb@chromium.org Revert "lib: cros_sdk_lib: Mount /run as tmpfs, bind mount /run/lock"
2023-10-19 saklein@chromium.org api: Proto refresh.
2023-10-19 vapier@chromium.org scripts: deploy_chrome: move lacros rm from shell command to argv list
2023-10-19 saklein@chromium.org service: sysroot: Report failed packages in UpdateChrootError.
2023-10-19 saklein@chromium.org telemetry: --log-telemetry option.
2023-10-19 jw.jung@navercorp.com Use flag arguments for verity
2023-10-19 semenzato@google.com service: further cleanup and target renaming
2023-10-19 vapier@chromium.org service: sysroot_unittest: mock out writing to /etc/cros_chroot_version
2023-10-19 vapier@chromium.org cbuildbot: deleted managed_chrome logic
2023-10-19 chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com Automated Commit: Updated config generated by config-updater builder.
2023-10-19 vapier@chromium.org scripts: cros_mark_chrome_as_stable: delete unused script
2023-10-19 nya@chromium.org service: BazelTest: Drop --build_tests_only
2023-10-19 tbain@google.com service: Fix TypeError when invoking Bazel
2023-10-18 jrosenth@chromium.org Generate /etc/os-release in SDK tarballs
2023-10-18 saklein@chromium.org chromite_config: root user owner handling.
2023-10-18 saklein@chromium.org lib: osutils: Minor clarification and spelling fixes.
2023-10-18 jonfan@google.com scripts: Stop throwing exception when _MountRootfsAsWritable fails
2023-10-18 bshai@google.com service: fix docker env variables
2023-10-18 tbain@google.com service: Collect Bazel performance artifacts
2023-10-18 vapier@chromium.org cbuildbot: extract minimal cros_mark_chrome_as_stable usage
2023-10-18 vapier@chromium.org scripts: deploy_chrome: move mount rebind from shell command to argv list
2023-10-18 chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com Automated Commit: Updated config generated by config-updater builder.
2023-10-18 vapier@chromium.org cbuildbot: delete SyncChrome stage
2023-10-18 tapted@chromium.org service: subtools: Add sys-devel/llvm to EXCLUDE_PACKAGES.
2023-10-18 semenzato@google.com service: starbase PUpr: fix format + add logging
2023-10-18 chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com Automated Commit: Updated config generated by config-updater builder.
2023-10-18 briannorris@chromium.org lib: cros_sdk_lib: Migrate chroot/var/{cache,log,tmp} to out/
2023-10-18 saklein@chromium.org osutils: Move GetNonRootUser to os_util.
2023-10-17 gbiv@google.com toolchain: remove builder-generated LLVM PGO bits
2023-10-17 saklein@chromium.org Scrub CROS_WORKON_SRCPATH.
2023-10-17 tapted@chromium.org scripts: Remove the test package from build_sdk_subtools.
2023-10-17 tapted@chromium.org api: subtools: Switch build API endpoint to virtual/target-sdk-subtools.
2023-10-17 bshai@google.com service: add luci auth support to signing docker
2023-10-17 vapier@chromium.org config: disable sync_chrome everywhere
2023-10-17 vapier@chromium.org scripts: cros_mark_as_stable: change --boards to space delimited
2023-10-17 vapier@chromium.org cbuildbot: delete chrome_sdk support
2023-10-17 vapier@chromium.org scripts: deploy_chrome: move stateful remount from shell command to argv list
2023-10-17 briannorris@chromium.org cli: cros try: Get PATH just the way we want it
2023-10-17 chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com Automated Commit: Updated config generated by config-updater builder.
2023-10-17 saklein@chromium.org lib: Global patch for portage_util._GetSysrootTool.
2023-10-17 vapier@chromium.org cbuildbot: delete unused --nochromesdk option
2023-10-17 tapted@chromium.org lib: subtools: allow files to come from multiple ebuild sources.
2023-10-17 briannorris@chromium.org lib: cros_sdk_lib: Mount /run as tmpfs, bind mount /run/lock
2023-10-16 vapier@chromium.org scripts: deploy_chrome: move root remount from shell command to argv list
2023-10-16 vapier@chromium.org scripts: cros_mark_android_as_stable: change --boards to space delimited
2023-10-16 saklein@chromium.org scripts: Run cros_list_modified_packages in the SDK.
2023-10-16 semenzato@google.com service: uprev_starbase_artifacts: add missing path component
2023-10-16 vapier@chromium.org cbuildbot: delete chrome_sdk_build_chrome support
2023-10-16 vapier@chromium.org scripts: deploy_chrome: move last login command from shell to argv list
2023-10-16 saklein@chromium.org lint: portage_layout_conf: master order validation.
2023-10-16 chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com Automated Commit: Updated config generated by config-updater builder.
2023-10-16 briannorris@chromium.org cli: build-packages: Drop --rebuild
2023-10-16 iby@chromium.org lib: deploy_chrome: Also copy metadata.json for Lacros
2023-10-16 vapier@chromium.org scripts: cros_sdk: stop passing $DEPOT_TOOLS down
2023-10-16 vapier@chromium.org scripts: deploy_chrome: move dbus restart from shell command to argv list
2023-10-16 vapier@chromium.org lib: cros_sdk_lib: stop writing locale.gen
2023-10-16 vapier@chromium.org lib: portage_util: log a clear warning when parsing 9999 ebuilds fail
2023-10-16 saklein@chromium.org image_lib: Type fixes.
2023-10-16 vapier@chromium.org scripts: cros_mark_chrome_as_stable: change --boards to space delimited
2023-10-16 vapier@chromium.org lib: portage_util: handle missing workon vars gracefully
2023-10-16 vapier@chromium.org config: disable chrome_sdk everywhere
2023-10-16 semenzato@google.com service: change starbase-artifacts ebuild location
2023-10-16 tapted@chromium.org lib: subtools: Follow symlinks before getting the file type.
2023-10-16 hscham@chromium.org ide: CROS_WORKON_DESTDIR is always an array like CROS_WORKON_LOCALNAME
2023-10-16 hscham@chromium.org ide: move all ebuild-related features to src/features/chromiumos/ebuild/
2023-10-16 oka@google.com ide: run tast tests: Unit test cancellation
2023-10-16 oka@google.com ide: Make commonUtil.CancelledError extend vscode.CancellationError
2023-10-16 oka@google.com ide: run tast tests: Improve unit test coverage
2023-10-16 oka@google.com ide: Improve messages for the result of running Tast tests
2023-10-16 ttylenda@chromium.org lib: namespaces: add new UID/GID args in CreateUserNs
2023-10-16 ttylenda@chromium.org ide: Bump the version to 0.23.2 for pre-release
2023-10-14 ttylenda@chromium.org sysroot: support lite-bazel build with a limited set of packages
2023-10-14 sfrolov@google.com cli: cop: add app-portage/gentoolkit to exceptions
2023-10-13 msturner@google.com lib: Set PKG_CONFIG_FDO_SYSROOT_RULES=1
2023-10-13 saklein@chromium.org service: setup_board: Skip chroot update on regen configs.
2023-10-13 xcl@google.com service: sdk: Log binhosts for update_chroot
2023-10-13 briannorris@chromium.org cli: cros query: Handle bad positional args
2023-10-13 saklein@chromium.org chromite_config: Use non-root user's config as root.
2023-10-13 jrosenth@chromium.org api: Regen protos
2023-10-13 vapier@chromium.org scripts: deploy_chrome: move lsof from shell command to argv list
2023-10-13 allenwebb@google.com scripts: package_has_missing_deps handle `virtual/libgudev`
2023-10-13 vapier@chromium.org scripts: deploy_chrome: use mkdir API instead of ad-hoc call
2023-10-13 fshao@chromium.org lib: constants: Support ~ in email regex
2023-10-13 oka@google.com ide: Don't throw in runTastTests
2023-10-13 oka@google.com ide: Show error message on cancelling running Tast tests
2023-10-13 nya@chromium.org api: Implement BazelTest endpoint
2023-10-13 ttylenda@chromium.org api: sysroot: fix lint error
2023-10-13 kimjae@chromium.org lib: Factory image mask DLC metadata
2023-10-12 tapted@chromium.org lib: Fix type signatures using `constants.SOURCE_ROOT` as str.
2023-10-12 vapier@chromium.org scripts: deploy_chrome: move df from shell command to argv list
2023-10-12 vapier@chromium.org utils: os_util: refactor sudo switch logic out of namespaces
2023-10-12 kimjae@chromium.org lib: Validate squashfs image for correctness
2023-10-12 briannorris@chromium.org lib: portage_util: Implement GetBoardUseFlags() with build_query
2023-10-12 engeg@google.com Revert "scripts: cros_run_unit_tests install testonly deps"
2023-10-12 hscham@chromium.org ide: use portage parser to provide ebuild links
2023-10-12 hscham@chromium.org ide: add hover for predefined read-only and ebuild-defined variables
2023-10-12 nya@chromium.org api: roll proto bindings
2023-10-12 briannorris@chromium.org service: image: cros_vm -> cros vm
2023-10-12 sfrolov@google.com scripts: cros_run_unit_tests install testonly deps
2023-10-11 briannorris@chromium.org scripts: cros_sdk: Support --read-only chroot
2023-10-11 briannorris@chromium.org service: sdk: Remount read/write for Update
2023-10-11 tapted@chromium.org lib: Rename sysroot.Path -> sysroot.JoinPath
2023-10-11 sfrolov@google.com cli: fix printed image relative path
2023-10-11 chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com Automated Commit: Updated config generated by config-updater builder.
2023-10-11 hscham@chromium.org ide: portage ebuild parser includes vscode.Range of parsed items
2023-10-11 hscham@chromium.org ide: parse.test.ts: move realistic example to a stand-alone file
2023-10-10 jrosenth@chromium.org lib: cros_build_lib: Preserve environment when creating a tarball
2023-10-10 briannorris@chromium.org lib: cros_sdk_lib: Restore source_root recursive bind ordering
2023-10-10 briannorris@chromium.org lib: cros_sdk_lib: Use chroot parameters for cwd translation
2023-10-10 briannorris@chromium.org lib: partial_mock: Spelling
2023-10-10 briannorris@chromium.org lib: cros_sdk_lib: Add Chroot{ReadWrite,ReadOnly) context managers
2023-10-10 briannorris@chromium.org lib: osutils: Add IsMountedReadonly() helper
2023-10-10 jackneus@google.com api: payload: plumb local signing params through from GenerationRequest
2023-10-10 vapier@chromium.org utils: prctl: add NO_NEW_PRIVS helpers
2023-10-10 chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com Automated Commit: Updated config generated by config-updater builder.
2023-10-10 ttylenda@chromium.org ide: fix indentation in test data using dedent
2023-10-10 fqj@chromium.org ide: Bump the version to 0.23.1 for pre-release
2023-10-10 ttylenda@chromium.org ide: test for ebuilds where local name starts with ".."
2023-10-10 tapted@chromium.org lib: Have cipd.search_instances return an empty list when no package.
2023-10-10 nergi@google.com service: Remove XkbToKcmConverter from system images
2023-10-10 tapted@chromium.org licensing: Generalise file exclusions based on extension.
2023-10-10 tapted@chromium.org lib: Show `cipd create` output.
2023-10-10 rrangel@chromium.org service: Add target/ prefix to bazel invocation
2023-10-09 chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com Automated Commit: Updated config generated by config-updater builder.
2023-10-09 briannorris@chromium.org README: Drop "trunk"
2023-10-09 vapier@chromium.org licensing: link to CrOS public manifest if available
2023-10-09 jackneus@google.com lib: signer_payloads_client: Read and return hash signatures
2023-10-09 jrosenth@chromium.org scripts: Restore Cq-Depend parsing on "gerrit deps"
2023-10-08 jrosenth@chromium.org Reland "Require Python 3.8+"
2023-10-07 jrosenth@chromium.org Revert "service: needs_chrome_source: search for binpkgs in virtual/target depgraph"
2023-10-06 chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com Automated Commit: Updated config generated by config-updater builder.
2023-10-06 allenwebb@google.com scripts: package_has_missing_deps: Add missing commas
2023-10-06 vapier@chromium.org lint: owners: have people use shared owners for bot accounts
2023-10-06 vapier@chromium.org utils: prctl: add {G,S}ET_NAME helpers

If this roll has caused a breakage, revert this CL and stop the roller
using the controls here:
https://autoroll.skia.org/r/chromite-chromium-autoroll
Please CC chrome-os-gardeners-reviews@google.com,chrome-os-gardeners@google.com,chromeos-velocity@google.com,yoshiki@google.com on the revert to ensure that a human
is aware of the problem.

To file a bug in Chromium: https://bugs.chromium.org/p/chromium/issues/entry

To report a problem with the AutoRoller itself, please file a bug:
https://issues.skia.org/issues/new?component=1389291&template=1850622

Documentation for the AutoRoller is here:
https://skia.googlesource.com/buildbot/+doc/main/autoroll/README.md

Cq-Include-Trybots: luci.chrome.try:chromeos-betty-pi-arc-chrome
Tbr: chrome-os-gardeners-reviews@google.com,yoshiki@google.com
Change-Id: I6b34c100285486f289eb794d19a943a68e901d27
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4977691
Commit-Queue: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>
Bot-Commit: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>
Cr-Commit-Position: refs/heads/main@{#1215321}