Revert "base/allocator: Move free-standing functions into PartitionRoot."
This reverts commit 6cbaba98a653ef970fdf15cade117e2b4dca52c7.

Reason for revert: Compile fail.
https://ci.chromium.org/p/chromium/builders/ci/GPU%20Linux%20Builder/208871?
[54/8426] CXX obj/base/base/partition_alloc.o
FAILED: obj/base/base/partition_alloc.o
/b/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF...(too long)
../../base/allocator/partition_allocator/partition_alloc.cc:468:16: error: explicit instantiation of 'PartitionReallocGenericFlags' does not refer to a function template, variable template, member function, member class, or static data member
template void* PartitionReallocGenericFlags<false>(PartitionRoot<false>*,
^

Original change's description:
> base/allocator: Move free-standing functions into PartitionRoot.
> 
> Bug: 787153
> Change-Id: Ic893d28524271bea0146cf203be252455f8deb1f
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2245598
> Reviewed-by: Kentaro Hara <haraken@chromium.org>
> Commit-Queue: Benoit L <lizeb@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#778707}

TBR=haraken@chromium.org,lizeb@chromium.org

Change-Id: I5037e0db9014065fa54ae17e161c5133242b2b30
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 787153
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2247464
Reviewed-by: Alan Cutter <alancutter@chromium.org>
Commit-Queue: Alan Cutter <alancutter@chromium.org>
Cr-Commit-Position: refs/heads/master@{#778711}