Revert of Isolate nacl_loader_unittests (https://codereview.chromium.org/322333006/)
Reason for revert:
This is causing the following error when running gyp_chromium with disable_nacl=1:

Traceback (most recent call last):
  File "./build/gyp_chromium", line 314, in <module>
    gyp_rc = gyp.main(args)
  File "/chromium/src/tools/gyp/pylib/gyp/__init__.py", line 527, in main
    return gyp_main(args)
  File "/chromium/src/tools/gyp/pylib/gyp/__init__.py", line 503, in gyp_main
    options.circular_check)
  File "/chromium/src/tools/gyp/pylib/gyp/__init__.py", line 129, in Load
    params['parallel'], params['root_targets'])
  File "/chromium/src/tools/gyp/pylib/gyp/input.py", line 2759, in Load
    RemoveLinkDependenciesFromNoneTargets(targets)
  File "/chromium/src/tools/gyp/pylib/gyp/input.py", line 1483, in RemoveLinkDependenciesFromNoneTargets
    if targets[t].get('variables', {}).get('link_dependency', 0):
KeyError: '/chromium/src/components/nacl.gyp:nacl_loader_unittests#target'


Original issue's description:
> Isolate nacl_loader_unittests
> 
> Isolate the Linux-only nacl_loader_unittests.
> 
> BUG=384515
> TBR=maruel
> NOTRY=true
> 
> Committed: https://src.chromium.org/viewvc/chrome?view=rev&revision=278620

TBR=vadimsh@chromium.org,mseaborn@chromium.org,maruel@chromium.org,jln@chromium.org
NOTREECHECKS=true
NOTRY=true
BUG=384515

Review URL: https://codereview.chromium.org/348803004

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@278643 0039d316-1c4b-4281-b951-d872f2087c98