Revert of Eliminate //chrome dependencies from MetricsServicesManager (patchset #4 id:120001 of https://codereview.chromium.org/1411593004/ )
Reason for revert:
Broke compilation on Google Chrome ChromeOS Google Chrome Linux x64 Google Chrome Mac

http://build.chromium.org/p/chromium.chrome/buildstatus?builder=Google%20Chrome%20Mac&number=4769

FAILED: /b/build/goma/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/chrome/browser/metrics/browser.metrics_services_manager.o.d -DV8_DEPRECATION_WARNINGS -DCLD_VERSION=2 -D__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORE=0 -DGOOGLE_CHROME_BUILD -DCR_CLANG_REVISION=247874-1 -DENABLE_RLZ -DUSE_LIBJPEG_TURBO=1 -DENABLE_ONE_CLICK_SIGNIN -DENABLE_PRE_SYNC_BACKUP -DENABLE_WEBRTC=1 -DENABLE_MEDIA_ROUTER=1 -DUSE_PROPRIETARY_CODECS -DENABLE_PEPPER_CDMS -DENABLE_CONFIGURATION_POLICY -DENABLE_NOTIFICATIONS -DENABLE_HIDPI=1 -DSYSTEM_NATIVELY_SIGNALS_MEMORY_PRESSURE -DENABLE_TASK_MANAGER=1 -DENABLE_EXTENSIONS=1 -DENABLE_PDF=1 -DENABLE_PLUGIN_INSTALLATION=1 -DENABLE_PLUGINS=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_THEMES=1 -DENABLE_AUTOFILL_DIALOG=1 -DENABLE_PROD_WALLET_SERVICE=1 -DENABLE_BACKGROUND=1 -DENABLE_GOOGLE_NOW=1 -DENABLE_PRINTING=1 -DENABLE_BASIC_PRINTING=1 -DENABLE_PRINT_PREVIEW=1 -DENABLE_SPELLCHECK=1 -DUSE_BROWSER_SPELLCHECKER=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_APP_LIST=1 -DENABLE_SETTINGS_APP=1 -DENABLE_SUPERVISED_USERS=1 -DENABLE_SERVICE_DISCOVERY=1 -DENABLE_WIFI_BOOTSTRAPPING=1 -DENABLE_HANGOUT_SERVICES_EXTENSION=1 -DV8_USE_EXTERNAL_STARTUP_DATA -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DMOJO_USE_SYSTEM_IMPL -DTOOLKIT_VIEWS=1 -DPROTOBUF_USE_DLLS -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DSK_SUPPORT_GPU=1 -DSK_IGNORE_LINEONLY_AA_CONVEX_PATH_OPTS -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DU_STATIC_IMPLEMENTATION -DLIBXML_STATIC '-DI18N_ADDRESS_VALIDATION_DATA_URL="https://i18napis.appspot.com/ssl-aggregate-address/"' -DI18N_ADDRESSINPUT_USE_BASICTYPES_OVERRIDE=1 -DWEBRTC_CHROMIUM_BUILD -DWEBRTC_MAC -DWEBRTC_POSIX -DMESA_EGL_NO_X11_HEADERS -DHUNSPELL_STATIC -DHUNSPELL_CHROME_CLIENT -DUSE_HUNSPELL -DUSE_CUPS -DUSE_LIBPCI=1 -DUSE_OPENSSL=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DNDEBUG -DOFFICIAL_BUILD -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -D_FORTIFY_SOURCE=2 -Igen -I../.. -Iobj/chrome/browser.gen -I../../skia/config -I../../third_party/khronos -I../../gpu -Igen/angle -I../../third_party/WebKit/Source -Igen/protoc_out -I../../third_party/protobuf -I../../third_party/protobuf/src -I../../third_party/dom_distiller_js/dist/proto_gen -Igen/chrome -Igen/components/strings -I../../third_party/WebKit -I../../third_party/mojo/src -Igen/third_party/mojo/src -I../../third_party/skia/include/core -I../../third_party/skia/include/effects -I../../third_party/skia/include/pdf -I../../third_party/skia/include/gpu -I../../third_party/skia/include/lazy -I../../third_party/skia/include/pathops -I../../third_party/skia/include/pipe -I../../third_party/skia/include/ports -I../../third_party/skia/include/utils -I../../third_party/skia/include/utils/mac -I../../skia/ext -I../../third_party/cacheinvalidation/overrides -I../../third_party/cacheinvalidation/src -I../../third_party/cacheinvalidation/google/cacheinvalidation -I../../third_party/icu/source/i18n -I../../third_party/icu/source/common -I../../third_party/libxml/mac/include -I../../third_party/libxml/src/include -I../../third_party/zlib -Igen/ui/resources -I../../third_party/re2 -Igen/components -Igen/content/app/resources/ -I../../third_party/opus/src/include -I../../third_party/leveldatabase/src/include -I../../third_party/leveldatabase/src -I../../third_party/leveldatabase -I../../third_party/libaddressinput/chromium/override -I../../third_party/libaddressinput/src/cpp/include -Igen/third_party/libaddressinput/ -I../../third_party/libyuv/include -I../../third_party/libyuv -I../../third_party/webrtc_overrides -I../../third_party -I../../third_party/mesa/src/include -I../../v8/include -Igen/ui/views/resources -Igen/policy -I../../third_party/google_toolbox_for_mac -I../../third_party/google_toolbox_for_mac/src -I../../third_party/google_toolbox_for_mac/src/AppKit -I../../third_party/google_toolbox_for_mac/src/DebugUtils -I../../third_party/google_toolbox_for_mac/src/Foundation -isysroot /Applications/Xcode5.1.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -O2 -gdwarf-2 -fvisibility=hidden -Werror -Wnewline-eof -mmacosx-version-min=10.6 -arch x86_64 -Wall -Wendif-labels -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wno-selector-type-mismatch -Wpartial-availability -Wheader-hygiene -Wno-char-subscripts -Wno-unneeded-internal-declaration -Wno-covered-switch-default -Wstring-conversion -Wno-c++11-narrowing -Wno-deprecated-register -Wno-inconsistent-missing-override -Wno-shift-negative-value -Wno-bitfield-width -Wexit-time-destructors -std=c++11 -fno-rtti -fno-exceptions -fvisibility-inlines-hidden -fno-threadsafe-statics -Xclang -load -Xclang /b/build/slave/google-chrome-rel-mac/build/src/third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.dylib -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang check-templates -fcolor-diagnostics -fno-strict-aliasing -fno-standalone-debug  -c ../../chrome/browser/metrics/metrics_services_manager.cc -o obj/chrome/browser/metrics/browser.metrics_services_manager.o
../../chrome/browser/metrics/metrics_services_manager.cc:107:5:error: expected ')'
    recording_groups |= rappor::SAFEBROWSING_RAPPOR_GROUP;
    ^
../../chrome/browser/metrics/metrics_services_manager.cc:106:6: note: to match this '('
  if (client_->IsSafeBrowsingEnabled(on_safe_browsing_update_callback)
     ^
1 error generated.
ninja: build stopped: subcommand failed.

Original issue's description:
> Eliminate //chrome dependencies from MetricsServicesManager
>
> This CL eliminates //chrome dependencies from MetricsServicesManager in
> preparation for componentizing that file to share with iOS. To do so, we
> introduce MetricsServicesManagerClient, which encapsulates the embedder
> information that MetricsServicesManager previously internalized.
>
> BUG=508025
> TBR=thestig, droger
>
> Committed: https://crrev.com/40b14cfa3f3458ae0d6f655886d952389aabc25c
> Cr-Commit-Position: refs/heads/master@{#355255}

TBR=asvitkine@chromium.org,droger@chromium.org,thestig@chromium.org,blundell@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=508025

Review URL: https://codereview.chromium.org/1418763002

Cr-Commit-Position: refs/heads/master@{#355262}