ScopedThrottlingToken: Include <memory> for std::unique_ptr
IWYU. This fixes the build with libstdc++ after c1ab712a08 ("Stop using
x-devtools-emulate-network-conditions-client-id header"):

    In file included from ../../services/network/throttling/scoped_throttling_token.cc:5:0:
    ../../services/network/throttling/scoped_throttling_token.h:29:15: error: ‘unique_ptr’ in namespace ‘std’ does not name a template type
       static std::unique_ptr<ScopedThrottlingToken> MaybeCreate(
                   ^~~~~~~~~~

Bug: 819294
Cq-Include-Trybots: luci.chromium.try:linux_mojo
Change-Id: I66b2db483ac9e90d0a132a65f83f15aa673f12f9
Reviewed-on: https://chromium-review.googlesource.com/1105825
Reviewed-by: Tsuyoshi Horo <horo@chromium.org>
Reviewed-by: Kinuko Yasuda <kinuko@chromium.org>
Commit-Queue: Raphael Kubo da Costa <raphael.kubo.da.costa@intel.com>
Cr-Commit-Position: refs/heads/master@{#568746}