Revert "Roll Depot Tools from 647cfe6bf10e to 10dbd7babddc (29 revisions)"
This reverts commit a3fce5e719193f142cf9380bd3c64c289aa1e1b7.

Reason for revert: Broke compile on all the bots:

FAILED: gen/chrome/browser/expired_flags_list.cc
python3 ../../tools/flags/generate_expired_list.py ../../chrome/browser/flag-metadata.json gen/chrome/browser/expired_flags_list.cc
Traceback (most recent call last):
File "../../tools/flags/generate_expired_list.py", line 21, in <module>
import list_flags
File "/b/s/w/ir/cache/builder/src/tools/flags/list_flags.py", line 24, in <module>
import owners
ModuleNotFoundError: No module named 'owners'


Original change's description:
> Roll Depot Tools from 647cfe6bf10e to 10dbd7babddc (29 revisions)
>
> https://chromium.googlesource.com/chromium/tools/depot_tools.git/+log/647cfe6bf10e..10dbd7babddc
>
> 2022-08-08 gavinmak@google.com Remove old DepotToolsOwners implementation
> 2022-08-08 recipe-mega-autoroller@chops-service-accounts.iam.gserviceaccount.com Roll recipe dependencies (trivial).
> 2022-08-06 recipe-mega-autoroller@chops-service-accounts.iam.gserviceaccount.com Roll recipe dependencies (trivial).
> 2022-08-05 brucedawson@chromium.org Improve presubmit no-network handling
> 2022-08-05 chanli@chromium.org [led] roll led
> 2022-08-05 chanli@chromium.org [depot_tools] roll led
> 2022-08-05 jojwang@chromium.org Add debug logs during Clone process.
> 2022-08-05 jwata@google.com Revert "Update led to the current version."
> 2022-08-05 jwata@google.com Revert "[depot_tools] roll led"
> 2022-08-05 bryner@google.com vpython(3) no longer needs to bootstrap python.
> 2022-08-04 chanli@chromium.org [depot_tools] roll led
> 2022-08-04 yukishiino@chromium.org Allow 'noparent' in DEPS
> 2022-08-03 gbeaty@chromium.org Update led to the current version.
> 2022-08-03 jojwang@chromium.org Add jojwang to OWNERS
> 2022-08-03 bryner@google.com Use the bundled interpreter instead of passing -vpython-interpreter.
> 2022-08-02 brucedawson@chromium.org Report more issues as errors with presubmit --all
> 2022-08-02 qyearsley@chromium.org Update lucicfg version 1.32.0 to 1.32.1
> 2022-08-01 bryner@google.com New vpython to depot_tools.
> 2022-08-01 jojwang@chromium.org [no-sync] bot_update: Remove previous no-sync exp changes and implement new one.
> 2022-08-01 jojwang@chromium.org [no-sync] Save previous values to files.
> 2022-07-29 recipe-mega-autoroller@chops-service-accounts.iam.gserviceaccount.com Roll recipe dependencies (trivial).
> 2022-07-28 zhihuixie@google.com depot_tools: Roll rdb
> 2022-07-28 arthurmilchior@google.com Clarify documentation from `gclient recurse`
> 2022-07-28 recipe-mega-autoroller@chops-service-accounts.iam.gserviceaccount.com Roll recipe dependencies (trivial).
> 2022-07-28 vadimsh@chromium.org [lucicfg] Update v1.31.5 => v1.32.0.
> 2022-07-27 jojwang@chromium.org [no-sync] Set _should_sync and add flag to control if the experiment should be enabled.
> 2022-07-27 brucedawson@chromium.org Treat UnitTests failures as presubmit --all errors
> 2022-07-25 recipe-mega-autoroller@chops-service-accounts.iam.gserviceaccount.com Roll recipe dependencies (trivial).
> 2022-07-25 recipe-mega-autoroller@chops-service-accounts.iam.gserviceaccount.com Roll recipe dependencies (trivial).
>
> If this roll has caused a breakage, revert this CL and stop the roller
> using the controls here:
> https://autoroll.skia.org/r/depot-tools-chromium-autoroll
> Please CC ajp@google.com,aravindvasudev@google.com,gavinmak@google.com,sokcevic@google.com on the revert to ensure that a human
> is aware of the problem.
>
> To file a bug in Chromium: https://bugs.chromium.org/p/chromium/issues/entry
>
> To report a problem with the AutoRoller itself, please file a bug:
> https://bugs.chromium.org/p/skia/issues/entry?template=Autoroller+Bug
>
> Documentation for the AutoRoller is here:
> https://skia.googlesource.com/buildbot/+doc/main/autoroll/README.md
>
> Bug: chromium:1151236,chromium:1171945,chromium:1309977,chromium:1318617,chromium:1339472,chromium:1347252,chromium:1348269,chromium:1349905,chromium:1350060,chromium:1350210,chromium:1350227
> Tbr: ajp@google.com,aravindvasudev@google.com,gavinmak@google.com,sokcevic@google.com
> Change-Id: I679e023e4d31c8893a0e160de06fc10dc560f338
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3818371
> Bot-Commit: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>
> Commit-Queue: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>
> Cr-Commit-Position: refs/heads/main@{#1032807}

Bug: chromium:1151236,chromium:1171945,chromium:1309977,chromium:1318617,chromium:1339472,chromium:1347252,chromium:1348269,chromium:1349905,chromium:1350060,chromium:1350210,chromium:1350227
Change-Id: Ibc7e7489cfb6ccdc7148fc7e903a28d7edb40600
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3817230
Auto-Submit: Adam Rice <ricea@chromium.org>
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Cr-Commit-Position: refs/heads/main@{#1032813}