Revert "Rename PCAService Model Executors to Handlers"
This reverts commit 3b56bcf7beb10f04a46eb10dcc3b95a1c5b5e6e3.

Reason for revert: Compilation failure, see https://ci.chromium.org/ui/p/chrome/builders/ci/arm-unpublished-builder/21975/overview

../../components/optimization_guide/internal/page_entities_model_executor_impl_unittest.cc:5:10: fatal error: 'components/optimization_guide/core/page_entities_model_executor_impl.h' file not found
#include "components/optimization_guide/core/page_entities_model_executor_impl.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated. 

Original change's description:
> Rename PCAService Model Executors to Handlers
>
> These classes live on the UI thread, so they should have been named
> Handler to start with.
>
> Also renames the UMA to keep everything tidy.
>
> Bug: b/259406572
> Change-Id: Ice96b69aeebc8b7bae4ffd0ef44e9c2782506af8
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4032026
> Commit-Queue: Robert Ogden <robertogden@chromium.org>
> Reviewed-by: Sophie Chang <sophiechang@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1074921}

Bug: b/259406572
Change-Id: I31bdbd7637020bfdc0a446b9f727eaeb632ef202
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4049633
Owners-Override: Theresa Sullivan <twellington@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Auto-Submit: Theresa Sullivan <twellington@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1074983}