Revert "More inclusive terminology for chrome/browser/win/conflicts/."
This reverts commit e0e81ba95ea1b2a630458fa927694660a6be8319.

Reason for revert: Breaks win64-chrome :(

[12574/27367] CXX obj/chrome/browser/browser/third_party_module_list_component_installer_win.obj
FAILED: obj/chrome/browser/browser/third_party_module_list_component_installer_win.obj
c:\b\s\w\ir\cache\goma\client\gomacc.exe ..\..\third_party\llvm-build\Release+Asserts\bin\clang-cl.e...(too long)
../../chrome/browser/component_updater/third_party_module_list_component_installer_win.cc(17,10): fatal error: 'chrome/browser/win/conflicts/module_blacklist_cache_util.h' file not found
#include "chrome/browser/win/conflicts/module_blacklist_cache_util.h"

https://ci.chromium.org/p/chrome/builders/ci/win64-chrome/10472

Original change's description:
> More inclusive terminology for chrome/browser/win/conflicts/.
>
> Bug: 1097283
> Change-Id: I570f98b1f42487aff2696c50f87fd0832667379b
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2547620
> Commit-Queue: Gabriel Charette <gab@chromium.org>
> Auto-Submit: Peter Kasting <pkasting@chromium.org>
> Reviewed-by: Gabriel Charette <gab@chromium.org>
> Reviewed-by: Jesse Doherty <jwd@chromium.org>
> Reviewed-by: Patrick Monette <pmonette@chromium.org>
> Reviewed-by: Ted Choc <tedchoc@chromium.org>
> Reviewed-by: Chris Hamilton <chrisha@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#830830}

TBR=pkasting@chromium.org,chrisha@chromium.org,gab@chromium.org,jwd@chromium.org,tedchoc@chromium.org,pmonette@chromium.org

Change-Id: Ibe482cba992b06bfc58fc1eaee200cca11b10d72
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 1097283
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2558083
Commit-Queue: Giovanni Ortuño Urquidi <ortuno@chromium.org>
Reviewed-by: Giovanni Ortuño Urquidi <ortuno@chromium.org>
Cr-Commit-Position: refs/heads/master@{#830887}