Revert "Add test coverage for scrolling vertical tabs via drag."
This reverts commit ba5eb45d66047eea237c0fbc97a1339effb98dc9.

Reason for revert: Likely caused compile failure:

[14856/15379] CXX obj/chrome/browser/ui/views/tabs/vertical/interactive_ui_tests/vertical_tab_drag_interactive_uitest.o obj/chrome/browser/ui/views/tabs/vertical/interactive_ui_tests/vertical_tab_drag_interactive_uitest.dwo
../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/chrome/browser/ui/views/tabs/vertical/interactive_ui_tests/vertical_tab_...(too long)
../../chrome/browser/ui/views/tabs/vertical/vertical_tab_drag_interactive_uitest.cc:267:34: error: no member named 'unpinned_tabs_scroll_view_for_testing' in 'VerticalTabStripView'
  267 |           return tab_strip_view->unpinned_tabs_scroll_view_for_testing()
      |                  ~~~~~~~~~~~~~~  ^
In file included from ../../chrome/browser/ui/views/tabs/vertical/vertical_tab_drag_interactive_uitest.cc:8:
In file included from ../../base/functional/bind.h:14:

Original change's description:
> Add test coverage for scrolling vertical tabs via drag.
>
> This adds the DragToScroll test case to VerticalTabDragTest, which
> verifies that dragging a tab to the edges of the vertical tab strip
> triggers automatic scrolling in the correct direction.
>
> Change-Id: I56b7c06f8a869d3740629f07f1b01d6ec9dc8b95
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7862078
> Commit-Queue: Kaan Alsan <alsan@chromium.org>
> Reviewed-by: Alison Gale <agale@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1634293}

No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Change-Id: I655a373ae5924d73a3e707337043dd4470e75b30
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7868750
Owners-Override: Samuel Huang <huangs@chromium.org>
Bot-Commit: rubber-stamper@appspot.gserviceaccount.com <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Samuel Huang <huangs@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1634311}