Revert of Cast:Add resolution settings to receiver app (https://codereview.chromium.org/203223003/)
Reason for revert:
Broke compilation again on Chromium on Linux x64:

../../media/cast/test/receiver.cc: In function 'void media::cast::GetResolution(int*, int*)':
../../media/cast/test/receiver.cc:99:60:error: invalid conversion from 'int' to 'const char*' [-fpermissive]
/usr/include/c++/4.6/bits/basic_string.tcc:214:5:error:   initializing argument 1 of 'std::basic_string<_CharT, _Traits, _Alloc>::basic_string(const _CharT*, const _Alloc&) [with _CharT = char, _Traits = std::char_traits<char>, _Alloc = std::allocator<char>]' [-fpermissive]
../../media/cast/test/receiver.cc:103:59:error: invalid conversion from 'int' to 'const char*' [-fpermissive]
/usr/include/c++/4.6/bits/basic_string.tcc:214:5:error:   initializing argument 1 of 'std::basic_string<_CharT, _Traits, _Alloc>::basic_string(const _CharT*, const _Alloc&) [with _CharT = char, _Traits = std::char_traits<char>, _Alloc = std::allocator<char>]' [-fpermissive]


Original issue's description:
> Cast:Add resolution settings to receiver app
> 
> 
> Add an option for the user the set the resolution in run-time,
> plus some clean up.
> 
> Committed: https://src.chromium.org/viewvc/chrome?view=rev&revision=257948
> 
> Committed: https://src.chromium.org/viewvc/chrome?view=rev&revision=258277

TBR=pwestin@chromium.org,mikhal@chromium.org
NOTREECHECKS=true
NOTRY=true

Review URL: https://codereview.chromium.org/206533003

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@258308 0039d316-1c4b-4281-b951-d872f2087c98