ts_library: Improve error message when path mappings are missing.
When a new cr_components/ folder is added, a new path mapping needs to
be added in tools/typescript/path_mappings.py, so that ts_library() can
automatically add such mappings based on |deps|.

The error message given previously if one forgot to add such a mapping
was not very helpful ("AssertionError" without any description). After
this change a clear instruction will be surfaced as follows

AssertionError: Missing path mapping for dependency
'//ui/webui/resources/cr_components/new_component:build_ts'. Update
//tools/typescript/path_mappings.py accordingly

Bug: 1412158
Change-Id: I9ce1c4d1f62662eca4b5ac379e40eb14aca3d63f
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4278083
Reviewed-by: Rebekah Potter <rbpotter@chromium.org>
Commit-Queue: Rebekah Potter <rbpotter@chromium.org>
Auto-Submit: Demetrios Papadopoulos <dpapad@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1108162}