Fix |pending| to force String type to |message| argument.
This fixes |pending| when it's called with invalid input, where it was
failing with "TypeError: message.replace is not a function" when
|message| argument was null, not provided or wrong type.

With this change the tests below no longer fail:
DriveSpecific/FileManagerBrowserTest.Test/2
DriveSpecific/FileManagerBrowserTest.Test/4
DriveSpecific/FileManagerBrowserTest.Test/5

Bug: 834507
Cq-Include-Trybots: master.tryserver.chromium.linux:closure_compilation
Change-Id: If060cdad8aa9d52b677947cceeadddb51068d654
Reviewed-on: https://chromium-review.googlesource.com/1018562
Reviewed-by: Noel Gordon <noel@chromium.org>
Commit-Queue: Luciano Pacheco (SYD) <lucmult@chromium.org>
Cr-Commit-Position: refs/heads/master@{#551958}