IWYU: include CrxUpdateItem for pair in accessibility main handler.
Fix build issue:
/usr/include/c++/9/bits/unordered_map.h:105:18:   required from ‘class std::unordered_map<std::__cxx11::basic_string<char>, update_client::CrxUpdateItem>’
../../chrome/browser/ui/webui/settings/accessibility_main_handler.h:72:7:   required from here
/usr/include/c++/9/bits/stl_pair.h:215:11: error: ‘std::pair<_T1, _T2>::second’ has incomplete type

Bug: 957519
Change-Id: I0c1f47c6cdd6f91828d3589bef4355d4602c2e1e
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2453451
Reviewed-by: Kyle Horimoto <khorimoto@chromium.org>
Commit-Queue: José Dapena Paz <jdapena@igalia.com>
Cr-Commit-Position: refs/heads/master@{#814575}