Reland "media/gpu/v4l2: Remove unused member from V4L2DecodeSurface"
This is a reland of commit aacbca5423b50f0aad7231ab4617c736e162d304

Original CL was reverted due to a printf modifier mistake:

...v4l2_decode_surface.cc:96:50: error: format specifies type 'int' but the argument has type 'size_t' (aka 'unsigned long') [-Werror,-Wformat]
base::StringAppendF(&out, "Buffer %d -> %d. ", input_buffer_.BufferId(),
~~           ^~~~~~~~~~~~~~~~~~~~~~~~
%zu

This CL fixes this in Patchsets after the second one.

Cq-Include-Trybots: luci.chromium.try:lacros-arm-generic-rel,lacros-arm64-generic-rel

Original change's description:
> media/gpu/v4l2: Remove unused member from V4L2DecodeSurface
>
> This CL removes V4L2DecodeSurface::input_record_ because it's
> unused, except for a debug printout where an alternative exists.
>
> No new functionality.
>
> Bug: b:222774780
> Change-Id: I88dd138a07ffe522947d9acc211c259ae81011a6
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3979248
> Reviewed-by: Nathan Hebert <nhebert@chromium.org>
> Commit-Queue: Miguel Casas-Sanchez <mcasas@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1063450}

Bug: b:222774780
Change-Id: I0d9000e3d647fc6401d3ec608ba8339066de2f0c
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3980000
Reviewed-by: Nathan Hebert <nhebert@chromium.org>
Commit-Queue: Miguel Casas-Sanchez <mcasas@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1063921}