IWYU: returning a unique_ptr<NativeDisplayDelegate> in OzonePlatformX11 requires its include
Fix build error with libstdc++:
    In file included from /usr/include/c++/12/memory:76,
                     from ../../ui/ozone/platform/x11/ozone_platform_x11.cc:7:
    /usr/include/c++/12/bits/unique_ptr.h: In instantiation of ‘void std::default_delete<_Tp>::operator()(_Tp*) const [with _Tp = display::NativeDisplayDelegate]’:
    /usr/include/c++/12/bits/unique_ptr.h:396:17:   required from ‘std::unique_ptr<_Tp, _Dp>::~unique_ptr() [with _Tp = display::NativeDisplayDelegate; _Dp = std::default_delete<display::NativeDisplayDelegate>]’
    ../../ui/ozone/platform/x11/ozone_platform_x11.cc:110:12:   required from here
    /usr/include/c++/12/bits/unique_ptr.h:93:23: error: invalid application of ‘sizeof’ to incomplete type ‘display::NativeDisplayDelegate’
       93 |         static_assert(sizeof(_Tp)>0,
          |                       ^~~~~~~~~~~

Bug: 957519
Change-Id: Icd27e79758c54d2bd4db9dbade86d58d1afd3982
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4626973
Reviewed-by: Nick Yamane <nickdiego@igalia.com>
Commit-Queue: José Dapena Paz <jdapena@igalia.com>
Cr-Commit-Position: refs/heads/main@{#1159852}