Revert "Add support for fetching experiments"
This reverts commit 84cf3e38409fdb23e3bb88a6cb9aa0ecb563bc3c.

Reason for revert: Some of the added tests have been very flaky since landing. The worst being All/ExperimentsManagerESAE2ETest.FetchingExperiments/0, see for example on
https://test-results.appspot.com/dashboards/flakiness_dashboard.html#tests=All%2FExperimentsManagerESAE2ETest.FetchingExperiments%2F0&testType=gcp_unittests

Example test output:

../../chrome/credential_provider/gaiacp/experiments_manager_unittests.cc(191): error: Expected equality of these values:
  experiment1_value
    Which is: "abc"
  ExperimentsManager::Get()->GetExperimentForUser( base::UTF16ToUTF8(OLE2W(sid)), Experiment::TEST_CLIENT_FLAG)
    Which is: "false"
Stack trace:
Backtrace:
	credential_provider::testing::ExperimentsManagerESAE2ETest_FetchingExperiments_Test::TestBody [0x00007FF624EC0ED6+3350] (o:\chrome\credential_provider\gaiacp\experiments_manager_unittests.cc:189)
	testing::internal::HandleExceptionsInMethodIfSupported<testing::Test,void> [0x00007FF6252EE67F+79] (o:\third_party\googletest\src\googletest\src\gtest.cc:2674)

../../chrome/credential_provider/gaiacp/experiments_manager_unittests.cc(194): error: Expected equality of these values:
  experiment2_value
    Which is: "def"
  ExperimentsManager::Get()->GetExperimentForUser( base::UTF16ToUTF8(OLE2W(sid)), Experiment::TEST_CLIENT_FLAG2)
    Which is: "false"
Stack trace:
Backtrace:
	credential_provider::testing::ExperimentsManagerESAE2ETest_FetchingExperiments_Test::TestBody [0x00007FF624EC1040+3712] (o:\chrome\credential_provider\gaiacp\experiments_manager_unittests.cc:192)
	testing::internal::HandleExceptionsInMethodIfSupported<testing::Test,void> [0x00007FF6252EE67F+79] (o:\third_party\googletest\src\googletest\src\gtest.cc:2674)



Original change's description:
> Add support for fetching experiments
>
> Bug: 1143836
> Change-Id: I0c787bf1c663b28d94e67c8015910dbcb48a4779
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2508633
> Commit-Queue: Yusuf Sengul <yusufsn@google.com>
> Reviewed-by: Rakesh Soma <rakeshsoma@google.com>
> Cr-Commit-Position: refs/heads/master@{#827540}

TBR=yusufsn@google.com,rakeshsoma@google.com,wrlewis@google.com,ssanapala@google.com

# Not skipping CQ checks because original CL landed > 1 day ago.

Bug: 1143836
Change-Id: Iad3912ce90d3d7f95a18b5747a8a6efbc68b11e9
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2544934
Reviewed-by: Marijn Kruisselbrink <mek@chromium.org>
Reviewed-by: Yusuf Sengul <yusufsn@google.com>
Commit-Queue: Marijn Kruisselbrink <mek@chromium.org>
Commit-Queue: Yusuf Sengul <yusufsn@google.com>
Cr-Commit-Position: refs/heads/master@{#828365}