Revert "Code cleanup: Fix includes in crOS inline login handler"
This reverts commit 198989217f761165f269a7e78574f9e783a74ed6.

Reason for revert: cause the error in chrome_session_manager_browsertest.cc

error: unknown type name 'StubInstallAttributes'; did you mean 'InstallAttributes'?

Bug:1364274

Original change's description:
> Code cleanup: Fix includes in crOS inline login handler
>
> Remove unneeded includes in:
>
> - inline_login_handler_chromeos.h
> - inline_login_handler_chromeos.cc
> - inline_login_handler_chromeos_browsertest.cc
> - inline_login_dialog_chromeos.h
> - chrome_session_manager_browsertest.cc
>
> This caused compilation failures in files which did not IWYU and
> unknowingly relied on transitive includes. Fix:
>
> - inline_login_dialog_chromeos.cc
> - chrome_session_manager.cc
>
> Change-Id: I7ee266b4e9887f662330ace6b72764c0d5805804
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3898952
> Reviewed-by: Roman Sorokin <rsorokin@google.com>
> Auto-Submit: Kush Sinha <sinhak@chromium.org>
> Commit-Queue: Roman Sorokin <rsorokin@google.com>
> Cr-Commit-Position: refs/heads/main@{#1047488}

Change-Id: I729a1fb812ed732bcf29c555797e80c5393a42d5
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3900346
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Reviewed-by: Andrew Xu <andrewxu@google.com>
Owners-Override: Andrew Xu <andrewxu@google.com>
Commit-Queue: Andrew Xu <andrewxu@google.com>
Cr-Commit-Position: refs/heads/main@{#1047689}