VideoFrame: Explicitly create a vector when creating a VideoFrameLayout
This fixes the GCC build after 53905008c ("Nuke set_strides in VideoFrame
and VideoFrameLayout"):

    ../../media/base/video_frame.cc: In static member function ‘static scoped_refptr<media::VideoFrame> media::VideoFrame::WrapExternalStorage(media::VideoPixelFormat, media::VideoFrame::StorageType, const gfx::Size&, const gfx::Rect&, const gfx::Size&, uint8_t*, size_t, base::TimeDelta, base::ReadOnlySharedMemoryRegion*, base::UnsafeSharedMemoryRegion*, base::SharedMemoryHandle, size_t)’:
    ../../media/base/video_frame.cc:963:75: error: call of overloaded ‘VideoFrameLayout(media::VideoPixelFormat&, const gfx::Size&, <brace-enclosed initializer list>)’ is ambiguous
                                {RowBytes(kYPlane, format, coded_size.width())}),
                                                                               ^
    In file included from ../../media/base/video_frame.h:28:0,
                     from ../../media/base/video_frame.cc:5:
    ../../media/base/video_frame_layout.h:67:3: note: candidate: media::VideoFrameLayout::VideoFrameLayout(media::VideoPixelFormat, const gfx::Size&, std::vector<media::VideoFrameLayout::Plane>, std::vector<long unsigned int>)
       VideoFrameLayout(VideoPixelFormat format,
       ^~~~~~~~~~~~~~~~
    ../../media/base/video_frame_layout.h:58:3: note: candidate: media::VideoFrameLayout::VideoFrameLayout(media::VideoPixelFormat, const gfx::Size&, std::vector<int>, std::vector<long unsigned int>)
       VideoFrameLayout(VideoPixelFormat format,
       ^~~~~~~~~~~~~~~~

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=84849 makes GCC fail to choose
the right overload when a class with multiple constructors that can take
initializer lists receive one.

Explicitly create an std::vector to resolve all ambiguities. See also:
https://chromium-review.googlesource.com/c/chromium/src/+/1170905

Bug: 819294
Change-Id: I594a8c8a69cfd600ebd505aa6bc3c8369c15fead
Reviewed-on: https://chromium-review.googlesource.com/c/1273528
Reviewed-by: John Rummell <jrummell@chromium.org>
Commit-Queue: Raphael Kubo da Costa (CET) <raphael.kubo.da.costa@intel.com>
Cr-Commit-Position: refs/heads/master@{#598518}