Revert "Selectively set AXMode depending on what UIA API is used."
This reverts commit d3fabb66f9d6358bf0f5c35e7a0d28e1748fbbbe.

Reason for revert: This caused a failing test 100% of the time on three Windows 7 test bots.  (It's passing on the Windows 10 test bots.)  See failures at:
https://ci.chromium.org/ui/p/chromium/builders/ci/Win7%20Tests%20(1)/116799/overview
https://ci.chromium.org/ui/p/chromium/builders/ci/Win%207%20Tests%20x64%20(1)/79836/overview
https://ci.chromium.org/ui/p/chromium/builders/ci/Win7%20Tests%20(dbg)(1)/90187/overview

The test failure is:
content/browser/accessibility/accessibility_win_browsertest.cc(5236): error: Expected: (first_child->get_CurrentLabeledBy(&labelled_by)) succeeds.
  Actual: 0x80004005 Unspecified error

Original change's description:
> Selectively set AXMode depending on what UIA API is used.
>
> New functionality is behind the kSelectiveUIAEnablement feature flag.
> This change adds the ability for UIA to be partially enabled
> depending on the API calls that are made. Previously, any UIA call
> would have resulted in us enabling all accessibility features, causing
> quite a bit of overhead for clients that do not require or use all
> the information
>
> This change should not have any user-facing effects, but should improve
> perf for non-screenreader UIA usage.
>
> Bug: 1213613
> AX-Relnotes: n/a
> Change-Id: I9c0b2e759d021374347d70596009c165fc2a85ce
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2915513
> Commit-Queue: Jacques Newman <janewman@microsoft.com>
> Reviewed-by: Daniel Libby <dlibby@microsoft.com>
> Reviewed-by: Aaron Leventhal <aleventhal@chromium.org>
> Reviewed-by: Kevin Babbitt <kbabbitt@microsoft.com>
> Cr-Commit-Position: refs/heads/master@{#900207}

Bug: 1213613
Change-Id: Ic8aaf477c7a480b6dd38b2725a6f327db9023dc6
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3019744
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Owners-Override: David Baron <dbaron@chromium.org>
Commit-Queue: David Baron <dbaron@chromium.org>
Cr-Commit-Position: refs/heads/master@{#900319}