GCC: Fix conversion from base::StringPiece to std::string
Don't use brace-enclosed initializer for converting from
base::StringPiece to std::string.
Otherwise build fails when using GCC compiler.
The error example:
../../ui/color/color_provider_utils.cc:110:23: error: could not convert '{color_name}' from '<brace-enclosed initializer list>' to 'std::__1::string' {aka 'std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >'}
  110 |     return {color_name};
      |                       ^
      |                       |
      |                       <brace-enclosed initializer list>

Bug: 819294, 1282468
Change-Id: I9303229f861bc1d0f8a1485780fa372c29f3152e
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3460583
Reviewed-by: Peter Kasting <pkasting@chromium.org>
Commit-Queue: Peter Kasting <pkasting@chromium.org>
Cr-Commit-Position: refs/heads/main@{#970809}