Revert of Merge MediaControlsChromium into MediaControls (https://codereview.chromium.org/157403002/)
Reason for revert:
This CL broke the build on Android:

http://build.chromium.org/p/chromium.webkit/builders/Android%20Builder/builds/34503/steps/compile/logs/stdio

FAILED: /mnt/data/b/build/goma/gomacc /mnt/data/b/build/slave/Android_Builder/build/src/third_party/android_tools/ndk//toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++ -MMD -MF obj/third_party/WebKit/Source/core/html/shadow/webcore_html.MediaControlsChromiumAndroid.o.d -DV8_DEPRECATION_WARNINGS -D_FILE_OFFSET_BITS=64 -DNO_TCMALLOC -DDISABLE_NACL -DCHROMIUM_BUILD -DUSE_LIBJPEG_TURBO=1 -DENABLE_WEBRTC=1 -DUSE_PROPRIETARY_CODECS -DENABLE_CONFIGURATION_POLICY -DDISCARDABLE_MEMORY_ALWAYS_SUPPORTED_NATIVELY -DSYSTEM_NATIVELY_SIGNALS_MEMORY_PRESSURE -DUSE_OPENSSL=1 -DENABLE_EGLIMAGE=1 -DENABLE_AUTOFILL_DIALOG=1 -DCLD_VERSION=1 -DENABLE_PRINTING=1 -DENABLE_MANAGED_USERS=1 -DBLINK_IMPLEMENTATION=1 -DINSIDE_BLINK -DENABLE_CUSTOM_SCHEME_HANDLER=0 -DENABLE_SVG_FONTS=1 -DENABLE_GDI_FONTS_ON_WINDOWS=0 -DENABLE_HARFBUZZ_ON_WINDOWS=1 -DWTF_USE_CONCATENATED_IMPULSE_RESPONSES=1 -DENABLE_FAST_MOBILE_SCROLLING=1 -DENABLE_INPUT_SPEECH=0 -DENABLE_LEGACY_NOTIFICATIONS=0 -DENABLE_MEDIA_CAPTURE=1 -DWTF_USE_WEBAUDIO_OPENMAX_DL_FFT=1 -DENABLE_WEB_AUDIO=1 -DENABLE_OPENTYPE_VERTICAL=1 -DU_USING_ICU_NAMESPACE=0 -DU_STATIC_IMPLEMENTATION -DSK_ENABLE_INST_COUNT=0 -DSK_SUPPORT_GPU=1 '-DGR_GL_CUSTOM_SETUP_HEADER="GrGLConfig_chrome.h"' -DSK_ENABLE_LEGACY_API_ALIASING=1 -DSK_ATTR_DEPRECATED=SK_NOTHING_ARG1 -DGR_GL_IGNORE_ES3_MSAA=0 -DSK_BUILD_FOR_ANDROID -DSK_USE_POSIX_THREADS -DSK_DEFERRED_CANVAS_USES_FACTORIES=1 -DCHROME_PNG_WRITE_SUPPORT -DPNG_USER_CONFIG -DCHROME_PNG_READ_PACK_SUPPORT -DLIBXML_STATIC -DLIBXSLT_STATIC -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DANDROID -D__GNU_SOURCE=1 -DUSE_STLPORT=1 -D_STLP_USE_PTR_SPECIALIZATIONS=1 '-DCHROME_BUILD_ID=""' -DHAVE_SYS_UIO_H -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -D_FORTIFY_SOURCE=2 -I../../third_party/WebKit/Source -I../.. -I../../skia/config -I../../third_party/khronos -I../../gpu -I../../third_party/WebKit -Igen/blink -Igen/blink/bindings -I../../third_party/openmax_dl -I../../third_party/angle/include -I../../third_party/icu/source/i18n -I../../third_party/icu/source/common -I../../third_party/skia/src/core -I../../third_party/skia/include/core -I../../third_party/skia/include/effects -I../../third_party/skia/include/pdf -I../../third_party/skia/include/gpu -I../../third_party/skia/include/lazy -I../../third_party/skia/include/pathops -I../../third_party/skia/include/pipe -I../../third_party/skia/include/ports -I../../third_party/skia/include/utils -I../../skia/ext -I../../third_party/iccjpeg -I../../third_party/libpng -I../../third_party/libwebp -I../../third_party/libxml/linux/include -I../../third_party/libxml/src/include -I../../third_party/libxslt -I../../third_party/npapi -I../../third_party/npapi/bindings -I../../third_party/ots/include -I../../third_party/qcms/src -I../../third_party/sqlite -I../../third_party/zlib -I../../v8/include -fstack-protector --param=ssp-buffer-size=4 -Werror -fno-exceptions -fno-strict-aliasing -Wall -Wno-unused-parameter -Wno-missing-field-initializers -fvisibility=hidden -pipe -fPIC -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=softfp -mthumb -fno-tree-sra -fuse-ld=gold -Wno-psabi -mthumb-interwork -ffunction-sections -funwind-tables -g -fstack-protector -fno-short-enums -finline-limit=64 -Wa,--noexecstack --sysroot=/mnt/data/b/build/slave/Android_Builder/build/src/third_party/android_tools/ndk//platforms/android-14/arch-arm -I/mnt/data/b/build/slave/Android_Builder/build/src/third_party/android_tools/ndk//sources/cxx-stl/stlport/stlport -Os -fno-ident -fdata-sections -ffunction-sections -fomit-frame-pointer -funwind-tables -g1 -fno-rtti -fno-threadsafe-statics -fvisibility-inlines-hidden -Wsign-compare -Wno-c++0x-compat -Wno-abi  -c ../../third_party/WebKit/Source/core/html/shadow/MediaControlsChromiumAndroid.cpp -o obj/third_party/WebKit/Source/core/html/shadow/webcore_html.MediaControlsChromiumAndroid.o
../../third_party/WebKit/Source/core/html/shadow/MediaControlsChromiumAndroid.cpp: In static member function 'static WTF::PassRefPtr<WebCore::MediaControls> WebCore::MediaControls::create(WebCore::Document&)':
../../third_party/WebKit/Source/core/html/shadow/MediaControlsChromiumAndroid.cpp:34:1:error: 'WebCore::MediaControlsChromiumAndroid::MediaControlsChromiumAndroid(WebCore::Document&)' is private
../../third_party/WebKit/Source/core/html/shadow/MediaControlsChromiumAndroid.cpp:46:103:error: within this context
../../third_party/WebKit/Source/core/html/shadow/MediaControlsChromiumAndroid.h:45:43:error: 'WebCore::MediaControlOverlayPlayButtonElement* WebCore::MediaControlsChromiumAndroid::m_overlayPlayButton' is private
../../third_party/WebKit/Source/core/html/shadow/MediaControlsChromiumAndroid.cpp:52:15:error: within this context
../../third_party/WebKit/Source/core/html/shadow/MediaControlsChromiumAndroid.h:46:42:error: 'WebCore::MediaControlOverlayEnclosureElement* WebCore::MediaControlsChromiumAndroid::m_overlayEnclosure' is private
../../third_party/WebKit/Source/core/html/shadow/MediaControlsChromiumAndroid.cpp:57:15:error: within this context


Original issue's description:
> Merge MediaControlsChromium into MediaControls
> 
> To the largest extent possible, code was copied from
> MediaControlsChromium.* to MediaControls.* without modification. Where
> MediaControlsChromium virtual functions called the MediaControls base
> functions, the order was preserved to avoid changing behavior.
> 
> BUG=341813
> 
> Committed: https://src.chromium.org/viewvc/blink?view=rev&revision=166753

TBR=acolwell@chromium.org,philipj@opera.com
NOTREECHECKS=true
NOTRY=true
BUG=341813

Review URL: https://codereview.chromium.org/144083003

git-svn-id: svn://svn.chromium.org/blink/trunk@166755 bbb929c8-8fbe-4397-9dbb-9b2b20218538