Revert of Add remoting_host target to chromium_builder_webrtc dependencies. (patchset #1 id:1 of https://codereview.chromium.org/706753003/)
Reason for revert:
Breaks Linux ChromiumOS Ozone Builder

http://goo.gl/oHjcNA

________ running '/usr/bin/python src/build/gyp_chromium' in '/b/build/slave/Linux_ChromiumOS_Ozone_Builder/build'
Updating projects from gyp files...
Traceback (most recent call last):
  File "src/build/gyp_chromium", line 318, in <module>
    gyp_rc = gyp.main(args)
  File "/b/build/slave/Linux_ChromiumOS_Ozone_Builder/build/src/tools/gyp/pylib/gyp/__init__.py", line 525, in main
    return gyp_main(args)
  File "/b/build/slave/Linux_ChromiumOS_Ozone_Builder/build/src/tools/gyp/pylib/gyp/__init__.py", line 501, in gyp_main
    params, options.check, options.circular_check)
  File "/b/build/slave/Linux_ChromiumOS_Ozone_Builder/build/src/tools/gyp/pylib/gyp/__init__.py", line 129, in Load
    params['parallel'], params['root_targets'])
  File "/b/build/slave/Linux_ChromiumOS_Ozone_Builder/build/src/tools/gyp/pylib/gyp/input.py", line 2745, in Load
    RemoveLinkDependenciesFromNoneTargets(targets)
  File "/b/build/slave/Linux_ChromiumOS_Ozone_Builder/build/src/tools/gyp/pylib/gyp/input.py", line 1489, in RemoveLinkDependenciesFromNoneTargets
    if targets[t].get('variables', {}).get('link_dependency', 0):
KeyError: '/b/build/slave/Linux_ChromiumOS_Ozone_Builder/build/src/remoting/remoting.gyp:remoting_host#target'
Error: Command /usr/bin/python src/build/gyp_chromium returned non-zero exit status 1 in /b/build/slave/Linux_ChromiumOS_Ozone_Builder/build
Hook '/usr/bin/python src/build/gyp_chromium' took 14.48 secs

Original issue's description:
> Add remoting_host target to chromium_builder_webrtc dependencies.
>
> This will make it possible for us to catch compile failures in the
> remoting_host component when rolling the WebRTC and libjingle revisions
> in Chromium DEPS using the bots in
> http://build.chromium.org/p/chromium.webrtc.fyi/waterfall
>
> Committed: https://crrev.com/32e1bf6e3fcc38662eb1dd1b0a1a2739a95992ec
> Cr-Commit-Position: refs/heads/master@{#303436}

TBR=perkj@chromium.org,kjellander@chromium.org
NOTREECHECKS=true
NOTRY=true

Review URL: https://codereview.chromium.org/713023002

Cr-Commit-Position: refs/heads/master@{#303453}