[gin] Fix formatted flag parsing
`SetV8FlagsFormatted` currently removes 1 from the length provided by
`vsnprintf`, but `vsnprintf` does not include the null terminator in
the returned length. This cuts off the last character in the string,
resulting in log spam:
Error: Value for flag --concurrent-sparkplug-max-threads= of type uint is out of bounds [0-4294967295]

Bug: None
Change-Id: I92e41f88cfb1f6d768528b2a9a892911d6276aae
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3449054
Reviewed-by: Camillo Bruni <cbruni@chromium.org>
Commit-Queue: Leonard Grey <lgrey@chromium.org>
Cr-Commit-Position: refs/heads/main@{#968901}