Revert of Fix getUserMedia so that failure is reported for invalid audio sources. (patchset #2 id:250001 of https://codereview.chromium.org/2622643006/ )
Reason for revert:
Reverting for later reland (and review)

Original issue's description:
> Reland of Fix getUserMedia so that failure is reported for invalid audio sources. (patchset #1 id:1 of https://codereview.chromium.org/2626533002/ )
>
> Reason for revert:
> Preparing reland
>
> Original issue's description:
> > Revert of Fix getUserMedia so that failure is reported for invalid audio sources. (patchset #2 id:20001 of https://codereview.chromium.org/2623443002/ )
> >
> > Reason for revert:
> > Revert due to WebRTC tests failing:
> >
> > https://uberchromegw.corp.google.com/i/chromium.win/builders/Win7%20Tests%20%28dbg%29%281%29/builds/56312
> >
> > [4832:364:0109/131325.673:4351226:ERROR:browser_test_utils.cc(147)] Cannot communicate with DOMMessageQueue.
> > c:\c\win\src\contentrowser\webrtc\webrtc_content_browsertest_base.cc(66): error: Value of: ExecuteScriptAndExtractString(shell(), javascript, &result)
> >   Actual: false
> > Expected: true
> > Failed to execute javascript callAndRenegotiateToVideo({audio: true}, {audio: true, video:true});.
> > From javascript: (nothing)
> > When executing 'callAndRenegotiateToVideo({audio: true}, {audio: true, video:true});'
> > c:\c\win\src\contentrowser\webrtc\webrtc_content_browsertest_base.cc(90): error: Failed
> >
> > and
> >
> > [4704:4156:0109/131352.840:4378402:ERROR:browser_test_utils.cc(147)] Cannot communicate with DOMMessageQueue.
> > c:\c\win\src\contentrowser\webrtc\webrtc_content_browsertest_base.cc(66): error: Value of: ExecuteScriptAndExtractString(shell(), javascript, &result)
> >   Actual: false
> > Expected: true
> > Failed to execute javascript getUserMediaInIframeAndCloseInSuccessCb({audio: true});.
> > From javascript: (nothing)
> > When executing 'getUserMediaInIframeAndCloseInSuccessCb({audio: true});'
> > c:\c\win\src\contentrowser\webrtc\webrtc_content_browsertest_base.cc(90): error: Failed
> >
> > Original issue's description:
> > > Fix getUserMedia so that failure is reported for invalid audio sources.
> > > This changes getUserMedia to wait for initialization of local
> > > audio sources before issuing the completion callback (either success or
> > > failure).
> > > Previously, if an error occurs between attempting to start a local
> > > audio source and the render side OnStreamCreated callback, getUserMedia
> > > would report successful completion with an audio track but no audio
> > > would actually be delivered for that track.
> > >
> > > BUG=679210
> > > CQ_INCLUDE_TRYBOTS=master.tryserver.chromium.linux:linux_optional_gpu_tests_rel;master.tryserver.chromium.mac:mac_optional_gpu_tests_rel;master.tryserver.chromium.win:win_optional_gpu_tests_rel
> > >
> > > Review-Url: https://codereview.chromium.org/2623443002
> > > Cr-Commit-Position: refs/heads/master@{#442323}
> > > Committed: https://chromium.googlesource.com/chromium/src/+/81cb66acf3f8099e416c7fc5ecbcaabf6d5c3c04
> >
> > TBR=jochen@chromium.org,guidou@chromium.org,xhwang@chromium.org,tommi@chromium.org
> > # Skipping CQ checks because original CL landed less than 1 days ago.
> > NOPRESUBMIT=true
> > NOTREECHECKS=true
> > NOTRY=true
> > BUG=679210
> >
> > Review-Url: https://codereview.chromium.org/2626533002
> > Cr-Commit-Position: refs/heads/master@{#442373}
> > Committed: https://chromium.googlesource.com/chromium/src/+/f05caaa1349e44abd44a00f88506bf140a0bc887
>
> TBR=jochen@chromium.org,guidou@chromium.org,xhwang@chromium.org,dewittj@chromium.org
> # Skipping CQ checks because original CL landed less than 1 days ago.
> BUG=679210
> CQ_INCLUDE_TRYBOTS=master.tryserver.chromium.linux:linux_optional_gpu_tests_rel;master.tryserver.chromium.mac:mac_optional_gpu_tests_rel;master.tryserver.chromium.win:win_optional_gpu_tests_rel
>
> Review-Url: https://codereview.chromium.org/2622643006
> Cr-Commit-Position: refs/heads/master@{#442628}
> Committed: https://chromium.googlesource.com/chromium/src/+/5d02cf8e38acafeea410906105d5fc11c3e3395b

TBR=jochen@chromium.org,guidou@chromium.org,xhwang@chromium.org,dewittj@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=679210

Review-Url: https://codereview.chromium.org/2628603003
Cr-Commit-Position: refs/heads/master@{#442660}