[UPM] Using com.google.common.base.Optional instead of java.util.Optional
java.util.Optional causes an error when compiling clank.
Error: Call requires API level 24 (current min is 23):
java.util.Optional#isPresent

Bug: 1279444
Change-Id: Idac2f0fe2073bd274a65cee22f644d39bae7a3c0
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3467894
Reviewed-by: Friedrich Horschig <fhorschig@chromium.org>
Commit-Queue: Viktor Semeniuk <vsemeniuk@google.com>
Cr-Commit-Position: refs/heads/main@{#971748}