Revert "Deprecate uninstall_metrics."
This reverts commit e15311e12a8ecdab3aa451e2fcab3b2b38f61824.

Reason for revert: causes consistent compile failures on win64-chrome bot, starting here:

Failure looks like:
[3375/20246] CXX obj/chrome/installer/setup/lib/google_chrome_behaviors.obj
FAILED: obj/chrome/installer/setup/lib/google_chrome_behaviors.obj
c:\b\s\w\ir\cache\goma\client\gomacc.exe ..\..\third_party\llvm-build\Release+Asserts\bin\clang-cl.e...(too long)
../../chrome/installer/setup/google_chrome_behaviors.cc(27,10): fatal error: 'chrome/installer/setup/uninstall_metrics.h' file not found
#include "chrome/installer/setup/uninstall_metrics.h"
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.


Original change's description:
> Deprecate uninstall_metrics.
>
> Remove the tracking/persisting of these metrics in prefs. Removed
> uploading in uninstaller.
>
> Bug: 1107516
> Change-Id: I84499820cea86b5f785949d9274e8b2205714aae
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2308133
> Reviewed-by: Tommy Li <tommycli@chromium.org>
> Reviewed-by: Nate Fischer <ntfschr@chromium.org>
> Reviewed-by: Greg Thompson <grt@chromium.org>
> Commit-Queue: Robert Kaplow <rkaplow@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#825461}

TBR=rkaplow@chromium.org,tommycli@chromium.org,ntfschr@chromium.org,grt@chromium.org

Change-Id: I9873f0a1da27389ca4066b23e312fd3e4cefbf67
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 1107516
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2527847
Reviewed-by: Mark Pearson <mpearson@chromium.org>
Commit-Queue: Mark Pearson <mpearson@chromium.org>
Cr-Commit-Position: refs/heads/master@{#825495}