Fix alarms_api_unittest.cc on GCC 4.6.3 linux 64 with -Werror=uninitialized:
../../testing/gtest/include/gtest/gtest-printers.h:169:42: error: ‘level’ may be used uninitialized in this function [-Werror=uninitialized]
../../chrome/browser/extensions/api/alarms/alarms_api_unittest.cc:280:32: note: ‘level’ was declared here

(introduced in http://crrev.com/176004)

TBR=jyasskin

Review URL: https://codereview.chromium.org/11823052

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@176059 0039d316-1c4b-4281-b951-d872f2087c98