Fix use-after-move in //components/viz/service/display_embedder/
Fix use-after-move (potential) bugs found by the
"bugprone-use-after-move" clang-tidy check.

Error: "'overlays' used after it was moved".

Bug: 1122844
Change-Id: I8eb3ffe4d54bf442ad55c184e47b4b922a6043b1
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2601362
Reviewed-by: Peng Huang <penghuang@chromium.org>
Commit-Queue: Maksim Ivanov <emaxx@chromium.org>
Cr-Commit-Position: refs/heads/master@{#839110}