Add missing sequence checks in generated_code_cache_context.cc
A recent change d9b11cc42978906d36d08543d494802c086c4adc has added
persistent_cache_collection_ member to GeneratedCodeCacheContext. The
member is supposed to only be accessed from a specific sequence. This
condition should be enforced by the compiler so the member is decorated
with GUARDED_BY_CONTEXT(sequence_checker_). Unfortunately this check is
not triggered since in recent chromium versions this code is compiled
with -Wno-thread-safety flag. The flag is added into most chromium
compilation units by //third_party/gemmlowp:gemlowp_includes. When the
flag is commented out generated_code_cache_context.cc fails to build
due to errors like:

  generated_code_cache_context.cc:197:7: error: reading variable
    'persistent_cache_collection_' requires holding context
    'sequence_checker_' [-Werror,-Wthread-safety-analysis]
     197 |   if (persistent_cache_collection_) {
         |       ^

Fix this by adding missing sequence_checker_ DCHECKs.

Bug: 473851455
Change-Id: I5c61d9a9ce41f443025cebe5e45b23fccfa636e7
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7408630
Reviewed-by: Olivier Li <olivierli@chromium.org>
Commit-Queue: Piotr Tworek <piotr.tworek@xperi.com>
Reviewed-by: Avi Drissman <avi@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1566141}