Revert "Modernize code calling GetLogicalDriveStrings()"
This reverts commit a2c7b6a8c41589c1b82a21ee874e2713a35a390d.

Reason for revert: broke branded builds with:
chrome/browser/win/conflicts/module_load_attempt_log_listener_unittest.cc(88,29): error: no member named 'StringViewFromCString' in namespace 'base'

Original change's description:
> Modernize code calling GetLogicalDriveStrings()
>
> As part of updating chrome/browser/win/ to remove unsafe buffer
> usage, ModuleLoadAttemptLogListener::UpdateDeviceToLetterPathMapping()
> is changed to use base::SplitStringPiece().
>
> In order to standardize the usage of GetLogicalDriveStrings(),
> base::DevicePathToDriveLetterPath() is also modernized.
>
> Change-Id: I512e9083d21f4acf63d65d72d5523806b6d75367
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5691501
> Reviewed-by: danakj <danakj@chromium.org>
> Commit-Queue: Patrick Monette <pmonette@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1327098}

Change-Id: I7525653d789ba0f84ddf7ad1de5bfffc049ce54c
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5703638
Reviewed-by: Greg Thompson <grt@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Greg Thompson <grt@chromium.org>
Auto-Submit: Greg Thompson <grt@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1327124}