closure: fix compilation error.
(ERROR) Error in: extensions.js
## /mnt/data/b/build/slave/Closure_Compilation_Linux/build/src/chrome/browser/resources/extensions/extension_list.js:292: ERROR - Function optionsClickListener: called with 1 argument(s). Function requires at least 0 argument(s) and no more than 0 argument(s).
##           optionsClickListener(e);
##           ^

TBR=kalman@chromium.org
BUG=393873

Review URL: https://codereview.chromium.org/654143003

Cr-Commit-Position: refs/heads/master@{#299639}