A11y: Add missing chrome_event ts_definition
This was causing remote execution to fail and fallback to local execution:

RuntimeError: Command '/b/f/w/third_party/node/linux/node-linux-x64/bin/node /b/f/w/third_party/node/node_modules/typescript/bin/tsc --project gen/chrome/browser/resources/chromeos/accessibility/common/tsconfig_ts_build.json' failed
[96m../../chrome/browser/resources/chromeos/accessibility/common/chrome_event_handler.ts[0m:[93m5[0m:[93m27[0m - [91merror[0m[90m TS2792: [0mCannot find module '/tools/typescript/definitions/chrome_event.js'. Did you mean to set the 'moduleResolution' option to 'nodenext', or to add aliases to the 'paths' option?
import {ChromeEvent} from '/tools/typescript/definitions/chrome_event.js';

Bug: b/325861271
Change-Id: I743f3e29e88df9894dad987a132bd4259d852e7f
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5307314
Reviewed-by: Jacob Francis <francisjp@google.com>
Commit-Queue: Richard Wang <richardwa@google.com>
Cr-Commit-Position: refs/heads/main@{#1263147}