CastOS: fix compile failure of cast_audio_renderer
Spanify an unsafe buffer access to fix a compile error caused by:
https://chromium-review.googlesource.com/c/chromium/src/+/6914274

Error:
../../chromecast/media/audio/cast_audio_renderer.cc:494:28: error: no member named 'data' in 'media::DecoderBuffer'

Bot:
./tools/mb/mb.py gen -m tryserver.chromium.linux -b linux-cast-x64-dbg ./out/bot

Bug: 365814210
Change-Id: I6cfbe689f9a813407104e0255435de96b8a52062
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7159857
Commit-Queue: Arthur Sonzogni <arthursonzogni@chromium.org>
Reviewed-by: Simeon Anfinrud <sanfin@chromium.org>
Auto-Submit: Arthur Sonzogni <arthursonzogni@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1547232}