Revert 221776 "RenderTextWin: Break runs between any two charact..."
Compile error:

render_text_unittest.cc(1662) :error C2039: 'Range' : is not a member of 'ui'

Revision 221776 change collided with revision 221762, which moved Range
from ui to gfx namespace.

> RenderTextWin: Break runs between any two characters that are not in the same code block
> 
> BUG=278913
> 
> Review URL: https://chromiumcodereview.appspot.com/23522018

TBR=ckocagil@chromium.org

Review URL: https://codereview.chromium.org/23707025

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@221780 0039d316-1c4b-4281-b951-d872f2087c98