Probably broke Win7 Tests (dbg)(6). http://build.chromium.org/p/chromium.win/builders/Win7%20Tests%20%28dbg%29%286%29/builds/27654/steps/browser_tests/logs/SendQuery
[ RUN      ] GcdPrivateAPITest.SendQuery
[4036:2900:0709/150928:ERROR:singleton_hwnd.cc(43)] Cannot create windows on non-UI thread!
[956:2412:0709/150928:WARNING:extension_apitest.cc(282)] Workaround for 177163, prematurely returning
c:\b\build\slave\win_builder__dbg_\build\src\chrome\browser\extensions\api\gcd_private\gcd_private_apitest.cc(276): error: Actual function call count doesn't match EXPECT_CALL(*test_service_discovery_client_, OnSendTo(std::string(reinterpret_cast\u003Cconst char*>(kQueryPacket), sizeof(kQueryPacket))))...
         Expected: to be called twice
           Actual: never called - unsatisfied and active
[  FAILED  ] GcdPrivateAPITest.SendQuery, where TypeParam =  and GetParam() =  (5746 ms)


Revert 282099 "Add API stubs for GCD device commands."

> Add API stubs for GCD device commands.
> Changed registration API to work for one network at once.
> Fixed comments.
> Replaced argument GCDDevice with just string id.
> 
> BUG=383167
> R=alexsemenov@chromium.org, asargent@chromium.org, asvitkine@chromium.org, noamsml@chromium.org
> 
> Review URL: https://codereview.chromium.org/363883002

TBR=vitalybuka@chromium.org

Review URL: https://codereview.chromium.org/385483002

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@282175 0039d316-1c4b-4281-b951-d872f2087c98