Reland "WebUI: Run relevant cr_elements_browsertests on Android"
This is a reland of commit afd2170a973e4806bc37f3f582fd56474688470e

Allowing subpixel variance for measured values in CrSplitter tests.
Previous failures causing revert were similar to:
AssertionError: expected 100.00000762939453 to equal 100


Original change's description:
> WebUI: Run relevant cr_elements_browsertests on Android
>
> Add cr_elements tests to Android builds, for all cr_elements that are
> included on Android and have browsertests. The tests added are for:
>
> CrLitElement (tests that depend on and test integration with Polymer
>               are excluded since Polymer is not included on Android)
> cr-button
> cr-tree
> cr-ripple and CrRippleMixin
> cr-splitter
>
> Note that cr-tabs is included on Android, but is tested via an
> interactive_ui_test. Adding interactive_ui_tests to Android builds to
> run this test will be done in a later CL.
>
> Bug: 40108641
> Change-Id: I4448fc96da192ffe8b832eb24d9c6c62285c0935
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6253805
> Reviewed-by: Demetrios Papadopoulos <dpapad@chromium.org>
> Commit-Queue: Rebekah Potter <rbpotter@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1419541}

Bug: 40108641, 396345744
Change-Id: I015a1e7e20782cd353fdf02544714257442c4784
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6265523
Reviewed-by: Demetrios Papadopoulos <dpapad@chromium.org>
Commit-Queue: Rebekah Potter <rbpotter@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1420157}