Reland "Write a test to check the sequence of ComponentReady."
This is a reland of 26af927a4e0c84e8ebc3d00b6ce04bcb42a720f9

The reason the original failed on some CI bots where the DCHECKS are off.
Such as https://ci.chromium.org/p/chromium/builders/ci/Linux%20ChromiumOS%20Full


[17135/50187] CXX obj/components/component_updater/unit_tests/component_installer_unittest.o
FAILED: obj/components/component_updater/unit_tests/component_installer_unittest.o
/b/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF...(too long)
../../components/component_updater/component_installer_unittest.cc:371:53: error: lambda capture 'this' is not used [-Werror,-Wunused-lambda-capture]
ON_CALL(*this, ComponentReady).WillByDefault([this]() {
^~~~
../../components/component_updater/component_installer_unittest.cc:374:55: error: lambda capture 'this' is not used [-Werror,-Wunused-lambda-capture]
CI bots:


Original change's description:
> Write a test to check the sequence of ComponentReady.
>
> This test temporarily installs a component, invokes Register
> for the component, and checks that ComponentReady is called before
> the completion callback of ComponentInstaller::Register is posted.
>
> Bug: 1283120
> Change-Id: I45e7c7c6552bcc89bde443058508ca1b4402781b
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3362333
> Reviewed-by: Joshua Pawlicki <waffles@chromium.org>
> Commit-Queue: Sorin Jianu <sorin@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#955203}

Bug: 1283120
Change-Id: I609c4d99ca728c8b82f33d222aded282c912d0c6
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3366743
Reviewed-by: Joshua Pawlicki <waffles@chromium.org>
Commit-Queue: Sorin Jianu <sorin@chromium.org>
Cr-Commit-Position: refs/heads/main@{#955289}