Fix missing deps on on obj/components/search_engines/regional_settings/regional_settings.o
In file included from gen/components/search_engines/regional_settings.cc:10:
gen/components/search_engines/regional_settings.h:17:10: fatal error: 'third_party/search_engines_data/resources/definitions/prepopulated_engines.h' file not found
   17 | #include "third_party/search_engines_data/resources/definitions/prepopulated_engines.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Bug: 405841105
Change-Id: I31e81e889d84407d7b55181e27b44e286acaefa5
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6383879
Auto-Submit: Fumitoshi Ukai <ukai@google.com>
Commit-Queue: Nicolas Dossou-Gbété <dgn@chromium.org>
Reviewed-by: Nicolas Dossou-Gbété <dgn@chromium.org>
Reviewed-by: Takuto Ikuta <tikuta@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1436924}