Avoid class verification for RenderProcessGoneDetail in WebViewContentsClientAdapter
This adds the Utility class ApiHelperForO. It moves references to
RenderProcessGoneDetail, which was added in O, into a separate class. On
pre-O devices, this reduces log spam caused by a NoClassDefFoundError.
It also improves startup time.

Bug: 791099, 838702
Test: adb logcat | grep 'Failed resolution of'
Test: run_webview_instrumentation_test_apk -f org.chromium.android_webview.test.AwContentsClientOnRenderProcessGoneTest#*
Change-Id: Iee47d5d5553b6eb339123fbea238dcbf9969de49
Reviewed-on: https://chromium-review.googlesource.com/1089477
Commit-Queue: James Wallace-Lee <jamwalla@chromium.org>
Reviewed-by: Nate Fischer <ntfschr@chromium.org>
Reviewed-by: Bo <boliu@chromium.org>
Cr-Commit-Position: refs/heads/master@{#565451}