Copy mock.py instead of using symlinks
os.symlink requires special user privileges on Windows that are off by
default on some machines. Copying the file works fine (it is quite
small) and the increased portability and decreased requirements are
enough to justify this change. On machines without this privilege
there can be errors like this when running presubmits:

      os.symlink(MOCK_PY, path)
  OSError: [WinError 1314] A required privilege is not held
  by the client

These errors were seen when running this command on my cloudtop
machine:

  git cl presubmit --force --files infra\config\scripts\tests\*

Bug: 1309977
Change-Id: If1abc2ee2b0701f36b19dae7b0400b5039bc910b
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3715570
Reviewed-by: Wanda Mora <morawand@google.com>
Commit-Queue: Bruce Dawson <brucedawson@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1016265}