libstdc++: std::vector members should not be const, in ChromeDownloadManagerDelegate unit tests
Fix build break using libstdc++:
    /usr/include/c++/11/bits/stl_vector.h: In instantiation of ‘class std::vector<const std::__cxx11::basic_string<char> >’:
    ../../chrome/browser/download/chrome_download_manager_delegate_unittest.cc:496:34:   required from here
    /usr/include/c++/11/bits/stl_vector.h:401:66: error: static assertion failed: std::vector must have a non-const, non-volatile value_type
      401 |       static_assert(is_same<typename remove_cv<_Tp>::type, _Tp>::value,
          |                                                                  ^~~~~

Bug: 957519
Change-Id: I8ca55444dc150cc7b13b7289f5b7772806b69935
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3377526
Reviewed-by: Min Qin <qinmin@chromium.org>
Commit-Queue: José Dapena Paz <jdapena@igalia.com>
Cr-Commit-Position: refs/heads/main@{#957138}