Add missing perfetto::Flow and TRACE_EVENT includes
Refs https://chromium-review.googlesource.com/c/chromium/src/+/5022285

Fixes the following build errors:

../../third_party/blink/renderer/core/workers/worker_global_scope.cc:581:19: error: no member named 'Flow' in namespace 'perfetto'
  581 |         perfetto::Flow::Global(message_event->GetTraceId()));
      |         ~~~~~~~~~~^

../../third_party/blink/renderer/core/workers/dedicated_worker_messaging_proxy.cc:245:19: error: no member named 'Flow' in namespace 'perfetto'
  245 |         perfetto::Flow::Global(event->GetTraceId()));
      |         ~~~~~~~~~~^

../../third_party/blink/renderer/core/workers/worker_global_scope.cc:576:5: error: use of undeclared identifier 'TRACE_EVENT'
  576 |     TRACE_EVENT(
      |     ^

../../third_party/blink/renderer/core/workers/dedicated_worker_messaging_proxy.cc:240:5: error: use of undeclared identifier 'TRACE_EVENT'
  240 |     TRACE_EVENT(
      |     ^

resultant of missing includes for:

- base/trace_event/typed_macros.h
- third_party/perfetto/include/perfetto/tracing/track_event_args.h

These errors were observed in Electron when pulling in latest changes from upstream.

Bug: N/A
Change-Id: I3101827621e292cdbc1d6c9cd225beaf0ebdc5fc
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5365462
Reviewed-by: Nate Chapin <japhet@chromium.org>
Reviewed-by: Yang Guo <yangguo@chromium.org>
Commit-Queue: Yang Guo <yangguo@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1272071}