Revert "Fix suggestions thumbnail and title text sizes."
This reverts commit 3761901e7e3ed79142dc1a90f2b21a8e54100a1a.

Reason for revert: Causing compile failure: https://build.chromium.org/p/chromium.linux/builders/Android%20Builder/builds/87759
with error:
../../chrome/android/java/src/org/chromium/chrome/browser/suggestions/SuggestionsBinder.java:404: error: cannot find symbol         if (FeatureUtilities.isChromeHomeModernEnabled()) {

Original change's description:
> Fix suggestions thumbnail and title text sizes.
> 
> Bug: i761987
> Change-Id: I34c7e03e549589c6de959de07486371b89d3dbfb
> Reviewed-on: https://chromium-review.googlesource.com/677287
> Commit-Queue: Michael van Ouwerkerk <mvanouwerkerk@chromium.org>
> Reviewed-by: Bernhard Bauer <bauerb@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#503488}

TBR=bauerb@chromium.org,mvanouwerkerk@chromium.org

Change-Id: Ib7ec5816963b0cc0a2ab479b4738b469ce4b726b
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: i761987
Reviewed-on: https://chromium-review.googlesource.com/677073
Reviewed-by: Jesse Doherty <jwd@chromium.org>
Commit-Queue: Jesse Doherty <jwd@chromium.org>
Cr-Commit-Position: refs/heads/master@{#503499}