ukm: Don't use unicode type
The unicode type no longer exists in Python 3.
All UKM data seems to be ASCII, so we can go the easy route and use the str type.

Traceback (most recent call last):
  File "../../tools/metrics/ukm/gen_builders.py", line 16, in <module>
    import ukm_model
  File "C:\Google\chromium\src\tools\metrics\ukm\ukm_model.py", line 31, in <module>
    ('type', unicode, None),
NameError: name 'unicode' is not defined

Bug: 941669
Change-Id: I54542ea0e6f186432a75b24763486bac2624b163
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2081813
Auto-Submit: Raul Tambre <raul@tambre.ee>
Commit-Queue: Brian White <bcwhite@chromium.org>
Reviewed-by: Brian White <bcwhite@chromium.org>
Cr-Commit-Position: refs/heads/master@{#748419}