IWYU: usage of memcpy in buffer_iterator.h requires declaration.
Fix build issue:
    ../../base/containers/buffer_iterator.h:99:13: error: ‘memcpy’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
       99 |       memcpy(&t.emplace(), remaining_.data(), sizeof(T));
          |       ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Bug: 957519
Change-Id: I1151e9c67694958cfdcfc0b2c7baae7d3095da07
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3966223
Reviewed-by: Daniel Cheng <dcheng@chromium.org>
Commit-Queue: José Dapena Paz <jdapena@igalia.com>
Cr-Commit-Position: refs/heads/main@{#1062850}