SyncerError: Make sure NetworkConnectionUnavailable() is used
SyncerErrors with type NETWORK_CONNECTION_UNAVAILABLE should only be
created through the NetworkConnectionUnavailable() factory function, to
make sure that the expected net_error_code is always set.

Bug: 842096
Change-Id: Ibad86d6f0be6a36306db8b7e0e0d28404321f841
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1560190
Commit-Queue: Eric Orth <ericorth@chromium.org>
Reviewed-by: Eric Orth <ericorth@chromium.org>
Reviewed-by: Jan Krcal <jkrcal@chromium.org>
Auto-Submit: Marc Treib <treib@chromium.org>
Cr-Commit-Position: refs/heads/master@{#649663}