Revert "Python3Migration: components/viz/PRESUBMIT"
This reverts commit 8fa4304dfd96e181ce06822524020e1e275b35eb.

Reason for revert:

  File "C:\src\trunk\src\components\viz\presubmit_checks.py", line 100, in CheckPassByValue
    string.join(pass_by_value_types, '|'),
AttributeError: module 'string' has no attribute 'join'

Original change's description:
> Python3Migration: components/viz/PRESUBMIT
>
> Bug: 1212022
> Change-Id: Iaacc8f9291bbed9511b1e30d73bcaae55746d051
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2964918
> Reviewed-by: kylechar <kylechar@chromium.org>
> Commit-Queue: Elaine Chien <elainechien@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#892668}

Bug: 1212022
Change-Id: I2087fb0e63f387c0b3498fa3395769e2375b8b35
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2965760
Auto-Submit: Peter Kasting <pkasting@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Peter Kasting <pkasting@chromium.org>
Reviewed-by: Elaine Chien <elainechien@chromium.org>
Owners-Override: Peter Kasting <pkasting@chromium.org>
Cr-Commit-Position: refs/heads/master@{#893022}