Fix ash_pixeltests linking in the component build
Without ASH_EXPORT on FakeVideoConferenceTrayEffectsManager ash_pixeltests fails to link when is_component_build = true with an
undefined reference to FakeVideoConferenceTrayEffectsManager's
constructor.

This likely broke in crrev.com/c/5163020, unfortunately we don't seem to
have CQ or CI coverage for this configuration.

Bug: None
Change-Id: I593c742f4a8d799418e8df2b4d08d512bf2b398d
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5194624
Reviewed-by: Andre Le <leandre@chromium.org>
Commit-Queue: Peter Boström <pbos@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1246735}