Use 0 instead of NULL to make GCC 4.6 for Chrome OS happy.
content/renderer/java_bridge_dispatcher.cc:69:76: error: passing NULL to non-pointer argument 4 of 'bool CreateNPVariant(const NPVariant_Param&, NPChannelBase*, NPVariant*, gfx::NativeViewId, const GURL&)' [-Werror=conversion-null]

BUG=None
TEST=build Chrome inside Chrome OS chroot.
TBR=steveblock@chromium.org

Review URL: http://codereview.chromium.org/8362025

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@106675 0039d316-1c4b-4281-b951-d872f2087c98