Exclude memory_test compilation on Windows
The memory_test target fails to build on Windows due to a variety of
errors related to MOCK_METHOD(). For example:

    memory_test.cc(542,3): error: static_assert failed "(size_t) should
    be enclosed in parentheses."

This is generated by the line:
    MOCK_METHOD(value_type*, allocate, (size_t));

"(size_t)" is clearly enclosed by parentheses (the error message even
indicates this), but both clang and MSVC fail to compile correctly on
Windows due to these errors.

Bug: angleproject:4873
Bug: 1116473
Test: Build on Windows and Linux
Change-Id: Ie83e7f2ebcdbd641b9e87ac7de7ef28f19b0bbac
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2353403
Reviewed-by: Jamie Madill <jmadill@chromium.org>
Reviewed-by: Mirko Bonadei <mbonadei@chromium.org>
Commit-Queue: Tim Van Patten <timvp@google.com>
Cr-Commit-Position: refs/heads/master@{#798249}