Revert "Add debug logging to WebFeedFollowIntroController and reenable tests"
This reverts commit 3358f005c87eb39b5cd07158053383d461ebae23.

Reason for revert: Compilation error:
WebFeedFollowIntroController.java:53: error: duplicate declaration of field: TAG

See log:
https://ci.chromium.org/ui/p/chromium/builders/ci/android-lollipop-arm-rel/10470/overview

Original change's description:
> Add debug logging to WebFeedFollowIntroController and reenable tests
>
> Logs temporarily using ERROR level so that output will be visible in
> release bots.
>
> Bug: 1227610
> Change-Id: Ibdf7fdc5e7c611b72489c0ccba371c11eee67ab2
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3018739
> Reviewed-by: Peter Williamson <petewil@chromium.org>
> Commit-Queue: Carlos Knippschild <carlosk@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#900593}

Bug: 1227610
Change-Id: I8cb40736ab7fd442fe541b9f63a6835280d03879
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3021604
Auto-Submit: David Baron <dbaron@chromium.org>
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Owners-Override: David Baron <dbaron@chromium.org>
Cr-Commit-Position: refs/heads/master@{#900612}