Add component export to FakeInputMethodContext
This patch fixes the following error:
error: undefined symbol: ui::FakeInputMethodContext::FakeInputMethodContext()

The FakeInputMethodContext is used from other libraries now like
libgtkui. Thus, an export is needed.

TBR=shuchen@chromium.org

Change-Id: I08a92231f45b0409e30dfe9b7c45c470d4120f92
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1748687
Reviewed-by: Maksim Sisov <msisov@igalia.com>
Reviewed-by: Shu Chen <shuchen@chromium.org>
Commit-Queue: Maksim Sisov <msisov@igalia.com>
Cr-Commit-Position: refs/heads/master@{#685931}