IWYU: missing include for using memset in ScopedResState.
Fix build error with libstdc++:
    ../../net/dns/public/scoped_res_state.cc: In constructor ‘net::ScopedResState::ScopedResState()’:
    ../../net/dns/public/scoped_res_state.cc:20:3: error: ‘memset’ was not declared in this scope
       20 |   memset(&res_, 0, sizeof(res_));
          |   ^~~~~~

Bug: 957519
Change-Id: Id6202959ebb15b7be25d966843ce25214b3407d3
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3377522
Reviewed-by: Eric Orth <ericorth@chromium.org>
Commit-Queue: José Dapena Paz <jdapena@igalia.com>
Cr-Commit-Position: refs/heads/main@{#957142}