Revert of Move TouchSelectionController from content to ui (patchset #12 id:600001 of https://codereview.chromium.org/759433002/)
Reason for revert:
Suspected of causing Win8 GN failure

http://build.chromium.org/p/chromium.win/builders/Win8%20GN/builds/1552/steps/compile/logs/stdio#error1

FAILED: ninja -t msvc -e environment.x86 -- "C:\b\depot_tools\win_toolchain\vs2013_files\VC\bin\amd64_x86/cl.exe" /nologo /showIncludes /FC @obj/ui/base/dragdrop/ui_base_unittests.os_exchange_data_provider_aurax11_unittest.obj.rsp /c ../../ui/base/dragdrop/os_exchange_data_provider_aurax11_unittest.cc /Foobj/ui/base/dragdrop/ui_base_unittests.os_exchange_data_provider_aurax11_unittest.obj /Fdobj/ui/base/ui_base_unittests_cc.pdb
c:\b\build\slave\win8_gn\build\src\ui\base\dragdrop\os_exchange_data_provider_aurax11.h(8) : fatalerror C1083: Cannot open include file: 'X11/Xlib.h': No such file or directory

Original issue's description:
> Move TouchSelectionController from content to ui
>
> This patch is only moving new unified touch selection files from
> content/ to ui/touch_selection/. This is the first step to allow Aura
> use the new unified TouchSelectionController.
>
> The only change to TouchSelectionController needed for this move is
> replacing use of cc::ViewportSelectionBound with ui::SelectionBound.
>
> The actual use of the new touch selection for Aura will happen in future
> CL(s). After that, we can remove current touch selection code from
> ui/base/touch/.
>
> BUG=399721
>
> Committed: https://crrev.com/29fd405ca491a6fcf0dde6277d92d44300cb2926
> Cr-Commit-Position: refs/heads/master@{#307336}

TBR=jdduke@chromium.org,mfomitchev@chromium.org,sadrul@chromium.org,boliu@chromium.org,jam@chromium.org,mohsen@chromium.org
NOTREECHECKS=true
NOTRY=true
BUG=399721

Review URL: https://codereview.chromium.org/754963007

Cr-Commit-Position: refs/heads/master@{#307344}