Revert of Showing previews UI for Offline Previews (patchset #17 id:320001 of https://codereview.chromium.org/2362033002/ )
Reason for revert:
Speculative revert: might have broken a bunch of infobar tests. This CL is the only infobar-related one in the blamelist.  https://uberchromegw.corp.google.com/i/chromium.linux/builders/Android%20Tests%20%28dbg%29/builds/36738

For instance org.chromium.chrome.browser.infobar.InfoBarContainerTest#testCloseTabOnAdd:

junit.framework.AssertionFailedError: expected:<2> but was:<1>
	at org.chromium.chrome.browser.infobar.InfoBarContainerTest.addInfoBarToCurrentTab(InfoBarContainerTest.java:103)
	at org.chromium.chrome.browser.infobar.InfoBarContainerTest.testCloseTabOnAdd(InfoBarContainerTest.java:223)

Original issue's description:
> Showing previews UI for Offline Previews
>
> This changes the functionality of is_offline_preview() in OfflinePageTabHelper to check the provisional information as well.
>
> Additionally, this CL addresses other consumers of this information that
> want access to it in DidFinishNavigation. Specifically,
> PreviewsPageLoadMetricsObserver will access the is_offline_previews bit
> as will PreviewsInfoBarHelper.
>
> This also prevents showing the offline pages snackbar and replaces it with
> the previews infobar. This leaves the Offline omnibox and other UI
> features.
>
> BUG=615564,649148
>
> Committed: https://crrev.com/21364834a65e541369e8895d93695dfaf114056b
> Committed: https://crrev.com/e28ec590f2f8f5103fb724c587d3abc1a6782cb8
> Cr-Original-Commit-Position: refs/heads/master@{#427902}
> Cr-Commit-Position: refs/heads/master@{#428124}

TBR=bmcquade@chromium.org,jianli@chromium.org,megjablon@chromium.org,dewittj@chromium.org,ryansturm@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=615564,649148

Review-Url: https://codereview.chromium.org/2450353005
Cr-Commit-Position: refs/heads/master@{#428324}