webnn: fix the fuzzer stack overflow issue on Windows
ASan inflates stack frames significantly, and the fuzzer deep call chain
overflows the default 1MB stack on Windows, causes the ASan to throw
ERROR: AddressSanitizer: stack-overflow when launching the fuzzer.

So increases the stack to 8MB that also matches chrome.exe.

Bug: 495837550
Change-Id: I54fddf56f24cd6713a6680e9cad91a6cef9e4099
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7862383
Auto-Submit: Zou, Shiyi <shiyi.zou@intel.com>
Reviewed-by: Hu, Ningxin <ningxin.hu@intel.com>
Commit-Queue: Zou, Shiyi <shiyi.zou@intel.com>
Cr-Commit-Position: refs/heads/main@{#1634043}