[AndroidSPC] Fix NoSuchMethodError
A NoSuchMethodError happened for WebAuthSecurityChecksResults
because CL[1] introduced JNI tries to find WebAuthSecurityChecksResults
at "chromium/content/browser/framehost/WebAuthSecurityChecksResults"
but the class actually lived in RenderFrameHost.java.

This CL solves it by moving out the class to be an standalone class.

[1]: https://chromium-review.googlesource.com/c/chromium/src/+/3037402

Bug: 1232044
Change-Id: I621ed671233dd54743b68f220334bb0351a96f70
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3045719
Commit-Queue: Liquan (Max) Gu <maxlg@chromium.org>
Reviewed-by: Bo <boliu@chromium.org>
Cr-Commit-Position: refs/heads/master@{#904510}