fix missing deps for obj/chrome/browser/web_applications/proto/proto_extras_to_value/web_app_database_metadata.to_value.o
```
FAILED: obj/chrome/browser/web_applications/proto/proto_extras_to_value/web_app_database_metadata.to_value.o
"python3" ../../build/toolchain/clang_code_coverage_wrapper.py --target-os=linux --files-to-instrument=../../.code-coverage/files_to_instrumen...(too long)
gen/chrome/browser/web_applications/proto/web_app_database_metadata.to_value.cc:11:10: fatal error: 'chrome/browser/web_applications/proto/web_app_database_metadata.pb.h' file not found
11 | #include "chrome/browser/web_applications/proto/web_app_database_metadata.pb.h"
|          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

Bug: 429279785
Change-Id: I9f9644c6321b96094346b264c4d75ee988f251d5
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6712775
Auto-Submit: Fumitoshi Ukai <ukai@google.com>
Reviewed-by: Hidehiko Abe <hidehiko@chromium.org>
Commit-Queue: Fumitoshi Ukai <ukai@google.com>
Cr-Commit-Position: refs/heads/main@{#1483534}