Revert of Various changes required to support ChromeVox Next to read Views and Windows. (patchset #13 id:240001 of https://codereview.chromium.org/743273002/)
Reason for revert:
This change broken the ChromiumOS on Chromium build:

http://build.chromium.org/p/chromiumos.chromium/builders/Daisy%20%28chromium%29/builds/3342

With the error:
chrome/browser/ui/ash/accessibility/ax_root_obj_wrapper.h:17:7: error: 'AXRootObjWrapper' has a field 'AXRootObjWrapper::alert_window_' whose type uses the anonymous namespace [-Werror]

Original issue's description:
> Various changes required to support ChromeVox Next to read Views and Windows.
>
> - adds support for valueChanged event (e.g. to read adjustment of the volume slider)
> - add textChanged event handler to process omnibox character echo/deletion.
> - braille support for the textChanged,textSelectionChanged events
> - whitelist ChromeVox for automation API up to stable.
> - remove the --enable-chromevox-next cmd line flag.
> - adds options for Output module (to only output braille, for example).
> - adds a "dummy" alert window as a child of the desktop root node; this window will be used to fire alert events. Due to the way we support alerts now without backing views, this is necessary.
> - start generating context for window on "enter". This picks up announcements like "status tray" when entering the status tray bar with alt+shift+s.
> - exclude the first child (only child) of the desktop node from having a name set; this is because that particular window has a non-human readable name "Display<xxx>" which gets read frequently when entering a screen/display.
>
> Committed: https://crrev.com/113aa4f1f3e207b4b134ecc7316b9c46e29a22ad
> Cr-Commit-Position: refs/heads/master@{#306855}

TBR=dmazzoni@chromium.org,plundblad@chromium.org,kalman@chromium.org,zelidrag@chromium.org,oshima@chromium.org,dtseng@chromium.org
NOTREECHECKS=true
NOTRY=true

Review URL: https://codereview.chromium.org/779103002

Cr-Commit-Position: refs/heads/master@{#306868}