Revert "WTF: Add contains() and ContainsIgnoringAsciiCase() to AtomicString"
This reverts commit a8383f4cfec21a6663d5956ee1562c1c945aa879.

Reason for revert: Causes compile failure starting at
https://ci.chromium.org/ui/p/chromium/builders/ci/mac-arm64-rel/145678

LOG: 
[882/20169] CXX obj/third_party/blink/renderer/platform/platform/spot_light_source.o
../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/third_party/blink/renderer/platform/platform/spot_light_source.o.d -D__S...(too long)
In file included from ../../third_party/blink/renderer/platform/graphics/filters/spot_light_source.cc:35:
In file included from ../../third_party/blink/renderer/platform/wtf/text/string_builder_stream.h:10:
In file included from ../../third_party/blink/renderer/platform/wtf/text/string_builder.h:35:
../../third_party/blink/renderer/platform/wtf/text/atomic_string.h:151:20: error: no member named 'FindIgnoringASCIICase' in 'blink::String'
  151 |     return string_.FindIgnoringASCIICase(value) != kNotFound;


Original change's description:
> WTF: Add contains() and ContainsIgnoringAsciiCase() to AtomicString
>
> This change introduces `contains()` and `ContainsIgnoringAsciiCase()` to
> `AtomicString` to replace the existing `Contains()` method that used a
> `TextCaseSensitivity` parameter.
>
> The new methods make the case-sensitivity of the search explicit in the
> method name, improving readability, and the `contains()` method
> improves std::string compatibility. The change updates existing call
> sites to use the new methods and adds corresponding unit tests.
>
> This CL has no behavior changes.
>
> Bug: 473854537
> Change-Id: I1a0c95e336d42c63cdf8f4c21b3c5c58195df393
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7577454
> Reviewed-by: Fredrik Söderquist <fs@opera.com>
> Commit-Queue: Fredrik Söderquist <fs@opera.com>
> Auto-Submit: Kent Tamura <tkent@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1585337}

Bug: 473854537
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Change-Id: I6db854301913ee159d955d955cab4db197885d41
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7581653
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Ivan Šandrk <isandrk@chromium.org>
Owners-Override: Ivan Šandrk <isandrk@chromium.org>
Reviewed-by: Ivan Šandrk <isandrk@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1585340}