Fix -Wimplicit-int-conversion warning in hwnd_message_handler.cc
The latest warning of Clang warns, e.g:

  ../../ui/views/win/hwnd_message_handler.cc(1644,47):
  error: implicit conversion loses integer precision: 'LONG' (aka 'long') to 'int' [-Werror,-Wimplicit-int-conversion]
   1644 |     OffsetRect(&work_rect, -window_rect.left, -window_rect.top);
	|     ~~~~~~~~~~                                ^~~~~~~~~~~~~~~~

The issue being that RECT's members are long's, whereas OffsetRect expects
ints.

Bug: 402154971
Change-Id: I78eadc2a26b6c9025199386427acb51cdd686705
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6343455
Reviewed-by: Nico Weber <thakis@chromium.org>
Owners-Override: Nico Weber <thakis@chromium.org>
Commit-Queue: Hans Wennborg <hans@chromium.org>
Auto-Submit: Hans Wennborg <hans@chromium.org>
Commit-Queue: Nico Weber <thakis@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1430868}