libstdc++: do not use operator<< in std::unique_ptr in XR CameraIndicationServer
Building with libstdc++ fails in XR CameraIndicationServer, trying to
use operator<< on an std::unique_ptr. This operator is defined for
C++20 standard, but not for C++17 (which we use) or C++14.

../../chrome/browser/vr/chrome_xr_integration_client.cc:51:62: error: no match for ‘operator<<’ (operand types are ‘std::basic_ostream<char>’ and ‘std::unique_ptr<content::MediaStreamUI>’)
   51 |              << num_runtimes_with_camera_in_use_ << ", ui_=" << ui_;
      |                                                              ^~ ~~~
      |                                                                 |
      |                                                                 std::unique_ptr<content::MediaStreamUI>

Bug: 957519
Change-Id: I78eb40e63acf47657f5afc9458d343c157f7efca
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3489026
Reviewed-by: Piotr Bialecki <bialpio@chromium.org>
Commit-Queue: José Dapena Paz <jdapena@igalia.com>
Cr-Commit-Position: refs/heads/main@{#975333}