Revert of add more polymer tests (https://codereview.chromium.org/257283002/)
Reason for revert:
This delta breaks telemetry_perf_unittests testMeasurementSmoke

ERROR:root:Errored pages:
http://localhost:8000/components/paper-calculator/demo.html
Traceback (most recent call last):
File "/mnt/data/b/build/slave/Linux_ChromiumOS_Tests__1_/build/src/tools/perf/../telemetry/telemetry/decorators.py", line 50, in wrapper
func(*args, **kwargs)
File "/mnt/data/b/build/slave/Linux_ChromiumOS_Tests__1_/build/src/tools/perf/measurements/measurement_unittest.py", line 73, in testMeasurementSmoke
msg='Failed: %s' % benchmark)
AssertionError: Failed: <class 'benchmarks.thread_times.ThreadTimesPolymer'>

Original issue's description:
> add more polymer tests
> 
> BUG=333078
> R=dtu@chromium.org
> NOTRY=true
> 
> Committed: https://src.chromium.org/viewvc/chrome?view=rev&revision=266955

TBR=dtu@chromium.org,ykyyip@chromium.org
NOTREECHECKS=true
NOTRY=true
BUG=333078

Review URL: https://codereview.chromium.org/257253003

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@266971 0039d316-1c4b-4281-b951-d872f2087c98