Revert "Switch from GNU to LLVM based tools."
This reverts commit bf16b3352482efbbcd326523e3fee40bf5b24c88.

Reason for revert: Suspected cause of build failure on "Android ASAN (dbg)": https://ci.chromium.org/ui/p/chromium/builders/ci/Android%20ASAN%20(dbg)/31602/overview

[2581/35024] ACTION //third_party/angle:compressed_symbols(//build/toolchain/android:android_clang_arm)
FAILED: lib.compressed/libEGL_angle.cr.so 
python3 ../../third_party/angle/android/compress_symbols.py --objcopy ../../third_party/android_ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-objcopy --nm ../../third_party/android_ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/nm --strip ../../third_party/android_ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/strip --unstrippedsofile ./lib.unstripped/libEGL_angle.cr.so --output ./lib.compressed/libEGL_angle.cr.so
Traceback (most recent call last):
  File "../../third_party/angle/android/compress_symbols.py", line 98, in <module>
    sys.exit(main())
  File "../../third_party/angle/android/compress_symbols.py", line 33, in main
    nm_cmd = subprocess.Popen([args.nm, '-D', args.output, '--format=posix', '--defined-only'],
  File "/b/s/w/ir/cipd_bin_packages/cpython3/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/b/s/w/ir/cipd_bin_packages/cpython3/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '../../third_party/android_ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/nm'

Original change's description:
> Switch from GNU to LLVM based tools.
>
> Android NDK 23 switched to a LLVM based toolchain. However some LLVM
> based tools like llvm-readobj and llvm-objcopy are available with NDK 22
> already. To prepare the roll to NDK 23, switch to llvm-readobj and
> llvm-copy for Android builds.
>
> Bug: 1246049
> Change-Id: I1cc3cec4aeaa159f6189f810ff6e709879b51204
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3162163
> Reviewed-by: Hans Wennborg <hans@chromium.org>
> Commit-Queue: Richard Townsend <richard.townsend@arm.com>
> Cr-Commit-Position: refs/heads/main@{#922566}

Bug: 1246049
Change-Id: I7cb45001e9d0d7a3a47bd60cca069947849b3ad8
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3169596
Auto-Submit: Thomas Anderson <thomasanderson@chromium.org>
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Cr-Commit-Position: refs/heads/main@{#922637}