Reland 2 More Settings Page Interaction UMA
This reverts commit d5252bd9ae00db5b10addc40315ccf0516befba7.

Reason for revert: Tests were flaking due to time out, tests have been split up to increase speed and prevent time out.

Original change's description:
> Reland "[Sheriff]: Revert "More Settings Page Interaction UMA""
> 
> This reverts commit dbfd6f350f85cbfeca1a9f7818342886f56019b4.
> 
> Reason for revert: CrSettingsSiteSettingsPageTest.UMALoggingTestsPart2 is failing flakily.
> 
> Bug: 1044708
> 
> Original change's description:
> > Revert "[Sheriff]: Revert "More Settings Page Interaction UMA""
> > 
> > This reverts commit 0bfc424a0f213471768ae1a47a5e75bc983efe2f.
> > 
> > Reason for revert: Found cause of revert and fixed
> > 
> > Original change's description:
> > > [Sheriff]: Revert "More Settings Page Interaction UMA"
> > >
> > > This reverts commit 561bf1af38509f6029ba688219b37f76a4e4f3b4.
> > >
> > > Reason for revert:
> > > Strongly suspect this is causing failures on the debug builders:
> > > [29058:775:0117/070736.663833:ERROR:CONSOLE(49)] "Mocha test failed: PersonalizationOptionsTests_AllBuilds signinAllowedToggle
> > > Error: Uncaught TypeError: Cannot read property 'PRIVACY_CHROME_SIGN_IN' of undefined (chrome://settings/privacy_page/personalization_options.js:102)
> > >
> > > r732804 was reverted earlier for the same reasons, but there are still failures coming from the settings code, albeit less
> > >
> > > Original change's description:
> > > > More Settings Page Interaction UMA
> > > >
> > > > Move the settings enum and the call to uma to a separate browser proxy.
> > > >
> > > > Add UMA to all site settings subpage interactions and new toggles moved to the main settings card
> > > >
> > > > Bug: 1032584
> > > > Change-Id: Icadd71d4511fa1f604f2d3acbda92c0e84700173
> > > > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1967651
> > > > Commit-Queue: Sean Harrison <harrisonsean@chromium.org>
> > > > Reviewed-by: Dan Beam <dbeam@chromium.org>
> > > > Cr-Commit-Position: refs/heads/master@{#732785}
> > >
> > > TBR=dbeam@chromium.org,harrisonsean@chromium.org
> > >
> > > Change-Id: Id4ee78d89487ecf7e6d1935088d02b29de89c7c8
> > > No-Presubmit: true
> > > No-Tree-Checks: true
> > > No-Try: true
> > > Bug: 1032584
> > > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2007829
> > > Reviewed-by: Leonard Grey <lgrey@chromium.org>
> > > Commit-Queue: Leonard Grey <lgrey@chromium.org>
> > > Cr-Commit-Position: refs/heads/master@{#732870}
> > 
> > Change-Id: Id60aa270741ac9305effac5a13587eb1a1d89102
> > Bug: 1032584
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2007716
> > Reviewed-by: Dan Beam <dbeam@chromium.org>
> > Commit-Queue: Sean Harrison <harrisonsean@chromium.org>
> > Cr-Commit-Position: refs/heads/master@{#733913}
> 
> TBR=dbeam@chromium.org,lgrey@chromium.org,harrisonsean@chromium.org
> 
> Change-Id: I9491e91268ed0ef59837a49161d79692e9c44ceb
> No-Presubmit: true
> No-Tree-Checks: true
> No-Try: true
> Bug: 1032584
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2015562
> Reviewed-by: Sebastien Lalancette <seblalancette@chromium.org>
> Commit-Queue: Sebastien Lalancette <seblalancette@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#734135}

Bug: 1044708, 1032584
Change-Id: I9276e6f02558db53201048225c2376eca37eb680
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2014968
Reviewed-by: Dan Beam <dbeam@chromium.org>
Reviewed-by: Sean Harrison <harrisonsean@chromium.org>
Commit-Queue: Sean Harrison <harrisonsean@chromium.org>
Cr-Commit-Position: refs/heads/master@{#734854}