ui/display: Include <bitset> for std::bitset
Follow-up to commit 1b7e6d75f ("ui/display: extend EdidParser for HDR
metadata") to fix the build with libstdc++ (and maybe MSVC):

./../../ui/display/util/edid_parser.cc:416:22: error: no template named 'bitset' in namespace 'std'
          const std::bitset<kMaxNumColorimetryEntries>
                ~~~~~^
./../../ui/display/util/edid_parser.cc:430:22: error: no template named 'bitset' in namespace 'std'
          const std::bitset<kMaxNumHDRStaticMedatataEntries>
                ~~~~~^

Bug: 957519, 1012846
Change-Id: Ic3c9c9416ac446bde9f190b9575ef1a386aa8e8e
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1862917
Commit-Queue: Raphael Kubo da Costa <raphael.kubo.da.costa@intel.com>
Commit-Queue: Miguel Casas <mcasas@chromium.org>
Auto-Submit: Raphael Kubo da Costa <raphael.kubo.da.costa@intel.com>
Reviewed-by: Miguel Casas <mcasas@chromium.org>
Cr-Commit-Position: refs/heads/master@{#705965}