Fix erroneous use of ref-counted class in supervised_user_service.
A completely unrelated change of mine resulted in
supervised_user_service actually having the header included when it
compiled, resulting in this error message:

error: static_assert failed
"a_parameter_is_refcounted_type_and_needs_scoped_refptr"

Review URL: https://codereview.chromium.org/905343004

Cr-Commit-Position: refs/heads/master@{#315824}