Revert "glic: Fix floaty positioning."
This reverts commit b06129d28a955087f7ccf91b1491fe63af4c4248.

Reason for revert:
Causes failures on multiple Mac bots, starting when it landed
https://ci.chromium.org/ui/p/chromium/builders/ci/mac11-arm64-rel-tests/52280/
https://ci.chromium.org/ui/p/chromium/builders/ci/mac13-arm64-rel-tests/42546/
https://ci.chromium.org/ui/p/chrome/builders/ci/linux64-rel-ready/41849/

The failing test is in interactive_ui_tests:
GlicWindowControllerUiTest.DoNotCrashWhenReopening

I also saw a failure of GlicWindowControllerUiTest.ShowAndCloseAttachedWidget.  (See second link above.)

Failures looks like:
112890:112890:0127/140629.250289:ERROR:interactive_browser_test.cc(735)] ExecuteJsAt() failed: 
Error: Target element is zero size or has empty intersection with the viewport.
    at EvalJs-runner.js:52:17
    at func (EvalJs-runner.js:75:6)
    at EvalJs-runner.js:82:17
    at EvalJs-runner.js:83:10
    at EvalJs-runner.js:90:11
../../ui/base/interaction/interactive_test_internal.cc:195: Failure
Failed
Interactive test failed on step 13 (CloseGlicWindow: InAnyContext(): ClickElement()) with reason kFailedForTesting; step type kShown; id ElementIdentifier kGlicContentsElementId; element 0x256c0371fe40


Original change's description:
> glic: Fix floaty positioning.
>
> There was 1 callsite that was not anchoring the top-right corner and was
> instead anchroing the top-left corner. This CL creates a helper method
> to address this edge case.
>
> Another fix: if glic calls Resize() while the open animation is playing,
> previously the open animation would be immediately overwritten and
> replaced with the new animation. Now the opening animation is
> maintained, and the new animation is played after the opening animation
> finishes.
>
> Bug: 392633732
> Change-Id: I423661e6bdf698eb5a792b53db383713caa1f38a
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6204241
> Commit-Queue: Erik Chen <erikchen@chromium.org>
> Reviewed-by: Ian Wells <iwells@chromium.org>
> Code-Coverage: findit-for-me@appspot.gserviceaccount.com <findit-for-me@appspot.gserviceaccount.com>
> Cr-Commit-Position: refs/heads/main@{#1411863}

Bug: 392633732
Change-Id: I1c3088165ce2e6edf2eba49a12f2d7ed762a05c2
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6203731
Commit-Queue: Mark Pearson <mpearson@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Reviewed-by: Erik Chen <erikchen@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1411931}