IWYU: libstdc++ unique_ptr cast from nullptr requires declaration of type
fallback_linux_ui.cc returns a nullptr as a result of several
calls returning a std::unique_ptr of a type that has not been declared
and that's not allowed in libstdc++ implementation.

Fix build errors:
    /usr/include/c++/12/bits/unique_ptr.h: In instantiation of ‘void std::default_delete<_Tp>::operator()(_Tp*) const [with _Tp = ui::LinuxInputMethodContext]’:
    /usr/include/c++/12/bits/unique_ptr.h:396:17:   required from ‘std::unique_ptr<_Tp, _Dp>::~unique_ptr() [with _Tp = ui::LinuxInputMethodContext; _Dp = std::default_delete<ui::LinuxInputMethodContext>]’
    ../../ui/linux/fallback_linux_ui.cc:35:10:   required from here
    /usr/include/c++/12/bits/unique_ptr.h:93:23: error: invalid application of ‘sizeof’ to incomplete type ‘ui::LinuxInputMethodContext’
       93 |         static_assert(sizeof(_Tp)>0,
          |                       ^~~~~~~~~~~
    /usr/include/c++/12/bits/unique_ptr.h: In instantiation of ‘void std::default_delete<_Tp>::operator()(_Tp*) const [with _Tp = ui::NavButtonProvider]’:
    /usr/include/c++/12/bits/unique_ptr.h:396:17:   required from ‘std::unique_ptr<_Tp, _Dp>::~unique_ptr() [with _Tp = ui::NavButtonProvider; _Dp = std::default_delete<ui::NavButtonProvider>]’
    ../../ui/linux/fallback_linux_ui.cc:133:10:   required from here
    /usr/include/c++/12/bits/unique_ptr.h:93:23: error: invalid application of ‘sizeof’ to incomplete type ‘ui::NavButtonProvider’

Bug: 957519
Change-Id: I5e7f096003d8f5de8f5be36137ac4427799bf7a5
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4310671
Reviewed-by: Thomas Anderson <thomasanderson@chromium.org>
Commit-Queue: Thomas Anderson <thomasanderson@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1113983}