Roll src/third_party/libyuv/ a6a2ec654..a4ccf9940 (115 commits)
https://chromium.googlesource.com/libyuv/libyuv.git/+log/a6a2ec654b1b..a4ccf9940e23

$ git log a6a2ec654..a4ccf9940 --date=short --no-merges --format='%ad %ae %s'
2024-04-18 george.steed [AArch64] Add I8MM implementation of ARGBToUV444Row
2024-06-11 george.steed [AArch64] Add missing feature disable flags to unit_test.cc
2024-07-12 george.steed Revert "Disable NV12ToARGB_SVE2 which fails the 'any' test"
2024-07-12 george.steed [AArch64] Fix rotate by odd sizes
2024-07-11 fbarchard Disable NV12ToARGB_SVE2 which fails the 'any' test
2024-04-18 george.steed [AArch64] Use full vectors in ARGB4444To{Y,UV}Row_NEON
2024-05-14 george.steed [AArch64] Rework data loading in ScaleARGBFilterCols_NEON
2024-04-17 george.steed [AArch64] Use full vectors in ARGB1555To{Y,UV}Row_NEON
2024-07-10 fbarchard Change inline to __asm__ for C
2024-07-09 fbarchard Fix for source/row_neon64.cc:551:12: error: unused variable 'alpha' [-Werror,-Wunused-variable]   551 |   uint16_t alpha = 0xc000;       |            ^~~~~ 1 error generated.
2024-05-16 george.steed [AArch64] Add SVE2 implementations of ARGBTo{RAW,RGB24}Row
2024-04-24 george.steed [AArch64] Keep UV interleaved in some *ToARGBRow_SVE2 kernels
2024-05-03 george.steed [AArch64] Add SVE2 implementation of RGB24ToARGBRow
2024-06-11 george.steed [AArch64] Enable SME feature detection on Apple Silicon
2024-04-25 george.steed [AArch64] Add SVE2 implementation of RAWToRGB24Row
2024-04-25 george.steed [AArch64] Add SVE2 implementations for RAWTo{ARGB,RGBA}Row
2024-04-10 george.steed [AArch64] Add P{210,410}To{ARGB,AR30}Row_NEON
2024-07-02 fbarchard [AArch64] Fix SVE/SME vector length printing in cpuid
2024-04-10 george.steed [AArch64] Add Neon implementation for I422ToAR30Row_NEON
2024-04-10 george.steed [AArch64] Add Neon impls for I212To{ARGB,AR30}Row_NEON
2024-07-02 fbarchard cpuid show vector length on ARM and RISCV
2024-07-01 fbarchard Add volatile for gcc inline to avoid being removed
2024-06-05 fbarchard Disable RVV ScaleDownBy4 if compiler option is not enabled
2024-06-17 fbarchard RVV remove unused variables
2023-08-09 bruce.lai Support RVV v0.12 intrinsics for row_rvv.cc & scale_rvv.cc
2024-06-12 george.steed [Arm][AArch64] Stop explicitly optimising for speed in BUILD.gn
2024-04-24 george.steed [AArch64] Add SVE2 impls for {UYVY,YUY2}ToARGBRow
2024-04-23 george.steed [AArch64] Add SVE2 implementation of I400ToARGBRow
2024-04-23 george.steed [AArch64] Add SVE2 implementations for NV{12,21}ToARGBRow
2024-04-10 george.steed [AArch64] Add I8MM implementation of ARGBColorMatrixRow
2024-04-19 george.steed [AArch64] Avoid unnecessary widening in I422ToARGB1555Row_NEON
2024-04-18 george.steed [Arm][AArch64] Remove unused ARGBToUVJ444Row_NEON definition
2024-05-20 george.steed [AArch64] Print the SVE and SME vector lengths in cpu_id
2024-05-20 george.steed [AArch64] Add SME feature detection on Linux
2024-06-07 george.steed [AArch64] Remove redundant semicolons after ANY41CT
2024-05-22 george.steed [AArch64] Add initial build system support for SME
2024-06-05 george.steed [AArch64] Remove unused vars in I{210,410}{,Alpha}ToARGBRow_NEON
2024-04-23 george.steed [AArch64] Add SVE2 implementation of I422ToRGBARow
2024-04-22 george.steed [AArch64] Add SVE2 implementations for AYUVTo{UV,VU}Row
2024-04-17 george.steed [AArch64] Add SVE2 implementation of ARGB1555ToARGBRow
2024-04-15 george.steed [AArch64] Add SVE2 implementation of ARGBToRGB565DitherRow
2024-03-23 george.steed [AArch64] Use full Neon vectors in ARGB4444ToARGBRow_NEON
2024-04-10 george.steed [AArch64] Remove pointless MOVI in ARGB1555ToARGBRow_NEON
2024-04-10 george.steed [AArch64] Add Neon impls for I{210,410}ToAR30Row_NEON
2024-05-22 george.steed [docs] Add documentation on AArch64 SME for feature detection
2024-05-14 george.steed [Arm] Clean up rotate_neon.cc kernels
2024-04-15 george.steed [AArch64] Add SVE2 implementation of ARGBToRGB565Row
2024-04-10 george.steed [AArch64] Add Neon impls for I{210,410}ToARGBRow_NEON
2024-04-10 george.steed [AArch64] Add Neon impls for I{210,410}AlphaToARGBRow_NEON
2024-03-22 george.steed [AArch64] Optimize MergeXR30Row_10_NEON
(...)
2024-04-12 george.steed [AArch64] Add SVE2 implementations for ARGBToUVRow and similar
2024-04-25 george.steed [AArch64] Add Neon implementation of HashDjb2
2024-03-14 george.steed [AArch64] Use LD1/ST1 rather than LD4/ST4 in ARGBShadeRow_NEON
2024-04-19 george.steed [AArch64] Avoid extraneous CMP in I{444,422}ToARGBRow_SVE2 impl
2024-03-17 george.steed [AArch64] Add SVE implementation for I422AlphaToARGBRow
2024-03-17 george.steed [AArch64] Add SVE implementation for I444AlphaToARGBRow
2024-03-17 george.steed [AArch64] Add SVE implementation for I422ToARGBRow
2024-04-25 george.steed [AArch64] Add Neon dot-product implementation of HammingDistance
2024-04-26 george.steed [AArch64] Unroll SumSquareError_NEON_DotProd
2024-03-15 george.steed [AArch64] getauxval(AT_HWCAP{,2}) feature detection, attempt #2
2024-03-14 george.steed [AArch64] Replace UQXTN{,2} with UZP2 in Convert16To8Row_NEON
2024-03-13 george.steed [AArch64] Replace SHRN{,2} pair by UZP2 in DivideRow_16_NEON
2024-04-16 george.steed [AArch64] Add Neon dot-product implementation of SumSquareError
2024-02-20 george.steed [AArch64] Replace instances of ORR with MOV where possible
2024-04-18 fbarchard Fix environment variable LIBYUV_CPU_INFO for unittests
2024-04-19 fbarchard Revert "[AArch64] Use getauxval(AT_HWCAP{,2}) for feature detection"
2024-03-18 george.steed [AArch64] Add missing clobber, fix zero-init for compare kernels
2024-03-15 george.steed [AArch64] Use getauxval(AT_HWCAP{,2}) for feature detection
2024-04-16 george.steed [AArch64] Load full vectors in ARGB{Add,Subtract}Row
2024-03-13 george.steed [AArch64] Improve RGB565TOARGB using SRI instructions
2024-03-14 george.steed [AArch64] Avoid lane-indexed loads for UV when loading I444/I422
2024-03-13 george.steed [AArch64] Improve ARGB{,1}555TOARGB using SRI instructions
2024-03-13 george.steed [AArch64] Improve ARGBTOARGB4444 using SRI instructions
2024-03-14 george.steed [AArch64] Avoid unnecessary work in READYUV400
2024-03-24 george.steed [AArch64] Use LD1/ST1 rather than LD4/ST4 in ARGBMultiplyRow_NEON
2024-03-24 george.steed [AArch64] Use LD1/ST1 rather than LD4/ST4 in ARGBSubtractRow_NEON
2024-03-24 george.steed [AArch64] Use LD1/ST1 rather than LD4/ST4 in ARGBAddRow_NEON
2024-04-11 martin CMake: Use CMAKE_SOURCE_DIR in GTEST_SRC_DIR
2024-04-11 martin CMake: Allow the user to set GTEST_SRC_DIR when cross compiling
2024-04-11 martin CMake: Improve the checks for CMAKE_SYSTEM_PROCESSOR
2024-04-10 george.steed [Arm] Don't expose DotProd kernels, fix CMakeLists.txt
2024-02-14 cosmina.dunca [AArch64] Optimize ScaleARGBRowDown2Box_NEON
2024-02-12 cosmina.dunca [AArch64] Optimize ScaleARGBRowDownEven_NEON
2024-04-09 george.steed [AArch64] Fix CMakeLists.txt to enable architecture extensions
2024-03-16 george.steed [AArch64] Add SVE2 implementation for I444ToARGBRow
2024-03-21 george.steed [AArch64] Add :libyuv_sve library in preparation for SVE kernels
2024-03-15 george.steed [AArch64] Use Neon dot-product instructions in ARGBToYMatrixRow
2024-03-19 george.steed [AArch64] Add Neon DotProduct and I8MM extensions when building
2024-04-08 uioptt24 [DEPS] Remove `cleanup_links` pre_deps_hooks
2024-03-15 george.steed [AArch64] Enable detection of additional architecture features
2024-03-22 daniel.l Fix missing headers in GN/GYP build files
2024-03-24 george.steed [AArch64] Remove out of date TODO around ARGBMultiplyRow_NEON
2024-03-25 george.steed [AArch64] Remove declarations of P{210,410}To{ARGB,AR30}Row_NEON
2024-03-18 fbarchard Add CHROMIUM define when building libyuv with GN
2024-03-12 george.steed [AArch64] Replace UQSHRN{,2} pair by UZP2 in YUVTORGB
2024-03-12 george.steed [AArch64] Avoid LD2 in YUY2ToARGBRow_NEON
2024-03-12 george.steed [AArch64] Avoid unnecessary lane-indexed loads in READYUV
2024-01-19 george.steed Add missing memory/cc clobbers to AArch64 Neon kernels
2024-02-29 fbarchard Revert "AMX detect OS support for linux kernel"
2024-02-27 fbarchard AMX detect OS support for linux kernel

Created with:
  roll-dep src/third_party/libyuv

Change-Id: Id7a5114654d0b585b3a836c4e55aeaae56ec3d39
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5778746
Reviewed-by: Frank Barchard <fbarchard@chromium.org>
Auto-Submit: Wan-Teh Chang <wtc@google.com>
Commit-Queue: Wan-Teh Chang <wtc@google.com>
Cr-Commit-Position: refs/heads/main@{#1340085}