Revert 227521 "Blink roll 159088:159109"
Compile fails with:
c:\b\build\slave\cr-win-dbg-x64\build\src\third_party\webkit\source\platform\audio\hrtfkernel.cpp(60) :error C2220: warning treated as error - no 'object' file generated
c:\b\build\slave\cr-win-dbg-x64\build\src\third_party\webkit\source\platform\audio\hrtfkernel.cpp(60) : warning C4334: '<<' : result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)

http://build.chromium.org/p/chromium.win/buildstatus?builder=Win%20x64%20Builder%20%28dbg%29&number=3072

> Blink roll 159088:159109
> 
> http://build.chromium.org/f/chromium/perf/dashboard/ui/changelog_blink.html?url=/trunk&range=159089:159109&mode=html
> TBR=
> BUG=
> 
> Review URL: https://codereview.chromium.org/26454003

TBR=eseidel@chromium.org

Review URL: https://codereview.chromium.org/26482004

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@227526 0039d316-1c4b-4281-b951-d872f2087c98