SnapSelectionStrategy: Include <memory>
IWYU. std::unique_ptr needs <memory>, which was being included indirectly
and breaking the libstdc++ build after commit e806ef73a7 ("Snap after
pressing arrow key"):

In file included from ../../cc/input/snap_selection_strategy.cc:5:0:
../../cc/input/snap_selection_strategy.h:20:15: error: ‘unique_ptr’ in namespace ‘std’ does not name a template type
   static std::unique_ptr<SnapSelectionStrategy> CreateForEndPosition(
               ^~~~~~~~~~
../../cc/input/snap_selection_strategy.h:24:15: error: ‘unique_ptr’ in namespace ‘std’ does not name a template type
   static std::unique_ptr<SnapSelectionStrategy> CreateForDirection(
               ^~~~~~~~~~
../../cc/input/snap_selection_strategy.h:27:15: error: ‘unique_ptr’ in namespace ‘std’ does not name a template type
   static std::unique_ptr<SnapSelectionStrategy> CreateForEndAndDirection(
               ^~~~~~~~~~
../../cc/input/snap_selection_strategy.cc:9:6: error: ‘unique_ptr’ in namespace ‘std’ does not name a template type
 std::unique_ptr<SnapSelectionStrategy>
      ^~~~~~~~~~
../../cc/input/snap_selection_strategy.cc:18:6: error: ‘unique_ptr’ in namespace ‘std’ does not name a template type
 std::unique_ptr<SnapSelectionStrategy>
      ^~~~~~~~~~
../../cc/input/snap_selection_strategy.cc:24:6: error: ‘unique_ptr’ in namespace ‘std’ does not name a template type
 std::unique_ptr<SnapSelectionStrategy>
      ^~~~~~~~~~

Bug: 819294
Change-Id: I83c594b1ae71a34f21e77c7c9d866e47629c7a61
Reviewed-on: https://chromium-review.googlesource.com/c/1304418
Reviewed-by: David Bokan <bokan@chromium.org>
Commit-Queue: Raphael Kubo da Costa <raphael.kubo.da.costa@intel.com>
Cr-Commit-Position: refs/heads/master@{#603480}