Revert "[Battery] Add WebRtcEventProvider"
This reverts commit 7c76677b0fabdfcf65a6251887b23e5c940ccc72.

Reason for revert: WebRtcEventProviderBrowserTest.DetectWebRtc fails for Win7
https://ci.chromium.org/ui/p/chromium/builders/ci/Win7%20Tests%20(1)/115960/overview

../../chrome/browser/metrics/usage_scenario/webrtc_event_provider_browsertest.cc(59): error: Expected equality of these values:
  data_store()->webrtc_open_connection_count_for_testing()
    Which is: 0
  2
Stack trace:
Backtrace:
	WebRtcEventProviderBrowserTest_DetectWebRtc_Test::RunTestOnMainThread [0x0167565E+542]
	content::BrowserTestBase::ProxyRunTestOnMainThreadLoop [0x04F4D64C+348]
	ChromeBrowserMainParts::PreMainMessageLoopRunImpl [0x04DE67D8+3176]
	ChromeBrowserMainParts::PreMainMessageLoopRun [0x04DE5ABC+60]
	content::BrowserMainLoop::PreMainMessageLoopRun [0x034DE2B1+65]
	content::StartupTaskRunner::RunAllTasksNow [0x037FBC89+45]


Original change's description:
> [Battery] Add WebRtcEventProvider
>
> This class provides WebRTC peer connection events to
> the UsageScenarioDataStore.
>
> Bug: 1191026
> Change-Id: Ie41dc1e2554e18822af1848bf0bd8f1b9dca8cb7
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2704605
> Reviewed-by: Sébastien Marchand <sebmarchand@chromium.org>
> Commit-Queue: Patrick Monette <pmonette@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#870738}

Bug: 1191026
Change-Id: I7df4f3ddfec5e720f9e0fe1692bed6e8aacc92bd
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2817979
Auto-Submit: Maxim Kolosovskiy  <kolos@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Leonard Grey <lgrey@chromium.org>
Reviewed-by: Maxim Kolosovskiy  <kolos@chromium.org>
Reviewed-by: Leonard Grey <lgrey@chromium.org>
Owners-Override: Maxim Kolosovskiy  <kolos@chromium.org>
Cr-Commit-Position: refs/heads/master@{#870937}