Revert "Migrate NavigationHandle from String URLs to GURL"
This reverts commit 0b0e075344e2d851a6eb71946b93348791054e00.

Reason for revert: Android builders failing after this is checked in. Error message is related:
error: incompatible types: String cannot be converted to GURL

Original change's description:
> Migrate NavigationHandle from String URLs to GURL
> 
> Migrates NavigationHandle to use GURL internally and adds getUrlString
> for callsites that still need URLs to be a string (to be fixed in
> followups).
> 
> Some unit tests needed to be moved to Instrumentation tests, one
> requiring a change to CriteriaHelper to allow checking for a condition
> after every task.
> 
> QualityEnforcerUnitTest was too difficult to migrate to Instrumentation
> tests, so it now uses JUnitTestGURLs to use GURL in junit tests.
> 
> Bug: 783819
> Change-Id: I1283d5d7d1946e666e964f8d24aeaf0352eb8805
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2419140
> Reviewed-by: Yaron Friedman <yfriedman@chromium.org>
> Commit-Queue: Michael Thiessen <mthiesse@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#809396}

TBR=yfriedman@chromium.org,mthiesse@chromium.org

Change-Id: Idb17bbf3cba4034c8ce47afc331b77117608ab9b
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 783819
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2425006
Reviewed-by: Wenbin Zhang <wenbinzhang@google.com>
Commit-Queue: Wenbin Zhang <wenbinzhang@google.com>
Cr-Commit-Position: refs/heads/master@{#809480}