Revert "Deflake SchemeRegistryTest.BypassSecureContextCheck"
This reverts commit 081122ecd70780703081aebe0c5bfaedd5f55861.

Reason for revert: Compile failure in CQ
error: no member named 'SetIsBeforeThreadCreatedForTest' in namespace 'WTF'

Original change's description:
> Deflake SchemeRegistryTest.BypassSecureContextCheck
>
> Due to the check reintroduced by:
> https://chromium-review.googlesource.com/c/chromium/src/+/2838326
>
> The test:
> SchemeRegistryTest.BypassSecureContextCheck
> is now flaky.
>
> The test is modifying the scheme registry after some Thread might have
> been created.
>
> Fixed: 1229522
> Bug: 1229522
> Change-Id: I2d56295192f8e04ba7d99a99d743e65978d80c55
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3035023
> Commit-Queue: Mike West <mkwst@chromium.org>
> Auto-Submit: Arthur Sonzogni <arthursonzogni@chromium.org>
> Reviewed-by: Mike West <mkwst@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#902926}

Bug: 1229522
Change-Id: Ia3247c928e6cc617582da8f5aca3a8a36ebfe4b7
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3035773
Auto-Submit: Friedrich [CET] <fhorschig@chromium.org>
Reviewed-by: Friedrich [CET] <fhorschig@chromium.org>
Reviewed-by: Ioana Pandele <ioanap@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Ioana Pandele <ioanap@chromium.org>
Owners-Override: Friedrich [CET] <fhorschig@chromium.org>
Cr-Commit-Position: refs/heads/master@{#902930}