Revert "chromeos/assistant: CrosActionModule ctor fix compilation"
This reverts commit 2e21ac993df016a4c031505927b8a73d6a2a6b9a.

Reason for revert: Persistent compile failure is blocking any src-internal roll for 30+ hours
error: no matching constructor for initialization of 'chromeos::assistant::action::CrosActionModule'
    return unique_ptr<_Tp>(new _Tp(_VSTD::forward<_Args>(__args)...));
                               ^   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../chromeos/services/assistant/assistant_manager_service_impl.cc:160:27: note: in instantiation of function template specialization 'std::__1::make_unique<chromeos::assistant::action::CrosActionModule, chromeos::assistant::AssistantManagerServiceImpl *, bool, bool, bool>' requested here
      action_module_(std::make_unique<action::CrosActionModule>(
                          ^
../../chromeos/assistant/internal/action/cros_action_module.h:159:12: note: candidate constructor not viable: requires at most 3 arguments, but 4 were provided
  explicit CrosActionModule(AssistantActionObserver* assistant_event_observer,

link: https://ci.chromium.org/p/chrome/builders/ci/linux-chromeos-chrome/3983

Original change's description:
> chromeos/assistant: CrosActionModule ctor fix compilation
>
> Roll src/chromeos/assistant/internal/ d3a99ca02..4e7273378
> added a parameter to CrosActionModule ctor, but the code what was
> instantiating one still assumes there are only three parameters.
>
> This CL adds the fourth parameter where we instantiate CrosActionModule.
>
> Bug: b:149570650
> Test: Now chrome for chromeos compiles
> Change-Id: I950a3557df7d996b5d0695b9fa2de4633c448afe
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2103717
> Reviewed-by: Xiaohui Chen <xiaohuic@chromium.org>
> Commit-Queue: Xiaohui Chen <xiaohuic@chromium.org>
> Auto-Submit: Daniele Castagna <dcastagna@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#750409}

TBR=dcastagna@chromium.org,xiaohuic@chromium.org,dmblack@google.com

# Not skipping CQ checks because original CL landed > 1 day ago.

Bug: 1061670, b:149570650
Change-Id: I385b38f8dfde3233cccc8213e85ebb9d67f88a75
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2102994
Reviewed-by: Trent Apted <tapted@chromium.org>
Commit-Queue: Trent Apted <tapted@chromium.org>
Cr-Commit-Position: refs/heads/master@{#750456}