Revert "siso: update to version 1.3.12"
This reverts commit be0d23742daddde982478861aae4f58782f77f31.

Reason for revert: 
https://ci.chromium.org/ui/p/chromium/builders/ci/linux-extended-tracing-rel/93660/overview

```
../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/content/browser/browser/save_file_manager.o.d -D__STDC_CONSTANT_MACROS -...(too long)
clang++: error: no such file or directory: '../../content/browser/download/save_file_manager.cc'
clang++: error: no input files
remote-exec 82384a6b6655bfb1b0d3023107ba674802614a10830fa406e91897c66d526b92/355 failed: exit=1
error: 1 steps failed: remote-exec 82384a6b6655bfb1b0d3023107ba674802614a10830fa406e91897c66d526b92/355 failed: exit=1
```

Bug: 436113143
Original change's description:
> siso: update to version 1.3.12
>
> ukai@ukai ...src/infra/infra % git log --oneline \
>  887a10bc8a038d8e330d06d1ad5ae6ec646f3040..948637c5fe0dcb9b5de28268939dfaff907bb11c \
>   go/src/infra/build/siso
> 948637c5fe [Siso] execute: Wrap errors with more context
> 9b8228f35c siso: fix version
> 53d8543752 siso: show credential type
> ffe8181001 siso: remove go.chromium.org/luci dependency.
> 54b407a89d siso: cache-write continue on error
> 986a68d348 siso: use luci-auth binary instead of go.chromium.org/luci/auth
> 5d38d46d12 revive clang -M deps scanning for scandeps unprocessable inputs
> 7a27a1d596 siso: cache-write cleanup unused test files
> aa4502abb9 siso: cache-write rename nit followups
> 7b33956acb siso: fix backtrace for siso_build.pprof
> 11658bdfb7 siso: rename local-upload to cache-write followup
> 2c2137c587 siso: remove dependency to go.chromium.org/luci/cipd/version
> 8eca0bbaa1 siso: fix noctx lint error in reapi/reapi_test.go
> 40cbf77425 siso: fix noctx lint error after 6799580 merge
> d687cb68af siso: update version string to v1.3.12
>
> Bug: 436113143
> Change-Id: Ia7342bff4069ca1d99cc9a893505c91bd97d7e02
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6820441
> Auto-Submit: Fumitoshi Ukai <ukai@google.com>
> Reviewed-by: Takuto Ikuta <tikuta@chromium.org>
> Commit-Queue: Fumitoshi Ukai <ukai@google.com>
> Cr-Commit-Position: refs/heads/main@{#1497290}

Bug: 436113143
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Change-Id: I45764634c021e06d583c52fb291382ac086c4ac1
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6819941
Auto-Submit: Fumitoshi Ukai <ukai@google.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Cr-Commit-Position: refs/heads/main@{#1497301}