DevicePosturePlatformProviderAndroid: Speculative fix for NoClassDefFoundError
Moves the is-the-API-available logic of WindowLayoutInfoListener, since
that class uses types that are accessible only when the API is
available.

Bug: 336827691
Change-Id: Id31e71862637e8e7ff014681717a6e2343c52220
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5490190
Reviewed-by: Sam Maier <smaier@chromium.org>
Commit-Queue: Andrew Grieve <agrieve@chromium.org>
Owners-Override: Andrew Grieve <agrieve@chromium.org>
Auto-Submit: Andrew Grieve <agrieve@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1293757}