Revert of Gets native_widget_unittest running for mus (patchset #6 id:100001 of https://codereview.chromium.org/1739333002/ )
Reason for revert:
Suspect for failure :
https://build.chromium.org/p/chromium/builders/Mac/builds/12488

FAILED: /b/build/goma/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/ui/views/cocoa/macviews_interactive_ui_tests.bridged_native_widget_interactive_uitest.o.d -DV8_DEPRECATION_WARNINGS -DCLD_VERSION=2 -D__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORE=0 -DCHROMIUM_BUILD -DCR_CLANG_REVISION=261368-1 -DUSE_LIBJPEG_TURBO=1 -DENABLE_WEBRTC=1 -DENABLE_MEDIA_ROUTER=1 -DENABLE_PEPPER_CDMS -DENABLE_CONFIGURATION_POLICY -DENABLE_NOTIFICATIONS -DENABLE_TOPCHROME_MD=1 -DFIELDTRIAL_TESTING_ENABLED -DENABLE_TASK_MANAGER=1 -DENABLE_EXTENSIONS=1 -DENABLE_PDF=1 -DENABLE_PLUGIN_INSTALLATION=1 -DENABLE_PLUGINS=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_THEMES=1 -DENABLE_AUTOFILL_DIALOG=1 -DENABLE_PRINTING=1 -DENABLE_BASIC_PRINTING=1 -DENABLE_PRINT_PREVIEW=1 -DENABLE_SPELLCHECK=1 -DUSE_BROWSER_SPELLCHECKER=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_APP_LIST=1 -DENABLE_SETTINGS_APP=1 -DENABLE_SUPERVISED_USERS=1 -DENABLE_SERVICE_DISCOVERY=1 -DV8_USE_EXTERNAL_STARTUP_DATA -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DGTEST_HAS_POSIX_RE=0 -DGTEST_LANG_CXX11=0 -DTOOLKIT_VIEWS=1 -DSK_SUPPORT_GPU=1 -DSK_IGNORE_LINEONLY_AA_CONVEX_PATH_OPTS -DUNIT_TEST -DGTEST_HAS_RTTI=0 -DUSE_LIBPCI=1 -DUSE_OPENSSL=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -D_FORTIFY_SOURCE=2 -Igen -I../.. -I../../skia/config -I../../third_party/khronos -I../../gpu -Igen/angle -I../../third_party/WebKit/Source -I../../third_party/skia/include/core -I../../third_party/skia/include/effects -I../../third_party/skia/include/pdf -I../../third_party/skia/include/gpu -I../../third_party/skia/include/lazy -I../../third_party/skia/include/pathops -I../../third_party/skia/include/pipe -I../../third_party/skia/include/ports -I../../third_party/skia/include/utils -I../../third_party/skia/include/utils/mac -I../../skia/ext -I../../testing/gtest/include -Igen/ui/resources -Igen/ui/views/resources -isysroot /Applications/Xcode5.1.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -O2 -gdwarf-2 -fvisibility=hidden -Werror -mmacosx-version-min=10.6 -arch x86_64 -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wno-selector-type-mismatch -Wpartial-availability -Wheader-hygiene -Wno-char-subscripts -Wno-unneeded-internal-declaration -Wno-covered-switch-default -Wstring-conversion -Wno-c++11-narrowing -Wno-deprecated-register -Wno-inconsistent-missing-override -Wno-shift-negative-value -std=c++11 -stdlib=libc++ -fno-rtti -fno-exceptions -fvisibility-inlines-hidden -fno-threadsafe-statics -Xclang -load -Xclang /b/build/slave/Mac/build/src/third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.dylib -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang check-templates -Xclang -plugin-arg-find-bad-constructs -Xclang follow-macro-expansion -fcolor-diagnostics -fno-strict-aliasing -Wobjc-missing-property-synthesis -fobjc-call-cxx-cdtors  -c ../../ui/views/cocoa/bridged_native_widget_interactive_uitest.mm -o obj/ui/views/cocoa/macviews_interactive_ui_tests.bridged_native_widget_interactive_uitest.o
../../ui/views/cocoa/bridged_native_widget_interactive_uitest.mm:272:39: error: base class has incomplete type
class HitTestNativeWidgetMac : public NativeWidgetMac {
                               ~~~~~~~^~~~~~~~~~~~~~~
../../ui/views/cocoa/bridged_native_widget.h:37:7: note: forward declaration of 'views::NativeWidgetMac'
class NativeWidgetMac;
      ^
../../ui/views/cocoa/bridged_native_widget_interactive_uitest.mm:286:50: error: only virtual member functions can be marked 'override'
  NonClientFrameView* CreateNonClientFrameView() override {
                                                 ^~~~~~~~~
../../ui/views/cocoa/bridged_native_widget_interactive_uitest.mm:276:9: error: type 'views::NativeWidgetMac' is not a direct or virtual base of 'views::test::HitTestNativeWidgetMac'
      : NativeWidgetMac(delegate), native_frame_view_(native_frame_view) {
        ^~~~~~~~~~~~~~~
../../ui/views/cocoa/bridged_native_widget_interactive_uitest.mm:277:5: error: incomplete type 'views::NativeWidgetMac' named in nested name specifier
    NativeWidgetMac::bridge_.reset(new HitTestBridgedNativeWidget(this));
    ^~~~~~~~~~~~~~~~~
../../ui/views/cocoa/bridged_native_widget.h:37:7: note: forward declaration of 'views::NativeWidgetMac'
class NativeWidgetMac;
      ^
../../ui/views/cocoa/bridged_native_widget_interactive_uitest.mm:277:40: error: no matching constructor for initialization of 'views::test::(anonymous namespace)::HitTestBridgedNativeWidget'
    NativeWidgetMac::bridge_.reset(new HitTestBridgedNativeWidget(this));
                                       ^                          ~~~~
../../ui/views/cocoa/bridged_native_widget_interactive_uitest.mm:182:12: note: candidate constructor not viable: no known conversion from 'views::test::HitTestNativeWidgetMac *' to 'views::NativeWidgetMac *' for 1st argument
  explicit HitTestBridgedNativeWidget(NativeWidgetMac* widget)
           ^
../../ui/views/cocoa/bridged_native_widget_interactive_uitest.mm:210:28: note: candidate constructor not viable: no known conversion from 'views::test::HitTestNativeWidgetMac *' to 'const views::test::(anonymous namespace)::HitTestBridgedNativeWidget' for 1st argument
  DISALLOW_COPY_AND_ASSIGN(HitTestBridgedNativeWidget);
                           ^
../../base/macros.h:26:3: note: expanded from macro 'DISALLOW_COPY_AND_ASSIGN'
  TypeName(const TypeName&);               \
  ^
../../ui/views/cocoa/bridged_native_widget_interactive_uitest.mm:282:9: error: incomplete type 'views::NativeWidgetMac' named in nested name specifier
        NativeWidgetMac::bridge_.get());
        ^~~~~~~~~~~~~~~~~
../../ui/views/cocoa/bridged_native_widget.h:37:7: note: forward declaration of 'views::NativeWidgetMac'
class NativeWidgetMac;
      ^
../../ui/views/cocoa/bridged_native_widget_interactive_uitest.mm:306:29: error: assigning to 'views::NativeWidget *' from incompatible type 'test::HitTestNativeWidgetMac *'
  init_params.native_widget = native_widget;
                            ^ ~~~~~~~~~~~~~
7 errors generated.
ninja: build stopped: subcommand failed.

Original issue's description:
> Gets native_widget_unittest running for mus
>
> These tests subclass the NativeWidget implementation for a couple of
> things. I had to restructure the code so that for views_mus_unittests
> we create the appropriate NativeWidgetMus.
>
> BUG=577274
> TEST=covered by tests
> R=ben@chromium.org
>
> Committed: https://crrev.com/0eafe80be1171d67a79db3b7e74f5fa90f4559c2
> Cr-Commit-Position: refs/heads/master@{#378005}

TBR=ben@chromium.org,sky@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=577274

Review URL: https://codereview.chromium.org/1747503002

Cr-Commit-Position: refs/heads/master@{#378038}