telemetry: Add stub for webdriver default browser selection
The WebDriver browser finder needs to implement SelectDefaultBrowser()
to avoid the following exception:

    Traceback (most recent call last):
      File "content/test/gpu/run_gpu_test", line 14, in <module>
        sys.exit(test_runner.Main())
      File "content/test/gpu/../../../tools/telemetry/telemetry/test_runner.py", line 162, in Main
        return command.Run(options, args)
      File "content/test/gpu/../../../tools/telemetry/telemetry/test_runner.py", line 106, in Run
        test_failures = _GetTests()[test_name]().Run(copy.copy(options))
      File "content/test/gpu/../../../tools/telemetry/telemetry/test.py", line 43, in Run
        results = page_runner.Run(test, ps, expectations, options)
      File "content/test/gpu/../../../tools/telemetry/telemetry/page/page_runner.py", line 225, in Run
        possible_browser = browser_finder.FindBrowser(options)
      File "content/test/gpu/../../../tools/telemetry/telemetry/core/browser_finder.py", line 57, in FindBrowser
        default_browser = finder.SelectDefaultBrowser(curr_browsers)
    AttributeError: 'module' object has no attribute 'SelectDefaultBrowser'

NOTRY=true
TEST=content/test/gpu/run_gpu_test --browser=android-chrome webgl_conformance

Review URL: https://chromiumcodereview.appspot.com/22866007

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@217799 0039d316-1c4b-4281-b951-d872f2087c98