Revert of Re-land: Use script in depot_tools to retrieve builders from new cq.cfg (patchset #2 id:20001 of https://codereview.chromium.org/1148303006/)
Reason for revert:
Breaks the "git cl try" command, see chromium-dev@ and crbug.com/495219.

Traceback (most recent call last):
  File "/b/depot_tools/commit_queue.py", line 28, in <module>
    from cq_client import cq_pb2
  File "/b/depot_tools/third_party/cq_client/cq_pb2.py", line 9, in <module>
    from google.protobuf import symbol_database as _symbol_database
ImportError: cannot import name symbol_database

BUG=495219

Original issue's description:
> Re-land: Use script in depot_tools to retrieve builders from new cq.cfg
>
> TBR=akuegel@chromium.org, jochen@chromium.org
> TEST=ran git-cl-try on this CL on Win, Mac and Linux
>
> Committed: https://crrev.com/2c7fb79b2aad9d924dcbcd663e09f3022884f502
> Cr-Commit-Position: refs/heads/master@{#332369}

TBR=akuegel@chromium.org,jochen@chromium.org,sergiyb@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true

Review URL: https://codereview.chromium.org/1160783004

Cr-Commit-Position: refs/heads/master@{#332384}