Revert of Unify enum NextProto and enum AlternateProtocol. (patchset #4 id:60001 of https://codereview.chromium.org/2373663002/ )
Reason for revert:
https://build.chromium.org/p/chromium.memory.full/builders/Chromium%20Linux%20ChromeOS%20MSan%20Builder/builds/2943/steps/compile/logs/stdio

../../components/grpc_support/test/get_stream_engine.cc:52:56: error: no member named 'AlternateProtocol' in namespace 'net'; did you mean 'AlternateProtocolUsage'?
      net::AlternativeService alternative_service(net::AlternateProtocol::QUIC,
                                                  ~~~~~^~~~~~~~~~~~~~~~~
                                                       AlternateProtocolUsage

Original issue's description:
> Unify enum NextProto and enum AlternateProtocol.
>
> * Use NextProto instead of AlternateProtocol everywhere.
> * Remove enum AlternateProtocol, AlternateProtocolFromNextProto().
> * Move SSLClientSocketImpl::NextProto{To,From}String() to
> * next_proto.cc.
> * Combine AlternateProtocol{To,From}String() into
> * NextProto{To,From}String().
> * Remove unused SpdyHttpStream::negotiated_protocol_.
>
> BUG=116575
>
> Committed: https://crrev.com/f98f01d87fb1f315de400c6829ad467ae95caa7a
> Cr-Commit-Position: refs/heads/master@{#431572}

TBR=rch@chromium.org,xunjieli@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=116575

Review-Url: https://codereview.chromium.org/2496953002
Cr-Commit-Position: refs/heads/master@{#431575}