Fix a build error on the Mac OS with the case-sensitive file system.
On Mac OS with HFS+, ToT currently breaks at:
In file included from ../../third_party/WebKit/Source/platform/mac/LocalCurrentGraphicsContext.mm:21:
../../third_party/WebKit/Source/platform/mac/LocalCurrentGraphicsContext.h:20:10: fatal error: 'platform/Geometry/IntRect.h' file not found

".../Geometry/..." should be changed to lowercase.

Review URL: https://codereview.chromium.org/513013002

git-svn-id: svn://svn.chromium.org/blink/trunk@181008 bbb929c8-8fbe-4397-9dbb-9b2b20218538