libstdc++: fix copy constructors declaration in update_client
The copy constructors declaration for protocol_request::Data and
ProtocolParser::Result::Data are missing const, so they are not the
regular copy constructor.

This does not play well with libstdc++ implementation of std::vector.

Fixes these compilation errors:
    /usr/include/c++/11/bits/stl_algobase.h:385:25: error: binding reference of type ‘update_client::protocol_request::Data&’ to ‘const update_client::protocol_request::Data’ discards qualifiers
      385 |               *__result = *__first;
          |               ~~~~~~~~~~^~~~~~~~~~
    In file included from ../../components/update_client/protocol_serializer.h:15,
                     from ../../components/update_client/protocol_serializer.cc:5:
    ../../components/update_client/protocol_definition.h:84:19: note:   initializing argument 1 of ‘update_client::protocol_request::Data& update_client::protocol_request::Data::operator=(update_client::protocol_request::Data&)’
       84 |   Data& operator=(Data&);
          |                   ^~~~~
    /usr/include/c++/11/bits/stl_algobase.h:385:25: error: binding reference of type ‘update_client::ProtocolParser::Result::Data&’ to ‘const update_client::ProtocolParser::Result::Data’ discards qualifiers
      385 |               *__result = *__first;
          |               ~~~~~~~~~~^~~~~~~~~~
    In file included from ../../components/update_client/component.h:22,
                     from ../../components/update_client/update_engine.h:19,
                     from ../../components/update_client/update_engine.cc:5:
    ../../components/update_client/protocol_parser.h:63:23: note:   initializing argument 1 of ‘update_client::ProtocolParser::Result::Data& update_client::ProtocolParser::Result::Data::operator=(update_client::ProtocolParser::Result::Data&)’
       63 |       Data& operator=(Data&);
          |                       ^~~~~

Bug: 957519
Change-Id: I19ae96f9a9355a964952c4919947c3adc90e1fbd
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3515642
Reviewed-by: Joshua Pawlicki <waffles@chromium.org>
Commit-Queue: José Dapena Paz <jdapena@igalia.com>
Cr-Commit-Position: refs/heads/main@{#979925}