Reland: Include translate information in onProvideAssistContent.
Fixing by removing the AssistContent dependency from tests. Only TranslateAssistContentTest.java has been modified from the original CL.

AssistContent and onProvideAssistContent are only present in M+ SDKs, which was causing some bots to fail to enumerate tests due to a NoClassDefFoundError.

Rather than calling onProvideAssistContent, call getTranslateDataForTab directly in tests.

This is a reland of commit 243dbcb1fbc30d08f6195a0f2f48f19c8b75a863, which was reverted by commit fa5127d228843b2d0e1b9f6974cd393aa4a89370. The original CL description:

> Include translate information in onProvideAssistContent.
>
> Assistant will use this information to determine whether or not to show a translate prompt when Assistant is opened over Chrome.
>
> This is controlled by the "TranslateAssistContent" Feature and is off by default.
>
> Design doc here: https://docs.google.com/document/d/1xZR09XTTGgY0F00_lFOEX7nUc0oqgSrCs5lZFU9INA0/edit

Bug: 1110943, 1135658, 1136112
Change-Id: I9a769f6670fc7278bcdc08b995965241610034d9
Tbr: isherman@chromium.org
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2459106
Commit-Queue: Josh Simmons <jds@google.com>
Reviewed-by: Michael Thiessen <mthiesse@chromium.org>
Reviewed-by: Scott Little <sclittle@chromium.org>
Cr-Commit-Position: refs/heads/master@{#820411}