Revert of Makes the component installers return a Result instead of a bool. (patchset #1 id:1 of https://codereview.chromium.org/2479633003/ )
Reason for revert:
Breaks official build.

http://build.chromium.org/p/chromium.chrome/builders/Google%20Chrome%20Mac/builds/15483

FAILED: obj/chrome/browser/browser/pepper_flash_component_installer.o
/b/c/cipd/goma/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/chrome/...-inlines-hidden -std=c++11 -stdlib=libc++ -fno-rtti -fno-exceptions -c ../../chrome/browser/component_updater/pepper_flash_component_installer.cc -o obj/chrome/browser/browser/pepper_flash_component_installer.o
../../chrome/browser/component_updater/pepper_flash_component_installer.cc:162:8: error: virtual function 'OnCustomInstall' has a different return type ('bool') than the function it overrides (which has return type 'update_client::CrxInstaller::Result')
  bool OnCustomInstall(const base::DictionaryValue& manifest,
  ~~~~ ^
../../components/component_updater/default_component_installer.h:61:47: note: overridden virtual function is here
  virtual update_client::CrxInstaller::Result OnCustomInstall(
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
1 error generated.

Original issue's description:
> Makes the component installers return a Result instead of a bool.
>
> This allows conveying more error information from the component
> installers to other layers of the component updater.
>
> Before this change, the component install execution path could
> only return one error. We are trying to understand the reasons
> why the component installers fail.
>
> BUG=615669
>
> Committed: https://crrev.com/73769a84d74113a4a10e4152e63d219eb72f2630
> Cr-Commit-Position: refs/heads/master@{#429995}

TBR=waffles@chromium.org,agl@chromium.org,asargent@chromium.org,sdefresne@chromium.org,pastarmovj@google.com,pastarmovj@chromium.org,sorin@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=615669

Review-Url: https://codereview.chromium.org/2483513002
Cr-Commit-Position: refs/heads/master@{#430008}