Rename Sad Tab metric due to collision with UKM keyword
Case-insensitive `event` is a keyword in UKM, and metrics with this name trigger build errors server-side:

```
readable_event.proto.h:165645:22: error: class member cannot be redeclared
 165645 |   [[nodiscard]] bool has_event() const;
        |                      ^
readable_event.proto.h:165646:8: error: class member cannot be redeclared
 165646 |   void clear_event() ;
        |        ^
```

Bug: 512880289
Change-Id: I4e9a2b97da6bfd371b91d36fd7c46b3a61af53fb
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7864030
Reviewed-by: Rohit Rao <rohitrao@chromium.org>
Auto-Submit: Sun Yueru <yrsun@chromium.org>
Reviewed-by: Matt Reichhoff <mreichhoff@chromium.org>
Commit-Queue: Rohit Rao <rohitrao@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1633888}