Revert "Roll Chromite from e852b077f0b6 to af3d4787a860 (10 revisions)"
This reverts commit cd76c5866cc0c504320fcea82c7e8255d843159c.

Reason for revert: Broke Chrome uprevs

With failures like:
ModuleNotFoundError: No module named 'chromite.third_party.pyelftools'

BUG=1213565

Original change's description:
> Roll Chromite from e852b077f0b6 to af3d4787a860 (10 revisions)
>
> https://chromium.googlesource.com/chromiumos/chromite.git/+log/e852b077f0b6..af3d4787a860
>
> 2021-05-25 vapier@chromium.org google.{api,rpc}: move to explicit import
> 2021-05-25 vapier@chromium.org switch to unittest.mock
> 2021-05-24 vapier@chromium.org pyelftools: move to explicit import
> 2021-05-24 vapier@chromium.org lddtree: drop LD_ARGV0 in favor of --argv0
> 2021-05-24 ahassani@chromium.org xbuddy: Handle both LATEST-main and LATEST-master
> 2021-05-24 ahassani@chromium.org minios: Add Mini OS kernel image builder functions
> 2021-05-24 vyshu@google.com chromite: Extract minios paygen
> 2021-05-24 vapier@chromium.org unittests: migrate off deprecated assertDictContainsSubset
> 2021-05-24 vapier@chromium.org requests: fix collections.abc deprecated warnings
> 2021-05-24 vapier@chromium.org httplib2: move to explicit import
>
> If this roll has caused a breakage, revert this CL and stop the roller
> using the controls here:
> https://autoroll.skia.org/r/chromite-chromium-autoroll
> Please CC chrome-os-gardeners@google.com on the revert to ensure that a human
> is aware of the problem.
>
> To report a problem with the AutoRoller itself, please file a bug:
> https://bugs.chromium.org/p/skia/issues/entry?template=Autoroller+Bug
>
> Documentation for the AutoRoller is here:
> https://skia.googlesource.com/buildbot/+doc/master/autoroll/README.md
>
> Cq-Include-Trybots: luci.chrome.try:chromeos-betty-pi-arc-chrome;luci.chromium.try:chromeos-kevin-rel
> Tbr: chrome-os-gardeners@google.com
> Change-Id: I926691eab3e52847c6bf1bce14eab3e4dca851d2
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2916508
> Commit-Queue: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>
> Bot-Commit: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>
> Cr-Commit-Position: refs/heads/master@{#886333}

Change-Id: I9f815b30c5f964b0927c1bf6da20fb232fb561f1
Cq-Include-Trybots: luci.chrome.try:chromeos-betty-pi-arc-chrome;luci.chromium.try:chromeos-kevin-rel
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2919648
Auto-Submit: Ahmed Fakhry <afakhry@chromium.org>
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Reviewed-by: Mike Frysinger <vapier@chromium.org>
Cr-Commit-Position: refs/heads/master@{#886904}