mini-installer test cleaning directories bug
This was failing because `stat.S_ISDIR` requires a mode not an
object, the following stack trace happened:

TypeError: unsupported operand type(s) for &: 'nt.stat_result' and 'int'

BUG=1066235

Change-Id: Iac03eef706f684f4bcccba0d22f8fc7a4aa23730
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2128459
Commit-Queue: Greg Thompson <grt@chromium.org>
Reviewed-by: Greg Thompson <grt@chromium.org>
Cr-Commit-Position: refs/heads/master@{#754856}