[gardener] Change getClientWindows test to TestExpectations
WPT test is failing on Linux:
webdriver/tests/bidi/browser/get_client_windows/get_client_windows.py

The txt expectation is failing because it is expecting the string:
"AttributeError: 'Browser' object has no attribute 'get_client_windows'"
But the error message is actually
"webdriver.bidi.error.UnknownErrorException: unknown error (Method
browser.getClientWindows is not implemented.)"

We fix this by removing the txt file and adding it to TestExpectations.

Change-Id: I7d0709ecdb2f42dd94c049f4d3f06490534215f8
Bug: 377977965
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6006196
Reviewed-by: Haihan Chen <haihan@google.com>
Commit-Queue: Di Zhang <dizhangg@chromium.org>
Auto-Submit: Di Zhang <dizhangg@chromium.org>
Commit-Queue: Haihan Chen <haihan@google.com>
Cr-Commit-Position: refs/heads/main@{#1380667}