[gardener] Revert "Roll DevTools Frontend from fc6c88bbe0e8 to b4d97ce01d46 (4 revisions)"
This reverts commit 912b71e9e4a045a3c83b67af27021e8510fde4f5.
Original CL: https://crrev.com/c/8313892

Reason for revert:
TypeScript compilation failed on linux-full-remote-rel builder.
https://ci.chromium.org/ui/p/chromium/builders/try/linux-full-remote-rel
css_grid_label_helpers.ts(5,25): error TS2307: Cannot find module '../front_end/core/common/ColorUtils.js' or its corresponding type declarations.

Original change's description:
Roll DevTools Frontend from fc6c88bbe0e8 to b4d97ce01d46 (4 revisions)

https://chromium.googlesource.com/devtools/devtools-frontend.git/+log/fc6c88bbe0e8..b4d97ce01d46

2026-08-28 jacktfranklin@chromium.org AIv2: implement getCookieValues tool
2026-08-28 szuend@chromium.org [ts_library] Migrate foundation to split compilation
2026-08-28 szuend@chromium.org [ts_library] Migrate models/ai_assistance to split compilation
2026-08-28 yangguo@chromium.org Use size tokens in consoleInsight and codeBlock

If this roll has caused a breakage, revert this CL and stop the roller
using the controls here:
https://autoroll.skia.org/r/devtools-frontend-chromium
Please CC chrome-devtools-staff+oncall-change@google.com,liviurau@google.com on the revert to ensure that a human
is aware of the problem.

To report a problem with the AutoRoller itself, please file a bug:
https://issues.skia.org/issues/new?component=1389291&template=1850622

Documentation for the AutoRoller is here:
https://skia.googlesource.com/buildbot/+doc/main/autoroll/README.md

TAG=agy
CONV=b990d40a-e8bd-4518-82c5-1146b0a084b2

Bug: None
Change-Id: Ibd88f4b1fce268f5d3a08724f2c1ee296f314df3
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/8319407
Auto-Submit: Minoru Chikamune <chikamune@chromium.org>
Reviewed-by: Hiroki Nakagawa <nhiroki@chromium.org>
Commit-Queue: Minoru Chikamune <chikamune@chromium.org>
Commit-Queue: Hiroki Nakagawa <nhiroki@chromium.org>
Owners-Override: Minoru Chikamune <chikamune@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1688832}