Revert "Rename wrapper_scripts for generated_script tests in MB."
This reverts commit 8700df8a8aef14e8d88dec7668be4b4e16c7c204.

Reason for revert: 

Android builders started failing since this commit:
https://ci.chromium.org/p/chrome/builders/ci/android-builder-perf/217957

Traceback (most recent call last):
  File "/b/s/w/ir/cache/builder/src/tools/mb/mb.py", line 105, in Main
    ret = self.args.func()
  File "/b/s/w/ir/cache/builder/src/tools/mb/mb.py", line 378, in CmdGen
    return self.RunGNGen(vals)
  File "/b/s/w/ir/cache/builder/src/tools/mb/mb.py", line 961, in RunGNGen
    ret = self.GenerateIsolates(vals, isolate_targets, isolate_map, build_dir)
  File "/b/s/w/ir/cache/builder/src/tools/mb/mb.py", line 1075, in GenerateIsolates
    command, extra_files = self.GetIsolateCommand(target, vals)
  File "/b/s/w/ir/cache/builder/src/tools/mb/mb.py", line 1392, in GetIsolateCommand
    'generated_scripts can no longer customize the script path')
AssertionError: generated_scripts can no longer customize the script path


Original change's description:
> Rename wrapper_scripts for generated_script tests in MB.
> 
> A few tests (some Android resource_sizes tests, and one Perfetto
> test), were using generated_script tests that were generating
> wrappers that weren't named 'bin/run_$target_name'.
> 
> We want all generated_script tests to be using consistent names, so
> this CL changes those targets.
> 
> Bug: 816629
> Change-Id: If447fbee6b33637de4c9711e87379128272285af
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2380672
> Commit-Queue: Dirk Pranke <dpranke@google.com>
> Reviewed-by: John Chen <johnchen@chromium.org>
> Reviewed-by: Andrew Grieve <agrieve@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#802694}

TBR=dpranke@google.com,agrieve@chromium.org,johnchen@chromium.org

# Not skipping CQ checks because original CL landed > 1 day ago.

Bug: 816629
Change-Id: I11ec06405105860f01f3b7752df2024615f7badc
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2384069
Reviewed-by: Wenbin Zhang <wenbinzhang@google.com>
Commit-Queue: John Chen <johnchen@chromium.org>
Cr-Commit-Position: refs/heads/master@{#802984}