Revert "[AF] Refactor legal messages to be parsed in CreditCardSaveManager."
This reverts commit ce1b75b20276c736b8910b2e10a186a55dce10f0.

Reason for revert: compile failure:

clang++ [...]test_payments_client.cc -o obj/components/autofill/core/browser/test_support/test_payments_client.o
../../components/autofill/core/browser/payments/test_payments_client.cc:61:27: error: moving a temporary object prevents copy elision [-Werror,-Wpessimizing-move]
                          std::move(TestPaymentsClient::LegalMessage()),
                          ^
../../components/autofill/core/browser/payments/test_payments_client.cc:61:27: note: remove std::move call here
                          std::move(TestPaymentsClient::LegalMessage()),
                          ^~~~~~~~~~                                  ~


Original change's description:
> [AF] Refactor legal messages to be parsed in CreditCardSaveManager.
> 
> The parsing currently occurs in multiple places like in
> AutofillSaveCardInfoBarDelegateMobile, SaveCardBubbleControllerImpl,
> and CWVAutofillController. This changes centralizes the parsing in an
> earlier place to fail earlier.
> 
> BUG=993849
> 
> Change-Id: I27867970bca726d1c2a8efbf6b0e0f9691b44343
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1766089
> Reviewed-by: Fabio Tirelo <ftirelo@chromium.org>
> Reviewed-by: Moe Ahmadi <mahmadi@chromium.org>
> Reviewed-by: Jared Saul <jsaul@google.com>
> Reviewed-by: Richard Coles <torne@chromium.org>
> Reviewed-by: Matthew Jones <mdjones@chromium.org>
> Commit-Queue: Alfonso Garza <alfonsogarza@google.com>
> Cr-Commit-Position: refs/heads/master@{#696455}

TBR=torne@chromium.org,mdjones@chromium.org,mahmadi@chromium.org,jsaul@google.com,ftirelo@chromium.org,alfonsogarza@google.com

Change-Id: I5cb8ea213e8dfc4bc72f2d68fbbfec1988cbd619
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 993849
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1804136
Reviewed-by: Avi Drissman <avi@chromium.org>
Commit-Queue: Avi Drissman <avi@chromium.org>
Cr-Commit-Position: refs/heads/master@{#696464}