Reland "[ios] Disable manifest verification for catalyst builds"
This reverts commit be098ad3686e1ebbbd0f1dad4859024c7eefd600.

Reason for revert: Suspected of causing build failures on  Libfuzzer Upload iOS Catalyst Debug:

[6364/31366] POST PROCESSING //ios/third_party/material_components_ios:material_components_ios_signed_bundle(//build/toolchain/ios:ios_clang_x64)
python3 ../../build/config/apple/codesign.py code-sign-bundle -t=macosx -i= -b=obj/ios/third_party/material_components_ios/MaterialComponents -M=mobileprovisions.filelist -L=obj/ios/third_party/material_components_ios/material_components_ios_signed_bundle.manifest --disable-embedded-mobileprovision MaterialComponents.framework
error: 2 missing files:
  - MaterialComponents
  - Versions/Current
exit=1



Bug: 436908594, 408138713
Original change's description:
> Revert "[ios] Disable manifest verification for catalyst builds"
>
> This reverts commit 189805f2b44d019626c0842c99741b1bd3c5aae7.
>
> Reason for revert: this is no longer needed as the codesign.py script
> has been fixed to work when building for the catalyst environment.
>
> Bug: 436908594, 408138713
> Original change's description:
> > [ios] Disable manifest verification for catalyst builds
> >
> > The configuration of the code generating the bundle for the
> > catalyst builders is incorrect causing the script to complain
> > that some directories are missing from the bundle.
> >
> > Since the fix for the script is needed to fix other bots,
> > disable the verification when building for catalyst.
> >
> > Bug: 436908594, 408138713
> > Change-Id: I3a25ca935c601393388f9f285b6f7e1f3c194595
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6827485
> > Commit-Queue: Sylvain Defresne <sdefresne@chromium.org>
> > Reviewed-by: Olivier Robin <olivierrobin@chromium.org>
> > Commit-Queue: Olivier Robin <olivierrobin@chromium.org>
> > Auto-Submit: Sylvain Defresne <sdefresne@chromium.org>
> > Cr-Commit-Position: refs/heads/main@{#1498232}
>
> Bug: 436908594, 408138713
> Cq-Include-Trybots: luci.chromium.try:ios-catalyst
> Change-Id: I478be21534989e600f4ea59b17a09ce29260a869
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6827267
> Commit-Queue: Sylvain Defresne <sdefresne@chromium.org>
> Reviewed-by: Olivier Robin <olivierrobin@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1498690}

Bug: 436908594, 408138713
Cq-Include-Trybots: luci.chromium.try:ios-catalyst
Change-Id: If5196ba751acc3a1865d2a33f0ef170cb9a2e746
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6828694
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Auto-Submit: Marijn Kruisselbrink <mek@chromium.org>
Owners-Override: Marijn Kruisselbrink <mek@chromium.org>
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Cr-Commit-Position: refs/heads/main@{#1498863}