Revert of Removing TODO for It2Me Confirmation Dialog (patchset #3 id:40001 of https://codereview.chromium.org/2342393003/ )
Reason for revert:
Compile failure

see https://build.chromium.org/p/chromium/builders/Android/builds/62438/

FAILED: libremoting_host_jni.so libremoting_host_jni.so.TOC lib.unstripped/libremoting_host_jni.so
python "/b/c/b/Android/src/build/toolchain/gcc_solink_wrapper.py" --readelf="../../third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-readelf" --nm="../../third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-nm" --strip=../../third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-strip --sofile="./lib.unstripped/libremoting_host_jni.so" --tocfile="./libremoting_host_jni.so.TOC" --output="./libremoting_host_jni.so"  -- ../../third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++ -shared -Wl,--fatal-warnings -fPIC -Wl,-z,noexecstack -Wl,-z,now -Wl,-z,relro -Wl,-z,defs -Wl,--as-needed -fuse-ld=gold -Wl,--icf=all -Wl,--build-id=sha1 -Wl,--no-undefined -Wl,--exclude-libs=libgcc.a -Wl,--exclude-libs=libc++_static.a -Wl,--exclude-libs=libvpx_assembly_arm.a -Wl,--warn-shared-textrel -Wl,-O1 -Wl,--gc-sections -nostdlib -Wl,--warn-shared-textrel --sysroot=../../third_party/android_tools/ndk/platforms/android-16/arch-arm  -Wl,--version-script=/b/c/b/Android/src/build/android/android_no_jni_exports.lst -Wl,-wrap,calloc -Wl,-wrap,free -Wl,-wrap,malloc -Wl,-wrap,memalign -Wl,-wrap,posix_memalign -Wl,-wrap,pvalloc -Wl,-wrap,realloc -Wl,-wrap,valloc -L../../third_party/android_tools/ndk/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a -o "./lib.unstripped/libremoting_host_jni.so" -Wl,-soname="libremoting_host_jni.so" @"./libremoting_host_jni.so.rsp"
obj/remoting/host/it2me/common/it2me_confirmation_dialog.o:it2me_confirmation_dialog.cc:vtable for remoting::It2MeConfirmationDialogFactory: error: undefined reference to 'remoting::It2MeConfirmationDialogFactory::Create()'
collect2: error: ld returned 1 exit status

Original issue's description:
> Removing TODO for It2Me Confirmation Dialog
>
> Now that the It2Me confirmation dialog has been implemented on all platforms
> we currently support, we can remove the TODO/workaround which would auto-
> approve connections for platforms w/o a dialog.  Note that Android has an
> It2Me host implementation but is not currently used so I did not implement
> a dialog there.  I have added a NOTIMPLEMENTED() macro to indicate this if we
> decide to proceed with it.
>
> BUG=645540
>
> Committed: https://crrev.com/a4829361cdafaa4fe5e5b70b4a786289bb66f97c
> Cr-Commit-Position: refs/heads/master@{#419776}

TBR=sergeyu@chromium.org,jamiewalch@chromium.org,joedow@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=645540

Review-Url: https://codereview.chromium.org/2352123002
Cr-Commit-Position: refs/heads/master@{#419791}