bindings: Write to file as text
Python 3 distinguishes strings and bytestrings better.
This functions seems to be used to write strings. encode() them before writing so writing in binary mode works on Python 3.

Traceback (most recent call last):
  File "../../third_party/blink/renderer/bindings/scripts/generate_event_interfaces.py", line 137, in <module>
    sys.exit(main())
  File "../../third_party/blink/renderer/bindings/scripts/generate_event_interfaces.py", line 132, in main
    write_event_interfaces_file(event_idl_files, options.event_interfaces_file,
  File "../../third_party/blink/renderer/bindings/scripts/generate_event_interfaces.py", line 123, in write_event_interfaces_file
    write_file('\n'.join(lines), destination_filename)
  File "C:\Google\chromium\src\third_party\blink\renderer\bindings\scripts\utilities.py", line 344, in write_file
    destination_file.write(new_text)
TypeError: a bytes-like object is required, not 'str'

Bug: 941669
Change-Id: I28e7f81f83a24d300628794d9e2fb991870c7b08
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2124832
Commit-Queue: Yuki Shiino <yukishiino@chromium.org>
Reviewed-by: Yuki Shiino <yukishiino@chromium.org>
Auto-Submit: Raul Tambre <raul@tambre.ee>
Cr-Commit-Position: refs/heads/master@{#755226}