partition_alloc: Fix missing include on Windows.
Fix error:
https://logs.chromium.org/logs/skia/722c5712e125a511/+/steps/ninja/0/stdout

```
platform_thread.h(71,46): error: no type named 'string' in namespace 'std'
platform_thread.h(102,34): error: no type named 'string' in namespace 'std'
```

Bug: 351867706
Change-Id: Ieed39c2a0958ede97d99988a665afee035278991
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6760876
Reviewed-by: Benoit Lize <lizeb@chromium.org>
Commit-Queue: Benoit Lize <lizeb@chromium.org>
Commit-Queue: Arthur Sonzogni <arthursonzogni@chromium.org>
Auto-Submit: Arthur Sonzogni <arthursonzogni@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1487727}