Revert "Fix browser tests compilation error."
This reverts commit ca3fa29b5d0ab4509ded779f2d5390bce6002e74.

Reason for revert: 
Seems that the issue was fixed differently in https://crrev.com/c/2866827 and now this CL causes the issue again.

Original change's description:
> Fix browser tests compilation error.
>
> ../../third_party/googletest/src/googletest/include/gtest/gtest.h:1545:11: error: comparison of integers of different signs: 'const long' and 'const unsigned long' [-Werror,-Wsign-compare]
>
> ...
>
> ../../chrome/browser/chromeos/policy/status_collector/device_status_collector_browsertest.cc:3431:3: note: in instantiation of function template specialization 'testing::internal::EqHelper::Compare<long, unsigned long, nullptr>' requested here
>   EXPECT_EQ(partition.total_space(), kTotalSpace);
>
> Fixed: 1
> Change-Id: Ibe2c1490c6bd540d00d7b6ce247a5540ccaaf9f4
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2874534
> Commit-Queue: Sergey Poromov <poromov@chromium.org>
> Commit-Queue: Aya Elsayed <ayaelattar@chromium.org>
> Auto-Submit: Sergey Poromov <poromov@chromium.org>
> Reviewed-by: Aya Elsayed <ayaelattar@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#879381}

Change-Id: Ibccaea5f66bf49e40ae5453897af2a1cb425703d
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2874557
Auto-Submit: Sergey Poromov <poromov@chromium.org>
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Cr-Commit-Position: refs/heads/master@{#879729}