Revert of Make WebURLLoader capable of retaining received buffers. (patchset #19 id:560001 of https://codereview.chromium.org/1103813002/)
Reason for revert:
It broke Win x64 GN (dbg)
http://build.chromium.org/p/chromium.win/builders/Win%20x64%20GN%20%28dbg%29/builds/2674/steps/compile/logs/stdio

e:\b\build\slave\win_x64_gn__dbg_\build\src\content\public\child\fixed_received_data.cc(34) :error C2220: warning treated as error - no 'object' file generated
e:\b\build\slave\win_x64_gn__dbg_\build\src\content\public\child\fixed_received_data.cc(34) : warning C4267: 'return' : conversion from 'size_t' to 'int', possible loss of data

Original issue's description:
> Make WebURLLoader capable of retaining received buffers.
>
> In order to implement backpressure on resource loading, this CL
> makes WebURLLoader capable of retaining received buffers. In the
> current implementation, ResourceDispatcher takes care of the buffer
> lifetime in OnReceivedData. With this CL, it passes a ReceivedData
> object that contains payload, length and encoded_length. The difference
> is that a ReceivedData object keeps payload valid while it is alive,
> so we can store the buffer if we like (with care, of course).
>
> This CL does not change the behavior, except one: it replaces a possible
> use-after-free in ResourceDispatcher::OnReceivedData when using
> |alternative_data| with |threaded_data_provider| with an incorrect
> , but safe operation.
>
> BUG=480746
>
> Committed: https://crrev.com/65d393906dd7532c51bbb70c9c181eae3b1e1758
> Cr-Commit-Position: refs/heads/master@{#332512}

TBR=jochen@chromium.org,tyoshino@chromium.org,yhirano@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=480746

Review URL: https://codereview.chromium.org/1159113009

Cr-Commit-Position: refs/heads/master@{#332520}