Revert "Add InterestFeedV2 feature flag"
This reverts commit b84a396f2950635980c682ad8398d2a3ef32562d.

Reason for revert: in-flight conflict with d438f8da15cfb9c787759ae3be62f0458844e4e6 leads to compile failure

../../chrome/browser/android/feed/v2/feed_stream_surface.h:27:63: error: only virtual member functions can be marked 'override'
  void InitialStreamState(const feedui::StreamUpdate& update) override;
                                                              ^~~~~~~~
1 error generated.


Original change's description:
> Add InterestFeedV2 feature flag
> 
> If enabled, the v2 feed stream loading task is kicked off when the NTP
> or start surface is created. Not currently user-visible; this is
> happening silently while the existing feed is created and shown.
> 
> The binary size increase is mainly due to generated proto code that was
> added previously but has not been linked until now. We are generating
> the sources with "option optimize_for = LITE_RUNTIME;" which matches the
> existing feed library and provides an acceptable speed/size tradeoff.
> 
> Once the v2 feed component is fully launched, we can begin removing the
> existing feed library. For a recent measurement of the binary size we
> would eliminate by removing the existing feed library, see this CL:
> https://chromium-review.googlesource.com/c/chromium/src/+/1829821.
> 
> Binary-Size: The increase is temporary (see above).
> Bug: 1044139
> Change-Id: Ic596d28e03300ad617f98f0b725cdf5ed1b0b986
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2132648
> Reviewed-by: Dan H <harringtond@chromium.org>
> Commit-Queue: Ian Wells <iwells@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#756004}

TBR=iwells@chromium.org,harringtond@chromium.org

Change-Id: I42d29a3d64b655fef99944573784f8ce923de78d
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 1044139
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2134962
Reviewed-by: Evan Stade <estade@chromium.org>
Commit-Queue: Evan Stade <estade@chromium.org>
Cr-Commit-Position: refs/heads/master@{#756020}