Reland "Roll libc++ from c105b13e377d to 1ce2525ae355 (6 revisions)"
This reverts commit 02ec4d7f766072cda9756f48a812839b0ddbbe9e.

Reason for revert: Fixed here:
https://chromium-review.googlesource.com/c/chromium/src/+/6806280

Original change's description:
> Revert "Roll libc++ from c105b13e377d to 1ce2525ae355 (6 revisions)"
>
> This reverts commit 82255e4a19409a9c41702720e8f4fad34dc0e135.
>
> Reason for revert: Suspected cause of compile failure on arm-builder-rel
>
> Builder:
> https://ci.chromium.org/ui/p/chrome/builders/ci/arm-builder-rel/36926/overview
>
> Error snippet:
> ../../base/libcpp_hardening_test.cc:62:35: error: ignoring return value of function declared with 'nodiscard' attribute [-Werror,-Wunused-result]
>
> Original change's description:
> > Roll libc++ from c105b13e377d to 1ce2525ae355 (6 revisions)
> >
> > https://chromium.googlesource.com/external/github.com/llvm/llvm-project/libcxx.git/+log/c105b13e377d..1ce2525ae355
> >
> > 2025-07-31 varconsteq@gmail.com [libc++][hardening] Add a greppable prefix to assertion messages. (#150560)
> > 2025-07-30 victor.campos@arm.com Revert "[libc++][Clang] Added explanation why is_constructible evaluated to false. Updated the diagnostics checks in libc++ tests. (#144220)"
> > 2025-07-29 de34@live.cn [libc++][format][NFC] Granularize `__fmt_pair_like` (#150583)
> > 2025-07-29 nikolasklauser@berlin.de [libc++] Add [[nodiscard]] to the vector accessor functions (#150615)
> > 2025-07-29 varconsteq@gmail.com [libc++][hardening] Introduce assertion semantics. (#149459)
> > 2025-07-28 aidengrossman@google.com [libcxx] Enable installing new runner binary on existing container
> >
> > If this roll has caused a breakage, revert this CL and stop the roller
> > using the controls here:
> > https://autoroll.skia.org/r/libcxx-chromium
> > Please CC hans@chromium.org,thakis@chromium.org on the revert to ensure that a human
> > is aware of the problem.
> >
> > To file a bug in Chromium: https://bugs.chromium.org/p/chromium/issues/entry
> >
> > To report a problem with the AutoRoller itself, please file a bug:
> > https://issues.skia.org/issues/new?component=1389291&template=1850622
> >
> > Documentation for the AutoRoller is here:
> > https://skia.googlesource.com/buildbot/+doc/main/autoroll/README.md
> >
> > Tbr: hans@chromium.org,thakis@chromium.org
> > Change-Id: I2807d1c71f9c35aa7b3a401a0a7173c29e30745a
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6805821
> > Commit-Queue: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>
> > Bot-Commit: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>
> > Cr-Commit-Position: refs/heads/main@{#1494814}
>
> No-Presubmit: true
> No-Tree-Checks: true
> No-Try: true
> Change-Id: I04404539d415004b906d4d315a64d905e7eca378
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6806890
> Auto-Submit: Matthew Jones <mdjones@chromium.org>
> Owners-Override: Matt Jones <mdjones@google.com>
> Owners-Override: Mark Pearson <mpearson@chromium.org>
> Reviewed-by: Mark Pearson <mpearson@chromium.org>
> Commit-Queue: Matthew Jones <mdjones@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1494897}

Change-Id: I9f6355dab48567c45ee8cf42167b509cfb7ca71a
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6806442
Commit-Queue: Nico Weber <thakis@chromium.org>
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Auto-Submit: Nico Weber <thakis@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1495089}