Fix mac_views_browser compile after r513338
Failing since http://go/macviewsbuilder/builds/27922 with

avatar_button.cc:46:15: error: unused variable 'kGenericAvatarIconSize'

To fix, expose the code in AvatarButton::SetupThemeColorButton() used
for Windows to Mac also. 

The mac_views_browser doesn't yet draw the avatar icon (crbug/565989).
However, the Cocoa browser's profile_chooser_controller.mm uses
kAccountCircleIcon also, and AvatarButton::IsCondensible() has TODO
"all platforms should return true". So we will want this eventually on
Mac as well. Sharing code is good, and this avoids the compile error.

Bug: 565989, 425229
Change-Id: Ib5ed53e5dd0cfb247e0a29271dcde6ade5f43089
Reviewed-on: https://chromium-review.googlesource.com/750421
Reviewed-by: Thomas Anderson <thomasanderson@chromium.org>
Commit-Queue: Trent Apted <tapted@chromium.org>
Cr-Commit-Position: refs/heads/master@{#513420}