Revert of Initialize document m_URL, m_baseURL to blankURL. (patchset #4 id:60001 of https://codereview.chromium.org/2749803003/ )
Reason for revert:
This CL seems to break interactive_ui_tests on multiple bots:

A sample of error log was:
https://build.chromium.org/p/chromium.chromiumos/builders/Linux%20ChromiumOS%20Ozone%20Tests%20%281%29/builds/44135

../../chrome/test/base/extension_js_browser_test.cc:64: Failure
Failed
Failed: RUN_TEST_F("AutomationTreeWalkerTest","Backward")
ReferenceError: DesktopAutomationHandler is not defined
    at AutomationTreeWalkerTest.ChromeVoxNextE2ETest (tree_walker_test.extjs:8556:3)
    at AutomationTreeWalkerTest (tree_walker_test.extjs:8663:24)
    at createTestCase (tree_walker_test.extjs:7607:19)
    at RUN_TEST_F (tree_walker_test.extjs:7721:25)
    at tree_walker_test.extjs:7523:20
    at runTestFunction (tree_walker_test.extjs:7593:37)
    at runTest (tree_walker_test.extjs:7567:18)
    at tree_walker_test.extjs:8851:1
gen/chrome/browser/resources/chromeos/chromevox/cvox2/background/tree_walker_test-gen.cc:69: Failure
Value of: RunJavascriptTestF( true, "AutomationTreeWalkerTest", "Backward")
  Actual: false
Expected: true
[  FAILED  ] AutomationTreeWalkerTest.Backward, where TypeParam =  and GetParam() =  (1196 ms)

Original issue's description:
> Initialize document m_URL & m_baseURL to blankURL.
>
> This patch will ensure that m_URL and m_baseURL are initialized to
> blankURL (about:blank) as is specified in [1]. This patch fixes the
> tests in [2] and [3].
>
> [1] https://dom.spec.whatwg.org/#interface-document
> [2] http://w3c-test.org/dom/nodes/DOMImplementation-createDocument.html
> [3] http://w3c-test.org/dom/nodes/DOMImplementation-createHTMLDocument.html
>
> BUG=563986
>
> Review-Url: https://codereview.chromium.org/2749803003
> Cr-Commit-Position: refs/heads/master@{#457347}
> Committed: https://chromium.googlesource.com/chromium/src/+/9168f165fe92e37664a5e39fef987f0e3ad72a62

TBR=tkent@chromium.org,martin@martinrogalla.com
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=563986

Review-Url: https://codereview.chromium.org/2757573002
Cr-Commit-Position: refs/heads/master@{#457366}