[Telemetry] Suppress red-herring error messages.
These confuse sheriffs in the log because they are harmless and
just mean that the browser closed the connection to the webserver
aburptly.

WPR has the same logic here:
https://github.com/chromium/web-page-replay/blob/master/httpproxy.py

This eliminates this stack:
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 342, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 310, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer

BUG=

Review URL: https://codereview.chromium.org/386963006

Cr-Commit-Position: refs/heads/master@{#290948}
git-svn-id: svn://svn.chromium.org/chrome/trunk/src@290948 0039d316-1c4b-4281-b951-d872f2087c98