Also bundle repackage_native_impl output
As things stand, both repackage_native and repackage_test_jars
bundle org/chromium/base/natives/GEN_JNI.class. This causes issues
downstream, where the one bundled in repackage_native is currently
winning (for not well defined reasons). Winning in this context means
that Java -> C++ JNI calls will be resolved looked up inside
GEN_JNI.class. This is a problem because repackage_native's GEN_JNI
doesn't contain JNI defined by tests, so tests fails with
java.lang.NoSuchMethodError: No static method
org_chromium_net_NativeTestServer_startNativeTestServer

This CL circumvent the issue by also bundling the output of
repackage_native_impl. Its output is in fact exactly the same of
repackage_native, modulo the stripping of GEN_JNI.class. This way
the one bundled in repackage_test_jars will always win.

Rename repackage_native_impl to repackage_native_without_jni
to better reflect its contents.

Bug: b:266917718, 1401015
Change-Id: I7509bab3761ca240ee1c0220fb179a15baee3d6a
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4204647
Reviewed-by: Andrew Grieve <agrieve@chromium.org>
Commit-Queue: Stefano Duo <stefanoduo@google.com>
Cr-Commit-Position: refs/heads/main@{#1099738}