Revert "Renew Storage Access permission grants from user interactions"
This reverts commit e69bb704722489870fea7d16febdc88b2932c51b.

Reason for revert:
Breaks ChromeOS build.
https://ci.chromium.org/ui/p/chromium/builders/ci/chromeos-arm-generic-rel/105996/overview

```
[18630/36215] CXX obj/chrome/browser/storage_access_api/storage_access_api/storage_access_api_service_impl.o
FAILED: obj/chrome/browser/storage_access_api/storage_access_api/storage_access_api_service_impl.o
../../build/cros_cache/chrome-sdk/symlinks/arm-generic+15516.0.0+target_toolchain/bin/armv7a-cros-li...(too long)
../../chrome/browser/storage_access_api/storage_access_api_service_impl.cc:78:39: error: no viable conversion from 'ContentSettingsForOneType *' (aka 'vector<ContentSettingPatternSource> *') to 'absl::optional<content_settings::SessionModel>'
&grants);
^~~~~~~
```

Original change's description:
> Renew Storage Access permission grants from user interactions
>
> This gives ContentSettings the ability to be refreshed, if they were
> initially set with a lifetime & expiration. The Storage Access API
> tab helper uses this ability to refresh a Storage Access API grant
> after user interaction in an embedded context, at most once per day
> per grant.
>
> Bug: 1450356
> Change-Id: Ice7f09bf887b636ee93b75b757f00c108348fc8e
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4627738
> Reviewed-by: Christian Dullweber <dullweber@chromium.org>
> Reviewed-by: Shuran Huang <shuuran@chromium.org>
> Commit-Queue: Chris Fredrickson <cfredric@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1162548}

Bug: 1450356
Change-Id: If714103b15b3761dcf517d2f82391a6bffce2e51
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4646591
Auto-Submit: Min Chen <minch@chromium.org>
Owners-Override: Min Chen <minch@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Cr-Commit-Position: refs/heads/main@{#1162597}