input tests: Rename |EventHandler()| to avoid naming conflicts
GCC is stricter than clang when it comes to class members' names and how
they can change the meaning of a previously existing symbol with the same
name:

    ../../third_party/WebKit/Source/core/input/PointerEventManagerTest.cpp:90:3: error: declaration of ‘blink::EventHandler& blink::PointerEventManagerTest::EventHandler()’ [-fpermissive]
       }
       ^
    In file included from ../../third_party/WebKit/Source/core/input/PointerEventManagerTest.cpp:8:0:
    ../../third_party/WebKit/Source/core/input/EventHandler.h:79:19: error: changes meaning of ‘EventHandler’ from ‘class blink::EventHandler’ [-fpermissive]
     class CORE_EXPORT EventHandler final
                       ^~~~~~~~~~~~

    ../../third_party/WebKit/Source/core/input/TouchEventManagerTest.cpp:21:3: error: declaration of ‘blink::EventHandler& blink::TouchEventManagerTest::EventHandler()’ [-fpermissive]
       }
       ^
    In file included from ../../third_party/WebKit/Source/core/input/TouchEventManagerTest.cpp:9:0:
    ../../third_party/WebKit/Source/core/input/EventHandler.h:79:19: error: changes meaning of ‘EventHandler’ from ‘class blink::EventHandler’ [-fpermissive]
     class CORE_EXPORT EventHandler final
                       ^~~~~~~~~~~~

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=84709 contains a longer
explanation, but essentially having an |EventHandler()| method can change
the meaning of references to |EventHandler| in the code dependending on
where it is declared, which contradicts the C++ standard.

Fix it by renaming the method to |GetEventHandler()|.

Change-Id: I2d54280bb86a2af0bc9920115ba16fdb49ad7186
Reviewed-on: https://chromium-review.googlesource.com/968491
Reviewed-by: David Bokan <bokan@chromium.org>
Commit-Queue: Raphael Kubo da Costa <raphael.kubo.da.costa@intel.com>
Cr-Commit-Position: refs/heads/master@{#544040}