Revert "Use llvm symbolizer for stack script."
This reverts commit b6e038a7a7b07f680eba6d6ec1c32319ae89cd78.

Reason for revert: Broke stack_tool_with_logcat_dump

Traceback (most recent call last):
  File "/b/c/b/WebKit_Android__Nexus4_/src/third_party/android_platform/development/scripts/stack", line 247, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/b/c/b/WebKit_Android__Nexus4_/src/third_party/android_platform/development/scripts/stack", line 238, in main
    arch_defined, symbolizer)
  File "/b/c/b/WebKit_Android__Nexus4_/src/third_party/android_platform/development/scripts/stack_core.py", line 192, in ConvertTrace
    ResolveCrashSymbol(list(useful_log), more_info, llvm_symbolizer)
  File "/b/c/b/WebKit_Android__Nexus4_/src/third_party/android_platform/development/scripts/stack_core.py", line 331, in ResolveCrashSymbol
    if pid != -1 and pid in java_stderr_by_pid:
NameError: global name 'java_stderr_by_pid' is not defined

https://uberchromegw.corp.google.com/i/chromium.webkit/builders/WebKit%20Android%20%28Nexus4%29/builds/72002

Original change's description:
> Use llvm symbolizer for stack script.
> 
> llvm symbolizer is a more efficient symbolizer than addr2line, objdump,
> etc.
> 
> In this cl, I 1)created a wrapper instance to interact with
> llvm symbolizer, 2)made the stack script to use llvm symbolizer instance,
> and then 3)added llvm symbolizer into isolated inputs.
> 
> Bug: 774267
> Change-Id: I971fb808b97f3a569eb9615f99efa41e3a56f3cb
> Reviewed-on: https://chromium-review.googlesource.com/789376
> Reviewed-by: agrieve <agrieve@chromium.org>
> Reviewed-by: Dirk Pranke <dpranke@chromium.org>
> Commit-Queue: Zhiling Huang <hzl@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#521820}

TBR=dpranke@chromium.org,agrieve@chromium.org,hzl@chromium.org,bpastene@chromium.org,jbudorick@chromium.org

Change-Id: I166549a6fbfcd04529096cbe65aa5befb767b4ce
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 774267
Reviewed-on: https://chromium-review.googlesource.com/810010
Reviewed-by: Ojan Vafai <ojan@chromium.org>
Commit-Queue: Ojan Vafai <ojan@chromium.org>
Cr-Commit-Position: refs/heads/master@{#521905}