GCC: do not convert DictionaryValue to Value returning RunAttributionSimulationOrExit
Fix error compiling with GCC, because now copy constructor is not
available anymore.
    ../../content/test/attribution_simulator_impl.cc:192:10: error: use of deleted function ‘base::Value::Value(const base::Value&)’
      192 |   return output;
          |          ^~~~~~

Bug: 819294
Change-Id: I671a0114643a790ff2c5660fd9ea4d5e67a8c2bb
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3452783
Reviewed-by: Nasko Oskov <nasko@chromium.org>
Commit-Queue: José Dapena Paz <jdapena@igalia.com>
Cr-Commit-Position: refs/heads/main@{#969605}