Revert of Make --headless flag work on Mac (patchset #2 id:20001 of https://codereview.chromium.org/2720863003/ )
Reason for revert:
This CL is braking Mac buildbot, when trying to build headless_example and headless_shell with component build set to false. With the following error:
AILED: headless_example headless_example.unstripped
export DEVELOPER_DIR=/b/c/b/mac/src/build/mac_files/Xcode.app;  TOOL_VERSION=1487140455 ../../build/toolchain/mac/linker_driver.py ../../third_party/llvm-build/Release+Asserts/bin/clang++  -stdlib=libc++ -arch x86_64 -Wcrl,unstripped,/b/c/b/mac/src/out/Release -Werror -Wl,-dead_strip -isysroot /b/c/b/mac/src/build/mac_files/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.9 -Wl,-ObjC -Wl,-pie -Wcrl,strip,-x,-S -L../../build/mac_files/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/lib -o "./headless_example" -Wl,-filelist,"./headless_example.rsp"  -lbsm -framework Cocoa -framework Foundation -framework IOKit -framework Security -framework SystemConfiguration -framework ApplicationServices -framework AppKit -framework CoreFoundation -framework CoreGraphics -framework CoreText -framework CFNetwork -framework CoreServices -lresolv -framework IOBluetooth -framework Accelerate -framework AudioUnit -framework Carbon -framework CoreVideo -framework IOSurface -framework OpenGL -framework Quartz -framework QuartzCore -framework AVFoundation -framework CoreMedia -framework AudioToolbox -framework CoreAudio -framework VideoToolbox -framework DiskArbitration -framework CoreMIDI -lsandbox -framework GameController -framework CoreWLAN -lcups
Undefined symbols for architecture x86_64:
  "content::PpapiPluginMain(content::MainFunctionParams const&)", referenced from:
      content::RunNamedProcessTypeMain(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, content::MainFunctionParams const&, content::ContentMainDelegate*)::kMainFunctions in content_main_runner.o
  "content::PpapiBrokerMain(content::MainFunctionParams const&)", referenced from:
      content::RunNamedProcessTypeMain(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, content::MainFunctionParams const&, content::ContentMainDelegate*)::kMainFunctions in content_main_runner.o
ld: symbol(s) not found for architecture x86_64

Original issue's description:
> Make --headless flag work on Mac
>
>
> BUG=687407
>
> Review-Url: https://codereview.chromium.org/2720863003
> Cr-Commit-Position: refs/heads/master@{#453778}
> Committed: https://chromium.googlesource.com/chromium/src/+/664dcbac5d9fac9223b5e273e30ee094d91489b3

TBR=skyostil@chromium.org,sky@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=687407

Review-Url: https://codereview.chromium.org/2727503002
Cr-Commit-Position: refs/heads/master@{#453792}