Revert "[PriceTracking] Handle product image loading failure in side panel"
This reverts commit 8185641ef7780c6043ef697556c5454c4c8ffe23.

Reason for revert: Step "browser_tests" failing on builder "chromium/ci/Win7 Tests (1)"

List of failed builders:

Builder: Win7 Tests (1)
https://ci.chromium.org/p/chromium/builders/ci/Win7%20Tests%20%281%29
First failing build:
https://ci.chromium.org/p/chromium/builders/ci/Win7%20Tests%20%281%29/b8799730652553198785

[9184:6732:1020/141805.299:ERROR:web_ui_browser_test.cc(634)] JS ERROR: '[9184:6732:1020/141805.276:ERROR:CONSOLE(57)] "Mocha test failed: SidePanelShoppingListTest ObservesTrackedProductInfoUpdate
AssertionError: expected true to be false
    at assertFalse (chrome://webui-test/chai_assert.js:24:15)
    at checkProductElementRender (chrome://webui-test/side_panel/bookmarks/commerce/shopping_list_test.js:60:13)
    at Context.<anonymous> (chrome://webui-test/side_panel/bookmarks/commerce/shopping_list_test.js:263:9)
", source: chrome://webui-test/mocha_adapter.js (57)
'

Original change's description:
> [PriceTracking] Handle product image loading failure in side panel
>
> This CL adds logic to fallback to the layout with favicon when the
> product image loading fails. This CL also adds a histogram to monitor
> the success/failure rate of image loading.
>
> Bug: 1376593
> Change-Id: Ieea3bf0f08303e8c08cf4bb0d448883e3e6cb0a7
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3967483
> Auto-Submit: Yue Zhang <yuezhanggg@chromium.org>
> Commit-Queue: Yue Zhang <yuezhanggg@chromium.org>
> Commit-Queue: John Lee <johntlee@chromium.org>
> Reviewed-by: John Lee <johntlee@chromium.org>
> Reviewed-by: Wei-Yin Chen <wychen@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1061783}

Change-Id: I1fd757d292e3f46dc65506ceb7c0c57ee925a25c
Fixed: 1377189
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3970359
Owners-Override: Giovanni Ortuno Urquidi <ortuno@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Auto-Submit: Giovanni Ortuno Urquidi <ortuno@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1062006}