Revert "[sheriff] Disable AutofillAssistantOverlayIntegrationTest#testShowCastOnIFrameElementInScrollIFrame"
This reverts commit a8ef99dc709787fe0cae591f328755f6825c804f.

Reason for revert: Build is failing due to missing import.

../../chrome/android/features/autofill_assistant/javatests/src/org/chromium/chrome/browser/autofill_assistant/AutofillAssistantOverlayIntegrationTest.java:308: error: could not resolve DisabledTest
    @DisabledTest(message = "https://crbug.com/1182103")

Original change's description:
> [sheriff] Disable AutofillAssistantOverlayIntegrationTest#testShowCastOnIFrameElementInScrollIFrame
>
> TBR=engedy@chromium.org
> NOTRY=true
>
> Bug: 1182103
> Change-Id: I82286d9afc23f0c6fafad55808d004f9aea224e3
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2773158
> Reviewed-by: Xida Chen <xidachen@chromium.org>
> Reviewed-by: Balazs Engedy <engedy@chromium.org>
> Commit-Queue: Xida Chen <xidachen@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#864221}

Bug: 1182103
Change-Id: I412d811531caa275e8cbfba71d25b88a90196a14
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2773182
Auto-Submit: Sky Malice <skym@chromium.org>
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Cr-Commit-Position: refs/heads/master@{#864234}