[Fuzzing] Fix java dependencies in android fuzzers
The added dependencies solve errors at runtime similar to `JAVA
EXCEPTION: Caused by: java.lang.ClassNotFoundException`

Fixing fuzzer audio_decoder_fuzzer, content_security_policy_util_fuzzer

R=titouan@chromium.org

Bug: 510921438
Change-Id: Ib4af50747ac76c340052f8d97e3da00b4c133ca5
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7866188
Commit-Queue: Titouan Rigoudy <titouan@chromium.org>
Reviewed-by: Daniel Cheng <dcheng@chromium.org>
Reviewed-by: Titouan Rigoudy <titouan@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1640018}