Revert of Switch telemetry over to use typ to run the unit tests. (patchset #9 id:170001 of https://codereview.chromium.org/659293003/)
Reason for revert:
This CL causes telemetry_perf_unittests failure:
http://build.chromium.org/p/chromium.linux/buildstatus?builder=Linux%20Tests&number=15802
http://build.chromium.org/p/chromium.mac/buildstatus?builder=Mac%2010.6%20Tests%20%28dbg%29%281%29&number=54625

Its stack trace was:
Traceback (most recent call last):
  <module> at tools/telemetry/telemetry/unittest/run_tests.py:179
    RunTestsCommand.main()
  main at tools/telemetry/telemetry/unittest/run_tests.py:85
    return obj.Run(options)
  Run at tools/telemetry/telemetry/unittest/run_tests.py:126
    ret, _, _ = runner.run()
  run at third_party/typ/typ/runner.py:187
    upload_ret = self._upload(full_results)
  _upload at third_party/typ/typ/runner.py:599
    full_results)
  make_upload_request at third_party/typ/typ/json_results.py:113
    content_type, data = _encode_multipart_form_data(attrs, full_results)
  _encode_multipart_form_data at third_party/typ/typ/json_results.py:183
    body = CRLF.join(lines)
TypeError: sequence item 3: expected string, NoneType found

Original issue's description:
> Switch telemetry over to use typ to run the unit tests.
>
> Using typ allows us to run the tests in parallel and share
> the logic for parsing the results and uploading them to the
> flakiness dashboard with other python test steps.
>
> R=dtu@chromium.org, tonyg@chromium.org, nduca@chromium.org
> BUG=402172, 388256
>
> Committed: https://crrev.com/3e7c2a6ee80e05fc6b8090bee850c40b8a2a3810
> Cr-Commit-Position: refs/heads/master@{#302570}

TBR=dtu@chromium.org,tonyg@chromium.org,nduca@chromium.org,achuith@chromium.org,dpranke@chromium.org
NOTREECHECKS=true
NOTRY=true
BUG=402172, 388256

Review URL: https://codereview.chromium.org/700703003

Cr-Commit-Position: refs/heads/master@{#302575}