Revert "[Discounts] Add data plumbing for Quest 1.0"
This reverts commit 7fc8ba191243e0e11e939218c560b5769112eb2a.

Reason for revert: Local build fails on Windows:

Traceback (most recent call last):
  File "../../tools/typescript/ts_library.py", line 273, in <module>
    main(sys.argv[1:])
  File "../../tools/typescript/ts_library.py", line 235, in main
    node.RunNode([
  File "C:\src\trunk\src\out\Debug\..\..\third_party\node\node.py", line 34, in RunNode
    raise RuntimeError('Command \'%s\' failed\n%s' % (' '.join(cmd), err))
RuntimeError: Command 'C:\src\trunk\src\out\Debug\..\..\third_party\node\win\node.exe C:\src\trunk\src\out\Debug\..\..\third_party\node\node_modules\typescript\bin\tsc --project gen/chrome/browser/resources/new_tab_page\tsconfig_build_ts.json' failed
error TS6053: File 'C:/src/trunk/src/out/Debug/gen/chrome/browser/resources/new_tab_page/preprocessed/discount.mojom-webui.ts' not found.
  The file is in the program because:
    Part of 'files' list in tsconfig.json

  gen/chrome/browser/resources/new_tab_page/tsconfig_build_ts.json:194:5
    194     "preprocessed\\discount.mojom-webui.ts",
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    File is matched by 'files' list specified here.

gen/chrome/browser/resources/new_tab_page/preprocessed/history_clusters.mojom-webui.ts:17:8 - error TS2792: Cannot find module './discount.mojom-webui.js'. Did you mean to set the 'moduleResolution' option to 'nodenext', or to add aliases to the 'paths' option?

17 } from './discount.mojom-webui.js';
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 2 errors in the same file, starting at: gen/chrome/browser/resources/new_tab_page/preprocessed/history_clusters.mojom-webui.ts:17

Original change's description:
> [Discounts] Add data plumbing for Quest 1.0
>
> * Add DiscountProcessor to fetch discount data from ShoppingService
>   and provide to WebUI.
> * Define mojo interface for WebUI to fetch data from browser.
> * Show discount chip in Quest module with the discount data.
>
> Bug: b/295064763
> Change-Id: Ibd5919f7883848797b0b816afa6cd89bd8972caa
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4808933
> Reviewed-by: Roman Arora <romanarora@chromium.org>
> Reviewed-by: Alex Gough <ajgo@chromium.org>
> Commit-Queue: Yue Zhang <yuezhanggg@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1188598}

Bug: b/295064763
Change-Id: I77e8b483166fc8edcaa2f1922ff2f2aa111fe67e
Validate-Test-Flakiness: skip
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4815533
Owners-Override: Peter Kasting <pkasting@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Peter Kasting <pkasting@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1188836}