Reland "Reland "[dPWA]: Skeleton for OS Integration Sub Managers""
This reverts commit a97b6358484096f99ab0780eccdeb77889e90dac.

Reason for revert: Compilation error on chrome_sync_client.cc because
web app code is not supposed to be built on Android.

Original change's description:
> Revert "Reland "[dPWA]: Skeleton for OS Integration Sub Managers""
>
> This reverts commit 0bbbbb41dbee3eb312820b5e0c991a0379d45dc5.
>
> Reason for revert: FindIt has identified this cl breaks the build. Sample failed build: https://ci.chromium.org/b/8806644749499419313
>
> Original change's description:
> > Reland "[dPWA]: Skeleton for OS Integration Sub Managers"
> >
> > This reverts commit bb5d34e03fe26386b722bae1b5b4fee6b225b498.
> >
> > This CL relands the original OS Integration sub-manager code by
> > removing the erroneous dependency. The build failure is not reproducible
> > locally though, so not sure if using the proto field for the
> > os_integration_state would need to be modified.
> >
> > Original change's description:
> > > Revert "[dPWA]: Skeleton for OS Integration Sub Managers"
> > >
> > > This reverts commit fd112e842a1db0caa219d2921de6357d78ee133a.
> > >
> > > Reason for revert: Tree is closed because of compilation error: https://ci.chromium.org/ui/p/chromium/builders/ci/android-x86-rel/9101/overview
> > >
> > > Original change's description:
> > > > [dPWA]: Skeleton for OS Integration Sub Managers
> > > >
> > > > This CL introduces the prototype for the OS Integration sub-manager
> > > > design and sets up the initial plumbing.
> > > >
> > > > DD: go/osintegrationsubmngrdd
> > > >
> > > > Bug: 1295044
> > > > Change-Id: I06de9b04f8939095b2e97fa82700999519f26290
> > > > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3758034
> > > > Commit-Queue: Dibyajyoti Pal <dibyapal@chromium.org>
> > > > Reviewed-by: Daniel Murphy <dmurph@chromium.org>
> > > > Reviewed-by: Phillis Tang <phillis@chromium.org>
> > > > Cr-Commit-Position: refs/heads/main@{#1031493}
> > >
> > > Bug: 1295044
> > > Change-Id: Ib59cf62089ec40ef3b9d5291251831ff228df464
> > > No-Presubmit: true
> > > No-Tree-Checks: true
> > > No-Try: true
> > > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3810939
> > > Reviewed-by: Stephen McGruer <smcgruer@chromium.org>
> > > Owners-Override: Liviu Tinta <liviutinta@chromium.org>
> > > Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
> > > Commit-Queue: Liviu Tinta <liviutinta@chromium.org>
> > > Cr-Commit-Position: refs/heads/main@{#1031502}
> >
> > Bug: 1295044
> > Change-Id: I4a03510e5a8170d4bf47254165cda925ae500763
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3810234
> > Commit-Queue: Dibyajyoti Pal <dibyapal@chromium.org>
> > Auto-Submit: Dibyajyoti Pal <dibyapal@chromium.org>
> > Reviewed-by: Daniel Murphy <dmurph@chromium.org>
> > Cr-Commit-Position: refs/heads/main@{#1032032}
>
> Bug: 1295044
> Change-Id: If742541bde38d3205ffe0cb12ea6f644b3f2fd05
> No-Presubmit: true
> No-Tree-Checks: true
> No-Try: true
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3813935
> Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
> Commit-Queue: Mei Liang <meiliang@chromium.org>
> Owners-Override: Mei Liang <meiliang@chromium.org>
> Auto-Submit: Mei Liang <meiliang@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1032051}

Bug: 1295044
Change-Id: Ibb2b9cfe4b253f857337f5426e4c68e9a7d07492
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3814232
Reviewed-by: Scott Violet <sky@chromium.org>
Commit-Queue: Dibyajyoti Pal <dibyapal@chromium.org>
Reviewed-by: Daniel Murphy <dmurph@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1032627}