Fix redecleration of local variable url in ime_man_del_impl
The quick fix is just to rename this variable.

This is causing a build failure since wshadow - https://chromium-review.googlesource.com/c/chromium/src/+/3935480

Fix for build with gn arg is_chrome_branded = true
```
keithlee@keithlee:~/chromium/src$ autoninja -C out/Default chrome
../../chrome/browser/ash/input_method/component_extension_ime_manager_delegate_impl.cc:327:10: error: declaration shadows a local variable [-Werror,-Wshadow]
    GURL url = extensions::Extension::GetResourceURL(
         ^
../../chrome/browser/ash/input_method/component_extension_ime_manager_delegate_impl.cc8: note: previous declaration is here
  GURL url = extensions::Extension::GetResourceURL(
       ^
1 error generated.
ninja: build stopped: subcommand failed.

```

R=essential-inputs-team@google.com
BUG=b:252589422

Change-Id: I7d628bfe61d4789f8776ee43ad766d69f2b9b7fc
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3941148
Commit-Queue: Darren Shen <shend@chromium.org>
Auto-Submit: Keith Lee <keithlee@chromium.org>
Reviewed-by: Darren Shen <shend@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1056789}