Revert "[UPMLocalPwd] Add the second fragment"
This reverts commit 1c80ecc640b4a65905a9117e5457b09e0fce2196.

Reason for revert: breaks android-12l-x64-dbg-tests
https://ci.chromium.org/ui/p/chromium/builders/ci/android-12l-x64-dbg-tests/5353/blamelist

Trace:
java.lang.IllegalArgumentException: No view found for id 0x7f010368 (org.chromium.chrome.tests:id/fragment_container_view) for fragment PasswordMigrationWarningOptionsFragment{d5d74e5} (609c8982-62d7-4880-8226-b617939fa281 id=0x7f010368)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:547)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1943)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1845)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1782)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:565)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)


Original change's description:
> [UPMLocalPwd] Add the second fragment
>
> The second fragment contains radio buttons for more options:
> password export or syncing/signing in.
> At the moment the first offered option is always looking like the
> user is not signed in.
>
> Bug: 1439761
> Change-Id: I890f8686bcff931cb966dbce93b7e35463e1dc1d
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4527856
> Reviewed-by: Ioana Pandele <ioanap@chromium.org>
> Commit-Queue: Ivana Žužić <izuzic@google.com>
> Cr-Commit-Position: refs/heads/main@{#1147148}

Bug: 1439761
Change-Id: I306ce3408938e905563ebe04a7e7da65199dbe70
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4552259
Auto-Submit: Friedrich Horschig <fhorschig@chromium.org>
Commit-Queue: Friedrich Horschig <fhorschig@chromium.org>
Owners-Override: Friedrich Horschig <fhorschig@chromium.org>
Reviewed-by: Ivana Žužić <izuzic@google.com>
Cr-Commit-Position: refs/heads/main@{#1147203}