Gets gn check to execute cleanly in mojo/common
This one is trickier. I'm changing mojo/common:common_base to be a
source_set. Here's why. When I add the necessary deps, in particular
    "//third_party/mojo/src/mojo/public/cpp/bindings:bindings",
then I get link errors for the environment, eg
gen/third_party/mojo/src/mojo/public/interfaces/bindings/interface_control_messages.mojom.cc:719: error: undefined reference to 'mojo::Environment::GetDefaultLogger()'
These symbols are in //mojo/environment. If I add //mojo/environment
to the list of deps for common_base I end up with a cycle as
environment depends upon common_base. By changing to source_set
common_base isn't linked and everyone is happy.

As a result of this I had to consolidate //mojo/environment into a single source set.

BUG=none
TEST=none
R=ben@chromium.org

Review URL: https://codereview.chromium.org/1256593003

Cr-Commit-Position: refs/heads/master@{#340527}