Reland "tools/metrics/histograms/extract_histograms.py: Python 3 support"
This is a reland of 465e61733f722cb7ff716d52d90770de36e2d04e
gLinux has the html module from python-future, but it's missing unescape().
Switched the import order to import the html module only if importing HTMLParser fails.

Original change's description:
> tools/metrics/histograms/extract_histograms.py: Python 3 support
>
> Example error:
> Traceback (most recent call last):
>   File "../../tools/metrics/histograms/generate_expired_histograms_array.py", line 14, in <module>
>     import extract_histograms
>   File "C:\Google\chromium\src\tools\metrics\histograms\extract_histograms.py", line 60, in <module>
>     import HTMLParser
> ModuleNotFoundError: No module named 'HTMLParser'
>
> Also fixed deprecation warnings:
> C:\Google\chromium\src\tools\metrics\histograms\extract_histograms.py:150: DeprecationWarning: The unescape method is deprecated and will be removed in 3.5, use html.unescape() instead.
>   return HTMLParser().unescape(line)
> ...C:\Google\chromium\src\tools\metrics\histograms\extract_histograms_test.py:481: DeprecationWarning: Please use assertEqual instead.
>   self.assertEquals('This is a summary with & and " and \'',
>
> The changes are backwards compatible.
>
> Bug: 941669
> Change-Id: Ieb22e72b37ec26886f3ca1341e487be4f0ba3ab1
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1830657
> Auto-Submit: Raul Tambre <raul@tambre.ee>
> Commit-Queue: Alexei Svitkine <asvitkine@chromium.org>
> Reviewed-by: Alexei Svitkine <asvitkine@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#701265}

Bug: 941669
Change-Id: Ib42aa6819103fde6a388765867890589ea4ced82
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1834001
Commit-Queue: Raul Tambre <raul@tambre.ee>
Auto-Submit: Raul Tambre <raul@tambre.ee>
Reviewed-by: Dirk Pranke <dpranke@chromium.org>
Cr-Commit-Position: refs/heads/master@{#704209}