Revert "Add first-party notification styling in MD notification."
This reverts commit 01f38b46d3446cc7ae3f482d59dbc1841f625479.

Reason for revert: Sorry, this broke compilation on 3 bots:
- https://build.chromium.org/p/chromium.android/builders/Android%20x86%20Builder%20%28dbg%29
- https://build.chromium.org/p/chromium.android/builders/Android%20x64%20Builder%20%28dbg%29
- https://build.chromium.org/p/chromium.android/builders/Android%20MIPS%20Builder%20%28dbg%29

With the following linker error:

obj/ui/message_center/message_center/notification.o: In function `message_center::Notification::CreateSystemNotification(...)':
../../ui/message_center/notification.cc:182: undefined reference to `gfx::kNoneIcon'
obj/ui/message_center/message_center/notification.o: In function `message_center::Notification::CreateSystemNotification(...)':
../../ui/message_center/notification.cc:232: undefined reference to `gfx::CreateVectorIcon(gfx::VectorIcon const&, unsigned int)'


Original change's description:
> Add first-party notification styling in MD notification.
> 
> In new-style notification, first-party notification should have
> different styling compared to general web notifications.
> To do this, all system notifications should be created by
> new CreateSystemNotification. (Previously, it was not a requirement.)
> 
> By using the function,
> * the display source defaults to string "ChromeOS system".
> * the notification has single accent color based on
>   SystemNotificationWarningLevel.
> * gfx::VectorIcon will be passed as small_image instead of gfx::Image
>   to perform icon coloring on CreateSystemNotification side.
> 
> TEST=out/Debug/message_center_unittests
> BUG=738779,726241,740807,740813
> 
> Change-Id: I9e85b3f1de33b6499297f060b5305d0b02157eef
> Reviewed-on: https://chromium-review.googlesource.com/566765
> Reviewed-by: James Cook <jamescook@chromium.org>
> Reviewed-by: Yoshiki Iguchi <yoshiki@chromium.org>
> Reviewed-by: Peter Beverloo <peter@chromium.org>
> Commit-Queue: Tetsui Ohkubo <tetsui@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#491592}

TBR=jamescook@chromium.org,yoshiki@chromium.org,peter@chromium.org,fukino@chromium.org,tetsui@chromium.org

Change-Id: I10fe30dbdad6012fbafe32c17a439065f4d816d3
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 738779, 726241, 740807, 740813
Reviewed-on: https://chromium-review.googlesource.com/600067
Reviewed-by: John Mellor <johnme@chromium.org>
Commit-Queue: John Mellor <johnme@chromium.org>
Cr-Commit-Position: refs/heads/master@{#491696}