Revert "[FedCM] Position pop-up window over button mode modal dialog"
This reverts commit 3819078936a6570821415bf5705556dec3f61191.

Reason for revert: Failing build:
[435/3946] CXX obj/chrome/test/unit_tests/fedcm_account_selection_view_desktop_unittest.obj
../../third_party/llvm-build/Release+Asserts/bin/clang-cl.exe /c ../../chrome/browser/ui/views/webid...(too long)
../../chrome/browser/ui/views/webid/fedcm_account_selection_view_desktop_unittest.cc(2502,35): error: too many braces around scalar initializer [-Werror,-Wmany-braces-around-scalar-init]
 2502 |       CreateIdentityProviderData({{kAccountId1, LoginState::kSignUp}});

Original change's description:
> [FedCM] Position pop-up window over button mode modal dialog
>
> To mitigate user confusion from seeing multiple new UI surfaces at once,
> we position pop-up windows for button mode over the loading dialog to
> direct user attention to the pop-up window. Note that we only apply this
> change to the loading dialog and not for the use other account flow, so
> that we can gather some data on the difference this change makes.
>
> Demo
> https://issues.chromium.org/action/issues/357920782/attachments/59228623?download=true
>
> Bug: 357920782
> Change-Id: I2ca41fa86b02b99949fbacebc99cf6ef9d816d0b
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5840454
> Reviewed-by: Yi Gu <yigu@chromium.org>
> Commit-Queue: Zachary Tan <tanzachary@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1353052}

Bug: 357920782
Change-Id: Ib8ac48bf09430b04b05c303541d26ffa95c7f88e
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5847380
Owners-Override: Ahmed Moussa <ahmedmoussa@google.com>
Commit-Queue: Ahmed Moussa <ahmedmoussa@google.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Cr-Commit-Position: refs/heads/main@{#1353067}