IWYU: missing PlatformKeyboardHook include in ozone_platform.cc
libstdc++ implementation of std::unique_ptr requires full declaration
of the contained type for converting from nullptr. Add the required
include in OzonePlatform for PlatformKeyboardHook.

This fixes this build error with GCC and libstdc++:
    /usr/include/c++/12/bits/unique_ptr.h:93:23: error: invalid application of ‘sizeof’ to incomplete type ‘ui::PlatformKeyboardHook’

Bug: 957519
Change-Id: I20429925dd00108cf684548b0260ebb053a8ada2
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4239869
Reviewed-by: Robert Kroeger <rjkroege@chromium.org>
Commit-Queue: José Dapena Paz <jdapena@igalia.com>
Cr-Commit-Position: refs/heads/main@{#1105184}