Revert 286199 "Implement chrome.serial.getDevices() on top of th..."
Causes compiles failures on the builder.
http://build.chromium.org/p/chromium/builders/Win/builds/22934

[1464/26469 | 38.034] CC obj\third_party\opus\src\silk\opus.debug.obj
FAILED: ninja -t msvc -e environment.x86 -- C:\b\build\goma/gomacc "C:\b\depot_tools\win_toolchain\vs2013_files\VC\bin\amd64_x86\cl.exe" /nologo /showIncludes /FC @obj\device\serial\device_serial_test_util.test_serial_io_handler.obj.rsp /c ..\..\device\serial\test_serial_io_handler.cc /Foobj\device\serial\device_serial_test_util.test_serial_io_handler.obj /Fdobj\device\serial\device_serial_test_util.cc.pdb 
c:\b\build\slave\win\build\src\device\serial\test_serial_io_handler.h(11) : fatalerror C1083: Cannot open include file: 'device/serial/serial.mojom.h': No such file or directory
ninja: build stopped: subcommand failed.


> Implement chrome.serial.getDevices() on top of the Mojo serial service.
> 
> This does not change Chrome to use the new implementation.
> 
> BUG=389016
> 
> Committed: https://src.chromium.org/viewvc/chrome?view=rev&revision=286122
> 
> Review URL: https://codereview.chromium.org/391413005

TBR=sammc@chromium.org

Review URL: https://codereview.chromium.org/423163002

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@286211 0039d316-1c4b-4281-b951-d872f2087c98