Revert of Make popup notification active on being clicked (patchset #2 id:60001 of https://codereview.chromium.org/2711313003/ )
Reason for revert:
This has broken the CQ compilation: https://build.chromium.org/p/chromium.chromiumos/builders/Linux%20ChromiumOS%20Builder%20%28dbg%29/builds/84017

Specifically:
ui/arc/notification/arc_custom_notification_view.cc:508: error: undefined reference to 'message_center::ToastContentsView::kViewClassName'
../../ui/arc/notification/arc_custom_notification_view.cc:510: error: undefined reference to 'message_center::ToastContentsView::ActivateToast()

Original issue's description:
> Make popup notification active on being clicked
>
> This notification adds the code to make a notification activatable and active. Currently this code is called when user clicks a popup notification (aka. toast), and fixes the issue that an EditText on toast doesn't work.
>
> BUG=b/35302601
>
> Review-Url: https://codereview.chromium.org/2711313003
> Cr-Commit-Position: refs/heads/master@{#453944}
> Committed: https://chromium.googlesource.com/chromium/src/+/54d43255d0c2a680e0ff933e675bc0b0a445809b

TBR=dewittj@chromium.org,oshima@chromium.org,yoshiki@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=b/35302601

Review-Url: https://codereview.chromium.org/2723153002
Cr-Commit-Position: refs/heads/master@{#453947}