Normalize expectations path separators to /
Chromium prefers / as a path separator whenever possible, in BUILD.gn
files and most build and test commands. Luckily Windows handles these
/ separators fine (file open works, path parameters to most commands
works), however Python prefers to generate paths with \ separators. This
discrepancy causes problems when doing string comparisons. In this case
the generation of \ path separators on Windows caused multiple presubmit
failures, which this change prevents.

Typical errors were:

       return self._expectation_content[filepath]
    KeyError: '\\tmp\\foo'

because the dictionary was expecting a '/tmp/foo' key.

Bug: 1309977
Change-Id: I3272d2c685ca7d17a91458330b653d8cda679343
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3590839
Reviewed-by: Brian Sheedy <bsheedy@chromium.org>
Commit-Queue: Bruce Dawson <brucedawson@chromium.org>
Cr-Commit-Position: refs/heads/main@{#993434}