Make module.Field hashable.
For Python3 compatibility.

Converting [module.StructField] into set requires StructField to be
hashable, but module.StructField has __eq__ defined only not __hash__.

$ python3 ./mojo/public/tools/bindings/mojom_bindings_generator.py generate $(pwd)/mojo/public/mojom/base/time.mojom --bytecode_path . -d $(pwd)
Traceback (most recent call last):
<stacktrace partially trimmed>
  File "/ssd2/chromium/src/mojo/public/tools/bindings/generators/mojom_cpp_generator.py", line 961, in <genexpr>
    for param_count in param_counts)
  File "/ssd2/chromium/src/mojo/public/tools/bindings/generators/mojom_cpp_generator.py", line 205, in __init__
    self._params = set(params)
TypeError: unhashable type: 'StructField'

Bug: 941669
Change-Id: I1ca8f67d86754cbad668a47a6f0ddd513e5ce896
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2277687
Commit-Queue: Qijiang Fan <fqj@chromium.org>
Auto-Submit: Qijiang Fan <fqj@chromium.org>
Reviewed-by: Ken Rockot <rockot@google.com>
Cr-Commit-Position: refs/heads/master@{#785294}