Revert of [Smart Lock] Add avatar picture to account chooser infobar. (patchset #4 id:200001 of https://codereview.chromium.org/1016393002/)
Reason for revert:
This patch causes an ARM build break.

[630/1044] ACTION Stripping libraries for cc_blink_unittests_apk
FAILED: /mnt/data/b/build/goma/gomacc /mnt/data/b/build/slave/Android_Arm64_Builder__dbg_/build/src/third_party/android_tools/ndk//toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-g++ -MMD -MF obj/chrome/browser/ui/android/infobars/browser_ui.account_chooser_infobar.o.d -DV8_DEPRECATION_WARNINGS -D_FILE_OFFSET_BITS=64 -DNO_TCMALLOC -DDISABLE_NACL -DCHROMIUM_BUILD -DCR_CLANG_REVISION=233105-1 -DUSE_LIBJPEG_TURBO=1 -DENABLE_WEBRTC=1 -DUSE_PROPRIETARY_CODECS -DENABLE_BROWSER_CDMS -DENABLE_CONFIGURATION_POLICY -DENABLE_NOTIFICATIONS -DSYSTEM_NATIVELY_SIGNALS_MEMORY_PRESSURE -DDONT_EMBED_BUILD_METADATA -DENABLE_AUTOFILL_DIALOG=1 -DENABLE_SAVE_WALLET_CARDS_LOCALLY=1 -DCLD_VERSION=1 -DENABLE_PRINTING=1 -DENABLE_BASIC_PRINTING=1 -DENABLE_SUPERVISED_USERS=1 -DVIDEO_HOLE=1 -DV8_USE_EXTERNAL_STARTUP_DATA -DMOJO_USE_SYSTEM_IMPL -DPROTOBUF_USE_DLLS -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DPASSWORD_MANAGER_ENABLE_SYNC -DAPPCACHE_USE_SIMPLE_CACHE -DSK_SUPPORT_GPU=1 -DSK_LEGACY_DRAWPICTURECALLBACK -DSK_SUPPORT_LEGACY_OPTIONLESS_GET_PIXELS -DSK_BUILD_FOR_ANDROID -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DU_STATIC_IMPLEMENTATION -DLIBXML_STATIC -DPOSIX_AVOID_MMAP -DMEDIA_DISABLE_FFMPEG -DMEDIA_DISABLE_LIBVPX -DXML_STATIC -DFEATURE_ENABLE_SSL -DFEATURE_ENABLE_VOICEMAIL -DEXPAT_RELATIVE_PATH -DGTEST_RELATIVE_PATH -DNO_MAIN_THREAD_WRAPPING -DNO_SOUND_SYSTEM -DANDROID -DPOSIX -DWEBRTC_POSIX -DUSE_LIBPCI=1 -DUSE_OPENSSL=1 -DUSE_OPENSSL_CERTS=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__GNU_SOURCE=1 -DUSE_STLPORT=1 -D_STLP_USE_PTR_SPECIALIZATIONS=1 '-DCHROME_BUILD_ID=""' -DHAVE_SYS_UIO_H -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DWTF_USE_DYNAMIC_ANNOTATIONS=1 -D_DEBUG -Igen -I../.. -Iobj/chrome/browser_ui.gen -I../../skia/config -I../../third_party/khronos -I../../gpu -I../../third_party/WebKit/Source -Igen/angle -Igen/protoc_out -I../../third_party/protobuf -I../../third_party/protobuf/src -Igen/chrome -I../../third_party/dom_distiller_js/dist/proto_gen -Igen/components -Igen/components/strings -I../../third_party/WebKit -I../../third_party/mojo/src -Igen/third_party/mojo/src -I../../third_party/skia/include/core -I../../third_party/skia/include/effects -I../../third_party/skia/include/pdf -I../../third_party/skia/include/gpu -I../../third_party/skia/include/lazy -I../../third_party/skia/include/pathops -I../../third_party/skia/include/pipe -I../../third_party/skia/include/ports -I../../third_party/skia/include/utils -I../../skia/ext -I../../third_party/cacheinvalidation/overrides -I../../third_party/cacheinvalidation/src -I../../third_party/cacheinvalidation/google/cacheinvalidation -I../../third_party/icu/source/i18n -I../../third_party/icu/source/common -I../../third_party/libxml/linux/include -I../../third_party/libxml/src/include -I../../third_party/zlib -Igen/ui/resources -Igen/content/app/resources/ -I../../third_party/expat/files/lib -I../../third_party/leveldatabase/src/include -I../../third_party/leveldatabase/src -I../../third_party/leveldatabase -I../../third_party/webrtc/overrides -I../../third_party/libjingle/overrides -I../../third_party/libjingle/source -I../../testing/gtest/include -I../../third_party -I../../third_party/npapi -I../../third_party/npapi/bindings -I../../third_party/re2 -I../../v8/include -Igen/policy -I../../third_party/boringssl/src/include --param=ssp-buffer-size=4 -Werror -fno-strict-aliasing -Wall -Wno-unused-parameter -Wno-missing-field-initializers -fvisibility=hidden -pipe -fPIC -Wno-unused-local-typedefs -ffunction-sections -funwind-tables -g -fno-short-enums -finline-limit=64 -Wa,--noexecstack --sysroot=../../third_party/android_tools/ndk//platforms/android-21/arch-arm64 -isystem../../third_party/android_tools/ndk//sources/cxx-stl/stlport/stlport -Os -g -gdwarf-4 -fdata-sections -ffunction-sections -funwind-tables -g0 -fno-exceptions -fno-rtti -fno-threadsafe-statics -fvisibility-inlines-hidden -Wsign-compare -std=gnu++11 -Wno-narrowing -Wno-literal-suffix  -c ../../chrome/browser/ui/android/infobars/account_chooser_infobar.cc -o obj/chrome/browser/ui/android/infobars/browser_ui.account_chooser_infobar.o
../../chrome/browser/ui/android/infobars/account_chooser_infobar.cc:46:8: error: 'void {anonymous}::AvatarFetcherAndroid::OnFetchComplete(GURL, const SkBitmap*)' marked override, but does not override
   void OnFetchComplete(const GURL url, const SkBitmap* bitmap) override;
        ^
In file included from ../../storage/browser/fileapi/plugin_private_file_system_backend.h:13:0,
                 from ../../storage/browser/fileapi/file_system_context.h:20,
                 from ../../content/public/browser/content_browser_client.h:29,
                 from ../../chrome/browser/profiles/profile.h:17,
                 from ../../chrome/browser/ui/android/infobars/account_chooser_infobar.cc:12:
../../storage/browser/fileapi/file_system_backend.h:43:13: error: 'storage::kMaximumLength' defined but not used [-Werror=unused-variable]
 const int64 kMaximumLength = std::numeric_limits<int64>::max();
             ^
cc1plus: all warnings being treated as errors

Original issue's description:
> [Smart Lock] Add avatar picture to account chooser infobar.
>
> After this change account chooser infobar will be able to display avatar
> of the account.
>
> BUG=454815
>
> Committed: https://crrev.com/58ec0cbfd99f9fcda5d1bbd0b3f111e7aa12a55a
> Cr-Commit-Position: refs/heads/master@{#322844}

TBR=mkwst@chromium.org,newt@chromium.org,dfalcantara@chromium.org,melandory@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=454815

Review URL: https://codereview.chromium.org/1042313003

Cr-Commit-Position: refs/heads/master@{#322847}