Revert "[tools/colabutils] Add context manager to keep a device awake over ADB"
This reverts commit 302f0570188e877597f39db5ec58d0edaeee0f06.

Reason for revert: Causing failures on https://ci.chromium.org/ui/p/chromium/builders/ci/win-presubmit/18962/overview

C:\b\s\w\ir\cache\builder\win_presubmit\src\tools\android\colabutils\memory_usage\memory_usage_view_unittest.py
vpython3.bat C:\b\s\w\ir\cache\builder\win_presubmit\src\tools\android\colabutils\memory_usage\memory_usage_view_unittest.py --verbose (0.63s) failed
Traceback (most recent call last):
  File "C:\b\s\w\ir\cache\builder\win_presubmit\src\tools\android\colabutils\memory_usage\memory_usage_view_unittest.py", line 15, in <module>
    from colabutils.memory_usage.memory_usage_view import (
  File "C:\b\s\w\ir\cache\builder\win_presubmit\src\tools\android\colabutils\__init__.py", line 5, in <module>
    from .caffeinate import caffeinate
  File "C:\b\s\w\ir\cache\builder\win_presubmit\src\tools\android\colabutils\caffeinate.py", line 9, in <module>
    from . import command_line
  File "C:\b\s\w\ir\cache\builder\win_presubmit\src\tools\android\colabutils\command_line.py", line 42, in <module>
    async def run(command, *args, input="", interruption_signal=signal.SIGKILL):
                                                                ^^^^^^^^^^^^^^
AttributeError: module 'signal' has no attribute 'SIGKILL'. Did you mean: 'SIGILL'?


Original change's description:
> [tools/colabutils] Add context manager to keep a device awake over ADB
>
> On MDM managed devices, the Android settings to keep the device awake
> and unlocked indefinitely might not be available. In those cases, the
> only viable option to keep the device awake is to send a key event over
> ADB at regular intervals.
>
> This change adds a context manager to "caffeinate" the Android device to
> to simplify keeping the device awake while profiling Chrome.
>
> Bug: 483758906
> Change-Id: I8db661c0797ff3582c0af45d40f6aa59da172135
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7573258
> Reviewed-by: Andrew Grieve <agrieve@chromium.org>
> Commit-Queue: Anand Ravi <anandrv@google.com>
> Cr-Commit-Position: refs/heads/main@{#1589628}

Bug: 483758906
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Change-Id: Ic942db63bcbb4f77862e027f92e558850fa199d9
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7604378
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Auto-Submit: Marijn Kruisselbrink <mek@chromium.org>
Owners-Override: Marijn Kruisselbrink <mek@chromium.org>
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Cr-Commit-Position: refs/heads/main@{#1589759}