[Sheriff] Revert "Register the Updater and Chrome app ids with the //chrome/updater."
This reverts commit afcc5be94a181733cbb912fdd38f177e1fe41ce6.

Reason for revert: Appears to have closed the tree by breaking "compile":
see https://ci.chromium.org/p/chromium/builders/ci/Win%20Builder/89067?:
FAILED: obj/chrome/updater/base/installer.obj 
../../chrome/updater/installer.cc(52,10): error: use of undeclared identifier 'sequence_checker_'
  DCHECK(sequence_checker_.CalledOnValidSequence());
         ^
../../chrome/updater/installer.cc(56,10): error: use of undeclared identifier 'sequence_checker_'
  DCHECK(sequence_checker_.CalledOnValidSequence());
         ^

Original change's description:
> Register the Updater and Chrome app ids with the //chrome/updater.
> 
> This change uses prefs to store and retrieve app ids for the apps
> registered for updates.
> 
> Bug: 1020285
> Change-Id: I7dea36049e6e09ff7039b61f79acb268e94baddb
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2053584
> Commit-Queue: Sorin Jianu <sorin@chromium.org>
> Reviewed-by: Joshua Pawlicki <waffles@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#745125}

TBR=sorin@chromium.org,waffles@chromium.org

Change-Id: I0e270d1c6b4fc855f0c4686ee6de0551dbfcbcd1
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 1020285
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2078844
Reviewed-by: Katie Dektar <katie@chromium.org>
Commit-Queue: Katie Dektar <katie@chromium.org>
Cr-Commit-Position: refs/heads/master@{#745130}