Don't build window_finder_mus on Mac
Mus isn't supported on Mac. Most of the mus files are guarded by ash, but
window_finder_mus moved from an aura guard to a toolkit-views guard in
r424384. For it to build on Mac, it would still need aura, which isn't
supported either.

Currently a mac_views_browser=true build fails with

window_finder_mus.cc:27:21: error: cannot initialize a variable of type
  'aura::Window *' with an rvalue of type 'gfx::NativeWindow' (aka 'NSWindow *')
      aura::Window* content_window = widget->GetNativeWindow();

R=erg@chromium.org
BUG=425229

Review-Url: https://codereview.chromium.org/2424683002
Cr-Commit-Position: refs/heads/master@{#425791}