Remove variable shadowing in blink/modules/cache_storage
In an effort to reduce or even ban variable shadowing, this renames
a variable to avoid such shadowing. I'm interested in prohibiting
shadowing because I think it might prevent potential jumbo problems.

The exact error this avoid is:

third_party/blink/renderer/modules/cache_storage/inspector_cache_storage_agent.cc:313:22: error: declaration shadows a local variable [-Werror,-Wshadow]
    for (const auto& request_response : responses_) {
                     ^
third_party/blink/renderer/modules/cache_storage/inspector_cache_storage_agent.cc:277:22: note: previous declaration is here
    RequestResponse& request_response =

Bug: 923510
Change-Id: I8f6b6cd11f80a254c2c926e934dacefaa6dfccf8
Reviewed-on: https://chromium-review.googlesource.com/c/1477285
Reviewed-by: Ben Kelly <wanderview@chromium.org>
Commit-Queue: Daniel Bratell <bratell@opera.com>
Cr-Commit-Position: refs/heads/master@{#633715}