[ios] Fix Official builder
The CL https://crrev.com/1977655 did not update some code that was
only compiled on Official builder. This caused the following error
as ios/chrome/test/app/chrome_test_util.h was no longer imported:

  ..../settings_egtest.mm:315:23: error: no member named 'SetWWANStateTo' in namespace 'chrome_test_util'
      chrome_test_util::SetWWANStateTo(YES);
      ~~~~~~~~~~~~~~~~~~^

Add a new method to SettingsAppInterface that wraps the call to
chrome_test_util::SetWWANStateTo() thus allowing this code to be
built for both EarlGrey and EarlGrey2.

Bug: none
Change-Id: Icf85d50a8a83603b68cb3eee99ef276a9f4dc042
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1980614
Auto-Submit: Sylvain Defresne <sdefresne@chromium.org>
Commit-Queue: Stepan Khapugin <stkhapugin@chromium.org>
Reviewed-by: Stepan Khapugin <stkhapugin@chromium.org>
Cr-Commit-Position: refs/heads/master@{#727183}