Make DiffHunk._annotate use while loop instead of recursive call.
This CL fixes "RecursionError: maximum recursion depth exceeded in
 comparison" inside _annotate. e.g.
---
    DiffHunk._annotate(lines, index + 1, 0, end - line_len,
  File "/usr/local/google/home/tasak/Workspace/chromium/local/workspace2/src/third_party/blink/tools/blinkpy/common/pretty_diff.py", line ..., in _annotate
    DiffHunk._annotate(lines, index + 1, 0, end - line_len,
  [Previous line repeated 30 more times]
  File "/usr/local/google/home/tasak/Workspace/chromium/local/workspace2/src/third_party/blink/tools/blinkpy/common/pretty_diff.py", line ..., in _annotate
    annotations[index].append((start, min(line_len, end)))

---

RecursionError: maximum recursion depth exceeded in comparison
Change-Id: Idcb74e6248597ac44d22f2a3ea64e70431d7399e
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4480694
Commit-Queue: Takashi Sakamoto <tasak@google.com>
Reviewed-by: Kent Tamura <tkent@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1137055}