Revert "Cleanup global dir of IME"
This reverts commit d7a8b3abe9de42777d51f2b7743734e74f92d717.

Reason for revert:
Breaks the builders

../../chromeos/services/ime/decoder/system_engine.cc:12:10: fatal error: 'chromeos/services/ime/public/cpp/buildflags.h' file not found
#include "chromeos/services/ime/public/cpp/buildflags.h"

Original change's description:
> Cleanup global dir of IME
>
> Rm unused global dir for IME service.
> It throws many logging errors now.
>
> BUG=b:195259020
>
> Change-Id: I0ae04db915aabfd8ce9cfb143920d49723b0975c
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3067018
> Reviewed-by: Leo Zhang <googleo@chromium.org>
> Reviewed-by: Keith Lee <keithlee@chromium.org>
> Commit-Queue: Leo Zhang <googleo@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#907478}

Bug: b:195259020
Change-Id: Id397a8c2554c785e3ef477d6a7767a002db69eb3
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3066241
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Reviewed-by: Matthias Körber <koerber@google.com>
Reviewed-by: Christoph Schwering <schwering@google.com>
Owners-Override: Matthias Körber <koerber@google.com>
Auto-Submit: Matthias Körber <koerber@google.com>
Commit-Queue: Christoph Schwering <schwering@google.com>
Cr-Commit-Position: refs/heads/master@{#907483}