Fix gn check failure on linux-arm64-cast-rel bot.
gn check fails because of enable_extensions=false. i.e.
error: "including a header is not allowed."

This CL does:
if "X including a header Y is not allowed." is found,
(1) if Y is inside #if BUILDFLAG(ENABLE_EXTENSIONS)...
  #endif, use //nogncheck.
  e.g.
    #if BUILDFLAG(ENABLE_EXTENSISION)
    #include "Y"  //nogncheck
    #endif
(2) otherwise,
   - if X is a header file, update public_deps.
   - if X is .cc file, update deps.

Sample build fauilre:
https://ci.chromium.org/ui/p/chromium/builders/ci/linux-arm64-cast-rel/14783/

Sample log:
ERROR at //chrome/browser/apps/app_service/app_icon/app_icon_factory.cc:38:11: Can't include this header from here.
#include "services/data_decoder/public/cpp/decode_image.h"
          ^----------------------------------------------
The target:
  //chrome/browser/apps/app_service/app_icon:app_icon
is including a file from the target:
  //services/data_decoder/public/cpp:cpp
...

Change-Id: Ife4c1e5c297cd988c32dcda3229285649879832e
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5738765
Commit-Queue: Takashi Sakamoto <tasak@google.com>
Reviewed-by: Erik Chen <erikchen@chromium.org>
Reviewed-by: Takashi Toyoshima <toyoshim@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1334564}