build: Add missing dep //chrome/browser:lcp_critical_path_predictor_proto to //chrome/browser/ui:ui
This fixes the following build error.

FAILED: a0e913f7-1690-4324-b3af-55ac95e99dbe "./obj/chrome/browser/ui/ui/chrome_omnibox_client.o" CXX obj/chrome/browser/ui/ui/chrome_omnibox_client.o
stderr:
In file included from ../../chrome/browser/ui/omnibox/chrome_omnibox_client.cc:34:
In file included from ../../chrome/browser/predictors/loading_predictor.h:20:
In file included from ../../chrome/browser/predictors/preconnect_manager.h:20:
In file included from ../../chrome/browser/predictors/resource_prefetch_predictor.h:23:
../../chrome/browser/predictors/lcp_critical_path_predictor/lcp_critical_path_predictor_util.h:10:10: fatal error: 'chrome/browser/predictors/lcp_critical_path_predictor/lcp_critical_path_predictor.pb.h' file not found
   10 | #include "chrome/browser/predictors/lcp_critical_path_predictor/lcp_critical_path_predictor.pb.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Bug: 345654220
Fixed: 345654220
Change-Id: I2ca88ef76479226f3898e4c6c2613f9a82c7cf6e
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5632918
Commit-Queue: Junji Watanabe <jwata@google.com>
Reviewed-by: Fumitoshi Ukai <ukai@google.com>
Commit-Queue: Fumitoshi Ukai <ukai@google.com>
Auto-Submit: Junji Watanabe <jwata@google.com>
Cr-Commit-Position: refs/heads/main@{#1315061}