Revert "Moves core/{ => css }/CSSValueKeywords.h/cpp)"
This reverts commit 4d894378a2b24efd1b6bf00a42cda8ad309d5d35.

Reason for revert: Compile failure:
https://build.chromium.org/p/chromium.chrome/builders/Google%20Chrome%20Linux%20x64/builds/21116
fatal error: 'core/CSSValueKeywords.h' file not found

Original change's description:
> Moves core/{ => css }/CSSValueKeywords.h/cpp)
> 
> This patch moves the output of make_css_value_keywords.py to be in
> core/css, and updates all the #includes.
> 
> Bug: 732657
> Cq-Include-Trybots: master.tryserver.chromium.linux:linux_layout_tests_slimming_paint_v2
> Change-Id: Iff197dd4066bc92cda8fb1d808c02d8253f0f92f
> Reviewed-on: https://chromium-review.googlesource.com/590907
> Commit-Queue: Darren Shen <shend@chromium.org>
> Reviewed-by: meade_UTC10 <meade@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#500514}

TBR=meade@chromium.org,shend@chromium.org

Change-Id: Iabddd68087e2ba0c152db7425325c49ca7e05a4a
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 732657
Cq-Include-Trybots: master.tryserver.chromium.linux:linux_layout_tests_slimming_paint_v2
Reviewed-on: https://chromium-review.googlesource.com/656798
Reviewed-by: Matt Giuca <mgiuca@chromium.org>
Commit-Queue: Matt Giuca <mgiuca@chromium.org>
Cr-Commit-Position: refs/heads/master@{#500519}