Reland "Reland "Roll clang+rust llvmorg-20-init-13894-g8cb44859-1 : llvmorg-20-init-16062-g091448e3-1 / a522d78598415cdd614ccc6d961160f192f64b5c-1 : 8a1f8039a7ded79d3d4fe97b110016d89f2b11e2-1""
This reverts commit b198121decca6f38503409af96a539b7ba98feed.

Reason for revert: should be better after
https://chromium-review.googlesource.com/c/chromium/src/+/6115847

Original change's description:
> Revert "Reland "Roll clang+rust llvmorg-20-init-13894-g8cb44859-1 : llvmorg-20-init-16062-g091448e3-1 / a522d78598415cdd614ccc6d961160f192f64b5c-1 : 8a1f8039a7ded79d3d4fe97b110016d89f2b11e2-1""
>
> This reverts commit cb59cac5a03953631e731b8dcd145399437a1a49.
>
> Reason for revert:
> LUCI Bisection has identified this change as the culprit of a build failure. See the analysis: https://ci.chromium.org/ui/p/chromium/bisection/compile-analysis/b/8727971662145799313
>
> Sample failed build: https://ci.chromium.org/b/8727971662145799313
>
> If this is a false positive, please report it at http://b.corp.google.com/createIssue?component=1199205&description=Analysis%3A+https%3A%2F%2Fchromium-review.googlesource.com%2Fc%2Fchromium%2Fsrc%2F%2B%2F6111305&format=PLAIN&priority=P3&title=Wrongly+blamed+https%3A%2F%2Fci.chromium.org%2Fui%2Fp%2Fchromium%2Fbisection%2Fcompile-analysis%2Fb%2F8727971662145799313&type=BUG
>
> Original change's description:
> > Reland "Roll clang+rust llvmorg-20-init-13894-g8cb44859-1 : llvmorg-20-init-16062-g091448e3-1 / a522d78598415cdd614ccc6d961160f192f64b5c-1 : 8a1f8039a7ded79d3d4fe97b110016d89f2b11e2-1"
> >
> > This reverts commit dca68566e7efca3368542b8329cad45e875ba0ae.
> >
> > Reason for revert: already fixed
> >
> > Original change's description:
> > > Revert "Roll clang+rust llvmorg-20-init-13894-g8cb44859-1 : llvmorg-20-init-16062-g091448e3-1 / a522d78598415cdd614ccc6d961160f192f64b5c-1 : 8a1f8039a7ded79d3d4fe97b110016d89f2b11e2-1"
> > >
> > > This reverts commit 32fd5de30ad9dcb9d47816e97161de85b36b63c6.
> > >
> > > Reason for revert: tree-closing compilation failures:
> > > https://ci.chromium.org/ui/p/chromium/builders/ci/linux-cast-arm-rel/10744
> > > https://ci.chromium.org/ui/p/chromium/builders/ci/linux-cast-arm64-rel/11108
> > > https://ci.chromium.org/ui/p/chromium/builders/ci/linux-cast-x64-rel/6736
> > > with the error:
> > > chromecast/browser/cast_web_contents_impl.h:182:26: error: private field 'parent_cast_web_contents_' is not used [-Werror,-Wunused-private-field]
> > >   182 |   CastWebContents* const parent_cast_web_contents_ = nullptr;
> > >
> > > Original change's description:
> > > > Roll clang+rust llvmorg-20-init-13894-g8cb44859-1 : llvmorg-20-init-16062-g091448e3-1 / a522d78598415cdd614ccc6d961160f192f64b5c-1 : 8a1f8039a7ded79d3d4fe97b110016d89f2b11e2-1
> > > >
> > > > https://chromium.googlesource.com/external/github.com/llvm/llvm-project/+log/8cb44859..091448e3
> > > >
> > > > https://chromium.googlesource.com/external/github.com/rust-lang/rust/+log/a522d7859841..8a1f8039a7de
> > > >
> > > > Ran: ./tools/clang/scripts/upload_revision.py 091448e3c17bc8e7812dd7b571c852576d648977
> > > >
> > > > Additionally:
> > > > * Ran tools/rust/gnrt_stdlib.py
> > > > * Updated //chrome/android/static_initializers.gni because it referred
> > > >   to a static initializer in sme-abi-init.c, a file in compiler-rt that
> > > >   was removed in https://github.com/llvm/llvm-project/pull/119414.
> > > >
> > > > Bug: 382540640
> > > > Disable-Rts: True
> > > > Change-Id: I4fd6f81827ed519770048adb74430e8ec1fd849d
> > > > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6111009
> > > > Auto-Submit: Alan Zhao <ayzhao@google.com>
> > > > Commit-Queue: Zequan Wu <zequanwu@google.com>
> > > > Commit-Queue: Alan Zhao <ayzhao@google.com>
> > > > Reviewed-by: Zequan Wu <zequanwu@google.com>
> > > > Cr-Commit-Position: refs/heads/main@{#1399472}
> > >
> > > Bug: 382540640
> > > Change-Id: Ib8d123e61472090b0643b5617aa7a259abd8ff58
> > > No-Presubmit: true
> > > No-Tree-Checks: true
> > > No-Try: true
> > > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6108066
> > > Owners-Override: David Baron <dbaron@chromium.org>
> > > Auto-Submit: David Baron <dbaron@chromium.org>
> > > Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
> > > Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
> > > Cr-Commit-Position: refs/heads/main@{#1399476}
> >
> > Bug: 382540640
> > Change-Id: I0c6504bd82a38b6a8fddb27b080af3b639e4acc6
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6111305
> > Commit-Queue: Alan Zhao <ayzhao@google.com>
> > Reviewed-by: Alan Zhao <ayzhao@google.com>
> > Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
> > Commit-Queue: Nico Weber <thakis@chromium.org>
> > Cr-Commit-Position: refs/heads/main@{#1399482}
> >
>
> Bug: 382540640
> Change-Id: Ic3fc3671ab942245b89aaa461cf8e5c5331d96d2
> No-Presubmit: true
> No-Tree-Checks: true
> No-Try: true
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6116109
> Bot-Commit: luci-bisection@appspot.gserviceaccount.com <luci-bisection@appspot.gserviceaccount.com>
> Owners-Override: luci-bisection@appspot.gserviceaccount.com <luci-bisection@appspot.gserviceaccount.com>
> Commit-Queue: luci-bisection@appspot.gserviceaccount.com <luci-bisection@appspot.gserviceaccount.com>
> Cr-Commit-Position: refs/heads/main@{#1399490}

Bug: 382540640
Change-Id: I0e783f8acad96b4bf57d715f33fef50c8af9b4a4
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6114634
Commit-Queue: Nico Weber <thakis@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Auto-Submit: Nico Weber <thakis@chromium.org>
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Cr-Commit-Position: refs/heads/main@{#1399535}