Extend variadic template hack for /analyze.
A recent Chrome change broke the /analyze builder by using a larger
Tuple than had been allowed for in the previous VC++ bug workaround.
This change unblocks the /analyze builder and will not affect
/analyze builds.

The /analyze error is:
e:\b\build\slave\chromium_windows_analyze\build\src\base\tuple.h(99) : error C2027: use of undefined type 'MakeIndexSequenceImpl<0xc>'
e:\b\build\slave\chromium_windows_analyze\build\src\device\usb\usb_device_handle_impl.cc(608)

and came from https://codereview.chromium.org/980023002

R=thakis@chromium.org
BUG=427616

Review URL: https://codereview.chromium.org/1095543003

Cr-Commit-Position: refs/heads/master@{#325877}