Fix incorrect translation expectations path
Without this CL the upload_screenshots.py script fails to run with:

$ python tools/translation/upload_screenshots.py
Traceback (most recent call last):
  File "tools/translation/upload_screenshots.py", line 212, in <module>
    main()
  File "tools/translation/upload_screenshots.py", line 155, in main
    TRANSLATION_EXPECTATIONS_PATH))
  File "tools/translation/upload_screenshots.py", line 108, in find_screenshots
    repo_root, list_grds_in_repository(repo_root), translation_expectations)
  File "$HOME/repos/chromium/src/tools/translation/helper/translation_helper.py", line 101, in get_translatable_grds
    (translation_expectations_path, '\n - '.join(errors)))
Exception: $HOME/repos/chromium/src/tools/gritsettings/translation_expectations.pyl needs to be updated. Please fix these issues:
 - chrome/android/features/media_router/java/strings/android_chrome_media_router_strings.grd appears to be translatable (because it contains <file> or <message> elements), but is not listed in the translation expectations.
 - chrome/android/features/media_router/strings/android_chrome_media_router_strings.grd is listed in the translation expectations, but this grd file does not exist.

Change-Id: I6cd2daf6091881df16ac0b169bc5eec591a0b9a9
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1502339
Auto-Submit: Alan Cutter <alancutter@chromium.org>
Reviewed-by: Lei Zhang <thestig@chromium.org>
Commit-Queue: Lei Zhang <thestig@chromium.org>
Cr-Commit-Position: refs/heads/master@{#637621}