Fix some build failures due to exit-time destructors.
For example:
```
../../chromecast/starboard/media/renderer/chromium_starboard_conversions.cc:36:21: error: declaration requires an exit-time destructor [-Werror,-Wexit-time-destructors]
   36 |   static base::Lock lock;
      |                     ^
1 error generated.
```
I'm not sure how the code initially compiled; maybe some compiler
settings were recantly changed.

Test:
tools/autotest.py -C out/glinux --run_all ./chromecast/starboard/media

Bug: None
Change-Id: I6e4fce26af9086d468e323ab308456baf8c29b56
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6896858
Reviewed-by: Shawn Quereshi <shawnq@google.com>
Commit-Queue: Antonio Rivera <antoniori@google.com>
Cr-Commit-Position: refs/heads/main@{#1513254}