[WPT] Fix missing script on Android runners
This script got introduced in crrev.com/c/3123432 but seems to be
missing on bots; they fail with the following exception in the logs:

ModuleNotFoundError: No module named 'wpt_android_lib'

Adding it to the wpt_tests_isolate group which is being used e.g. by
weblayer_shell_wpt and chrome_public_wpt should fix this issue.

Bug: None
Change-Id: I9af7abe7d095ca44a8cf33a49f0fbe65fbd076f1
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3122099
Commit-Queue: Rakib Hasan <rmhasan@google.com>
Reviewed-by: Rakib Hasan <rmhasan@google.com>
Cr-Commit-Position: refs/heads/main@{#915997}