chrome/browser/ash/policy/dlp: fix missing deps
e.g.
https://ci.chromium.org/ui/p/chromium/builders/build/linux-chromeos-build-perf-ninja/4502/overview
FAILED: obj/chrome/browser/ash/policy/dlp/dlp/dlp_content_manager_ash.o
(commandline omitted)
In file included from ../../chrome/browser/ash/policy/dlp/dlp_content_manager_ash.cc:28:
In file included from ../../chrome/browser/ui/ash/capture_mode/chrome_capture_mode_delegate.h:22:
In file included from ../../chrome/browser/ui/lens/lens_overlay_query_controller.h:18:
../../chrome/browser/ui/lens/lens_overlay_request_id_generator.h:8:10: fatal error: 'third_party/lens_server_proto/lens_overlay_server.pb.h'
file not found
  8 | #include "third_party/lens_server_proto/lens_overlay_server.pb.h"
    |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

$ gn refs out/cros chrome/browser/ash/policy/dlp/dlp_content_manager_ash.cc
//chrome/browser/ash/policy/dlp:dlp
$ gn refs out/cros chrome/browser/ui/ash/capture_mode/chrome_capture_mode_delegate.h
//chrome/browser/ui/ash/capture_mode:capture_mode                               $ gn refs out/cros chrome/browser/ui/lens/lens_overlay_query_controller.h
//chrome/browser/ui/lens:lens
$ gn refs out/cros out/cros/gen/third_party/lens_server_proto/lens_overlay_server.pb.h
//third_party/lens_server_proto:lens_overlay_proto
//third_party/lens_server_proto:lens_overlay_proto_gen

add "//third_party/lens_server_prot:lens_overlay_proto" to
public_deps of //chrome/browser/ui/lens
as it has include header dependencies.

adding capture_mode->lens, or dlp->capture_mode causes dependency
cycles, so add "//third_party/lens_server_prot:lens_overlay_proto"
to "//chrome/browser:browser_public_dependencies"

Bug: 354839582
Change-Id: Icab503f53344059dd1e6eb6a2564ab67e9c19a04
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5968496
Reviewed-by: Joel Hockey <joelhockey@chromium.org>
Owners-Override: Joel Hockey <joelhockey@chromium.org>
Auto-Submit: Fumitoshi Ukai <ukai@google.com>
Commit-Queue: Joel Hockey <joelhockey@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1374465}