Revert "Roll Dawn from a7278454b28b to cb055303b5e0 (6 revisions)"
This reverts commit f60101d39824398546043f914d249389cc71d790.

Reason for revert: 
Error: file "Client.cpp" is not expected to have static initializers in binary "chrome"
https://logs.chromium.org/logs/chromium/buildbucket/cr-buildbucket.appspot.com/8866332587065352912/+/steps/check_static_initializers__with_patch_/0/stdout

Original change's description:
> Roll Dawn from a7278454b28b to cb055303b5e0 (6 revisions)
>
> https://dawn.googlesource.com/dawn.git/+log/a7278454b28b..cb055303b5e0
>
> 2020-10-15 dawn-autoroll@skia-public.iam.gserviceaccount.com Roll Tint from 481ecff293db to 95dc655bf8a6 (1 revision)
> 2020-10-15 dawn-autoroll@skia-public.iam.gserviceaccount.com Roll Tint from 53380f9ed76f to 481ecff293db (1 revision)
> 2020-10-15 cwallez@chromium.org Fix a small typo in Format.cpp alwaus -> always
> 2020-10-15 brandon1.jones@intel.com Change Device::Tick To Return Bool
> 2020-10-15 dawn-autoroll@skia-public.iam.gserviceaccount.com Roll Tint from ff267ca60e14 to 53380f9ed76f (1 revision)
> 2020-10-15 enga@chromium.org Replace the wire serializer with a no-op impl on disconnect
>
> If this roll has caused a breakage, revert this CL and stop the roller
> using the controls here:
> https://autoroll.skia.org/r/dawn-chromium-autoroll
> Please CC enga@google.com on the revert to ensure that a human
> is aware of the problem.
>
> To report a problem with the AutoRoller itself, please file a bug:
> https://bugs.chromium.org/p/skia/issues/entry?template=Autoroller+Bug
>
> Documentation for the AutoRoller is here:
> https://skia.googlesource.com/buildbot/+doc/master/autoroll/README.md
>
> Cq-Include-Trybots: luci.chromium.try:dawn-linux-x64-deps-rel;luci.chromium.try:dawn-mac-x64-deps-rel;luci.chromium.try:dawn-win10-x64-deps-rel;luci.chromium.try:dawn-win10-x86-deps-rel
> Bug: chromium:951558
> Tbr: enga@google.com
> Change-Id: Id52eaff3a4938c8407d968f5c7e5fe7c3933213b
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2477290
> Reviewed-by: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>
> Commit-Queue: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>
> Cr-Commit-Position: refs/heads/master@{#817733}

TBR=chromium-autoroll@skia-public.iam.gserviceaccount.com,enga@google.com

Change-Id: I1752d10375103eca674497be8d84da42ab3c8d78
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: chromium:951558
Cq-Include-Trybots: luci.chromium.try:dawn-linux-x64-deps-rel;luci.chromium.try:dawn-mac-x64-deps-rel;luci.chromium.try:dawn-win10-x64-deps-rel;luci.chromium.try:dawn-win10-x86-deps-rel
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2477138
Reviewed-by: Takuto Ikuta <tikuta@chromium.org>
Commit-Queue: Takuto Ikuta <tikuta@chromium.org>
Cr-Commit-Position: refs/heads/master@{#817780}