Fix error running Mac signing under py3.
  pipeline.py, line 46, in _binary_architectures
  output = output.replace(' ', ',')
  TypeError: a bytes-like object is required, not 'str'

BUG=1238067
R=rsesek@chromium.org

Change-Id: Id099ae273948651d976388dad4cf7b59f19e177e
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3082313
Commit-Queue: Michael Moss <mmoss@chromium.org>
Reviewed-by: Robert Sesek <rsesek@chromium.org>
Cr-Commit-Position: refs/heads/master@{#910016}