Revert of Switch ClangToTLinuxASan from gyp to gn. (patchset #1 id:1 of https://codereview.chromium.org/1924173004/ )
Reason for revert:
ASan builds don't work in gn yet (for nacl targets): https://build.chromium.org/p/chromium.fyi/builders/ClangToTLinuxASan/builds/4000/steps/compile/logs/stdio

[822/41484] LINK ./libc_free_x86_64.nexe
FAILED: libc_free_x86_64.nexe
../../third_party/llvm-build/Release+Asserts/bin/clang++ -nostdlib -shared -Wl,--no-undefined -Qunused-arguments -Wl,--fatal-warnings -fPIC -Wl,-z,noexecstack -Wl,-z,now -Wl,-z,relro -B../../third_party/binutils/Linux_x64/Release/bin -fuse-ld=gold -pthread -m64 -Wl,-O1 -Wl,--gc-sections --sysroot=../../build/linux/debian_wheezy_amd64-sysroot  -fsanitize=address -fsanitize=leak -Wl,-rpath-link=../Release -Wl,--disable-new-dtags -Wl,-rpath=\$ORIGIN/. -Wl,-rpath-link=. -o "./libc_free_x86_64.nexe" -Wl,--start-group @"./libc_free_x86_64.nexe.rsp"  -Wl,--end-group  -ldl -lrt
../../chrome/test/data/nacl/nonsfi/libc_free.c:214: error: undefined reference to '__asan_option_detect_stack_use_after_return'
../../chrome/test/data/nacl/nonsfi/libc_free.c:214: error: undefined reference to '__asan_stack_malloc_1'

Original issue's description:
> Switch ClangToTLinuxASan from gyp to gn.
>
> The other two ClangToTLinux bots are blocked on other things happening
> first (ubsan tests aren't green in gn builds yet, crbug.com/606003,
> and gn doesn't have linux_dump_symbols yet, crbug.com/605819)
>
> BUG=605732

TBR=hans@chromium.org,dpranke@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=605732

Review-Url: https://codereview.chromium.org/1932333002
Cr-Commit-Position: refs/heads/master@{#390708}