Fix build break due to missing //base dependency on target installer/lib
https://ci.chromium.org/p/chromium/builders/ci/win-archive-rel/3668
https://logs.chromium.org/logs/chromium/buildbucket/cr-buildbucket.appspot.com/8905912644874073840/+/steps/compile/0/stdout
[7588/69449] CXX obj/chrome/updater/win/installer/lib/installer.obj
FAILED: obj/chrome/updater/win/installer/lib/installer.obj
...
In file included from ../../chrome/updater/win/installer/installer.cc:31:
In file included from ../..\base/files/file_path.h:114:
In file included from ../..\base/stl_util.h:26:
../..\base/logging.h(23,10): fatal error: 'base/logging_buildflags.h' file not found
#include "base/logging_buildflags.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

TBR=waffles
CC=​jdonnelly

Bug: 989772
Change-Id: I4f660a6a5fc420c691a8c8c4018c90e32e76f2d5
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1739319
Reviewed-by: Sorin Jianu <sorin@chromium.org>
Commit-Queue: Sorin Jianu <sorin@chromium.org>
Cr-Commit-Position: refs/heads/master@{#684398}