Disable flaky test AccessibilityWinBrowserTest.TestIScrollProvider
Test was added by janewman@microsoft.com. Given that the linked bug
requires restricted permission, add the CL reviewer to TBR too.

Log:
accessibility_win_browsertest.cc(3234): error: The difference between
expected.size_horizontal and size_horizontal is 0.1705128205128208,
which exceeds error, where expected.size_horizontal evaluates to 12.65,
size_horizontal evaluates to 12.820512820512821, and error evaluates to
0.0099999997764825821.

accessibility_win_browsertest.cc(3274): error: The difference between
expected.size_vertical and size_vertical is 0.84176470588235119, which
exceeds error, where expected.size_vertical evaluates to 28.57,
size_vertical evaluates to 29.411764705882351, and error evaluates to
0.0099999997764825821.

TBR=dmazzoni@chromium.org, janewman@microsoft.com

Bug: 936440
Change-Id: I60a62582fcfda1006a6e87661a0bdc649954e6d8
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1499725
Commit-Queue: Yi Gu <yigu@chromium.org>
Reviewed-by: Yi Gu <yigu@chromium.org>
Cr-Commit-Position: refs/heads/master@{#637347}